### ISSUE TITLE
seek rounding error

### ISSUE THREAD

**Issue by sjolfr** [flowplayer/flowplayer#1000]
Hi,

I have noticed that there is a rounding error in the [seek method](https://github.com/flowplayer/flowplayer/blob/14388e1a9902dd08886621140fafe2becf65475f/lib/flowplayer.js#L334)

.toFixed(1) is rounding up the time variable to one decimal place, which can cause the video to seek to the wrong time.

For example, when the frame rate is 25, seeking to 00:03:31:24 in a video (211.96 seconds) will actually seek to 00:03:32:00 (212 seconds).

Thanks,

Phil

**Comment by nnarhinen** [comment]
Seeking to certain frame within HTML5 video tag is not guaranteed to be accurate and implementations across browsers vary. Can you point me to the video where you experience this so I can play around with the plain video tag and test with different browsers.

**Comment by sjolfr** [comment]
http://codepen.io/anon/pen/VaYYXm

**Comment by blacktrash** [comment]
@nnarhinen - note when considering a limit for `.toFixed` that the standard NTSC frame rate is 30000/1001 and is not that rare, in spite of being falsified often to 29.97

**Comment by sjolfr** [comment]
For that codepen example I provided: Try entering a time into the text input e.g. 2.923232 and you'll notice when clicking the Bugged Flowplayer Seek button that the flowplayer seek function sets the video to the incorrect time and the Working Seek button sets the video to the correct time.

**Comment by sjolfr** [comment]
Does toFixed need calling at all?

**Comment by blacktrash** [comment]
@sjolfr - probably not, unless it came in to avoid rounding issues.

**Comment by nnarhinen** [comment]
If I read git history right and my memory serves me right the `toFixed()` call was introduced when fixing seeking for iPad. It might have been the iOS Safari at that time did not work with too much precision or such. I'd be happy to remove it if someone confirms the recent iOS versions will not break with the removal.

**Comment by blacktrash** [comment]
ok, that would be https://github.com/flowplayer/flowplayer/commit/b6968045449e19d50bf5472322ee681720f802f6 which concerns seeking to unbuffered positions on touch devices with inline playback (#188).
Here's a demo for testing with a long video which loads flowplayer.js just with the `toFixed(1)` omitted: http://flowplayer.blacktrash.org/fp6/long.html
So far I could not detect a problem. But it should be tested more.
