### ISSUE TITLE
RTMPS 20 second delay behind firewall

### ISSUE THREAD

**Issue by colmaengus** [flowplayer/flowplayer#1001]
HI,

I'm seeing a 20 second delay when playing a rtmps stream from behind our company firewall (it works fine outside the firewall).
I imagine it might be related to another issue I'm having that rtmpt doesn't work at all behind our firewall #988.

Is there any way to change this behaviour ?

By comparison jwplayer starts playing straight away.

Regards

Colm A

**Comment by colmaengus** [comment]
Setting proxy: 'none' fixes the issue according to http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetConnection.html#proxyType

**Comment by blacktrash** [comment]
@colmaengus - out of curiosity: setting `rtmpt: false` does/did not help?

**Comment by colmaengus** [comment]
No, using rtmpt:false didn't work

Using proxy: 'none' also fixed my other issue of rtmpt not working behind our corporate proxy.

Looking at the code for ParallelConnector.as proxyType is the same for both connections. I'm wondering should it be set to 'none' for the parallel rtmpt connection to stop flash trying to connect via rtmp ?

This might mean that rtmpt:true would also fix my problem.

What do you think ?

**Comment by bbbo** [comment]
@anssip : comment / investigate please

**Comment by colmaengus** [comment]
any thoughts on this ?

**Comment by nnarhinen** [comment]
Don't we already have away to configure the proxy setting? If this is still an issue, please re-open with example code.
