### ISSUE TITLE
iOS uiwebview inline player

### ISSUE THREAD

**Issue by h3dkandi** [flowplayer/flowplayer#1004]
It is generally possible to play inline in a uiwebview if u set `webview.allowsInlineMediaPlayback = YES;` and add to the video tag `webkit-playsinline`.

I cant find a way to hack around this as you have to modify the video tag after it gets inserted and before it gets played. This means only source code modification could fix it and I would rather not use a custom modification of the player. Correct me if I am wrong.

**Comment by nnarhinen** [comment]
Yes I think this would need a new player option. Like `conf.webviewInline` that would disable the `!inline` hacks and add that `webkit-playsinline` attribute.

**Comment by nnarhinen** [comment]
Merging this with #1048
