### ISSUE TITLE
KeyboardEvent.keyLocation deprecated (and soon removed) by Chrome

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1008]
`KeyboardEvent.keyLocation` is in bean.js. Chrome gives ever more urgent messages regarding this:

''KeyboardEvent.keyLocation' is deprecated and will be removed in M50, around April 2016. Please use 'KeyboardEvent.location' instead. See https://www.chromestatus.com/features/4997403308457984 for more details.'

**Comment by nnarhinen** [comment]
This is not a problem. the bean library is just checking for (deprecated) `keyLocation` to support ancient browsers.

**Comment by blacktrash** [comment]
:+1:
