### ISSUE TITLE
Ready Event called more than once

### ISSUE THREAD

**Issue by pasupuletisrinath** [flowplayer/flowplayer#1009]
When src is changed ready is fired more than once.

If I change once it is fired twice, if I changed it again it is fired 3times, again if i change src it will call four time

**Comment by blacktrash** [comment]
Does this happen in conjunction with the hlsjs or dashjs plugin?
If yes, I'm currently working on a fix.

**Comment by blacktrash** [comment]
@pasupuletisrinath - should be fixed now. Can you confirm that
- it happened only in conjunction with the hlsjs or dashjs plugin
- it is not happening anymore for you
?

**Comment by blacktrash** [comment]
Not heard back. Closing.

**Comment by pasupuletisrinath** [comment]
@blacktrash , yeah It happened in conjunction with the hlsjs. 
Thanks for the fix. 
I'll check and let you know the status.

**Comment by divyenduz** [comment]
Should this happen in Flowplayer 6.0.5, "ready" event is being fired twice for me.

**Comment by blacktrash** [comment]
@divyenduz - please provide a link to a *minimal!* sample page focusing on the issue. And if it is only happening with hlsjs, file a bug in the plugin bug tracker: https://github.com/flowplayer/flowplayer-hlsjs/issues/

**Comment by divyenduz** [comment]
@blacktrash : While creating the minimal setup, I couldn't replicate this, found an issue with my non-minimal code base and resolved it. However, I am still facing an issue with VAST plugin, ad plays twice. What would be the best place to report that ?

Thanks

**Comment by blacktrash** [comment]
@divyenduz - that's almost certainly because your VAST plugin is not at its latest version; we recently fixed this bug. We'll refresh your plugin today, and then the issue should be gone. Otherwise, in matters VAST, contact us at support at flowplayer dot org.

**Comment by divyenduz** [comment]
@blacktrash : Thanks for the prompt response, can you notify us once our VAST plugin is refreshed. 
Do you need any other information from my end to refresh our VAST plugin ?

Regards,

**Comment by bbbo** [comment]
the plugin was just overwritten with 2.1.3

**Comment by divyenduz** [comment]
Thanks

**Comment by divyenduz** [comment]
@bbbo : This VAST issue has resurfaced for us. Ads coming multiple times again. Was the plugin overwritten again ?

**Comment by bbbo** [comment]
no, you're still at 2.1.3 . Can you provide a link to a page showing the issue? Which browsers?

**Comment by divyenduz** [comment]
We had paused the ads when we noticed the error. We can enable in specific countries / geolocations for us to test it. Can you tell us the countries where we should enable it for you guys to check ? 

Thanks

**Comment by bbbo** [comment]
I updated the plugin to 2.1.5, please try with that. If you still run into issues, please email us at support@flowplayer.org wirth a link to a sample, and ads enabled for Germany, Finland and Great Britain. Thanks.

**Comment by divyenduz** [comment]
Thanks for the prompt response. I will get back to you on this after some testing at our end 👍
