### ISSUE TITLE
Support to async load external plugins when embedding

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#101]
No source code available so not possible to properly test. 

```javascript
<script src="http://embed.flowplayer.org/5.0.1-beta/embed.min.js" data-engine="youtube" data-bitrates="true" data-defaultquality="large" data-activeclass="active"><div class="flowplayer" style="width: 620px; height: 350px;" data-origin="http://yt.electrocode.net/html/"><video><source type="video/youtube" src="http://www.youtube.com/watch?v=YE7VzlLtp-4"></video></div></script><script>flowplayer.conf.youtube = { qualityLabels: {"medium":"Medium","large":"Large","hd720":"HD"}}</script><script src="../javascript/youtube.js"></script>
```

A generated config like this doesn't work because flowplayer etc isn't loaded yet. Note the bit at the bottom to include a json config because impossible to do in html. It also needs to accept the engine config, I don't think thats working at all or thought out to include anything else but the html5 engine ? 

This will affect the DFP plugin etc also. 

Any ideas ?

**Comment by nnarhinen** [comment]
58f6998cf20fb140544f9ad07b1462c443ea9690 will address this
