### ISSUE TITLE
Flowplayer live stream in android firefox

### ISSUE THREAD

**Issue by nafisakanwal** [flowplayer/flowplayer#1010]
I have setup flowplayer for my live stream, but its not working in android Firefox .I have given RTSP format as well.
But the error is displaying "html5:Unsupported video format :Try installing Adobe Flash".

its working fine in chrome .
Please help ,what more i need to do in order to work it in the android Firefox browser
thanks in advance

**Comment by bbbo** [comment]
Please post such questions in the forums, this is not a bug...

Android Firefox does not support HLS natively. You need to use the [hlsjs plugin](https://flowplayer.org/docs/plugins.html#hlsjs) to play the stream with Media Source Extensions.

rtsp cannot be played in html5 video either so we don't offer it as fallback. You can provide a textual link to the rtsp stream of course.
