### ISSUE TITLE
Add support for Datalayer pushes to make analytics tracking more flexible 

### ISSUE THREAD

**Issue by grantkemp** [flowplayer/flowplayer#1011]
Currently Google analytics is supported for events  however this can be made more flexible by turning these calls into Datalayer pushes which are used by potentially any tracking tool including Google analytics, tag manager , qubit etc. 

https://developers.google.com/tag-manager/devguide#datalayer

its pretty easy to swap the code out using the Google Analytics code templates. Happy to advise how more specifically if this is a priority.

**Comment by nnarhinen** [comment]
I'd be happy to accept a pull request for this.

**Comment by grantkemp** [comment]
@nnarhinen  can you point out where you do the current events for Google Analytics - and then I can dive in and refactor. 

Will have a go this weekend.

**Comment by blacktrash** [comment]
@grantkemp - I suppose the analytics extension is a good place to start: https://github.com/flowplayer/flowplayer/blob/master/lib/ext/analytics.js

**Comment by grantkemp** [comment]
Thanks @blacktrash  thats a good place to start.

**Comment by grantkemp** [comment]
@blacktrash  @nnarhinen  I am done with the changes - would it still be compatible with the flash version  or just the Html5 version?

**Comment by grantkemp** [comment]
I think I have got it working - but I need some guidance on how to architect it within how flowplayer is embedded into the site.  Also where should I put the documentation for it as it will need some setting up on GA side.  I can do a blog about it if needed.

**Comment by nnarhinen** [comment]
If it's something that can be easily merged into flowplayer code base, then you could open a pull request (against the dev branch).

If it's more like a standalone plugin there's two options:
 * You hand over the code to us, we will host it under our organization in github and offer official documentation on our plugins page: https://flowplayer.org/docs/plugins.html
 * You host it yourself somewhere and we'll link to that plugin
