### ISSUE TITLE
embed: flowplayer 5 skin duplicated if loaded on same page

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1013]
When embedding on a page where a flowplayer skin is loaded:
- if the skin is of version 5.x, it is duplicated
- if the skin is of version 6.x the embed skin overrides the one for installed players on the page

I guess that's just how CSS works ;-), but especially the first case is somewhat a bummer in the rare cases it is encountered.

See: https://flowplayer.org/forum/#!/embedding_analytics:clip-urls-in-embedcode

**Comment by nnarhinen** [comment]
With traditional CSS there's not much we can do about this.

There's a (very partial) fix coming with the upcoming new embed-loader published with Drive later.

**Comment by Bargamut** [comment]
Can you separate CSS for embed from global CSS for flowplayer instances of site?

**Comment by blacktrash** [comment]
In theory one could use the current skins as embed skins, and use the not() selector `.flowplayer:not(.is-embedded)` throughout in the actual default skins ... not nice, not even sure how compatible/reliable `not()` is ...
