### ISSUE TITLE
Azure Media Services URLs not recognized by Flash(HLS) engine

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1014]
Azure URLs look like this:
`//example.mediaservices.windows.net/something.ism/manifest(format=m3u8-aapl-v3)`
and result in a video file not found error in Flash HLS. Generic and hlsjs works.

I played around with some URL encoding but so far haven't found a trick.

**Comment by blacktrash** [comment]
Sample URL: `//amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl-v3)`

**Comment by blacktrash** [comment]
Demo:
- [hlsjs enabled](http://demos.flowplayer.org/bug/1014.html) works
- [hlsjs disabled](http://demos.flowplayer.org/bug/1014.html?hlsjs-false) video file not found, unless generic playback is supported

**Comment by blacktrash** [comment]
Flash crossdomain policy for the sample address is ok:
```
$ curl -i http://amssamples.streaming.mediaservices.windows.net/crossdomain.xml
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Content-Type: text/xml
Date: Mon, 18 Apr 2016 08:45:38 GMT
Etag: "948db331587d11:0"
Last-Modified: Sat, 26 Mar 2016 04:08:50 GMT
Server: ECAcc (lcy/1D90)
X-Cache: HIT
X-Content-Type-Options: nosniff
X-Powered-By: ASP.NET
Content-Length: 120
Connection: close

<?xml version="1.0" ?>
<cross-domain-policy>
  <allow-access-from domain="*" secure="false" />
</cross-domain-policy>
```

**Comment by blacktrash** [comment]
Flowplayer Flash with flashls plugin handles these.

**Comment by nnarhinen** [comment]
WTF, why is the flash engine not even trying with flashls, it tries to play it as rtmp..

**Comment by nnarhinen** [comment]
Oh, there's this line: `if (conf.url.indexOf(".m3u") != -1) { ` which is obviously wrong.

But anyways, if you can control it, just add `.m3u` somewhere in the stream url and it should start working.

**Comment by bbbo** [comment]
AFAIK Azure users cannot control the clip url naming

**Comment by blacktrash** [comment]
But one could append a fake query:
```
//amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl-v3,audio-only=false)?suff=.m3u
```
works actually.

**Comment by blacktrash** [comment]
But in general it's of course not a good idea to relay on file naming to determine behaviour.

**Comment by blacktrash** [comment]
@bbbo - one can just append the `.m3u8` suffix in case it is missing.
For Flowplayer it is also a good idea to tell it to not use the audio-only track, it would have strange effects otherwise. That is, change:
```
http://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl-v3)
```
to:
```
http://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl-v3,audio-only=false).m3u8
```
See http://flowplayer.blacktrash.org/fp6/azure.html
But in general it's a good idea not to rely on suffix.

**Comment by irakpro** [comment]
http://irakpro.com/video%20format=m3u8-aapl.html
Convert online
MPEG-DASH & HLS Player Test
Select your format (DASH – .mpd, HLS – .M3U8 or Progressive, then enter the link to your video file.Convert online,HTTP Live Streaming (HLS.
