### ISSUE TITLE
api.seek() won't work on Firefox

### ISSUE THREAD

**Issue by groue** [flowplayer/flowplayer#1015]
Hello,

Here is the context: flowplayer 6.0.5, OS X El Capitan 10.11.4, Firefox 45.0.2, a video hosted on the flowplayer CDN, via the Economy plan (yes I'm a paying user), and a video player embedded with the raw HTML snippet copied and pasted from the embed button provided on the videos admin page.

My problem is that the seek() function does not behave as it should (and does in other browsers):

```javascript
player.on("ready", function(){
  player.seek(offset, function(){
    // here seek should have happened, but not on Firefox
  });
});
```

On Firefox the seek callback is called, but the seek did not happen: the video is stuck at its initial position.

The [documentation](https://flowplayer.org/docs/api.html#methods) for the seek() function says:

> `seek(time, [callback])`: Seeks to the given position in seconds. For example: 13.5. The callback is executed once after the seek.

So I think we have a bug here.

Is there a known workaround to this problem, until the bug is fixed?

**Comment by blacktrash** [comment]
What are you doing in the callback?
Seek on ready certainly works here http://demos.flowplayer.org/scripting/chapters.html - also in Firefox 45.0.2 on Mac.

**Comment by groue** [comment]
I'm setting up a minimal case.

**Comment by groue** [comment]
@blacktrash. OK I've a better understanding. Seeking exists on Firefox, but lacks precision. So much it looks like a bug. I lack deep experience on the subject, but I suspect seeking problems to be encoding problems (a lack of key frames), and now I'm not sure this repository is the correct place to report this issue.

So that you can see the trouble, here is the full source of a web page that reveals the issue, and the screenshots on Safari, Chrome, Firefox, and IE9 below. I let you guess which one is Firefox ;-)

```HTML
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//releases.flowplayer.org/6.0.5/skin/minimalist.css">
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//releases.flowplayer.org/6.0.5/flowplayer.min.js"></script>
  <script type="text/javascript">
    $(function() {
      var playerElement = $('.flowplayer');
      var player = flowplayer(playerElement);
      player.on("ready", function() {
        player.seek(5, function(){
        });
      });
    });
  </script>
</head>
<body>
  <div class="flowplayer" data-rtmp="rtmp://rtmp.flowplayer.org/cfx/st/" data-ratio="0.5625">
    <video>
      <source type="application/x-mpegurl" src="//cdn.flowplayer.org/273627/135446.m3u8">
      <source type="video/webm" src="//cdn.flowplayer.org/273627/135446.webm">
      <source type="video/mp4" src="//cdn.flowplayer.org/273627/135446.mp4">
      <source type="video/flash" src="mp4:273627/135446.mp4">
    </video>
  </div>
</body>
</html>
```

![capture d ecran 2016-04-21 a 15 13 28](https://cloud.githubusercontent.com/assets/54219/14710017/fadcf830-07d3-11e6-98e6-c0d7a875071f.png)
![capture d ecran 2016-04-21 a 15 13 32](https://cloud.githubusercontent.com/assets/54219/14710020/faf99b8e-07d3-11e6-962b-63b1ad822412.png)
![capture d ecran 2016-04-21 a 15 13 42](https://cloud.githubusercontent.com/assets/54219/14710019/faf81d5e-07d3-11e6-8192-f8e57381f871.png)
![capture d écran 2016-04-21 a 15 13 38](https://cloud.githubusercontent.com/assets/54219/14710021/fafcd3c6-07d3-11e6-85aa-7326a77be716.png)

Where would you advise me to look for support now?

**Comment by blacktrash** [comment]
Check the docs for the `seekmode` flashls option: https://flowplayer.org/docs/setup.html#flashls - by default in flashls the player seeks to the nearest keyframe.
So you want to set this to `"ACCURATE"` - but check first whether the behavior change on resume suits you.
Better yet: additionally load the hlsjs plugin - https://flowplayer.org/docs/plugins.html#hlsjs - and the problem will go away in most modern browsers, as flash hls is not used. See also the settings on comments for this demo: http://demos.flowplayer.org/scripting/preview.html

So, I advise you to look for support first in our public forum in the future http://flowplayer.org/forum/ as questions like this are important and of interest for other users too ;-)

**Comment by groue** [comment]
OK @blacktrash. Thanks for your time, your tips, and your links!
