### ISSUE TITLE
'KeyboardEvent.keyLocation' is deprecated in chrome

### ISSUE THREAD

**Issue by shaunbowe** [flowplayer/flowplayer#1016]
Open any demo of flowplayer in chrome and see this error in the console:
'KeyboardEvent.keyLocation' is deprecated and will be removed in M50, around April 2016. Please use 'KeyboardEvent.location' instead. See https://www.chromestatus.com/features/4997403308457984 for more details.

Example: https://flowplayer.org/demos/layout/

**Comment by bbbo** [comment]
duplicate of #1008

Not a problem ;)
