### ISSUE TITLE
How to pass a variable to the "sourse"

### ISSUE THREAD

**Issue by flijloku** [flowplayer/flowplayer#1019]
How to pass a variable "s" to the "sourse" of this type:
`"http://hls.goodgame.ru/hls/" + s + ".m3u8"`
For example in Clappr.Player it worked like this:

```
 <div id="player"></div>
 <script type="text/javascript" src="http://cdn.clappr.io/latest/clappr.min.js"></script>
 <script>
 var player = new Clappr.Player({source: "http://hls.goodgame.ru/hls/" + s + ".m3u8", parentId: "#player", width: "25%", height: "25%"});
 </script>
```
In dash.js it worked like this:
```
 <script src="/js/dash.all.min.js"></script>
 <script>
 (function(){
 var url = "http://hls.goodgame.ru/dash/" + s + "/index.mpd";
 var player = dashjs.MediaPlayer().create();
 player.initialize(document.querySelector("#videoPlayer"), url, true);
 })();
 </script>
```

but no longer works.
Is it possible to make similar in Flowplayer?
Links kind http://hls.goodgame.ru/hls/4423.m3u8 works in Flowplayer.

**Comment by blacktrash** [comment]
@flijloku - this the the Flowplayer _bug tracker_. Usage questions should be asked in our public forum, so it's good you did exactly that here: https://flowplayer.org/forum/#!/setup:how-to-pass-a-variable-to-t

Closing.
