### ISSUE TITLE
flash: utf http media locations are not found

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1020]
Looks like https://github.com/flowplayer/flowplayer/issues/162 was not solved completely, or a regression crept in: http://flowplayer.blacktrash.org/fp6/utf.html

RTMP works, but that does not help with Flash HLS (will create a hls location as well).

**Comment by blacktrash** [comment]
Regression introduced in 6.0.2 - on the other hand 6.0.2 made RTMP locations work.
Ideally both should work.

**Comment by nnarhinen** [comment]
http://flowplayer.blacktrash.org/fp6/utf.html All work for me in Chrome..

**Comment by bbbo** [comment]
even works in IE9 ;)

**Comment by blacktrash** [comment]
Not in Firefox (Mac).
Not in Safari (Mac) (for Safari 10 Flash has to be enabled).
As denoted on the page.
