### ISSUE TITLE
Android 4.4.4 stock browser won't play HLS

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#1022]
I'm using Android 4.4.4, SamsungBrowser/2.0 Chrome 34.0.1847.76. HLS should work since Android 4.3 I think.

I discovered that it doesn't work on my mobile - not sure if it's a Samsung - specific bug or not. I setup a demo here: http://foliovision.com/html/fp-hls.html

1) First player just won't let me play the video as it's a bare html5 video tag

2) Player number 2 works for me - with the HLS m3u8 URL in the video tag as the src attribute.

3) Flowplayer doesn't play the video if it's in source tag nested in video tag

4) Flowplayer doesn't play the video even if it's in src attribute in video tag - like it works without Flowplayer in player number 2.

Can you fix it so that the demoe number 3 works?

**Comment by blacktrash** [comment]
4) will fail because fp expects `src` as `source` attribute
1) is arguably a bug in the Samsung browser
2) is what Flowplayer does internally - so: does it work with a JavaScript install where the browser doesn't see the bare video tag?

**Comment by blacktrash** [comment]
At http://demos.flowplayer.org/basics/hls.html - the stock browser fails over to webm in the Android 4.4 I'm testing. And at http://demos.flowplayer.org/videotest/canplay.html it reports it cannot play `application/x-mpegurl`.

**Comment by foliovision** [comment]
1) & 2) & 3) Works on Android 4.3 Huawei. So this looks like a Samsung Android stock browser bug. Can you make it work?

Thanks,
Martin

**Comment by blacktrash** [comment]
Behaviour-wise it's not a bug: it says it cannot play HLS, and it doesn't.
Personally, I'm not sure whether it's worth introducing a special involved client-detection case, not the least because it often works in Android 4.4 stock browser on other devices.

**Comment by nnarhinen** [comment]
If HLS does not work in the plain video tag in Android it won't work in the Flowplayer html5 engine either. Broken devices are broken.

**Comment by blacktrash** [comment]
Well, it works 'accidentally' if a) one ignores the negative canPlay result (that's why it doesn't in Flowplayer 6 in a JavaScript install) and b) if you don't nest a source tag (which is expected for video tag based installs). - So, in theory one could work around this with a sophisticated client detection, but the risk of false positives in clients which behave correctly is too high imho, not the least use of the OS version will peter out rather sooner than later.

**Comment by nnarhinen** [comment]
I'm not willing to add this client detection to Flowplayer core, but as a workaround monkey-patching the `canPlayType` works:

![image](https://cloud.githubusercontent.com/assets/265438/15361893/1716606a-1d1c-11e6-9b71-7e75ddec4a0b.png)

Of course you want to add some conditions when to start supporting `application/x-mpegurl`
