### ISSUE TITLE
unload in paused state: browser continues to buffer

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1025]
When the player is unloaded in paused state, browsers continue to buffer the video.
Obviously also affects shutdown, potentially with serious consequences: https://flowplayer.org/forum/#!/setup_configuration:memory-leak-even-after

Could be worked around with something like this in unload:
```js
if (api.paused) { // probably some more conditionals, not hls etc
  api.one("resume", function () {
    api.unload();
  });
  api.resume();
} else {
  api.unload();
});
```

- tested so far in desktop Chrome, Firefox, Safari with MP4 and WebM sources.
- does not happen with hls.js or flash hls
- not tested so far with generic Safari HLS because segment traffic is hidden in application
- not tested on mobile devices and other browsers

**Comment by nnarhinen** [comment]
Please provide a demo with no HLS.js included.

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/lookandfeel/loading-custom.html - start the player with network console open, and then hit `q` to unload: mp4 continues to buffer.

**Comment by nnarhinen** [comment]
Can't reproduce:

![image](https://cloud.githubusercontent.com/assets/265438/15630081/0bf230c6-2535-11e6-80f9-749cd6b676d1.png)

**Comment by theone00** [comment]
@nnarhinen - Are you sure you shutdown the player in **PAUSED** state?

1.) Start playback
2.) Pause the player
3.) Shutdown the player

Network request will continue.

**Comment by nnarhinen** [comment]
@theone00 does not make a difference:

![image](https://cloud.githubusercontent.com/assets/265438/15631110/adc2b5f4-255f-11e6-864e-c9e37f9811ce.png)

**Comment by nnarhinen** [comment]
Also, `unload` in a splash setup removes the video tag with its sources. If the removal of the video tag does not stop sources from loading then I'd be inclined to deem as a browser bug.

**Comment by theone00** [comment]
If it is a "browser bug" then it sure is ironic that it occurs in ALL of the browsers I've tested (Chrome, FireFox, Safari).

Not to mention everyone that I have had test this problem experiences the same results, including two of your moderators.

The get request to the video is not terminated (in ANY browser) when the player is shutdown in paused state.

**Comment by nnarhinen** [comment]
Did you look at my screenshot? From what I can tell there are no HTTP requests pending after calling `unload` or are there?

**Comment by theone00** [comment]
I saw the screenshot but there would be no way for me to determine (based on a static image) if the request was terminated or not because that would require witnessing the progression of the network monitor.

**Comment by nnarhinen** [comment]
From the screenshot you can see the steps I made. Please redo them and tell if your browser continues buffering.

**Comment by theone00** [comment]
Allow me explain again the steps that I take to consistently recreate this problem in Chrome.

1.) Goto http://demos.flowplayer.org/lookandfeel/loading-custom.html
2.) Click the player to start playback.
3.) Click the player to pause the video.
4.) You will see request to the video progressing in the network monitor
5.) Press "q" to unload the player

..... the network request to the video is never terminated and the download continues to progress. 

However, if you unload the player while the video is in play state, the request is terminated immediately as it is supposed to.

**Comment by nnarhinen** [comment]
Ok I now understand what you mean. Still, this is arguably browser behaving badly. On `unload` flowplayer removes the video element (you can inspect the DOM tree). Why the browser does not stop buffering is beyond me. Unfortunately there is no method in the spec to abort loading media. Maybe we can come up with a decent workaround. 

Googling with some related keywords I found this: http://stackoverflow.com/questions/4071872/html5-video-force-abort-of-buffering 

We might have to do dirty things like setting the `src` attribute to an empty string and then force loading of that empty string. That will trigger a console error but I fear that cannot be avoided.

**Comment by blacktrash** [comment]
I concur this is weird browser behaviour, but as it's 'consistent' in all browsers I tested, something like the workaround from https://github.com/flowplayer/flowplayer/issues/1025#issue-156052903 - probably directly on the video tag - makes sense imho: force play after setting up a once callback to unload.

**Comment by theone00** [comment]
@blacktrash - There is a problem with your solution because although it terminates the video, it does not terminate the audio so when the player has been shutdown and removed, the audio continues to play.

**Comment by blacktrash** [comment]
@theone00 - there are even deeper problems. At least Firefox _always_ continues to buffer when the VOD is WebM, so the 'workaround' would only apply to MP4: http://flowplayer.blacktrash.org/fp6/long.html plays WebM and video continues to buffer also when you unload in playing state.

@nnarhinen - looks like setting `src` to empty string may help, hls.js was in the reverse situation, and does now both: https://github.com/dailymotion/hls.js/pull/277

I'll try and see what happens.

**Comment by blacktrash** [comment]
Yup. That seems to do the trick: http://flowplayer.blacktrash.org/fp6/long.html

**Comment by blacktrash** [comment]
The only drawback I can see is a console warning in Firefox: 'Invalid URI. Load of media resource failed.'  But that should be harmless.

**Comment by theone00** [comment]
OK, thanks! That looks promising, I'll use that.
