### ISSUE TITLE
Flash: narrow down scope of issue 922 hack

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1027]
We should try to narrow down the scope for #922:
- only trigger it with container dimensions below the critical margins - probably those have to be determined in practice unless there's an official Chrome doc somewhere
- confine to Chrome only

For instance http://demos.flowplayer.org/scripting/signed-ondemand.html?forceflash breaks on replay because of the hack in _all_ browsers - v5 without the hack works: http://demos.flowplayer.org/v5/scripting/signed-ondemand.html?forceflash

So the wide scope of the hack is rather annoying or breaking for the majority of cases with the purpose of catering for a minority (small container).
If narrowing the scope is too error prone, we should consider removing the hack, or wrapping it in an option.

**Comment by blacktrash** [comment]
@nnarhinen - the signed url example is bad because the problem seems to be caused by a change in RTMP behaviour in fp6, it probably requests again (can be worked around in demo).
However, as one gets the 'click player area to enable' message unnecessarily in the majority of cases (also with Flash HLS), I still consider this a valid issue.

**Comment by nnarhinen** [comment]
Please tell the reproduce steps with a simple demo where this happens.

**Comment by blacktrash** [comment]
If you use Flash HLS a lot it happens quite often, for instance with the quality selector when you switch back to Flash HLS at http://demos.flowplayer.org/scripting/qsel.html
<img width="435" alt="screen shot 2016-05-26 at 4 41 35 pm" src="https://cloud.githubusercontent.com/assets/168338/15578476/e05fd542-2360-11e6-9bb4-090a600ba2af.png">

**Comment by nnarhinen** [comment]
Can't see the message on that url. But I can understand it might happen, as it's a simple timer. Maybe as a first aid we have to make the treshold longer.

**Comment by blacktrash** [comment]
It definitely does happen, and very often, and in the described circumstance (switch back to 'Auto' with flash hls) basically all the time for me[tm]. Another scenario is http://demos.flowplayer.org/api/live-check.html#javascript-setup - where the message is hidden on purpose because it was confirmed by others too.

**Comment by blacktrash** [comment]
Here's another scenario: http://flowplayer.blacktrash.org/fp6/signed-ondemand.html?forceflash (same as http://demos.flowplayer.org/scripting/signed-ondemand.html?forceflash - but with `rtmp: true, proxy: "CONNECTOnly"` (proxy setting not required to repro, demo for customer) - play, seek to end of video: unusable on replay because it does not trigger the intended error which in turn triggers a new ajax request.
