### ISSUE TITLE
Allow seeking as low as 10ms

### ISSUE THREAD

**Issue by VarunAgw** [flowplayer/flowplayer#1034]
Currently it allow minimum seek of 100ms. I feel 10ms min seek will excellent if I need to emulate frame by frame seek (It will support as high as 100fps videos).

         seek: function(time, callback) {
            if (api.ready && !api.live) {

               if (typeof time == "boolean") {
                  var delta = api.video.duration * 0.1;
                  time = api.video.time + (time ? delta : -delta);
               }
               time = lastSeekPosition = Math.min(Math.max(time, 0), api.video.duration - 0.1).toFixed(1);
               var ev = api.trigger('beforeseek', [api, time], true);
               if (!ev.defaultPrevented) {
                  engine.seek(time);
                  if (isFunction(callback)) api.one("seek", callback);
               } else {
                  api.seeking = false;
                  common.toggleClass(root, 'is-seeking', api.seeking); // remove loading indicator
               }
            }
            return api;
         },

Note the line:

               time = lastSeekPosition = Math.min(Math.max(time, 0), api.video.duration - 0.1).toFixed(1);

It should be replaced with

               time = lastSeekPosition = Math.min(Math.max(time, 0), api.video.duration - 0.1).toFixed(2);

**Comment by blacktrash** [comment]
See #1000
Basically it has to be re-investigated whether `toFixed` is needed at all. It was introduced here: https://github.com/flowplayer/flowplayer/commit/b6968045449e19d50bf5472322ee681720f802f6 - so extensive tests on iPad would be required.

**Comment by nnarhinen** [comment]
Closing in favor of #1000
