### ISSUE TITLE
first frame JS setups do not catch all errors

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1039]
For instance error 10 is not triggered when the error listener is set up locally and splash is false:
https://flowplayer.org/forum/#!/scripting_api:js-events-error-code-10
What makes it more confusing that the issue seems to affect Windows Chrome and Firefox only.

Can be worked around by setting up the error listener globally. So it should be possible to set up the error trigger earlier in flowplayer.js? Is canPlay a good place?

**Comment by nnarhinen** [comment]
Can you add a bug demo to demos.flowplayer.org?

I think the video tag fires the error event before flowplayer starts listening and we miss it. Maybe we should check the `readyState` of the video tag or such.

**Comment by nnarhinen** [comment]
http://demos.1067f.flowplayer.me/bug/1039.html
