### ISSUE TITLE
analytics: update to analytics.js ?

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1040]
As per https://flowplayer.org/forum/#!/embedding_analytics:google-analytics-in-chrome recent Chrome may cancel ga.js events: http://prntscr.com/bt86o0 at least on Windows 10.
In theory this should be replicable at https://flowplayer.org/standalone/complete.html - but I can't. @bbbo, could you check?

Also note that analytics.js is lacking features of ga.js: http://stackoverflow.com/questions/17361992/google-analytics-events-canceled#comment-25342808

**Comment by bbbo** [comment]
@nnarhinen I guess we can close this as there will be no 7.3?
