### ISSUE TITLE
Flash (not flash hls): no events after finish

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1041]
To reproduce:
- go to http://demos.flowplayer.org/basics/rtmp.html
- play or seek until finished
- seek to somewhere: playback starts, but paused state is sticky (playbutton visible)
- returns to 'normal' only after pausing

See: https://flowplayer.org/forum/#!/scripting_api:rtmp-seek-after-finished-n

**Comment by blacktrash** [comment]
Actually this is not RTMP specifc, but Flash (flowplayer.swf - not flash hls) specifc.
Similar probs at http://demos.flowplayer.org/basics/flv.html

**Comment by nnarhinen** [comment]
https://github.com/flowplayer/flowplayer/blob/master/lib/engine/flash.js#L180 Most likely about this line. It does not send the progress events and thus finished state does not go away or something like this.

**Comment by blacktrash** [comment]
As it does not happen with flash hls, I believed the problem would be in flowplayer.swf; I'll check whether something can be tweaked in the JS API.

**Comment by blacktrash** [comment]
It's actually not only the events. Once one seeks in finished state, no api call has any effect anymore.

Something like this keeps the player in usable state:
```js
flowplayer(function (api) {
  api.on("beforeseek", function (e, api) {
    if (api.finished && api.video.type.toLowerCase() === "video/flash") > -1 {
      api.one("resume", function (e, api) {
        api.pause();
      });
      api.resume();
    }
  });
});
```

**Comment by nnarhinen** [comment]
@blacktrash take a look at http://demos.1066f.flowplayer.me/basics/flv.html

Seems the seek problem after finish is at least fixed. Can you confirm the other issues too?

**Comment by blacktrash** [comment]
@nnarhinen LGTM. - The progress bar does not update when you seek via keyboard until resuming, but then it never did.
