### ISSUE TITLE
deprecated KeyboardEvent.keyIdentifier M53 (chrome)

### ISSUE THREAD

**Issue by RaphaelYan** [flowplayer/flowplayer#1042]
Hi, due to the last Chrome update, I got this :
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by blacktrash** [comment]
@RaphaelYan - iirc this is an innocent warning, because Flowplayer _tries_ this for bw compatibility.
