### ISSUE TITLE
Flowplayer doesn't play when video width is small on Google Chrome

### ISSUE THREAD

**Issue by hadilnc01** [flowplayer/flowplayer#1046]
Hello, I've noticed that the video doesn't play when its width is smaller than 370px. For example, in on this site:
http://babyarabia.digitalcups.com/en/

There are 6 posts on the top. The second row contains 2 videos: one on the left and one on the right. Neither one of these videos plays when on Google Chrome. They only play if I increased their width or if I enlarge the video and then minimize it. Any idea on how I can solve this?

**Comment by nnarhinen** [comment]
This would be #922

**Comment by nnarhinen** [comment]
Most likely will be fixed by using the [hls.js plugin](https://flowplayer.org/docs/plugins.html#hlsjs) to avoid usage of flash that Google is trying to kill.

**Comment by hadilnc01** [comment]
Ok thank you!
