### ISSUE TITLE
load() loses buffer

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1047]
After an explicit `load()` of the current video, `api.video.buffer` is and stays `undefined`.

Could be that `player.buffer` is not fired or `vtag.buffered` not listened to for some reason.

See: https://flowplayer.org/forum/#!/setup:flow-player-buffering-issue

**Comment by nnarhinen** [comment]
It's not only the current video, all `load()` calls seem to do this. You  can observe the same thing with any playlist setup: http://demos.flowplayer.org/playlist/minimal.html

**Comment by nnarhinen** [comment]
When flowplayer/flowplayer-hlsjs#51 is merged, this can be tested at http://demos.1068f.flowplayer.me/playlist/minimal.html

**Comment by blacktrash** [comment]
@nnarhinen - http://demos.1068f.flowplayer.me/playlist/minimal.html behaves now better indeed. The buffer fills visibly also for other clips than the first one.
