### ISSUE TITLE
webkit-playsinline attribute for mobile Safari 10

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1048]
Apparently mobile Safari 10 supports inline playback and autoplay of videos w/o audio track on iPhones when `webkit-playsinline` attribute is added:
https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html#//apple_ref/doc/uid/TP40014305-CH11-DontLinkElementID_12

inline playback should not be that much of a problem, but autoplay because of enforced splash setup. In theory this would allow several players to autoplay as well.

**Comment by danrossi** [comment]
Is this still valid ? I had to add a hack plugin to inject a custom video tag to get the attribute added an example is below. 

Thankfully custom video tags can be injected and the engine still works. That is how I get crossorigin attributes added too because they get removed which break CORS features. 

Of course IOS10 have added the option although CORS is still busted. It's also needed for Cordova and "pinned" WebView apps. 

https://github.com/danrossi/flowplayer-inlinevideo

**Comment by nnarhinen** [comment]
Yes, support for inline playback on recent iPhones will be added in 7.0.

What comes to the `crossorigin` attributes, in #993 I asked for a link to a misbehaving setup, you didn't provide one. So from my perspective there is no problem with crossorigin attributes.

**Comment by atecarlos** [comment]
@nnarhinen do you have a timeline for the release of 7.0 ?

**Comment by nnarhinen** [comment]
As always with software, "When it's ready". ;) Seriously speaking: There's no fixed timeframe yet. I'd say mid-November is a realistic guess. You can check the Milestone progress to see what's on the table before release. After issues have been finished there's an overall testing phase along with documentation updates.

**Comment by foliovision** [comment]
The fix from @danrossi works, but when you exit fullscreen the video stops. We tested that some more and created a pull request with the fix in core Flowplayer #1069

**Comment by parisholley** [comment]
this would be a huge win for us to begin monetizing mobile ios traffic!

**Comment by nnarhinen** [comment]
http://demos.1075f.flowplayer.me/

**Comment by danrossi** [comment]
@nnarhinen the crossorigin attribute is needed for drawing the video to canvas and /or WebGL canvas. It needs to be set before a source is added. I don't have much time to check back so sorry about that mate. 

Of course for Safari and IE11 it needs a CORS proxy although Safari 10 reports it supports the attribute but it really doesn't, not even in macOS.

**Comment by danrossi** [comment]
My hack won't work because they have felt like randomly removing the prefixes now. It's just 

```playsinline 
```
for IOS 10. I just tested it.
