### ISSUE TITLE
looping hls does not work on iOS

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1050]
Important: this is not a Flowplayer bug! But how do we deal with the issue?

Video tag demo: http://flowplayer.blacktrash.org/test/videotag-hls-loop.html - also features an official Apple stream which exhibits the same problem.
- the ended event is not fired when the loop attribute is set on the video tag
- when playback ends, player is in playing state, not paused state
- does not happen on the Android devices I tested, they also work with Flowplayer as expected

Workaround:
- remove `loop` attribute (ended/finish event will be triggered)
- `videoTag.play()` aka `api.resume()` on ended/finish - see http://flowplayer.blacktrash.org/test/videotag-hls-loop.html#workaround

**Comment by blacktrash** [comment]
I have encountered this with some streams also in native playback.
*If* something like the above workaround helps, it would be good to have this working ugly but reliable.

**Comment by nnarhinen** [comment]
> I have encountered this with some streams also in native playback.

Native as in?

**Comment by blacktrash** [comment]
Native as in a plain video tag.
