### ISSUE TITLE
embed: propagate splash or poster setting

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1054]
see
https://flowplayer.org/forum/#!/embedding_analytics:poster-does-not-show-up-whe

actually especially propagating a splash setup makes sense because it (hopefully) prohibits preloading of embedded videos on page load, and hence streaming costs for users

**Comment by nnarhinen** [comment]
39c014373914e0a647bf36d29e4864d5281f40b4 makes all embeds iframe embeds and thus fixes this.
