### ISSUE TITLE
embed: offer config option for custom embed codes

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1055]
by user demand, consider offering an option

   ` embedCode: "somehtml"`

in the clip/sources configuration
which can contain a custom embed html like a `<script>` tag instead of `<iframe>`, showing whatever the user deems needful in the `<>` embed button of the player.

(quoting user)

in the player code we have

    if (embedConf.iframe) {
        var src = player.conf.embed.iframe,
           width = embedConf.width || video.width || common.width(root),
            height = embedConf.height || video.height || common.height(root);
         return '<iframe src="' + player.conf.embed.iframe + '" allowfullscreen style="width:' + width +     ';height:' + height + ';border:none;"></iframe>';
      }
   
It should be pretty easy to add:

    else if (embedConf.code) {
           return embedConf.code;
    }

which reads the embedCode string/varchar from the configuration.

**Comment by nnarhinen** [comment]
This is already possible:

```js
flowplayer(function(api) {
  api.embedCode = function() {
    return '<div>My embed</div>';
  };
});
```

**Comment by bbbo** [comment]
@nnarhinen we want things to be easy, so: include in core please

**Comment by nnarhinen** [comment]
There is no easy way of doing this so that it works for everyone.

If there would be a `code` config property, it would have to be a templated string. This is such a complex area that people without some coding experience couldn't use the configuration property.

**Comment by nnarhinen** [comment]
also:

```js
flowplayer('#player', {
  clip: { ... }
}).embedCode = function() {
  return '<div>My custom embed code</div>';
};
```

as core as it gets - the embed code (without some templating mechanism) could not be configured in global configuration anyway.
