### ISSUE TITLE
Flowplayer zoom issue

### ISSUE THREAD

**Issue by RopoMen** [flowplayer/flowplayer#1056]
Hi,

I'm using Reveal.js with Flowplayer and noticed that Flowplayer is not working perfectly when zoom / scale is used (depends on the browser which can be used)

If you seek from timeline the mouse cursor position and timeline percentage value are not looking correct. Also shown time is not in right position.

I made JSFiddle about this [issue](https://jsfiddle.net/RopoMen/cpjc5bkj/)

I made this fiddle with Mac+Chrome, but it is broken also in Windows+Chrome and Mac+Safari. Mac+Firefox will work correctly.

**Comment by nnarhinen** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=429140 This is most likely related

**Comment by nnarhinen** [comment]
http://codepen.io/anon/pen/gwvQEp?editors=1111

simple reproducable fiddle..

**Comment by nnarhinen** [comment]
We are not alone with the problem: https://github.com/zeroclipboard/zeroclipboard/issues/149

**Comment by nnarhinen** [comment]
http://codepen.io/anon/pen/LRQrAV?editors=1111 This seems to fix this, will try to apply to flowplayer code.

**Comment by nnarhinen** [comment]
Ok, so here are the symptoms:

 * `common.width(root)` is off by the zoom factor
 * `common.width(timeline)` is nothing seemingly reasonable

As much as I'd like to fix this properly I must deem this a browser bug and the only decent workaround is to enforce `zoom: 1` for the root element.

**Comment by nnarhinen** [comment]
Buggy zoom: http://demos.dev94.flowplayer.us/bug/1056.html
Enforced zoom: 1: http://demos.1058f.flowplayer.me/bug/1056.html

**Comment by RopoMen** [comment]
Good catch. I was looking in to YouTube iframe embed and why it's working correctly. Reason is that zoom: 1; because iframe has its own document and its default zoom is 1. And because fp is not embedded inside iframe, you need to force zoom: 1 in fp root elem. TY!
