### ISSUE TITLE
[Chrome] playlist: error on resume when last clip is in finished state

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1063]
https://flowplayer.org/standalone/playlist/javascript.html (no plugins)
- finish last clip
- resume by clicking or typing space or `flowplayer(0).resume()` in the console

yields:
```
flowplayer.min.js:6 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request
```
Which describes the problem exactly: play() is requested on the last clip, but interrupted by loading the first.
Proof: entering `next()` in the console does not trigger the error. Or resuming when the playlist has length 1.
Obviously does not happen either when advance is false.

A fix most likely has to be cross-checked in the Flash engine.

**Comment by nnarhinen** [comment]
I'm introducing a `beforeresume` event that can be canceled with `ev.preventDefault()`

**Comment by nnarhinen** [comment]
http://demos.1070f.flowplayer.me/playlist/minimal.html

**Comment by blacktrash** [comment]
Great!
Also tested successfully with dashjs.
