### ISSUE TITLE
Player freezing after url changed

### ISSUE THREAD

**Issue by bodzin89** [flowplayer/flowplayer#1071]
Hello! I've encountered with error: the video player is freezing on changing URL. It happens, when player at "play" state, and user clicks on a different link. 

We using flowplayer hls.js plugin.

You can try it. [link](https://jsfiddle.net/bodzin/gopy9jaL/1/)

I've tested it on:
OS: macOS Sierra
Browser: Chrome/Firefox

Also, our QA engineer said, that it happens on all platforms.

**Comment by blacktrash** [comment]
Thanks. A regression sneaked in. Works again now.
