### ISSUE TITLE
mute() may have no effect from within ready event

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1073]
- automatic install: never works
- manual install and javascript install: does not work from global function, but does work when grabbing api right after install or when chained to install script

See: https://flowplayer.org/forum/#!/setup:muteunmute-in-the-ready

**Comment by nnarhinen** [comment]
@blacktrash can you try with assets from http://demos.1081f.flowplayer.me/

**Comment by blacktrash** [comment]
@nnarhinen - looking good.
