### ISSUE TITLE
resume after seek on playlist finish starts first clip

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1077]
Setup: playlist with `advance: false, loop: false`.
1. play last clip until finished
2. seek to a position before end in paused state
3. resume

The resume in step 3 should resume from the position, instead it loads the first clip in the playlist.

Can be verified (example without engine plugin to show it's a core issue) for instance at https://flowplayer.org/demos/playlist/#js_demo

**Comment by nnarhinen** [comment]
Can we have a bug demo under demos.flowplayer.org thanks (or url to a demo where this is visible there) thanks :)

**Comment by blacktrash** [comment]
@nnarhinen - do you need this without hlsjs plugin? Otherwise any old playlist will do, like http://demos.flowplayer.org/playlist/minimal.html

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/playlist/ratio.html - but that contains also the RTMP bug (which is fixed in dev though).
I'll create an addtional issue demo.

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/bug/1077.html once it has propagated.

**Comment by nnarhinen** [comment]
http://demos.1083f.flowplayer.me/bug/1077.html

**Comment by blacktrash** [comment]
There must be something entirely different regarding playlist styling, it's completely gone in the fp7 version.

**Comment by nnarhinen** [comment]
Yes, the `.flowplayer` container has `overflow: hidden` which prevents elements being drawn outside the container
