### ISSUE TITLE
Freezing on first start in IE when opening the site locally

### ISSUE THREAD

**Issue by russlanz** [flowplayer/flowplayer#1078]
When the site is opened locally IE plays the sound but not the video and the site is stuck for about 40 seconds, after which the video appears.
When the site is open from the web server everything is ok.
We investigate that behavior and found that when started from local drive IE sends request to ip addreses in 52.222.174.x network to port number 445 (i.e tries to open a resource using file:// protocol)
We believe this is caused by the following fragment in flowplayer.js (v6.0.5) line 3614:

backgroundImage:"url("+[".png","logo","/",".net",".cloudfront","d32wqyuo10o653","//"].reverse().join("")+")"

For some reason IE interprets this url as file://d32wqyuo10o653.cloudfront.net/logo.png
After removing it the player works fine locally.

**Comment by bbbo** [comment]
You are not allowed to remove any of the branding code, this is a violation of the license.

Flowplayer is not designed to be run locally without a webserver anyway; if it works fine, but if not: do not alter the code!

**Comment by russlanz** [comment]
Yes, of course, i removed it only for testing purposes!
The point was that because of a bug in IE, it interprets the url as a file location, and if the protocol "https:" is specified the player will run fine locally also.
But if flowplayer is not designed for using locally, my comments are irrelevant of course.

**Comment by blacktrash** [comment]
@russlanz - it's rather how HTML5 video works. If you want to play local files use an approach like this: http://demos.flowplayer.org/scripting/filereader.html
