### ISSUE TITLE
Unload() ability without splash or ability to play multiple videos in splash mode.

### ISSUE THREAD

**Issue by KallDrexx** [flowplayer/flowplayer#1084]
We have a dashboard that has multiple flowplayer instances showing videos simultaneously from live sources.  There are times when these players need to be fully destroyed and completely removed.

As it currently is described [in the documentation](https://flowplayer.org/docs/setup.html#splash), I cannot use splash mode because splash causes only one video player to be active at any given time.

The problem is that `flowplayer.unload()` and `flowplayer.shutdown()` do not trigger in non-splash mode.  What this means is that the code to stop hlsjs is never executed so the browser keeps iterating through the hls playlist (including downloading new hls segments) even though I no longer have a reference to the flowplayer instance.  

The only way I have gotten around this is to manually call the engine specific call `flowplayer.engine.hlsjs.stopLoad()`, but I do not like the idea that any engine I use I might have to have custom code to fully stop it. 

Ideally this can be handled either by:

1. I can have multiple flowplayer instances in splash mode actively playing video at one time on a single HTML page (can't use iframes for each)
2. Calling `flowplayer.unload()` works correctly to unload the video player and propogate the unload call to any active engine calls.

More background on this can be seen in [this hlsjs plugin issue](https://github.com/flowplayer/flowplayer-hlsjs/issues/57#issuecomment-262622545)

**Comment by nnarhinen** [comment]
I think `flowplayer(0).shutdown()` will actually remove all event handlers etc on first frame setups too, you just need to remove the HTML elements by hand.
