### ISSUE TITLE
mute/volume inconsistent (localStorage)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1087]
http://flowplayer.blacktrash.org/fp6/overlay-fancybox-noplug.html

1. load overlay/player
2. mute player
3. close overlay/shutdown player
4. load overlay/player

Expected: player is muted
What happens: mute button crossed out, but volume is full - reflecting wrong localStorage values

See: https://flowplayer.org/forum/#!/scripting_api:localstorage-setting-being

**Comment by nnarhinen** [comment]
Can I have a bug demo for this in demos.flowplayer.org (dev branch prefered)

**Comment by blacktrash** [comment]
Seems to work in dev.

**Comment by blacktrash** [comment]
But setting explicitly `muted: false` in config does not override localStorage in dev either.
Demo bug/1087.html in dev.
See: https://flowplayer.org/forum/#!/setup:mute-state-seems-to-be-save

**Comment by nnarhinen** [comment]
If a user has explicitely muted the player, no configuration should override that (the user does not want sound).

**Comment by blacktrash** [comment]
ok - feels wrong to me, but so be it.
