### ISSUE TITLE
FlowPlayer messed up with Date.parse function

### ISSUE THREAD

**Issue by victordidenko** [flowplayer/flowplayer#1088]
Hello!

We are using DateJS library to parse our dates. DateJS library changes Date.parse() function to return Date instead of Number. I understand that is not a proper behavior, and this is not compliant with standard .parse() method behavior, but library is kinda old, and this behavior is expected and well documented!

When we've added FlowPlayer to our project, we discovered, that it changes Date.parse function as well.
Here is example: https://jsfiddle.net/za0d02rm/

Well, my point is: FlowPlayer is NOT a Date library, do not change Date object! Use simple clean functions inside, if you need them, don't change standard objects, let alone without documenting such behavior.

**Comment by nnarhinen** [comment]
We are shimming ES5 features for ancient browsers like IE8. You should just include flowplayer before datejs and you should be good to go.

**Comment by victordidenko** [comment]
Unfortunately, we cannot. In our case we have FlowPlayer loaded only for some browsers, not for all of them. And when player is needed -- it is loaded asynchronously, always after DateJS.
