### ISSUE TITLE
make engine source option persist in video tag based playlists

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1090]
This would be a nice to have in certain scenarios, e.g. http://demos.flowplayer.org/api/speed.html or,  temporarily in dev, /playlist/adverts-in-playlist.html

Pro:
- HTML playlists already are based on inference of file naming and type
- there are only 3 source options
- `engine`, if given, should persist as `type` does

**Comment by nnarhinen** [comment]
I'm not sure what this means?

**Comment by blacktrash** [comment]
The idea is to keep the engine user preference in a HTML playlist over the default engine selection.

I now think this too exotic a use case, there are far more important things to focus on.

**Comment by blacktrash** [comment]
This one is far more important: https://github.com/flowplayer/flowplayer-hlsjs/issues/50
