### ISSUE TITLE
How to play multiple videos at the same time

### ISSUE THREAD

**Issue by kangty7812** [flowplayer/flowplayer#1093]
I use the hlsjs plugin to playplay HLS streams in browsers.
But when I click one video,the other one will stop automatically and so do the demo which I found in the offical website.

**Comment by bbbo** [comment]
Please use the forums for usage questions; the issue tracker is for bugs only.

You're probably using a splash setup, which by definition (see https://flowplayer.org/docs/setup.html#splash ) . Without splash you should be able to play multiple clips simultaneously. If you still encounter problems, please pots a link to *minimal* (player setups only) example page in the forums.
