### ISSUE TITLE
Full screnn is not working 

### ISSUE THREAD

**Issue by Gandhiselvaraj** [flowplayer/flowplayer#1095]
Using jquery i try to Enter but its nor working

`var flowPlayer = flowplayer(
	   "#"+playerName, {
		   splash: true,
		   autoplay: autoplayStatus,
		   embed: true,
		   ratio: 9 / 16,
		   cuepoints: [-10],
		   clip: {
			   hlsQualities: [
				   {
					   level: 0,
					   label: "563k"
				   },
				   {
					   level: 1,
					   label: "828k"
				   },
				   {
					   level: 2,
					   label: "2128k"
				   }
			   ],
			   hlsjs: {
				   smoothSwitching: false
			   },
			   sources: [{
					   type: "application/x-mpegurl",
					   src: "xxxxxx.m3u8"
				   }
			   ]
		   }
	   });

flowPlayer.bind("cuepoint", function(e, api,
	   cuepoint) {
	   api.fullscreen();}
});`

**Comment by bbbo** [comment]
please use the forums for usage questions. See also http://demos.flowplayer.org/scripting/instantfs.html

**Comment by Gandhiselvaraj** [comment]
how can add the autoplay in it??

**Comment by bndr25** [comment]
بتاريخ ١٠‏/٠١‏/٢٠١٧ ٩:١٥ ص، كتب "Gandhiselvaraj" <notifications@github.com>:

**Comment by blacktrash** [comment]
As the referenced demo and the docs for the `fullscreen()` method - https://flowplayer.org/docs/api.html#methods - explain, fullscreen toggle is only allowed when triggered by a user interaction.
Therefore this is not possible in conjunction with autoplay. This is not a player restriction. Browsers do not allow this.
