### ISSUE TITLE
Chrome: embed code sometimes not copied to clipboard

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1099]
For some reason at
https://flowplayer.org/docs/quickstart.html
the clipboard does not receive the embed code in Chrome - `embedCode()` works though.

While at
https://flowplayer.org/standalone/quickstart.html
clipboard _does_ receive the embed code.

Chrome 55.0.2883.95 (64-bit) on Mac.

**Comment by nnarhinen** [comment]
Fixed in dev
