### ISSUE TITLE
FP7: no controls with native_fullscreen on Android

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1100]
Please see
http://stylebites.de/fp7/hlsqualities.html

going to fs in Android Chrome, you cannot invoke the native controls.

**Comment by nnarhinen** [comment]
I propose we only support `native_fullscreen` on devices that do not support the "Flowplayer fullscreen" method - http://demos.1112f.flowplayer.me/basics/native_fullscreen.html

I guess it's namely iPad / iPhone then..

**Comment by blacktrash** [comment]
iPhones + iPods which do not support inline video, and all iOS from within an iframe.
See also: https://github.com/flowplayer/library-front/commit/8e14f2629408bfcb6ebdb0e441e990254964112b#commitcomment-20519342

**Comment by nnarhinen** [comment]
I think you are mixing something here now. Android Chrome supports "native fullscreen" as in the same fulllscreen as desktop chrome etc.

Mobile Safari does not support fullscreen for `<div>` elements and we use the simulated fullscreen on those devices. For these devices `native_fullscreen` configuration option was introduced - the simulated fullscreen is not always optimal and desired.

**Comment by nnarhinen** [comment]
But as there really is no need to use `native_fullscreen` on Android Chrome, we can just skip the option.

**Comment by blacktrash** [comment]
Thanks for explaining. I agree ;-)
