### ISSUE TITLE
Flowplayer 7 BUG: Casting from desktop to chromecast does not work

### ISSUE THREAD

**Issue by ckim44** [flowplayer/flowplayer#1103]
I am unable to cast the video to chromecast from my desktop PC to chromecast. I have tried this on any of the demo videos in flowplayer.org and it did not work. The chromecast would display a black screen with a blue chromecast symbol in the middle but the video would continue to play on my desktop (chrome).

I have tried the same thing on my Android and it does work successfully.

**Comment by ckim44** [comment]
This bug was not a result of flowplayer but a simple conflict with an extension I had on my end.

**Comment by tomnis** [comment]
@ckim44 i think im running into the same issue. just curious, which extension was in conflict?

**Comment by ckim44** [comment]
I thought it was an extension but it was not. My computer is simply too old and underpowered.

Hope that helps,
Chris

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
