### ISSUE TITLE
DVR seeking not possible with iOS

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1104]
https://flowplayer.org/forum/#!/setup:flowplayer-hls-dvr-support

**Comment by nnarhinen** [comment]
@blacktrash are you able to seek here http://demos.flowplayer.org/videotest/dvr.html ?

From my tests it would seem iPad does not support seeking live HLS streams..

**Comment by blacktrash** [comment]
If you go fullscreen, you can seek backwards by 30 second intervals. But you can't seek forward anymore. (iOS 9.2)
On iOS 8.4 for instance both buttons do nothing.
I also tested with other streams.
In other words, it varies from iOS version to iOS version and device to device :-(

**Comment by nnarhinen** [comment]
From console (osx safari devtools attached to the simulator) I'm able to actually seek within the `video.seekable.start(null)` and `video.seekable.end(null)` range. So this should be somehow fixable.

Have to revisit the logic how the seek offsets etc are handled..

**Comment by blacktrash** [comment]
In view of #1102 it may be useful to look into the _array_ of `video.buffered.start` as well (I think `video.buffered.end` is always `Infinity` in this case).
For hlsjs and dashjs VOD we cycle through the `end` array to obtain a buffer animation: https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L457-L474 - maybe there are several `start` here, and the highest one is reachable (beginning of DVR window). - Just a thought.

**Comment by nnarhinen** [comment]
Found the cause.

In https://github.com/flowplayer/flowplayer/blob/master/lib/engine/html5.js#L168-L170 we are calling `play()` on the videotag in a timeout. This makes iOS Safari not send progress events. Need to figure out why this was implemented in the first place and try to workaround it..

**Comment by nnarhinen** [comment]
From https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/ControllingMediaWithJavaScript/ControllingMediaWithJavaScript.html

> Note: On the iPad, Safari does not begin downloading until the user clicks the poster or placeholder. Currently, downloads begun in this manner do not emit progress events.

**Comment by nnarhinen** [comment]
Even though the wording is not clear to me, I guess this is somehow intentional from the mobile safari developers - if the video playback is started by javascript, then do not send `progress` event or something..

**Comment by blacktrash** [comment]
Maybe that entire section https://github.com/flowplayer/flowplayer/blob/master/lib/engine/html5.js#L164-L170 has to be revisited. I only remember from the dark ages when implementing a video tag fallback for iOS that an additional `play()` call was needed, but not specifically for live streams.
As we specifically exclude mpegurl before (why was that?), maybe that was the reason it was added.
