### ISSUE TITLE
DVR - back to live by clicking LIVE in timeline

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer#1105]
I checked some other players, and usually you can back to live from DVR by clicking LIVE. Is it possible to attach click to word LIVE and prevent default changing LIVE to time display?

**Comment by nnarhinen** [comment]
I got the same idea yesterday. It will be implemented.

**Comment by popler** [comment]
Great:) Option to recognize current state (DVR or LIVE) will very usefull too. You can display custom message to user or change color of timeline to show what user is watching at the moment (past or live).

**Comment by blacktrash** [comment]
@popler - not sure whether that is possible? One could detect the incremental EVENT playlist type by parsing the manifest, otherwise, from the player side, isn't it just a decision from what size onwards one considers the DVR window as "true" DVR. For "true" live streams it's just rather short, e.g. 30 seconds.

**Comment by popler** [comment]
So maybe we can calculate time between current position and actual live and than set DVR to true, when it is more than 30s or live if less than 30s?

**Comment by blacktrash** [comment]
@popler - what I was trying to say was: the decision is up to the maintainer whether the window should be considered DVR. 30s is just an example. Depending on the _maintainer's_ decision it's DVR or not, and maintainer configures accordingly.
imho it makes sense that this is _configurable_ (by the user).

**Comment by nnarhinen** [comment]
Here's my proposal: http://demos.1111f.flowplayer.me/basics/dvr.html

There's a new configuration property call `livePositionOffset` with a default value of `120` seconds.

Suggestion for the property name can be given.

**Comment by blacktrash** [comment]
ah - ok, now I understand ;-)

**Comment by nnarhinen** [comment]
@blacktrash http://demos.1111f.flowplayer.me/basics/dvr.html looks good to you?

**Comment by popler** [comment]
It looks good for me:) Going back to live is working ok.

**Comment by blacktrash** [comment]
I'm now less convinced by this, and whether its needed. At least with hlsjs the dvr offset can be determined (which was required to fix #1102): https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L734-L739
