### ISSUE TITLE
Android live/dvr: shows "dvr" duration instead of "Live" (hlsjs) or "Infinity" (native)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1107]
http://demos.flowplayer.org/basics/live.html
http://demos.flowplayer.org/basics/live.html?hlsjs=false
http://demos.flowplayer.org/basics/dvr.html
http://demos.flowplayer.org/basics/dvr.html?hlsjs=false

**Comment by nnarhinen** [comment]
Is this somehow differen from #1101 ?

**Comment by blacktrash** [comment]
Inasmuch as it includes native HLS behavior. Feel free to merge both issues.

**Comment by nnarhinen** [comment]
testable at http://demos.dev94.flowplayer.us/
