### ISSUE TITLE
iPad: fp-full timeline

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1110]
Controls are "distributed" at regular distance instead of left aligned

**Comment by nnarhinen** [comment]
Link / screenshot?

**Comment by blacktrash** [comment]
https://flowplayer.org/docs/skinning.html#full
http://demos.flowplayer.org/basics/long.html

Sometimes current time and play button also go missing, controlbar does not become thick when trying to seek.
![ipad-full](https://cloud.githubusercontent.com/assets/168338/22087903/98c96a30-ddd8-11e6-90c7-3906fb0b2f2c.png)

Current time would be centered in the above if/when it was visible, play button on the left.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/basics/long.html Looks fine now on my iPad.
