### ISSUE TITLE
addPlaylistItem on last clip inconsistencies

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1117]
When `addPlaylistItem` is called while the last clip is playing:
1. prev/next become no-ops
2. the current last playlist item loses its `is-active` styling
3. the playlist does not continue with the new clip

Demo: https://flowplayer.blacktrash.org/fp7/setplaylist.html
1. play last clip
2. click "add clip"

Issue already present in version 6.

See also: https://flowplayer.org/forum/#!/setup:change-playlist-in-flowplay

**Comment by blacktrash** [comment]
https://flowplayer.org/forum/#!/setup:playlist-problem

**Comment by nnarhinen** [comment]
@blacktrash  Can you try with assets from http://demos.1160f.flowplayer.me/

**Comment by blacktrash** [comment]
Much better. 1. and 3. look like they are solved.
Only the UI problem (no active item in UI after adding while current clip is still playing) is still there. It actually happens (and happened before) _always_ when you add a clip, no matter which index is currently playing.

**Comment by nnarhinen** [comment]
Seems good now.
