### ISSUE TITLE
flash hls quality selection in playlist: scrubber may be frozen

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1119]
- go to http://demos.flowplayer.org/playlist/minimal.html?hlsjs=false
- start playback
- select a hls quality (preferably a higher one, to repro issue)
- wait for next clip
- scrubber is frozen (no seeking possible), progress often full from the start

**Comment by nnarhinen** [comment]
FlashLS reports `bytes` and `duration` as NaN. Will fix.

**Comment by nnarhinen** [comment]
http://demos.1120f.flowplayer.me/playlist/minimal.html?hlsjs=false

**Comment by blacktrash** [comment]
Sorry, is not reliable for me. I still get this, may be less often.
Are you sure you are trying to set `startfrombitrate` before loading? - https://flowplayer.org/docs/setup.html#flashls - I can hear the clip re-starting sometimes, which seems to indicate that it does a level reset after load. And I think even high levels should load faster, it looks like it is always starting on level -1, and resetting afterwards.

**Comment by blacktrash** [comment]
Note that in hlsjs I always keep around the last selected level to be able to set `startLevel` for the next clip (the corresponding option to `startfrombitrate` in hls.js): https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L244-L257

**Comment by blacktrash** [comment]
With `startfrombitrate` set flashls usually starts faster because it doesn't do its default bandwidth check with the first segment of level 0.

**Comment by blacktrash** [comment]
Duration is `0` when it doesn't work:
<img width="949" alt="screen shot 2017-01-24 at 11 02 22 am" src="https://cloud.githubusercontent.com/assets/168338/22244748/ba92cdbe-e224-11e6-8810-21c6d2d1920a.png">

**Comment by nnarhinen** [comment]
Better now?

**Comment by blacktrash** [comment]
Nope. (I tried to make absolutely sure to have caches empty).
More importantly it looks like neither `startfrombitrate` nor `startfromlevel` flashls options have any effect in our implementation with playlists. I always get:
```
INFO:enough download bandwidth, adjust start level from 0 to 7
```
- it looks like neither of the options is applied - otherwise console would report e.g. `INFO:HLSSettings.startFromBitrate = 3146299`
- there is a problem with the options: `startfromlevel` does not specify a specific level, only `0` (lowest), `0.5` (medium) and `1` (highest); whereas `startfrombitrate` expects literally a bitrate value, i.e., the value given in the `BANDWIDTH` parameter in the master manifest for the corresponding level.
Is there an internal way to start with a level by index?

**Comment by nnarhinen** [comment]
I'm not using `startfrombitrate` or `startfromlevel` options. I'm using the `hls` object directly.

Please give reproduce steps that always make it misbehave so I can properly fix this.

**Comment by blacktrash** [comment]
But it does the bandwidth check? I can even hear it.
There is actually a problem with playlist and flash hls: even without qsel (i.e. leaving on Auto), just by switching items relatively quickly the player gets in the above state without duration and a frozen progress bar. This does definitely not happen with fp6 here: https://flowplayer.blacktrash.org/fp6/playlist.html

**Comment by blacktrash** [comment]
With leaving on Auto I cannot repro the frozen bar/0 duration with 7.0.0 at http://demos.flowplayer.org/playlist/minimal.html?hlsjs=false - so something has regressed since 7.0.0.

**Comment by nnarhinen** [comment]
> Please give reproduce steps that always make it misbehave so I can properly fix this.

**Comment by blacktrash** [comment]
Let's look at the regression from 7.0.0 first: http://d12zt1n3pd4xhr.cloudfront.net/fp/test/flashls-playlist-switch-regression.mov
Maybe after fixing it, the rest sorts itself out. Happens both in Chrome PepperFlash and "normal" Flash.

**Comment by nnarhinen** [comment]
Video does not work

**Comment by blacktrash** [comment]
http://blacktrash-media.s3.amazonaws.com/fp/test/flashls-playlist-switch-regression.mov
Sorry, permissions were messed up.

**Comment by nnarhinen** [comment]
How about when you compare to demos.dev94.flowplayer.us?

**Comment by nnarhinen** [comment]
I mean, is it just the changes I made for this that made it misbehave?

**Comment by blacktrash** [comment]
Did some brutal stress tests:
fp7 (including 7.0.0)
http://demos.flowplayer.org/playlist/minimal.html?hlsjs=false
http://demos.dev94.flowplayer.us/playlist/minimal.html?hlsjs=false
http://demos.1120f.flowplayer.me/playlist/minimal.html?hlsjs=false
*all* run into this problem sooner or later

fp6 does not have this problem; BUT instead one can run into: 'flash: swf file not found //releases.flowplayer.org/6.0.5/flowplayer.swf' (note: *not* flowplayerhls.swf!) - _this_ I do not get with fp7
http://flowplayer.blacktrash.org/fp6/playlist.html?hlsjs=false

**Comment by blacktrash** [comment]
Me neither. Great job!
