### ISSUE TITLE
No video on iOS Chrome

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1123]
Regression from FP6, most likely caused by the playsinline attribute.

**Comment by nnarhinen** [comment]
Should be fixed on dev

**Comment by bbbo** [comment]
@nnarhinen is this related to the HLS audio only problems in iOS as mentioned in https://flowplayer.org/forum/#!/setup:fp7hls-on-iphone-and-ipad ?

**Comment by nnarhinen** [comment]
Only if we are talking about Chrome

**Comment by bbbo** [comment]
I asked for clarification, but I suppose it applies to Safari.
