### ISSUE TITLE
SVG filters not working when base href set

### ISSUE THREAD

**Issue by RopoMen** [flowplayer/flowplayer#1125]
Hi,

I noticed that in Firefox Flowplayer 7 is not applying svg filter. It is caused by `base` tag in head.

Not working play button.
![firefox_filter_not_aplied](https://cloud.githubusercontent.com/assets/7492812/22323582/894d3292-e3ac-11e6-9442-9bb6dc8b7e69.png)

Notice what I have added in to filter 'url()' to get play button work.
![screen shot 2017-01-26 at 09 43 13](https://cloud.githubusercontent.com/assets/7492812/22323583/8acdcbcc-e3ac-11e6-9806-f61ec9407269.png)

Domain where I'm working and my base tag is
```
<base href="http://markku-phz.devaus.ninja/">
```
![screen shot 2017-01-26 at 09 43 34](https://cloud.githubusercontent.com/assets/7492812/22323584/8c6bf800-e3ac-11e6-8a34-edc5c9e09a71.png)

I have previously solved similar issue with svg mask() and you can look the answer from here
http://stackoverflow.com/a/35923885

This means that you need to mangle those svg's with javascript before you can append those in to DOM.

**Comment by nnarhinen** [comment]
http://demos.flowplayer.org/bug/1125.html (7.0.0)

vs

http://demos.dev94.flowplayer.us/bug/1125.html

**Comment by yokrysty** [comment]
now there is a problem if the url already contains # the final url on svg filters would be:
`filter="url(http://127.0.0.1/test/##f1)"`

I've solved the problem by adding:
```
var u = window.location.href.replace(window.location.hash, "");
"#" != u[u.length-1] && (u += "#");
.............
.replace(/url\(#/g, 'url(' + u)
```

**Comment by nnarhinen** [comment]
Link to a problematic example page thank you.

**Comment by yokrysty** [comment]
use # in any link at the end; for the previous examples:
http://demos.flowplayer.org/bug/1125.html#
http://demos.dev94.flowplayer.us/bug/1125.html#

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/bug/1125.html#
http://demos.dev94.flowplayer.us/bug/1125.html
http://demos.dev94.flowplayer.us/bug/1125-1.html#
http://demos.dev94.flowplayer.us/bug/1125-1.html
http://demos.dev94.flowplayer.us/basics/minimal.html

**Comment by RopoMen** [comment]
Hi,

I'm writing this finding over here, because its related to this. I'm (for now) not sure whether I can fix this in our code or is it some bug in webview(s). 
We are opening a page inside native app webview in Android and iOS, for some reason svg filter does not get applied.

"Solution" (from webview console):
```
window.location.reload(); // does not fix svg filter

window.location.href = window.location.href; // does fix svg filter
```

Before href=href svg filter url is exactly the same than after href=href, but I have no idea why svg filter is not applied initially.

I have a hunch that this has something to do with https, when svg filter is not applied webview is loading page behind https. I have local instance and if I load page from http, webview is able to apply svg filter correctly. 

If I navigate to that https page using iOS Safari svg filter gets applied correctly and the url inside the filter is the same that it's inside the webview.

**Comment by RopoMen** [comment]
WOHOOO!

Ok, I was today able to solve why the svg filter was not applied inside webview ( in certain cases)
Our CI server has basic authentication enable + https, now when the page is opened inside the webview:

window.location.href returns "https://ci.example.com/GUID/" and svg filter url gets url(https://ci.example.com/GUID/#f1) now svg filter does not get applied.


what webview addressbar actually contains? AHHAHAHA nice one...
"https://myuser:mypass@ci.example.com/GUID/", BUT
window.location.href returns only "https://ci.example.com/GUID/" and svg filter gets url(https://ci.example.com/GUID/#f1)

BUT IT SHOULD HAVE 
url(https://myuser:mypass@ci.example.com/GUID/#f1) <--- this would apply svg filter.

**Comment by RopoMen** [comment]
Could you duplicate the svg filter code inside the different svg parts in javascript side? Where you now place the svg filter url you could just copy-paste the whole filter code inside the other svg elements...

Then you would still have that code only one time in repository...
