### ISSUE TITLE
FP7 HLS - iOS Fullscreen 

### ISSUE THREAD

**Issue by sergey-sedoy** [flowplayer/flowplayer#1126]
Fullscreen on iOS devices is not working with HLS source.

**Comment by nnarhinen** [comment]
Please consult our [Contribution guidelines](https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md#reporting-issues) before opening issues here.

If you still think this issue is valid, feel free to re-open with the needed information.
