### ISSUE TITLE
Offer build version through github

### ISSUE THREAD

**Issue by RopoMen** [flowplayer/flowplayer#1131]
Hi,

I noticed that you are not providing build version through Github / Flowplayer repository, why?

It would be easy to setup `dist` folder which contains build version of the js/css/icons. I'm using Bower and I do not want to build Flowplayer each time that it gets updated, all other 35 Bower packages which I'm using are offering build and minified version of their lib.

For now, I need to find your download page, open web inspector from Chrome, click download link and copy link from network monitor, which I'm then able to use in bower.json

Could you provide build versions at least from the release tags?

**Comment by RopoMen** [comment]
Same goes to plugins.

**Comment by nnarhinen** [comment]
You can use NPM to install flowplayer. Last time I checked bower did not support pre-bundling the player before publish.
