### ISSUE TITLE
fp-remaining: re-introduce minus sign prefix; display it by default for DVR

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1133]
The omission of the minus sign in the remaining time display borders on a design bug:
- goes against convention
- one has to see the decrementing values in action to understand what it does, a minus sign indicates this also in paused state

It is especially confusing with DVR where the remaining time sticks at a fixed value during playback - I am aware that display of remaining time is omitted by default in that case, but its display is much wanted for clarity.

**Comment by popler** [comment]
I'm also interested in this option. fp-timestamp should be also modified for DVR. It should be calculate from current video duration and DVR window and shown with minus sign. Probably this function should be rewritten - bean.on(root, 'mousemove', '.fp-timeline', function(ev) {....
I can try to modify this event. What is the easiest way to overwrite event in custom js script (not in core js)?

**Comment by blacktrash** [comment]
@popler - please do not mix issues/features etc. This is *only* about the minus sign display, UI only, not about functionality.
Note as well that the functional problem you are describing only exists for hlsjs.
