### ISSUE TITLE
Doesn't work video in compatible mode IE8-9

### ISSUE THREAD

**Issue by dmitriyparasochka** [flowplayer/flowplayer#1134]
Browser: IE 11 in compatible mode  IE8-9
OS: Windows 10
Url: http://demos.flowplayer.org/basics/fallback.html I had the same problem on my website
Screenshot: http://imgur.com/a/E71C1
Player version: 7 (HTML 5)

**Comment by bbbo** [comment]
does this have an real-world scenario impact? If you force some ancient (and unsupported by MS) rendering mode, you should reconsider your concept ;)
