### ISSUE TITLE
iPad Chrome - video does not load

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer#1135]
I can't play any video (live or file) from demos from flowplayer.org on Ipad (ios 10.2.1).

**Comment by nnarhinen** [comment]
No problem in any simulator I have at hand.

Re-open with more information or consult the forums.

![image](https://cloud.githubusercontent.com/assets/265438/22563688/5a1daba8-e98a-11e6-9adb-360e73a04fca.png)

**Comment by popler** [comment]
Do you now option to show webbrowser console on iOS?

**Comment by popler** [comment]
Sorry, I checked on second device and it is ok. Maybe I have problem with device or iOS. Sorry for alarm

**Comment by nnarhinen** [comment]
You have to connect your iOS device with your mac and use safari developer menu to open dev tools for the connected iOS device: https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by popler** [comment]
I can play videos on Safari with second iPad, but I have problem  with Chrome. I'm testing on minimal setup demo. I have to start playing - nothing happend, next push home button and next reopen Chrome - than video is playing.

**Comment by popler** [comment]
The video is playing with FP 6 on Chrome without problem.

**Comment by nnarhinen** [comment]
Testable at http://demos.dev94.flowplayer.us/basics/minimal.html
