### ISSUE TITLE
dvr: consistent timestamp across engines

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1137]
For DVR the timestamp is currently not shown. But it is especially useful for DVR.
When one forces it be shown via CSS, it is wrong.
In my opinion it should display the position within the DVR window.
Instead it shows the position within the total duration.

Sample implementation for hlsjs: https://flowplayer.blacktrash.org/fp7/dvr.html
Compare at same address with native playback.
Compare at https://flowplayer.blacktrash.org/fp7/dvr.html?hlsjs=false with flashls.

This only needs a tiny tweak in the percentage calculation for dvr, for native playback this doesn't make any difference as seekOffset is always 0.

@popler - I think it's clearer to show the actual position instead of the distance to the live edge.

**Comment by blacktrash** [comment]
I have moved the timestamp code as little 'plugin' into the HEAD of the demo at https://flowplayer.blacktrash.org/fp7/dvr.html (or https://flowplayer.blacktrash.org/fp7/dvr.html#hlsjs=false); it works imho consistently for all 3 engines (dashjs plugin is a different beast).

**Comment by popler** [comment]
@blacktrash Based on your code, I made some modification. You can check at http://www.popler.tv/embed/player7.php?user=poplerhd - player shows minus time form LIVE. I also add some color differences between LIVE and DVR (scrubber, title, LIVE) to better show the difference.

**Comment by blacktrash** [comment]
@popler - as per https://github.com/flowplayer/flowplayer/issues/1133 my stance is:
- do not special case the timestamp for DVR with a minus sign, which I find confusing at that place as well
- imho the minus sign belongs to remaining time, both for VOD and DVR
- the Live switch is currently a hybrid: it usurps fp-remaining with a boolean switch indicator and functionality, therefore it should be separate

@nnarhinen has to decide.
