### ISSUE TITLE
Safari: javascript "first frame" installs stuck in loading state (regression)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1138]
http://demos.flowplayer.org/basics/js-setup.html - JS install hangs in loading state
http://demos.flowplayer.org/basics/js-setup-autoplay.html (or splash) - JS install works
http://demos.flowplayer.org/basics/minimal.html - VIDEO tag install works

v6 works too: http://demos.flowplayer.org/v6/basics/js-setup.html

**Comment by blacktrash** [comment]
VOD, DVR:
- 7.0.0 works
- 7.0.1 hangs

Live:
- 7.0.0 works if `live` configured on player level
- 7.0.0 autoplays if `live` configured on clip level (with `autoplay: false`)
- 7.0.0 #1098 actually did not happen with JavaScript install(!)
- 7.0.1 hangs consistently

DVR:
- 7.0.0

**Comment by criticerz** [comment]
Hey @blacktrash, thanks for jumping on this. I'm alain.2 from the forum.

Let me know if there is any way I can help with this, even if it's just testing. 

I will try getting the splash setting working for now.

Cheers.

**Comment by blacktrash** [comment]
@criticerz - thanks a lot. Once a fix is prepared, there will be test pages available, and we will be grateful for another pair of eyes.

**Comment by nnarhinen** [comment]
http://demos.1140f.flowplayer.me/basics/js-setup.html I think I got it

**Comment by blacktrash** [comment]
@nnarhinen - looking good! Also doesn't re-introduce the 7.0.0 quirks.

**Comment by criticerz** [comment]
@nnarhinen @blacktrash demo works on my end as well! 🎉

**Comment by criticerz** [comment]
@nnarhinen do you know when 7.0.2 will be released? Waiting for this fix to deploy Flowplayer across our app.

**Comment by nnarhinen** [comment]
We'll make a quick QA run accross our team. Tomorrow or latest the day after that.

**Comment by jonas-arkulpa** [comment]
I think we have the same issue.
Thanks for the fix @nnarhinen.
The demo page also works on my end.
Waiting for the release.

**Comment by jonas-arkulpa** [comment]
With 7.0.2 (in Safari) the play button is not visible until I resize the window.
Otherwise the player is working.
![image](https://cloud.githubusercontent.com/assets/17269256/22777819/c1c8fe9a-eeb4-11e6-8448-d4c5e0d165d8.png)
(top: after resize - play button visible; bottom: without resize - play button invisible)

**Comment by nnarhinen** [comment]
Please open a new issue with this with a link to a sample page thank you. Or better yet, take this first to our forums to make sure it actually is an issue with the player and not your implementation. (Does this happen on our demo site?)

**Comment by criticerz** [comment]
Didn't realize 7.0.2 was out. I'll go ahead and test stuff now. Thanks guys!

**Comment by jonas-arkulpa** [comment]
For future reference:
I have investigated the [above mentioned issue](https://github.com/flowplayer/flowplayer/issues/1138#issuecomment-278593982) further and made a [more detailed post](https://flowplayer.org/forum/#!/setup_configuration:player-not-working-in-safar) in the forum.
