### ISSUE TITLE
add config option to disable Chromecast

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1141]
to prevent browsers from loading cast_sender.js and no Chromecast support is needed

**Comment by bbbo** [comment]
@nnarhinen this is a showstopper for some clients

**Comment by bbbo** [comment]
@nnarhinen can we get an option for airplay as well?

**Comment by nnarhinen** [comment]
That can be hidden by CSS, no config switch needed as it does not load any assets.
