### ISSUE TITLE
FP7: make subtitles responsive

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1143]
so the captions do not overlay the majority of the video on small devices. 

Comments by @nnarhinen :
the problem is they are absolute positioned
also, the subtitle demo is demonstrating the custom positioning, and thus makes some of the subtitles cropped on narrow screens
the problem of course is to figure out a good font size

Comment from Colin (in itrs):

font size for caption is fixed & doesnt work like it does on jwplayer where it shows properly for every screen resolution as they use Js to resize font; please find below code

 this.resize = function () {
            var width = _display.clientWidth,
                scale = Math.pow(width / 400, 0.6);
            if (scale) {
                var size = _options.fontSize * scale;
                _style(_display, {
                    fontSize: Math.floor(size*2)/2 + 'px'
                });
            }
            this.renderCues(true);
        };

https://github.com/jwplayer/jwplayer/blob/47da96bf889c4cc54a5191cbf5f9198c0e2e5343/src/js/view/captionsrenderer.js

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/basics/subtitle.html#vtt did not show the custom positioning because it wasn't adapted to fp7 yet ;-) It does now. ;-)
http://flowplayer.org/basics/subtitles.html and http://demos.flowplayer.org/basics/subtitle.html#srt show the default positioning.

**Comment by ankurss** [comment]
is this fixed in 7.0.2 ? or we need to wait for 7.1
