### ISSUE TITLE
Chromecast plugin and DVR

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer#1144]
DVR stream played on chromecast always starts from beginning (0 time), not from current live.

**Comment by Shahrudinov** [comment]
also hv this problem

**Comment by blacktrash** [comment]
That is because Chromecast is in charge of the HLS playback, and apparently it behaves that way.
See also https://github.com/flowplayer/flowplayer-hlsjs/issues/65
Injection of a Chromecast application is planned.
