### ISSUE TITLE
iOS on iPhones: option to disable inline playback

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1145]
by customer request: offer a no_inline option to disable inline playback on iPhones (iOS 10+) and use the Quicktime component

**Comment by blacktrash** [comment]
Unfortunately I'm absolutely +1 on that.
If the video happens to fill the viewport in horizontal mode, and one touches the UI to do something the stupid bottom menu comes up, and not only takes up space or overlays the controlbar (depending on the device's whims).
![simulator screen shot feb 14 2017 4 28 36 pm](https://cloud.githubusercontent.com/assets/168338/22938189/eaba8d42-f2d2-11e6-93b5-a1867a45c21e.png)

On the other hand `native_fullscreen: true` is usually overkill for iPad.

Or is there a way to prevent the bottom menu from appearing or hiding it during video playback?
