### ISSUE TITLE
iOS Chrome: volume controls

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1146]
enable volume control in the player for iOS Chrome, like we have for Android Chrome

**Comment by nnarhinen** [comment]
Does iOS chrome support volume control?

**Comment by bbbo** [comment]
I think someone demoed this with videojs (or claimed it would work). Perhaps check with

http://videojs.com/advanced/

**Comment by blacktrash** [comment]
On that page is a volume control _outside_ the player, _that_ works also in mobile Safari.

**Comment by bbbo** [comment]
so the volume button (which expands on click) _in_ the player is not present?
![image](https://user-images.githubusercontent.com/1395672/28869104-f67fd17c-777b-11e7-962f-3ddb930b1b8c.png)

**Comment by blacktrash** [comment]
I was talking about the volume slider _below_ the player, and that the user may have been confused by this.
Neither the mute button, nor the volume controls appear in mobile Safari (iPad - iPhone does not play inline, on that page at least).

**Comment by bbbo** [comment]
I understood that ;)
how about Chrome on iOS? do the player volume controls appear there (We had a user claiming that some time ago)

**Comment by fdambrosio** [comment]
hi, this will be fixed?

**Comment by nnarhinen** [comment]
I don't think iOS chrome supports volume controls.
