### ISSUE TITLE
PS4: fullscreen does not work

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1147]
according to clients, the PS4 internet browser does support html5 fullscreen, but the Flowplayer 7 FS button has no effect.

**Comment by FV-Edo** [comment]
Hi guys,

Have you made any progress with resolving this issue? 

Thanks,
Eduard

**Comment by nnarhinen** [comment]
Is there a way to emulate PS4 browser?

**Comment by FV-Edo** [comment]
Unfortunately no. It seems that there is no way to emulate PS4 on PC.
