### ISSUE TITLE
VAST demo not showing in Safari

### ISSUE THREAD

**Issue by iHiD** [flowplayer/flowplayer#1149]
This is a weird issue we've been battling for a couple of days, which we thought was a problem our end, but today we've realised that this is also an issue on the [Flowplayer VAST demo page](http://demos.flowplayer.org/ads/vast.html).

On Safari on MacOS, when watching a video with a VAST advert, after hitting play the sound can be heard but the video does not visually display. A repaint (e.g. resizing the window) forces the video to show. We are using Flowplayer 7.0.2, which I imagine is the same as on the VAST demo page.

We see this issue on:
- Mac OS 10.11.3 (15D21): Safari Version 9.0.3 (11601.4.4)
- Mac OS 10.11.6 (15G1217): Safari Version 9.1.3 (11601.7.8)

We have got round this on our deployment with the following:
```
player.on("ready", function(e) {
  $('#player_container').show()
})
```

Weirdly, the `show()` is enough, even though the div is visible. Also strangely, doing the equivalent of this via a DOM style update (setting display to block) rather than jQuery didn't work. I've not investigated what jQuery is doing that's special here, but that might be a useful entrance point to debugging for you.

Here is a [screencapture](https://github.com/flowplayer/flowplayer/files/777969/flowplayer_vast_bug.mov.zip) that shows the problem. No video displays (but sound is heard) until I resize the window.

If you cannot reproduce locally, I am happy to try updates if you post them to a your site.

**Comment by blacktrash** [comment]
I can confirm this for Safari 9.1.3.
Does not happen with Flowplayer 6.0.5 at http://demos.flowplayer.org/v6/ads/vast.html

**Comment by iHiD** [comment]
There's a lot of [talk on the forums](https://flowplayer.org/forum/#!/?safari) about this starting about 2 weeks ago. I mention this in case there might be information buried in those posts that helps make it easier for you to track it down. Thanks.

**Comment by blacktrash** [comment]
Confined to splash setups.
Also repro-ed with 7.0.0, so in all likelyhood not related to #1138 (the adhoc build for it does not help for this either).

**Comment by nnarhinen** [comment]
Is this still an issue with latest VAST plugin (2.1.3)?

**Comment by blacktrash** [comment]
Nope. Closing.

**Comment by iHiD** [comment]
This is still broken for me on both the demo page and on our local setup. Can you can clarify which version of Safari it is fixed for for you please?

**Comment by blacktrash** [comment]
9.1.3 you mentioned above:
<img width="1056" alt="screen shot 2017-03-07 at 3 31 08 pm" src="https://cloud.githubusercontent.com/assets/168338/23663660/2f1a142a-034b-11e7-894e-07ff0bf6ce25.png">
