### ISSUE TITLE
FP7: HLS does not work in UC Browser on Android

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1150]
to be tested with http://demos.flowplayer.org/basics/hls.html
http://demos.flowplayer.org/videotest/hls.html plays
Note: hlsjs doesn't work as UC does not report MSE capabilities

**Comment by nnarhinen** [comment]
What are the symptoms?

**Comment by nnarhinen** [comment]
I won't be installing such crap on my phone. To be allowed to use it it asks to be able to make phone calls.

**Comment by nnarhinen** [comment]
Not accurate anymore. The browser actually always takes video playback over in it's native video tag.
