### ISSUE TITLE
iPhone iOS < 10: subtitles not shown

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1151]
The switch to native subtitles on iPhones with iOS < 10 (no inline playback) does not work.
- https://flowplayer.org/standalone/basics/subtitles.html - fp7: no subtitles
- https://flowplayer.org/standalone/v6/basics/subtitles.html - fp6: subtitles are shown

See: https://flowplayer.org/forum/#!/scripting_api:subtitle-not-working-on-ios presumably.

**Comment by nnarhinen** [comment]
Hmm.. The commit (https://github.com/flowplayer/flowplayer/commit/6d7dbba9964ece969907f25fa8d55fc7d4b746e1) to force native subtitles for noninline-devices is still in place. Will investigate.

**Comment by blacktrash** [comment]
Somehow non-inline seems to be detected properly in general. The player also doesn't unload when you exit:
<img width="313" alt="screen shot 2017-02-17 at 10 09 37 pm" src="https://cloud.githubusercontent.com/assets/168338/23085207/41d632c4-f55e-11e6-9e01-e24dbe019522.png">


And indeed `flowplayer.support.inlineVideo` returns `true`. (iPhone 4s IOS 8.2)

**Comment by nnarhinen** [comment]
I don't have such old iOS available, can you paste me the results of http://demos.flowplayer.org/videotest/support.html

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/23145522/8a01094a-f7d7-11e6-99cf-d99730aced31.png)

**Comment by blacktrash** [comment]
On iOS 8.2 it's true on various devices.
![simulator screen shot feb 21 2017 12 00 51 am](https://cloud.githubusercontent.com/assets/168338/23145775/daaeaa64-f7c8-11e6-9a19-a28f5135fe53.png)
I wonder how fp6 behaves ok then - something in the evaluation for `inlineVideo` must have changed from fp6 to fp7.

On 8.4 I get false all through to 9.3.
Ironically it becomes harder to display captions then. but with fp6 I get subtitles once I deselect "Unknown CC" and choose e.g. "English" *after* exiting the player and restarting. It also seems to remember that setting.
With fp7 I never get captions, not matter what I tried.
Admittedly, as a "normal" user I would have given up for fp6 as well.
Certainly the default track is never reflected in the native menu etc.

**Comment by blacktrash** [comment]
I'm just seeing that what I took for 8.2 seems to be 10.1 - so in spite of doing complete re-installs of the simulators, you can probably ignore any detailed comments :-(

**Comment by Honzasejrak** [comment]
Sírra23
---------- Přeposlaná zpráva ----------Od: "Niklas Närhinen" <
notifications@github.com>
Datum: 21.2.2017 0:45
Předmět: Re: [flowplayer/flowplayer] iPhone iOS < 10: subtitles not shown
(#1151)
Komu: "flowplayer/flowplayer" <flowplayer@noreply.github.com>
Kopie: "Subscribed" <subscribed@noreply.github.com>

> I don't have such old iOS available, can you paste me the results of
http://demos.flowplayer.org/videotest/support.html

**Comment by nnarhinen** [comment]
@blacktrash So is there a case where subtitles do not work in iOS 9.x but do work in plain video tag?

**Comment by blacktrash** [comment]
Yes. E.g. iPhone 6s simulator (says correctly support.inlineVideo false now):
1. http://demos.flowplayer.org/videotest/subtitles.html works
2. http://flowplayer.blacktrash.org/test/videotag-subtitles.html works for default track, stops working after switch
3. https://flowplayer.org/standalone/subtitles.html does not work - that could be caused by the HLS root playlist not explicitly stating `CLOSED-CAPTIONS=NONE` -> needs deselecting 'Unknown CC' -> after selection does not work as in 2.
4. http://demos.flowplayer.org/basics/subtitles.html#vtt should work, but doesn't (similar to 1.)

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/basics/subtitle.html now adds the track element there and the subtitle menu appears. However no subtitles are shown.. Did I already mention, *I hate Mobile Safari*

**Comment by nnarhinen** [comment]
@blacktrash Can you confirm this? My simulators are doing weird stuff atm..

**Comment by blacktrash** [comment]
I'm observing the same, yes.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/basics/subtitle.html is fine now on my 9.x simulator.

@blacktrash this should not break anything but.. the change should affect only `nativesubtitles: true` and the fallback to that setting (iOS `native_fullscreen` and iPhone < iOS 10)

**Comment by blacktrash** [comment]
Yup, subtitles are off by default, but there once enabled. Great.
However, the player is unresponsive when exiting now.

**Comment by nnarhinen** [comment]
Should be better now.

**Comment by blacktrash** [comment]
Indeed.
However, the captions are lost once I seeked backwards. They appear again - except for the first one - on replay, or after seeking back manually to 0 after finish. - This does not happen at http://flowplayer.blacktrash.org/test/videotag-subtitles.html

**Comment by nnarhinen** [comment]
I can confirm this at http://demos.dev94.flowplayer.us/basics/subtitle.html but not locally.. will try to further replicate the demo..

**Comment by nnarhinen** [comment]
@blacktrash how does http://codepen.io/anon/pen/GWGpvP behave in your simulator? Only shows the first subtitle for me and then disappears :(

**Comment by blacktrash** [comment]
@nnarhinen - nope, I don't see any subtitles at all so far with iPhones at 9.2 ...

**Comment by nnarhinen** [comment]
And even more weird, the `cuechange` event fires constantly when the subtitles would be changing. The subtitles just are never shown.. This is 99,99% iOS bug..

**Comment by blacktrash** [comment]
FYI, I tried the codepen also with an HLS source because I previously found that this also varies depending on source type, but in this scripted case it was the same; at least for 9.2.

**Comment by blacktrash** [comment]
Same for iOS 8.2, 8.4, 9.0, 9.1:
- http://codepen.io/anon/pen/GWGpvP does not work
- http://demos.flowplayer.org/videotest/subtitles.html (vtt from same domain) works
- http://flowplayer.blacktrash.org/test/videotag-subtitles.html (vtt crossdomain) works

**Comment by fdambrosio** [comment]
Thanks, I have the same problem

**Comment by fdambrosio** [comment]
I'm using flowplayer 7.2.5 with hls m4a audio files and .vtt subtitles. 
It doesn't works on iOS 8 and iOS 9 (Safari) and the player thrown error. It play audio without the subtitles.  
demo page  http://web-0.radioradicale.it/prova/fp/error-ios.html
