### ISSUE TITLE
Android Fullscreen error with fp 7.0.2

### ISSUE THREAD

**Issue by RopoMen** [flowplayer/flowplayer#1152]
Hi,

I tried to put fullscreen on with my Android tablet, but I got fullscreen error from 'fullscreenerror' attached in to document element and the player is not going in to fullscreen. Event source is (srcElement) `div.fp-player`. (note: using webview, which shows up in UA, `wv` after Build information.

Video is embedded like this, it is using hlsjs + m3u8.
```
<video class="fp-engine hlsjs-engine" autoplay="" x-webkit-airplay="allow" src="blob:http://mydomain/c65bc271-32f9-4a44-8591-58ef4c274c33"></video>
```

Tablet information:
* Model number: Nexus 10
* Android version: 5.1.1
* Kernel version: 3.4.67
* Screen size: 1280x800
* userAgent: "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 10 Build/LMY49J; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Safari/537.36"

**Comment by RopoMen** [comment]
If I remember correctly iOS is using "fullscreen" by setting player element position: fixed; and stretching player in to fullscreen.

**Comment by RopoMen** [comment]
I tested in your website using Chrome https://flowplayer.org/docs/quickstart.html and player fullscreen works ok, Chrome UA is: 

"Mozilla/5.0 (Linux; Android 5.1.1; Nexus 10 Build/LMY49J) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by blacktrash** [comment]
@RopoMen - please try with latest 7.0.2 and make sure you load the latest hlsjs plugin as recommended.
http://demos.flowplayer.org/api/hlsjs.html works fine with
```
"Mozilla/5.0 (Linux; Android 5.1.1; Nexus 9 Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36"
```
(don't have Nexus 10 here).

**Comment by RopoMen** [comment]
I tried with FP 7.0.2 + HLSjs 0.7.0, but no change.

Before I got the 7.0.2 version I had time to Google the issue and it strongly seems to be Android webview issue.

http://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview
https://vimeo.com/forums/help/topic:281966
https://github.com/cprcrack/VideoEnabledWebView

It seems to require either application side webview specific code changes or client side fix.

While I was writing this message I remembered that I could look whether fullscreen is enabled at all inside the webview.
```
document.fullscreenEnabled // which returns false
```

**Comment by RopoMen** [comment]
I noticed that support.js https://github.com/flowplayer/flowplayer/blob/master/lib/ext/support.js#L62
is not looking in to 
```
document.webkitFullscreenEnabled
```

it only checks mozFullscreenEnabled

My previous comment contained `document.fullscreenEnabled` but that is only because I'm using polyfill which uses vendor prefixed versions behind it.
I checked also that 
```
document.webkitFullscreenEnabled // this is false also
```

**Comment by blacktrash** [comment]
What is weird is that it's no problem with WebM, it seems. Can you check
http://demos.flowplayer.org/basics/hls.html (native playback on Android, no hlsjs)
and
http://demos.flowplayer.org/videotest/hls.html (also for native)

I'm not aware of any fullscreen specific code in hls.js - maybe it's just some weird Chrome bug. As I said, I can't repro it in other device/Android OS/Chrome combos.

**Comment by RopoMen** [comment]
I tested both pages and those work ok. 

http://demos.flowplayer.org/basics/hls.html  on this page where Flowplayer (no native) is used to enter fullscreen, fullscreen functionality works ok.

Clarification:
- This fullscreen error comes only on webview on Android and it does not anything to do with hls, same happens with 'standard' mp4/webm combo. I added hls information on the first post because that was the setup where this initially happened.

in Android webview `document.webkitFullscreenEnabled` returns false, meaning that fullscreen is not supported, but Flowplayer is showing up 'Fullscreen'' button on top-right corner. 


I'm not sure if Flowplayer should use fullscreen fallback on that case and set the player 
position: fixed; + stretch the player in fullscreen, like it does on iOS inline setup (if I remember correctly)

**Comment by nnarhinen** [comment]
If you know you are running the page inside a webview you can just set `flowplayer.support.fullscreen = false`; right after loading flowplayer.js:

```html
<script src="//releases.flowplayer.org/7.0.2/flowplayer.min.js"></script>
<script>
flowplayer.support.fullscreen = false;
</script>
```

This is of course just a workaround. I'll change the support detection mechanism correctly discover fullscreen properties now that the implementations in browsers are becoming more stable. At the time native fullscreen was first implemented most of webkit browsers didn't have `webkitFullScreenEnabled` property and thus other indicators had to be used.

**Comment by nnarhinen** [comment]
Please test at http://demos.dev94.flowplayer.us

**Comment by RopoMen** [comment]
Tested over here http://demos.dev94.flowplayer.us/basics/hls.html with Nexus 10 Chrome. Fullscreen was working ok. 

After a release I can test how it works inside the webview in our app. For now I cannot test it quickly.
