### ISSUE TITLE
Is it possible to make `off` only remove certain listener?

### ISSUE THREAD

**Issue by Boxie5** [flowplayer/flowplayer#1153]
Currently, if we call function `player.off(type)`, that would remove all the listens for event `type`. 

But sometimes, we only want to remove certain listener for the certain event.

**Comment by blacktrash** [comment]
@Boxie5 - please ask usage questions in our forum - https://flowplayer.org/forum/ - first. In fairness to other users, so they can profit from the answers. Thank you.
You can name-space the event, when you set it up, and then turn off the name-spaced event: https://flowplayer.org/docs/api.html#name-space

**Comment by Boxie5** [comment]
Great, thank you!
