### ISSUE TITLE
Hidden menus stay clickable

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1154]
This is an easy to repro scenario where the header element is unnecessarily duplicated:
- start a player with `share` enabled
- select for instance `embed`
- click several times on screen

For each click a header dupe is appended. Once they have disappeared one by one, clicking on screen can have surprising effects, like the FB share window coming up.

**Comment by nnarhinen** [comment]
This is actually not about the header element being duplicated. It's that the hiding of the menu does not actually hide it, only makes it `opacity: 0`. You can reproduce this by just opening the menu and closing it again. Now if you click where the "Twitter" or "Embed" menu items used to be you get to click them.

**Comment by Honzasejrak** [comment]
sirra23
