### ISSUE TITLE
Subtitle wrapper never removed

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1155]
https://github.com/flowplayer/flowplayer/blob/master/lib/ext/subtitle.js#L73 should remove `.fp-captions`, not `.fp-subtitle`

https://flowplayer.org/forum/#!/drive_discussion:bug-multiple-subtitles-cre

**Comment by blacktrash** [comment]
@nnarhinen - I don't think this takes care of removal on unload. If there are subtitles visible when the player is unloaded, they stay visible.
imho they should also be hidden in poster state - https://flowplayer.org/standalone/basics/subtitles.html has always been like that, but it doesn't make sense.
