### ISSUE TITLE
FP7 does not play in stock Android Internet browser

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1156]
which seems to be problem especially for Asian users which do not use Chrome.

**Comment by nnarhinen** [comment]
Which vendors? Works in most Browserstack Samsung devices I tried in. Also works in my Samsung Galaxy S6

**Comment by bbbo** [comment]
Doesn't work in my Samsung Galaxy Tab 2 for example, just get a black canvas. I'll check for other vendor/device info.

**Comment by nnarhinen** [comment]
Which Android version..

**Comment by bbbo** [comment]
4.4.2 (there are no more updates from Samsung for older devices..)

**Comment by blacktrash** [comment]
@bbbo 
Is this for all video types or only for HLS?
If only for HLS: only with hls.js? - Background: on older Androids sometimes HLS works better hls.js (in spite of hls.js not being officially supported on Android < 5) than native, sometimes it's the other way round.

**Comment by bbbo** [comment]
this is for MP4 and WebM as well.
Video tests work, and so does FP6.

**Comment by nnarhinen** [comment]
God damn. I can reproduce this with browserstack samsung note devices (4.4.2) but there's no way to feature-detect or even parse from user agent..

**Comment by nnarhinen** [comment]
I lean towards ignoring this for now because it seems to affect only very old samsung devices. If there are devices that are less than two years old and run a stock browser that does not work I'll reconsider.

**Comment by bbbo** [comment]
seems to affect newer devices with Android 5x as well. It would be good if that could be solved somehow; we cannot expect users to buy new devices every two years...

**Comment by nnarhinen** [comment]
Exact device names and versions thank you.

**Comment by bbbo** [comment]
Asus Zenpad C7 (Z170x) with Android 5.0.2 for example, according to a customer.
I know this isn't fun, but it seems those devices with stock browser are still much used especially in Asia :-(

**Comment by nnarhinen** [comment]
User agents would be very much appreciated too - you can ask for a screenshot of this page for instance : http://demos.flowplayer.org/videotest/support.html

**Comment by foliovision** [comment]
I checked http://demos.flowplayer.org/basics/autoplay.html on Samsung Galaxy X-Cover 3 with Android 4.4.4 using the stock browser `Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG SM-G388F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.0 Chrome/34.0.1847.76 Mobile Safari 537.36` and I got some bad behavior.

On tap the play icon doesn't disappear, only the control bar shows up. After a while the video starts to play, but it was not obvious that it's going to play as there was not loading animation.

Same deal with http://demos.flowplayer.org/basics/minimal.html

Thanks,
Martin

**Comment by nnarhinen** [comment]
Fixed already in 7.2

**Comment by foliovision** [comment]
Both http://demos.flowplayer.org/basics/autoplay.html and http://demos.flowplayer.org/basics/minimal.html play for me on Samsung Galaxy X-Cover 3 with the user agent I mentioned before, but they also won't let me seek. The timeline tooltip with the time in the seek position appears, but the seek doesn't happen at all.
