### ISSUE TITLE
IE9: html5 sources do not work (regression from fp6)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1157]
IE9 on Win7
http://demos.flowplayer.org/basics/minimal.html gives
```
SCRIPT5007: Unable to get value of the property 'length': object is null or undefined
```
Not happening with fp6:
http://demos.flowplayer.org/v6/basics/minimal.html
Also not happening with flash engine (Flash HLS).

**Comment by bbbo** [comment]
confirmed on real Win7 with IE9. Hm I think I tested this with 7.0.0 ?

**Comment by blacktrash** [comment]
http://flowplayer.blacktrash.org/fp7/minimal.html (temporarily with 7.0.0) just gives a different error and does not event get as far as 7.0.2:
```
SCRIPT87: Invalid argument.
```

**Comment by blacktrash** [comment]
If 5007 is the line number, it's in `bean`s `delegate` `findTarget`:
```js
for (; target && target !== root; target = target.parentNode) {
  for (i = array.length; i--;) {
    if (array[i] === target) return target
  }
}
```
