### ISSUE TITLE
Safari, Chrome video tag based: videos downloaded before document ready

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1165]
This affects Safari 10, and, to a lesser extent, Chrome.
With Safari and pages which build otherwise dynamically, this can lead to a delay of *minutes* until the page is loaded.
By definition harder to observe on pages which are compact, minimal demos. http://demos.flowplayer.org/basics/subtitles.html at least gives an idea of what is happening:
<img width="851" alt="screen shot 2017-03-15 at 10 39 41 am" src="https://cloud.githubusercontent.com/assets/168338/23942192/c2707a9a-096b-11e7-9bb6-2c455bc89adf.png">

Here is a real world example:
<img width="843" alt="screen shot 2017-03-15 at 10 43 40 am" src="https://cloud.githubusercontent.com/assets/168338/23942379/696272ea-096c-11e7-989c-9e8e3f5d4689.png">

As the client handling of `preload="none"` is also inconsistent - https://flowplayer.org/docs/setup.html#video-tag-attributes - we cannot recommend that either.

**Comment by bbbo** [comment]
I vote for deprecating the <video> tag based installation method ;)
