### ISSUE TITLE
playlist: clicking on last item when last clip has finished advances (regression)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1166]
http://demos.flowplayer.org/playlist/minimal.html

1. play last clip
2. wait until finished
3. click last item in UI

Expected:
Last clip is played again.

Actual behavior:
First clip is played.

Happens with both defaultPlaylist and customPlaylist.

Does not happen with version 6: http://demos.flowplayer.org/v6/playlist/minimal.html

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/playlist/minimal.html - should be fixed
