### ISSUE TITLE
flash hls: video dimensions not honored when container ratio does not match video ratio

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1167]
If the container aspect ratio does not match video aspect ratio (or rather video width/height, as this is Flash) the Flash object may not resize in time.

EDIT: This happens with all streams, and is in fact a regression from version 6.x.

- http://demos.flowplayer.org/bug/1167.html (v7: issue)
- http://demos.flowplayer.org/bug/1167-v6.html (v6: ok)

**Comment by blacktrash** [comment]
Indeed the first breakig version is 7.0.0.

**Comment by nnarhinen** [comment]
Is there a way to reproduce this always? I can't reproduce this after the first attempt :(

**Comment by blacktrash** [comment]
I can always repro with simple cache-refresh.

**Comment by blacktrash** [comment]
I think Firefox is the easiest for reproducing.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/bug/1167.html better?

**Comment by blacktrash** [comment]
Better, but not as good as v6. With v7 I can see the Flash object resizing, with v6 it's almost unnoticeabl. Strange.
I'll revert to the multiplexed stream, then you should be able to see it clearer.

**Comment by nnarhinen** [comment]
hmm.... it should now resize already in poster state. Are you sure you have a clean cache?

**Comment by nnarhinen** [comment]
You will know if you get these lines in this order in console log:

![image](https://cloud.githubusercontent.com/assets/265438/24326988/6c3689ce-11c4-11e7-8aed-e27878c427e1.png)

**Comment by blacktrash** [comment]
Yes. I also tried various scenarios locally with the assets from dev.94.fp.org.
Let me check again tomorrow, I'm too tired. But in principle it's ok.

**Comment by blacktrash** [comment]
I can observe the resizing with empty cache or after cache refresh in v7 at http://demos.dev94.flowplayer.us/bug/1167.html
Not with v6 at http://demos.dev94.flowplayer.us/bug/1167-v6.html

Note with Chrome's PepperFlash both are ok.
In view of Flash moving off the radar I'm inclined to being ok with this state. The difference may still be worth investigating. In general I have the impression that v5 Flash HLS loads slower, noticeable especially when the (vod-)quality selector is used with Flash HLS.
