### ISSUE TITLE
HLS (and DASH): no loading animation while first fragments buffer

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1168]
With fast starting streams almost unnoticeable, but compare:
http://demos.flowplayer.org/api/hlsjs.html#live (v7)
with
http://demos.flowplayer.org/v6/api/hlsjs.html#live (v7)

I don't think it makes sense to attack this in the plugins because:
1. in the above comparison the same plugin is used
2. same observation in native playback

Decidedly different behaviour with VOD:
http://demos.flowplayer.org/lookandfeel/loading-custom.html

**Comment by nnarhinen** [comment]
And this is with splash setup only?

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/api/hlsjs.html#live

**Comment by blacktrash** [comment]
Great. imho a tiny, but very important UI improvement.
