### ISSUE TITLE
.fp-help exists, but not used in new skin

### ISSUE THREAD

**Issue by Tankzor** [flowplayer/flowplayer#1169]
In the v7+ skin(s), .fp-help is permanently hidden in the CSS, though the markup still exists and .is-help is still toggled on keydown (/).

Side note is also that Firefox uses / as a hotkey for quick search, so would need to prevent default if you want to keep it around.

I just noticed while migrating a custom skin to use v7 - on that note, some docs on flowplayer.org (skinning/subtitles at least) feature out of date HTML

**Comment by nnarhinen** [comment]
Should be gone now.
