### ISSUE TITLE
FP7 does not work in IE9

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1170]
http://demos.flowplayer.org/basics/minimal.html
fails with an "SCRIPT5007: Unable to get value of the property ‘length’: object is null or undefined" error.

**Comment by blacktrash** [comment]
Is this a duplicate of https://github.com/flowplayer/flowplayer/issues/1157 ?

**Comment by bbbo** [comment]
ah, probably.

**Comment by nnarhinen** [comment]
If http://demos.dev94.flowplayer.us/basics/minimal.html# works, then this is a duplicate. Please re-open if this is not the case.

**Comment by bbbo** [comment]
works, all good.
