### ISSUE TITLE
demo ui is broken

### ISSUE THREAD

**Issue by mankoell** [flowplayer/flowplayer#1171]
Downloaded the latest 7.0.2, put it on the server but also tried the current master branch. Both UI looks broken. No errors on console, all resources, css/js loaded successfully.

![b0fox42](https://cloud.githubusercontent.com/assets/1057526/24502348/ab9e4e12-154d-11e7-9d30-adc42c134126.png)

Browser: Google Chrome Version 54.0.2840.100 (64-bit) and Version 57.0.2987.98 (64 bit)
OS: Archlinux and Xubuntu 16.04.2 LTS

**Comment by mankoell** [comment]
seems like the skin.css is broken, the one from cdn works fine.

**Comment by nnarhinen** [comment]
Did you build the player, the dist builds are not in git repository.

**Comment by nnarhinen** [comment]
...and as always, link to a problematic setup, consult the forums first etc..

**Comment by mankoell** [comment]
@nnarhinen how about to just update the one on https://flowplayer.org/download/ instead of blaiming people? 7.0.2 download isn't working. would save people alot of time.

**Comment by nnarhinen** [comment]
Works fine for me.. Thus link to a problematic setup..

**Comment by mankoell** [comment]
7.0.2 is broken. Look yourself if you don't believe the stupid user. A fresh install from https://releases.flowplayer.org/7.0.2/flowplayer-7.0.2.zip

http://88.99.190.194/test/702

Did you test your build before you made a release?
...and as always, use a CI server to run your tests, blaim the user first, dev skills 101

**Comment by nnarhinen** [comment]
Yes we did test. You need to configure your server to send correct mime types...

![image](https://cloud.githubusercontent.com/assets/265438/24503368/760137a8-155a-11e7-98ef-4d44b2e9068a.png)

And result: http://aegon.codesense.fi/~nnarhinen/flowplayer702/

**Comment by nnarhinen** [comment]
(LMAO)

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/24503469/eac48c8e-155a-11e7-87e5-0fa7fbe7a14a.png)

Here's your problem most likely. You are welcome.

**Comment by bbbo** [comment]
yes, as a result the font file is not loaded. 
Same setup straight from the download: stylebites.de/702/index.html

**Comment by mankoell** [comment]
yeah, i'm a fuckin loser pls tell me
