### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bean' of undefined

### ISSUE THREAD

**Issue by kikar** [flowplayer/flowplayer#1173]
I'm trying to build my website with webpack, and I'm importing flowplayer with:
`import * as flowplayer from 'flowplayer';` after installing it with `npm install flowplayer`

I get the following error:
```
Uncaught TypeError: Cannot read property 'bean' of undefined
    at eval (flowplayer.js:4608)
    at name (flowplayer.js:4602)
    at Object.r.31 (flowplayer.js:4603)
    at s (flowplayer.js:219)
    at eval (flowplayer.js:220)
    at Object.r.28../common (flowplayer.js:3776)
    at s (flowplayer.js:219)
    at eval (flowplayer.js:220)
    at Object.r.29../engine/embed (flowplayer.js:4417)
    at s (flowplayer.js:219)
```

Any idea why?

**Comment by nnarhinen** [comment]
I have no idea why it does not work, I guess it has something to do with the way flowplayer is bundled.

`var flowplayer = require('flowplayer');` works though as a workaround

**Comment by kikar** [comment]
The error I was doing was passing it trough Babel before importing. Without Babel imports correctly.

**Comment by nnarhinen** [comment]
Thanks for sharing this tip!

**Comment by Amin52J** [comment]
@kikar I'm having the same issue, can you please elaborate on how you solved it?

**Comment by pranabVadakkath** [comment]
i updated angular app from 7 to 8.After that when i run the app it shows Uncaught TypeError: Cannot read property 'bean' of undefined.How can i fix this issue.

**Comment by bbbo** [comment]
Flowplayer 7 is deprecated and receives no further support or fixes, sorry.

**Comment by pranabVadakkath** [comment]
flowplayer showing 'bean undefined issue' while setting target in tsconfig.json as 'es2015'.

**Comment by bbbo** [comment]
Sure. It's an ES5 player.

**Comment by pranabVadakkath** [comment]
@bbbo , is there a way to prevent those errors in es5?

**Comment by bbbo** [comment]
don't set es2015 as target (which means es6).
