### ISSUE TITLE
Safari 10.1 fullscreen control stops working after minimising with escape

### ISSUE THREAD

**Issue by epicalex** [flowplayer/flowplayer#1174]
I noticed this on one of my own sites, but checked the demo and the same issue is there.

http://demos.flowplayer.org/lookandfeel/controls-only.html
This is only an issue in the latest Safari release (10.1), it was working previously.

To reproduce:

- Click fullscreen icon on player
- Video goes fullscreen
- Press escape key to exit fullscreen
- Fullscreen icon cannot be clicked again and shows as the minimise icon
- Flowplayer wrapper still has is-fullscreen class added
- Clicking fullscreen icon no longer does anything

Alternatively:

- Click fullscreen icon on player
- Video goes fullscreen
- Click fullscreen icon (should be minimise icon) - nothing happens, but
- Press escape key to exit fullscreen
- Fullscreen icon shows again and can be clicked again and triggers fullscreen

My guess is that this has happened because of a change to how Safari handles fullscreen and how it now allows keyboard interaction on fullscreen video. See 'Keyboard Input in Fullscreen' on https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html

**Comment by blacktrash** [comment]
Can also be repro-ed in a basic setup:
http://demos.flowplayer.org/basics/minimal.html
Note the fullscreen widget also does not change after going fullscreen.
If one then exits fullscreen via escape, it has changed the wrong way, and one can't go fullscreen anymore.
