### ISSUE TITLE
Google Analytic: title does not show up in GA

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1175]
https://stylebites.de/fp7/playersource.html has a title set, but GA only shows the file name:

![top events - analytics_2017-04-10_11-32-31](https://cloud.githubusercontent.com/assets/1395672/24855288/69a2bf38-1de1-11e7-887b-be24373927c9.png)

**Comment by nnarhinen** [comment]
You are specifying `data-title` on the container which won't work.

It should be either `<video data-title="Foo">` or `<div class="flowplayer" title="Foo">`.

**Comment by bbbo** [comment]
argh, yes. sorry for the noise.
