### ISSUE TITLE
Make font sizes more(?) responsive and/or smaller

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1176]
Even discarding portrait players, there are many setups out there where the player size is rather small.

On mobiles the scrubber is very often either non existent or unusable in many scenarios (the situation is better with Flowplayer v6).

Other cases include: quality menu too high -> cannot switch back to ABR.

For my personal taste the fonts are too big in general.

Related to #1143

**Comment by nnarhinen** [comment]
Please test this at http://demos.dev94.flowplayer.us/

Specially for performance related stuff as it's checking the container size in a loop. Would not want to ramp up CPU usage.

**Comment by blacktrash** [comment]
First (optical) impression: brillant!
