### ISSUE TITLE
Tracking to multiple Analytics codes

### ISSUE THREAD

**Issue by DanRobinsonRV** [flowplayer/flowplayer#1177]
I asked this on the [help forum](https://flowplayer.org/forum/#!/embedding_analytics:tracking-to-multiple-analyt) and it was recommended that I post a feature request here.

In Google Analytics, it's possible to use two tracking codes on the same page as follows:

https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers

It would be ideal if Flowplayer could support this behaviour, so that we can allow clients to track their videos while also receiving the stats ourselves. I think the implementation for this could be something like separating the IDs with a comma:

```
        flowplayer("#player", {
            ratio: 9/16,
            analytics: 'UA-XXXXXX-1, UA-YYYYYYY-1'
        });
```
or just an array:
```
        flowplayer("#player", {
            ratio: 9/16,
            analytics: ['UA-XXXXXX-1', 'UA-YYYYYYY-1']
        });
```

Thanks in advance.

**Comment by nnarhinen** [comment]
Analytics will be removed in the future and offered as a separate plugin
