### ISSUE TITLE
API Object not available on "fullscreen" event.

### ISSUE THREAD

**Issue by dattz** [flowplayer/flowplayer#1178]
I'm getting two arguments from my "fullscreen" event. First one is an “Event” object & the second one seems to be the video's div element object instead of the Flowplayer's "api" object.

I get the API object fine in other events like “ready”, “pause” etc.

JsFiddle:
https://jsfiddle.net/az8tp45f/1/

**Comment by blacktrash** [comment]
I confirm that the 2nd argument of the callback function is not the api object, but the `.fp-player` element.

@dattz - for the moment you can work around this for instance by doing this in the global `flowplayer` function:
```js
flowplayer(function (api, root) {
  // use a conditional if you want to confine this to certain players
  // otherwise omit
  if (root.id === "myplayer") {
    // do not reference the 'wrong' 'api'
    api.on("fullscreen", function () {
      api.load({sources: [{ type: "video/mp4", src: "othervideo.mp4" }]});
    });
  }
});
```

**Comment by dattz** [comment]
Any idea, approximately by when this will be fixed?
