### ISSUE TITLE
html5 video tag error handling: message can be empty

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1179]
E.g.
```html
<div class="flowplayer">
  <video>
    <source type="video/mp4" src="does-not-exist.mp4">
  </video>
</div>
```
will show 'html5: Video file not found' in Chrome and Safari, but no (empty?) message in Firefox, with console: 'TypeError: setting a property that has only a getter`.

**Comment by nnarhinen** [comment]
Example url please.

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/basics/bad-url.html
It must be a recent Firefox 'feature', otherwise I would have noticed earlier.
Definitely not a regression, see e.g. http://demos.flowplayer.org/v5/basics/bad-url.html

**Comment by nnarhinen** [comment]
I think this is already fixed?

**Comment by blacktrash** [comment]
Looks like it.
