### ISSUE TITLE
menus usable only once (regression from 7.0.2)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1181]
All self collapsing menus - e.g. quality selection - are not available anymore after one use.

CC menu is not affected, it does not collapse after selection (arguably an UX inconsistency though).

Example: http://demos.flowplayer.org/basics/hls.html (uses Flash HLS, so hlsjs plugin is not involved) and many others.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/basics/hls.html

**Comment by blacktrash** [comment]
Also works with:
- hlsjs
- dashjs
- speed menu
