### ISSUE TITLE
native_fullscreen prevents subtitles from showing (regression from 7.0.2)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1184]
Title says it all. Demo to follow.
Not a corner case as native_fullscreen must be true for iframes which are used for twitter sharing and embed.

**Comment by blacktrash** [comment]
The symptoms vary from browser to browser:
- Safari: no subtitles, also not with 7.0.2!
- Chrome, Firefox: 7.0.2 works, showing fp subtitles
- Firefox 7.0.4: no subtitles
- Chrome 7.0.4: subtitles are shown, but *native*!

Demos:
http://demos.flowplayer.org/bug/1184.html
http://demos.flowplayer.org/bug/1184-702.html

**Comment by nnarhinen** [comment]
Fixed at least for chrome. Please test.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/bug/1184.html

**Comment by blacktrash** [comment]
Desktop:
- Mac: Chrome (inkl. Opera, Vivaldi), Firefox ok
- Mac Safari: no
- IE 11 Win 10, IE 10 Win 8, IE 11 + 10 Win 7: ok
- Windows: IE Edge, IE 11 except Win 10, Chrome: first subtitle not shown
- IE 8, 9 Win 7: no

iOS mobile Safari:
- iPad: no, not even in native fullscreen

Android only cursory tests ok, in spite of Chrome complaining about no crossorigin attribute (I thought the player ads it?)

**Comment by nnarhinen** [comment]
> Mac Safari: no

Works for me..

**Comment by blacktrash** [comment]
> Works for me..

Which Safari version? 10.1.2 here.

**Comment by nnarhinen** [comment]
Same. How does it not work for you?

**Comment by blacktrash** [comment]
Ah - yikes. Had to do the full close-all-windows-empty-cache-restart-browser-routine ...
Works now.
