### ISSUE TITLE
automatic reload the video source if stream down

### ISSUE THREAD

**Issue by darkrole** [flowplayer/flowplayer#1185]
id like to know if is there a way to reload stream automatically if streams get an error for some reason.
im using this script but this just send an error message but dont reload the source:

```
<script>
    var container = document.getElementById("player");


    player = flowplayer(container, {
        ratio: 9 / 16,
        fullscreen: true,
        splash: true,
        live: true,
        embed: false,
        share: false,
        clip: {
            sources: [{
                title: "Canal",
                type: "application/x-mpegurl",
                src: "mystream"
            }]
        }
    }).on("error", function(e, api, err) {
        var x = container.querySelectorAll(".fp-message:not(.fp-title):not(.fp-shown)");
        var i;
        for (i = 0; i < x.length; i++) {
            x[i].innerHTML = "<h2>Channel offline!";
            x[i].innerHTML += "<p>Try again later.";
        }
    });
```

**Comment by nnarhinen** [comment]
All support requests / usage questions should go to the [forum](https://flowplayer.org/forum)

You are, however, most likely looking for something like http://demos.flowplayer.org/scripting/recover.html

**Comment by blacktrash** [comment]
Or, for live streams at http://demos.flowplayer.org/api/live-check.html which is based on the recover demo, but tailored for live streams.
