### ISSUE TITLE
Safari <= 9.1 JS setup: control widgets not appearing, timeline not expanding

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1186]
Safari rendering bug, e.g. http://demos.flowplayer.org/basics/long.html :
<img width="603" alt="screen shot 2017-05-01 at 12 16 13 pm" src="https://cloud.githubusercontent.com/assets/168338/25578628/7accf3e0-2e68-11e7-997e-753a2a32c073.png">

Regression from version 6.
Probably related to: #1138 - but rather with autoplay (including splash)

Goes away when e.g. window is resized.

**Comment by blacktrash** [comment]
FWIW, I'm hacking around this issue with:
```js
flowplayer(function (api, root) {
  if (flowplayer.support.browser.safari) {
    var common = flowplayer.common;

    api.on("ready", function () {
      common.width(root, common.width(root) - 1);
    }).one("progress", function () {
      common.css(root, "width", "100%");
    });
  }
});
