### ISSUE TITLE
Safari 10 does not show subtitle with splash setups

### ISSUE THREAD

**Issue by seizv** [flowplayer/flowplayer#1187]
https://codepen.io/SeizV/pen/gWryRb
Mac OSX 10.12 safari 10 does not show subtitle, but FF and Chrome show.

**Comment by blacktrash** [comment]
Seems to work here http://demos.flowplayer.org/basics/subtitle.html
<img width="1028" alt="screen shot 2017-05-04 at 12 26 32 am" src="https://cloud.githubusercontent.com/assets/168338/25685595/7ae70ad8-3060-11e7-8eef-dfe40698c5e8.png">
