### ISSUE TITLE
live (not DVR): seek to live position before resuming

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1190]
In my opinion this makes more sense. And the behavior can become slightly erratic if the player tries to play some cached segments outside the live window after a long pause.
https://flowplayer.org/forum/#!/open_word:pause-play-back-to

There is nothing to be done regarding native playback (duration == Infinity), except when a DVR stream is shown in a live UI, but Flash HLS is affected.

Easy to implement in a beforeresume callback.

@nnarhinen - let me know whether you are ok with this, I can submit a patch then.

Somewhat related:
https://github.com/flowplayer/flowplayer/issues/1189

**Comment by blacktrash** [comment]
Basically this does it:
```js
api.on("beforeresume", function (e, api) {
    if (api.video.duration && api.video.duration !== Infinity) {
      api.seek(api.video.duration);
   }
});
```
for Flash HLS. Not sure where the appropriate place for this would be in the code. @nnarhinen
