### ISSUE TITLE
iPad fullscreen not working when launched from a div with  z-index

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1193]
An example: http://download.serviio.org/temp/test/

It looks like fullscreen on iOS needs much higher z-index to be on top a potential z-indexed div it is placed in.

**Comment by blacktrash** [comment]
The problem is not z-index, but the `overflow-x: hidden` directive for the wrapper DIV in your sample.

**Comment by xnejp03** [comment]
I need that to be able to produce a 'modal box', incl. the player.

It this fixable in Flowplayer? It only happens on iOS.

**Comment by blacktrash** [comment]
Did you try our overlay plugin - https://flowplayer.org/docs/plugins.html#overlay ? Besides a 'native' implementation, it offers 2 vendor addons: https://flowplayer.org/docs/plugins.html#overlay-vendors
If that doesn't cover your needs, look at its code base for inspiration: https://github.com/flowplayer/flowplayer-overlay

**Comment by xnejp03** [comment]
Just tried the example URL with removed the z-index and fullscreen worked. So I think my original description was right (caused by z-index, not overflow).

For the record, this is the code that doesn't work:

```html
<div style="height: 300px; width: 400px; margin-left: 69.95px; margin-top: 45.8px; left: 0; top: 0; position: absolute; z-index: 10; overflow-x: hidden; background-color: blue">
	<div class="flowplayer" data-ratio="0.4167">
	   <video>
			<source type="video/webm" src="http://edge.flowplayer.org/functional.webm">
			<source type="video/mp4" src="http://edge.flowplayer.org/functional.mp4">
	   </video>
	</div>
</div>
```

**Comment by blacktrash** [comment]
Did you try removing overflow-x? From that point of view, we are both right ;-)

This works for me with your example:
```js
flowplayer(function (api, root) {
  api.on("fullscreen", function () {
    root.parentElement.style.overflow = "visible";
  });
});
---

**Comment by blacktrash** [comment]
btw, the symptoms are similar to when one tries to make the player go fullscreen from within an iframe on iOS and `native_fullscreen` is not set. That's why I went for overflow.

**Comment by xnejp03** [comment]
Thanks, the callback code seems to do the trick.

**Comment by nnarhinen** [comment]
This is not really fixable by the player. Hopefully in the future Safari will support real fullscreen.
