### ISSUE TITLE
nativesubtitles do not work

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1194]
http://demos.flowplayer.org/bug/577.html

They also don't work in JS installs.

**Comment by nnarhinen** [comment]
Workaround: use splash setup

**Comment by blacktrash** [comment]
@nnarhinen - that does not help in latest Firefox (which by now also has the problem).

**Comment by nnarhinen** [comment]
This is actually fixed now in dev (for browsers not misbehaving). Test results appreciated.

**Comment by nnarhinen** [comment]
Nope, not for video tag based setups yet..

**Comment by nnarhinen** [comment]
Now fixed properly.

**Comment by blacktrash** [comment]
Great.
Firefox doesn't show the subtitles on the first frame, but that's a nitpick and imho not worth pursuing.

**Comment by blacktrash** [comment]
@nnarhinen - no subtitles on iOS yet (this time I purged cache on iPhone); the issue was more about desktop browsers, so just FYI.
