### ISSUE TITLE
play m3u8

### ISSUE THREAD

**Issue by zengmeng1094** [flowplayer/flowplayer#1195]
I use flowplayer as my web player to play the video in my project.There is a question that if I play a M3U8 type video,the control become strange:if I use function seek(),it will seek to a near time not a exact time.By my experiments,I found that the player real seeked time is a TS section's head time which near to seek time(I chose).And the TS section from parsing M3U8 and got by HTTP.I want to get a exact time in the player,how to do ?

**Comment by blacktrash** [comment]
Please ask usage questions in our forum - https://flowplayer.org/forum - and please provide a link to a *minimal* sample page which demonstrates the problem.
I cannot reproduce this. Unless the Flash HLS engine is used. See the `seekmode` flashls option: https://flowplayer.org/docs/setup.html#flashls
