### ISSUE TITLE
iPad mute button doesn't work

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1196]
For example, load your Mute example player on the Skinning doc page. Clicking on the Mute button does not mute the sound.

iOS 10.3.1

**Comment by blacktrash** [comment]
The bug is that it appears on iOS in the first place: Volume changes are only possible via device controls. The volume bar is never shown on iOS.

**Comment by blacktrash** [comment]
Fix can be checked at http://demos.1197f.flowplayer.me/not-indexed/skins.html
