### ISSUE TITLE
seek to 0 reports undefined target pos in 3rd seek event callback argument

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1198]
This happens only with the html5 engine, regardless of video type.
Not with Flash, Flash HLS, hlsjs, or dashjs.

It also happens regardless of whether `loop` is specified on clip level or player level.

Can be worked around, but is inconsistent.

See: https://flowplayer.org/forum/#!/setup:target-position-undefined

**Comment by nnarhinen** [comment]
Not specific to loop.

**Comment by nnarhinen** [comment]
Fixed in #1263
