### ISSUE TITLE
Uncaught ReferenceError: flowplayer is not defined

### ISSUE THREAD

**Issue by tomybyte** [flowplayer/flowplayer#1199]
Hi,

on big pages (with a lot of Ads and JavaScript) the Script will be loaded successful (without errors in console)
    
    <script> src="//releases.flowplayer.org/7.0.4/flowplayer.min.js"></script>
    
But function call flowplayer failed with "Uncaught ReferenceError: flowplayer is not defined"

    var api = flowplayer('#player', {});

After a lot of debug I found the problem here:

    (function(f) {
    	if (typeof exports === "object" && typeof module !== "undefined") {
    		module.exports = f()
    	} else if (typeof define === "function" && define.amd) {
    		define([], f)
    	} else {
    		var g;
    		if (typeof window !== "undefined") {
    			g = window
    		} else if (typeof global !== "undefined") {
    			g = global
    		} else if (typeof self !== "undefined") {
    			g = self
    		} else {
    			g = this
    		}
    		g.flowplayer = f()
    	}
    })

This is the result of console.log(define.amd)

    Object {jQuery: true}

My Hack at the moment is this before loading flowplayer.min.js but it may have side effects to the rest of the webpage

    // @HACK: for flowplayer not working with Expose the class either via AMD
    if (typeof define === 'function' && define.amd) {
    	delete define.amd;
    }

The same Bug is in the HLS Plugin //releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js

**Comment by blacktrash** [comment]
This is taken from here: https://github.com/umdjs/umd/blob/master/templates/returnExports.js

@tomybyte - I would be interested in actual page where this happens. How are the scripts loaded, in what order, in HEAD or at end of body etc.

**Comment by tomybyte** [comment]
Hi blacktrash,

sorry but I cant give You a running example because it is part of a dynamic video content placement!
The Problem was on this urls:
http://www.giga.de/spiele/syberia-3/tests/syberia-3-im-test-grafisches-und-sprachliches-metzelfest/
http://de.moviepedia.wikia.com/wiki/Pflanzenmonster-Quiz

To have no document ready dependency the flowplayer JavaScript is loaded in body by script onload event

		--- snip ---
		var l = document.createElement('script');
		l.type = 'text/javascript';
		//l.async = true;
		l.src = url;
		if (onload) {
			if (l.addEventListener) {
				l.addEventListener('load', onload, false);
			} else if (s.readyState) {
				l.onreadystatechange = onload;
			}
		}
		--- snap ---

**Comment by tomybyte** [comment]
Hi blacktrash,

FYI this was the only what I found in web but it is the wrong way because it don't produced an exception https://groups.google.com/d/msg/amd-implement/c9EcRZyKmvA/XoQcS_OpL7AJ

	--- snip ---
	if (define && define.amd) {
	  try {
	    define([], myExports);
	  } catch (e) {
	    (module && module.exports) ? module.exports = myExports : window.myName = myExports;
	  }
	}
	else if (module && module.exports) {
	  module.exports = myExports;
	}
	else {
	  window.myName = myExports;
	}
	--- snap ---

**Comment by nnarhinen** [comment]
Lacks minimal reproducable test page.
