### ISSUE TITLE
Safari 10.1+ fullscreen mode not completed

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1203]
Player goes fullscreen, but:
- fullscreen canvas (.fp-player background) color not there
- fullscreen button still in normal
- click on fs button has no effect

Unfortunately does not happen regularly.
But I am not alone: https://flowplayer.org/forum/#!/setup:fullscreen-feature-in-safar

May be related to https://github.com/flowplayer/flowplayer/issues/1174 - or fix was not complete.

See also: https://github.com/flowplayer/flowplayer/issues/1191

**Comment by blacktrash** [comment]
FWIW - this hack https://github.com/flowplayer/flowplayer/issues/1186#issuecomment-306039414 seems to help here as well. Rather messy.

**Comment by nnarhinen** [comment]
Fixed by 6b2732b849ced8e46bf7ee45682e99135e971a76
