### ISSUE TITLE
windows phone: only works with hlsjs and dashjs engines

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1211]
- http://demos.flowplayer.org/basics/minimal.html - does not work
- http://demos.flowplayer.org/videotest/mp4.html - even plain video tag does not work, I haven't found a way to make a plain video tag work yet
- http://demos.flowplayer.org/api/hlsjs.html - works
- http://demos.flowplayer.org/api/dash.html - VOD works (investigating live example)

**Comment by nnarhinen** [comment]
Is this still true for 7.2?
