### ISSUE TITLE
windows phone: video tag always of 16:9 aspect ratio

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1212]
By lack of working simple MP4 examples (#1211):
- http://demos.flowplayer.org/basics/long.html - should be 4:3
- http://demos.flowplayer.org/api/hlsjs.html#vod - should be 12:5

Always a 16:9 video tag is fitted into the container with the correct aspect ratio.

I'll try with vanilla hls.js whether this is due to percentage CSS for the video tag, or whether even a) unit CSS dimensions b) width and height attributes are ignored.

**Comment by nnarhinen** [comment]
Is this a problem still?
