### ISSUE TITLE
buffer not updated after seek

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1213]
1. go to http://demos.flowplayer.org/basics/subtitle.html#srt
2. start playback
3. seek to somewhere in the middle of the video
4. wait
5. buffer display is not updated

This happens when there is more than one member in the videoTag.buffered time ranges, the buffer event only checks `buffered.end(null)`.
This does not happen with the hlsjs and dashjs engines which cycle to the time ranges array and picks the buffer which is nearest and higher/equal to playhead position, so I guess the html5 engine should do something similar.

**Comment by blacktrash** [comment]
See: https://flowplayer.com/forum/#!/skinning_css:buffering-bar-does-not-move

**Comment by nnarhinen** [comment]
This was fixed in 7.2
