### ISSUE TITLE
iOS fullscreen: navi bar sticks and interferes with video and player display

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1214]
This is a long standing issue. Often the navi bar goes after a user gesture, but not always.

Find out a way to hide the bar. Other players apparently do not have the problem. Personally I often set `native_fullscreen` because of this, but this can lead to other troubles (subtitles).
https://flowplayer.com/forum/#!/setup:flowplayer-ios-full-screen

**Comment by blacktrash** [comment]
So far my research is negative.
For iOS < 8 one could set a minimal viewport for the entire page (which is not really what we want), but even that is gone.
It looks like the alternatives are:
- hope that the user rotates devices once or twice
- set `native_fullscreen: true` (other players do only that)

**Comment by nnarhinen** [comment]
Yeah, this is hard to fix :/ Will close until we come up with a good solution.
