### ISSUE TITLE
embed code not copy

### ISSUE THREAD

**Issue by kabsila** [flowplayer/flowplayer#1216]
both html and javascript setup,  if set a title string embed code will not copy when click embed button.

**Comment by blacktrash** [comment]
I presume this is a duplicate of #1205 - the title string contains non-ascii characters?
Please confirm. Otherwise please provide a link to a *minimal* sample page demonstrating the problem, please.

**Comment by kabsila** [comment]
Yes, it contains non-ascii characters.

**Comment by blacktrash** [comment]
@kabsila - thanks.
Closing as it's a duplicate of #1205.
