### ISSUE TITLE
Safari native HLS over https: video width and height are 0

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1228]
This can be reliably reproduced on ready, causing this nasty issue: https://github.com/flowplayer/flowplayer-thumbnails/issues/13

Example: https://flowplayer.com/standalone/huge.html
<img width="833" alt="screen shot 2017-08-03 at 5 24 37 pm" src="https://user-images.githubusercontent.com/168338/28932280-d231d7c0-7870-11e7-81eb-5937ff467304.png">

Sometimes the dimensions are there, once one navigates back to the page and the video is cached.
The subtle timing issue also goes away when hlsjs is allowed for Safari for instance (plugin engine takes longer to get ready) or maybe in other caching circumstances.
It's 100% replicable with the thumbnails plugin though.

**Comment by blacktrash** [comment]
This gives a somewhat higher priority to https://github.com/flowplayer/flowplayer/issues/1200 - and while it will not solve the problem on ready, it could help in other cases.

**Comment by nnarhinen** [comment]
Does the assets for http://demos.1229f.flowplayer.me/basics/minimal.html fix this?

**Comment by blacktrash** [comment]
@nnarhinen - nope, not reliable, I'm afraid; presumably loadedmetadata is triggered before loadeddata anyway?

**Comment by nnarhinen** [comment]
Not necessarily. The order is not consistent: http://demos.flowplayer.org/videotest/events.html

By refreshing that even in chrome multiple times I sometimes get `loadeddata` before `loadedmetadata`.

Can you link to an example that uses the assets from #1229 and misbehaves.

The definition of `loadedmetadata` event says that all information that is going to get extracted from the video is now available. So it's then clearly safari misbehaving if that's not the case. Needs to be worked around of course but I want to see that this really is the case - `videoHeight` being zero on `loadedmetadata`.

**Comment by blacktrash** [comment]
https://flowplayer.blacktrash.org/fp7/hls.html (temporary).
I agree that this is a Safari issue.

**Comment by blacktrash** [comment]
@nnarhinen - FYI, in a plain video tag with preload none HLS video dimensions are 0 both over https and http, and both for loadedmetadata and loadeddata: https://flowplayer.blacktrash.org/test/videotag-ios.html (temporary, nevermind the filename).

**Comment by blacktrash** [comment]
> By refreshing that even in chrome multiple times I sometimes get loadeddata before loadedmetadata.
Arguably that's a bug too. loadeddata should happen  when the 1st frame can be rendered, and to render a video frame you need the metadata.

**Comment by nnarhinen** [comment]
Can you re-copy the assets.

**Comment by nnarhinen** [comment]
I changed the approach.

**Comment by nnarhinen** [comment]
I don't think it makes sense to do this in `progress`. As `ready` is where you need the width/height the most IMO.

**Comment by blacktrash** [comment]
Sure. You could postpone ready until the first progress ;-)
With hlsjs I get the best looking user facing experience in Safari on first seek (because hls.js does a minimal seek, probably to adjust timestamps) ... fails miserably with e.g. playlist next/prev though.

A timeout looks weird e.g. with https://flowplayer.blacktrash.org/fp7/hls.html?autoplay=true when the stream doesn't start quickly - not at the moment to show the dimensions problem with a fast loading stream.

**Comment by blacktrash** [comment]
How about `canplay`? Seems to come always after `loadeddata` at http://demos.flowplayer.org/videotest/events.html

**Comment by nnarhinen** [comment]
How about now?

**Comment by blacktrash** [comment]
Before I forget: desktop Safari detection is:
```js
flowplayer.support.browser.safari & flowplayer.support.dataload
```
Otherwise IEMobile is included, see: https://github.com/flowplayer/flowplayer-hlsjs/issues/79

**Comment by nnarhinen** [comment]
`IEMobile` can be considered obsolete at this point. It's practically dead.

**Comment by blacktrash** [comment]
Well, it was an easy fix, and will save me a couple of hours of debugging in the future ;-)

**Comment by blacktrash** [comment]
And, no, it doesn't help either :-( - close window, empty cache. quit, relaunch, navigate -> 0x0.

**Comment by blacktrash** [comment]
@nnarhinen - it seems to work with `canplaythrough`.

**Comment by nnarhinen** [comment]
Will use that for safari.

**Comment by nnarhinen** [comment]
Thanks for your help with this.

**Comment by blacktrash** [comment]
FWIW, I made a quick check with playlists, it doesn't seem to have any adverse effects.
