### ISSUE TITLE
Where can i change the request query params from flowplayerhls.swf?

### ISSUE THREAD

**Issue by JSoon** [flowplayer/flowplayer#1230]
I want to add a timestamp everytime i request the .m3u file from server, so i won't get A `from cache` file in the browser. This is worked for me when the server response with the same date(when i compile the swf myself, in my videojs project).

So which file should i modify and compile the flowplayer flash?

This is my situation:
![image](https://user-images.githubusercontent.com/7589350/29020499-cde4c160-7b94-11e7-99a1-dfd99a3ead32.png)

This is where i modify the request query params in my videojs project:

<img width="1166" alt="qq20170807-172834 2x" src="https://user-images.githubusercontent.com/7589350/29020845-e886f910-7b95-11e7-9967-0c7c8e6ecded.png">

**Comment by blacktrash** [comment]
That would likely be https://github.com/flowplayer/flowplayer/blob/master/lib/as/HLSStreamProvider.as

**Comment by blacktrash** [comment]
Note that for hlsjs this can be achieved with the `xhrSetup` hlsjs [option](https://flowplayer.com/docs/plugins.html#hlsjs-options): https://github.com/video-dev/hls.js/blob/v0.7.11/doc/API.md#xhrsetup

**Comment by JSoon** [comment]
Thanks for helping me last time, and now i may have a new problem with compiling flash.

1. When i ran the `make flash` command, i got a error that told me `./dist/Flowplayer.as: No such file or directory`

2. Then i realized that maybe it's because i didn't have a dist, so i just ran `npm install`, but i got lots of error after that.

So i think maybe i have a wrong version of node, can you tell me what's the right version of node should i use to install the packages? Or could u pls give us more details about the usage of **COMPILING FLASH** tutorial? Thanks, really need your help :)

**Comment by JSoon** [comment]
One more error, steps:

1. npm run fixmeprepublish

2. got a `/opt/flowplayer/flex3sdk/bin/mxmlc: No such file or directory`

**Comment by JSoon** [comment]
I got a Open Source Flex SDK, v4.5.1 and i set the right env path for sure.

**Comment by JSoon** [comment]
Could u help? I plan to buy a lisence before our site deployed but this would be a problem bases on our m3u8 stream. @blacktrash

**Comment by nnarhinen** [comment]
please run `mxmlc -version`

**Comment by nnarhinen** [comment]
it might be you need to set `PLAYERHOME_GLOBAL` or such env var too.

**Comment by JSoon** [comment]
Does Flex SDK only can be used under Windows? @nnarhinen

**Comment by nnarhinen** [comment]
No, it works on OSX and Linux as well.

**Comment by JSoon** [comment]
# compile flash
Loading configuration file /Users/Soon/__richinfo__/miguyinyue/player/video/flex_sdk/flex_sdk_4.5.1.21328A_mpl/frameworks/flex-config.xml
/Users/Soon/__richinfo__/miguyinyue/player/video/flowplayer/dist/Flowplayer.as(298): col: 58 Error: Access of undefined property JSON.

                  if (conf[prop] is String) conf[prop] = JSON.parse(conf[prop]);
                                                         ^

make: *** [flash] Error 1

**Comment by JSoon** [comment]
Soon@iMacOfSoon flowplayer (master) $ /Users/Soon/__richinfo__/miguyinyue/player/video/flex_sdk/flex_sdk_4.5.1.21328A_mpl/bin/mxmlc
Loading configuration file /Users/Soon/__richinfo__/miguyinyue/player/video/flex_sdk/flex_sdk_4.5.1.21328A_mpl/frameworks/flex-config.xml
Adobe Flex Compiler (mxmlc)
Version 4.5.1 build 21328
Copyright (c) 2004-2011 Adobe Systems, Inc. All rights reserved.

Error: a target file must be specified

Use 'mxmlc -help' for information about using the command line.

**Comment by JSoon** [comment]
Ok sir, i just completed the compilation:

**Comment by JSoon** [comment]
Soon@iMacOfSoon flowplayer (master) $ /Users/Soon/__richinfo__/miguyinyue/player/video/flex_sdk/flex_sdk_4.6/bin/mxmlc --version
Version 4.6.0 build 23201
Soon@iMacOfSoon flowplayer (master) $ make flash
# compile flash
Loading configuration file /Users/Soon/__richinfo__/miguyinyue/player/video/flex_sdk/flex_sdk_4.6/frameworks/flex-config.xml
/Users/Soon/__richinfo__/miguyinyue/player/video/flowplayer/dist/flowplayer.swf (8487 bytes)
Loading configuration file /Users/Soon/__richinfo__/miguyinyue/player/video/flex_sdk/flex_sdk_4.6/frameworks/flex-config.xml
/Users/Soon/__richinfo__/miguyinyue/player/video/flowplayer/dist/flowplayerhls.swf (61854 bytes)

**Comment by JSoon** [comment]
Maybe you should update the docs to flex_sdk_4.6 ? For me it's not working with flex_sdk_4.5 :(
