### ISSUE TITLE
Attempt to seek to undefined time

### ISSUE THREAD

**Issue by earshinov** [flowplayer/flowplayer#1231]
Hello! We use FlowPlayer in a web application and recently received a notification about an unhandled JavaScript exception throws inside flowplayer:

`"Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite."`

I have identified one possible cause of this error. Among hotkeys supported by FlowPlayer there is "." that presumably seeks video back to last seek position.

    case 190: el.seekTo(); break;                                     // to last seek position

    // ...

    seekTo: function(position, fn) {
        if (position === undefined) return api.seek(lastSeekPosition, fn);
        // ...
    }

The problem is that `lastSeekPosition` might not be initialized here. The case is reproducible in demo setup:
  1. open https://codepen.io/anon/pen/VzpQXy
  2. you might need to limit network bandwidth (e.g., setup throttling in Chrome DevTools)
  3. click anywhere on the demo page to begin loading FlowPlayer
  4. repeatedly press "." while the video is loading
  5. by the moment the video starts playing, there should have been several messages in browser console:

    Uncaught TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.
    at Object.seek (VM1306 flowplayer.hlsjs.min.js:23)
    at Object.seek (VM1305 flowplayer.min.js:8)
    at Object.seekTo (VM1305 flowplayer.min.js:8)
    at HTMLDocument.<anonymous> (VM1305 flowplayer.min.js:7)
    at r (VM1305 flowplayer.min.js:8)
    at HTMLDocument.a (VM1305 flowplayer.min.js:8)
    at HTMLDocument.D (VM1305 flowplayer.min.js:9)

**Comment by blacktrash** [comment]
Thanks @earshinov .

Another symptom of this issue can be observed without throttling and invoking seekTo() without an actual seeking having happened before (target position is undefined):
1. with the hlsjs engine (like in the sample here) the player becomes unpausable
2. with the html5 engine there is no error, but the player goes into seeking state without seeking, and the seeking state can only be "removed" with a seek by the user

**Comment by blacktrash** [comment]
@nnarhinen - in the engine plugins this can be avoided by event.preventDefault() in the beforeseek event.
I'll look into core whether this can/should be confined to seekTo() somehow, or are you OK with the above approach for core as well?
