### ISSUE TITLE
Consistent ID3 metadata handling

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#1235]
Currently ID3 metadata processing has the following issues:
- decodes only UINT arrays which are entirely ascii (just uses `atob`)
- splits into 1 key of arbitrary length, and a data value with an arbitrary limit of 21

To get  ID3 metadata evaluation in a consistent state I propose:
- do not bother about actual ID3 parsing - too many standards, too many tags, implementation or resource would be huge or incomplete
- instead return the complete string, and leave the parsing to the user
- require text-encoding - https://github.com/inexorabletash/text-encoding - because neither IE nor Edge provide a `TextDecoder`. The slim version decodes to UTF-8, UTF-16be, UTF-16le. UTF-16 is required for Windows. It will also automatically use the builtin TextDecoder for speed if present.
- as for text-encoding: as we will require it in the hlsjs plugin for decoding of HLS subtitles (flowplayer/flowplayer-hlsjs#85), expose its TextDecoder to plugins

**Comment by nnarhinen** [comment]
IIRC the text-encoding library is huge and the need for it is a very corner case.

I'd say the need for that polyfill should be left to the implementor.

**Comment by blacktrash** [comment]
We'll see. For the moment I am for passing the byte array on `metadata`.

**Comment by blacktrash** [comment]
As we only need UTF encodings the size can be dramatically reduced.
I did a quick and dirty reduction and the size difference for the minimized hlsjs plugin will be just 16k, or even less, once I get down to it.
