### ISSUE TITLE
7.1.0 splash mobile throws TypeError on start

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1241]
http://demos.flowplayer.org/basics/splash.html
```
TypeError: undefined is not an object (evaluating 'i.muted=!1')
```

**Comment by blacktrash** [comment]
Detected on iOS, but most likely on other mobile devices as well.

**Comment by blacktrash** [comment]
On iOS < 10, the error is: `TypeError: Attempted to assign to readonly property.`

**Comment by nnarhinen** [comment]
Does it affect playback? Anyways, added a check to a place that most likely throws it. Can you take a look at demos.dev94.flowplayer.us ?

**Comment by blacktrash** [comment]
Confirming fix.
Did not affect playback in the simple scenarios I was testing, but better safe than sorry.
