### ISSUE TITLE
7.1.0 iOS < 10: player unusable with autoplay etc.

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1242]
- http://demos.flowplayer.org/basics/autoplay - player unusable
  Most likely because it tries to autoplay (client detection required), and fails to load the native player component.
- http://demos.flowplayer.org/basics/minimal.html - "first frame setup" (impossible with native player component) may not show play button, can need 2 touches to start, exiting shows background "poster" without controls.

**Comment by blacktrash** [comment]
For the second symptom http://demos.flowplayer.org/basics/hls.html is clearer: on exit no controls are shown at all, only the background.

**Comment by nnarhinen** [comment]
@blacktrash Please test this as soon as you find the time at demos.dev94.flowplayer.us. Want to have this fix out before the mass email / blog post.

**Comment by blacktrash** [comment]
Looking good.

**Comment by blacktrash** [comment]
@nnarhinen - sorry, this applies to iPad as well, the bug title was misleading. I'll submit a patch.

**Comment by blacktrash** [comment]
@nnarhinen - something is wrong with current dev already:
- http://demos.flowplayer.org/basics/poster.html uses hlsjs engine if supported
- http://demos.dev94.flowplayer.us/basics/poster.html uses Flash HLS
