### ISSUE TITLE
Javascript API throws "invalid exception" during RTMP livestream

### ISSUE THREAD

**Issue by elyasolden** [flowplayer/flowplayer#1243]
I am using Flowplayer Free to play an RTMP livestream:

```
<div id="player"></div>
<script type="text/javascript" src="http://releases.flowplayer.org/js/flowplayer-3.2.13.min.js"></script>
...

var fp = flowplayer("player", "https://releases.flowplayer.org/swf/flowplayer-3.2.18.swf", {
        clip: {
            url: this.streamInfo.streamUrl,
            live: true,
            scaling: 'fit',
            provider: 'rtmp'
        },
        plugins: {
            rtmp: {
                url: "flowplayer.rtmp-3.2.13.swf",
                netConnectionUrl: this.streamInfo.netUrl
            }
        }
    });
```

The playback works fine, however, if I attempt to use the JavaScript API (e.g. `fp.getTime()`), the following error appears on the console:

```
(unknown) Uncaught Error: Error: An invalid exception was thrown.
    at b.x.(anonymous function) [as getStatus] (http://releases.flowplayer.org/js/flowplayer-3.2.13.min.js:22:7476)
    at <anonymous>:1:18
```

I tested on both Firefox and Chrome on Linux with same outcome.

This exception is thrown when calling any playback-related method (such as play(), pause() or getTime()). The other methods (such as getConfig()) are working fine. After the exception, the playback continues normally. The mouse controls and buttons are working at any time without a problem.

What is the issue here?

**Comment by blacktrash** [comment]
Can you provide a link to a *minimal!* sample page?
Does it fail [here](http://flowplayer.blacktrash.org/test/live.html) as well?

**Comment by crsepulv** [comment]
I had the same problem, the api doesn't worked because I was serving the flowplayer's files from an https CDN, but the player was on an http url, I changed the files to an http location an it worked ok.

This behavior is a bug or is on purpose?

**Comment by bbbo** [comment]
Flash does not like swfs served through https on a http site, hence the error. You should always link the player assets with // so the correct protocol will be chosen.

**Comment by nnarhinen** [comment]
Not something we can fix in flowplayer I think.
