### ISSUE TITLE
dev (build?): firstframe uses Flash HLS instead of hlsjs

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1246]
- http://demos.flowplayer.org/basics/poster.html uses hlsjs engine if supported
- http://demos.dev94.flowplayer.us/basics/poster.html uses Flash HLS

To make matters more confusing my own build of current dev flowplayer.min.js does not have the problem:
http://flowplayer.blacktrash.org/fp7/poster.html

**Comment by blacktrash** [comment]
In browsers where Flash is blocked, MP4 is played instead of HLS (on demos.dev94.flowplayer.us).

**Comment by nnarhinen** [comment]
Can you make a demo where both flowplayer.js and flowplayer hlsjs engine are unminified?

**Comment by nnarhinen** [comment]
I guess this has always been the case or then you have not had a version check in HLSjs engine before:

![image](https://user-images.githubusercontent.com/265438/29634953-2d304b32-8854-11e7-8b9e-ff0fcc9ca84c.png)

**Comment by nnarhinen** [comment]
gitbot seems to set flowplayer version to `dev`. I have not touched anything build specific so most likely just has not come up until now.

**Comment by blacktrash** [comment]
@nnarhinen - seems like good catch, but the version checks in hlsjs should be ok:
- `coreV6 = version.indexOf("6.") === 0` - should be false both with "7.x"and "dev"
- `/^6\.0\.[0-3]$/.test(version)` - should be false with "7.x" and "dev"
- `version.indexOf("5.") !== 0` - should be false with "7.x" and "dev"

That's it. And `Hls.isSupported()` returns true at demos.dev94.flowplayer.us - so I'm still baffled.

**Comment by blacktrash** [comment]
Moreover http://demos.dev94.flowplayer.us/plugins/dash.html uses the dash engine and I have the same version checks in there.

**Comment by blacktrash** [comment]
Aaah - gotcha, the light plugin has a different version check and only one (it doesn't support fp6).
Will take this into account.
Thanks for pointing me in the right direction!
