### ISSUE TITLE
Android Chrome firstframe: errors become fatal with engine plugins

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1248]
On Android Chrome this duration hack[1] always reports the well known `Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.`

With engine plugins this becomes fatal: https://github.com/flowplayer/flowplayer-hlsjs/issues/94 - right now can only be worked around by enforcing splash, plus at the price of a double click after the engine has enforced splash.

I *strongly* suggest to revert to enforcing splash instead of firstframe setups where muted autoplay is supported.

[1] https://github.com/flowplayer/flowplayer/blob/f880c43ba7d7e44c04e0b39c1574b4a45b31e530/lib/ext/mobile.js#L120-L139 - why is this triggered in Chrome? The comment makes it look like it should apply to Samsung Internet browser only? ah - detection problem
There is also the question whether this hack is still needed in view of: https://github.com/flowplayer/flowplayer/blob/master/lib/engine/html5.js#L398-L408

**Comment by nnarhinen** [comment]
Can you check the dev94 assets whether it helped?

**Comment by blacktrash** [comment]
Seems to work. But please re-enable at least mutedAutoplay for Android Firefox. It has/had less probs than Android Chrome.

**Comment by nnarhinen** [comment]
> Seems to work. But please re-enable at least mutedAutoplay for Android Firefox. It has/had less probs than Android Chrome

https://github.com/flowplayer/flowplayer/commit/60b65a3791838e9d8616e4498fb79e8095b2ef81 should not disable anything, only narrows down the `videoTag.play()` hack impact.

**Comment by blacktrash** [comment]
Sorry, https://github.com/flowplayer/flowplayer/commit/34f6b8e98a304e892fd940a1473ad84125effacf is about #1249
