### ISSUE TITLE
Samsung Internet browser: cannot handle firstframe and mutedAutoplay

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1249]
As a first step find a promising way of client detection. That's hard enough, so *if* there is a way, do not support firstframe and mutedAutoplay for it.

**Comment by nnarhinen** [comment]
Is there a device on browserstack that does not work?

**Comment by blacktrash** [comment]
It does/did not work on any Samsung device in browserstack.
But do *not* disable it for Android Firefox, it has the least problems in this regard!

**Comment by blacktrash** [comment]
Just check http://demos.dev94.flowplayer.us/basics/autoplay.html - depending on version also http://demos.dev94.flowplayer.us/basics/1080p.html also hangs.

**Comment by nnarhinen** [comment]
Which first frame setup does not work on which browserstack version? All first frame setups  worked what I tried out.

**Comment by blacktrash** [comment]
Here's the right place regarding: https://github.com/flowplayer/flowplayer/commit/34f6b8e98a304e892fd940a1473ad84125effacf#commitcomment-24020114

**Comment by blacktrash** [comment]
For me http://demos.dev94.flowplayer.us/basics/1080p.html is broken (hangs in loading animation) in stock browser on:
- Galaxy S8+ Android 7
- Galaxy S8 Android 7

On the *older* versions it seems to work. Which is why I suggested at a first step to disable completely because apparently it means diving into Internet browser *versions* as well.

**Comment by blacktrash** [comment]
And https://github.com/flowplayer/flowplayer/commit/34f6b8e98a304e892fd940a1473ad84125effacf#commitcomment-24020648 mutedAutoplay is also still allowed in spite of it being broken in _all_ stock browsers on browserstack: http://demos.dev94.flowplayer.us/basics/autoplay.html
It's because without further userAgent interpretation support.android.firefox == false is presumed to be android.chrome (where the new features work [first frame in dev now]).

**Comment by blacktrash** [comment]
@nnarhinen - it looks like the stock browser can be detected by checking whether userAgent contains `SAMSUNG`.

**Comment by nnarhinen** [comment]
@blacktrash can you open a pull request with proper client detection?

**Comment by blacktrash** [comment]
hm, I just discovered a can of worms: flowplayer.support.android is false for Firefox - check http://demos.flowplayer.org/videotest/support.html -, so flowplayer.support.android.firefox is useless - that's why muted autoplay is not enabled on Android Firefox, although it clearly works at http://demos.flowplayer.org/videotest/autoplay.htm

The stockbrowser thing is easy.

I'll try to sort out the FF stuff as well. Will take a little while.
