### ISSUE TITLE
"Hit ? for help" tooltip

### ISSUE THREAD

**Issue by ghost** [flowplayer/flowplayer#125]
1. Please insert a config option to disable this "Hit ? for help" tooltip. maybe you should also consider to initially hide/disable it, as it doesn't look nice seeing the tooltip all the time when hovering with mouse over video(s).
2. and/or please provide localisation for it! if it is no possible to remove tooltip i should at least be able to have it in my language shown (in my case german).

**Comment by kidequinox** [comment]
it would be awesome if I could disable the tooltip on embedded players also.
