### ISSUE TITLE
[REQUEST] Demo & Documentation update

### ISSUE THREAD

**Issue by hron84** [flowplayer/flowplayer#1253]
Demos page (like [this](http://demos.flowplayer.org/api/load.html)) is completely broken, it should be fixed because it just can't usable right now, codes are shown but I am not pretty sure there is not missing things from the soure.

But the main problem is you describe how FlowPlayer works on its own, but it's available as a jQuery plugin natively, but there is literally no example how can you use different methods if you load FlowPlayer through jQuery as at that point there is no reference to the FlowPlayer API object. If jQuery is a legal way to use FlowPlayer, then it should be definitelly documented more because as  jQuery user I have absolute no idea and no pointer how it should work.

**Comment by bbbo** [comment]
Please use the forums for docs and usage questions.

All docs and demo pages work fine for me in any current browser (the demo pages even in IE9, which we don not suppor with the main site). If you experience issues, please post a screenshot and detailed info on browser and OS version. Note: Internet Explorer's compatibility mode disables html5 video for the browser, do the pages won't work correctly with that.

Flowplayer is not a jQuery plugin and you can not use it through jQuery (we nowhere claim that...). It's there other way round, the player uses the jQuery library for ease of use in <video> tag setups , as explained in https://flowplayer.com/docs/setup.html#videotag-install (the Javascript setups do not use JQuery at all).

**Comment by hron84** [comment]
> Flowplayer is not a jQuery plugin and you can not use it through jQuery (we nowhere claim that...). 
vs
>  the player uses the jQuery library for ease of use in tag setups

So, make it clear: FlowPlayer can be used as normal jQuery plugins (even if it really is not a plugin, provides a jQuery interface). It seems be a legal way to use FlowPlayer.

However, I cannot found any information how to control FlowPlayer if it is set up through the jQuery helper function. You said in the documentation I can provide a configuration hash for the jQuery wrapper function, but I cannot see - and documentation does not help in it - how can I fine-tune loading for example, like on the link in my first post. This should be in the documentation (potentialy as a note in the setup page) because - as I saw - quite much ppl use FlowPlayer via the jQuery interface or whatever you call `$('.player').flowplayer()` function.

**Comment by blacktrash** [comment]
It is documented here: https://flowplayer.com/docs/setup.html#manual
