### ISSUE TITLE
mutedAutoplay: still more fine-grained client detection required

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1258]
For instance - just encountered in practice: Android Chrome < 53 does not support it.
As the player is unusable if the feature is misdetected, we should safeguard against older browsers failing, even if they are not encountered that often in the wild.

@nnarhinen - I suggest that I collect my findings and patches in a dedicated branch for the next release.

**Comment by blacktrash** [comment]
Note that the topic seems to become extremely messy:
https://developers.google.com/web/updates/2016/07/autoplay says in the comments:

>>> This no longer appears to work. Even the demo page doesn't work and I'm using chrome 57.

>> Does not work on Android - Chrome 57.

> Starts to work after changing autoplay policy (chrome://flags/#autoplay-policy). Seems like "Default" no longer supports autoplay muted start on some Android devices (and browser version is not a criteria here).

**Comment by blacktrash** [comment]
@nnarhinen - maybe rather go down the route of an actual capability test?
e.g. along the lines of https://gist.github.com/nathansearles/271870d4100f0f045c5c
?

**Comment by nnarhinen** [comment]
Should be fixed in #1263
