### ISSUE TITLE
Why is api.muted undefined when mute() is called skipping localStorage?

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1259]
For example in the mutedAutoplay case api.muted is undefined. And after unmuting by user interaction api.muted is still undefined.

api.muted is only defined after a call to mute(true/false, false) - why?

**Comment by nnarhinen** [comment]
???

**Comment by blacktrash** [comment]
Just check any setup:
- default behavior - also in mutedAutoplay scenarios(!): api.muted is `undefined`
- in the console, do `flowplayer().mute(true, true)` -> api.muted is still `undefined`
- in the console, do `flowplayer().mute(true)` -> api.muted is `true`

I'll try to come up with a demo with various scenarios.

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/bug/1259.html - play in device which supports mutedAutoplay.

**Comment by nnarhinen** [comment]
https://github.com/flowplayer/flowplayer/blob/master/lib/flowplayer.js#L406 -- this is clearly a bug. `api.muted` should be set in `skipStore = true` scenarios too.

**Comment by nnarhinen** [comment]
`mutedAutoplay` that sets `videoTag.muted = true` in 7.1 is considered a special thing and does not have any correspondence in FP API. It's considered an internal behavior that does not need to be exposed to the outside world. It's not even reflected in the UI in any way.

Can you explain me when you need to query that?

Also, seems the browsers too handle this as a special property - if you set `videoTag.muted = true` the sound indeed is muted, but `videoTag.volume` still returns the previous value, not zero.

To harmonize this, we would have to add a new engine method called `mute()` that either sets the `muted` attribute on video tag where supported or volume to zero.

**Comment by blacktrash** [comment]
1. it's rather counterintuitive when api.muted does not reflect the actual state of the player - one can't use it as a reliable conditional.
2. it _may_ come in handy for IMA, but I guess one could also check for the presence of the muted attribute - I don't know what's more confusing at that point ... similarly with https://github.com/flowplayer/flowplayer-viewport-autoplay/issues/1#issuecomment-330517242 - again it may not be absolutely needed.

Let's ponder this for a moment. If it helps to clarify situations around the whole autoplay kaboodle, we should revisit.

**Comment by nnarhinen** [comment]
As I said, if `api.muted` is to be equivalent of `videoTag.muted`, then the whole engine level volume handling needs to be changed.

And the whole muted autoplay failover is only for mobile clients and html5 video tag, so yes, you can just check the `videoTag.muted` property to detect the "state", if that really is a state that needs querying.

**Comment by blacktrash** [comment]
Righto, closing for now.
