### ISSUE TITLE
Safari 11 does not autoplay videos with sound or HLS

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1260]
http://demos.flowplayer.org/basics/autoplay.html
Stops on first frame. That would not be a problem. But the player does not 'notice', is in playing state, and becomes unusable.

support.firstframe is now definitely not synonymous with support.autoplay anymore.

**Comment by blacktrash** [comment]
As with mutedAutoplay UI-wise the question arises whether we need an option deciding on whether the user prefers mutedAutoplay or pause on firstframe, but unmuted in this scenario.

**Comment by blacktrash** [comment]
If autoplay is not preferred at all costs, it looks like we can works with play promise, at least when it's available, otherwise check video tag directly whether it's in paused state, and then set state accordingly. After that the player is usable again.
That would be kind of 'extended firstframe support'. As first step it would guarantee that the player is usable.

As we don't know beforehand whether a video has sound or not, mutedAutoplay should become more of an _option_ not a feature: the user decides whether they prefer autoplay at all costs. If not they get firstframe.

**Comment by blacktrash** [comment]
Related:
- #1254 - Android firstframe does not work
- #1259 - api.muted undefined with mutedAutoplay, both before and after user touch

**Comment by blacktrash** [comment]
- http://demos.flowplayer.org/videotest/autoplay.html
- http://demos.flowplayer.org/videotest/autoplay-preload.html
- http://demos.flowplayer.org/videotest/muted-autoplay.html

**Comment by blacktrash** [comment]
Similarly, but not exactly as https://github.com/flowplayer/flowplayer/issues/1262#issuecomment-331625518 it works with
- MP4 without soundtrack, regardless how autoplay is set, also with poster, but never with HLS!

**Comment by nnarhinen** [comment]
http://demos.1263f.flowplayer.me/basics/autoplay.html works here now

**Comment by blacktrash** [comment]
So the player is not unmuted anymore on click/touch with mutedAutoplay?

**Comment by nnarhinen** [comment]
It does on iOS where there is no volume control.

**Comment by blacktrash** [comment]
The question was about desktop Safari. And other desktop browsers potentially introducing the autoplay with sound block.

**Comment by nnarhinen** [comment]
Yeah well muted autoplay on desktop is a new feature. We can discuss about it. But for mouse powered browsers it's very intuitive to use the volume control to enable sound. That's how Facebook for instance does it.

**Comment by codener** [comment]
Dear Flowplayer staff, 
when will the "Don't crash on autoplay in Safari 11" fix be released for the commercial version?

**Comment by fdambrosio** [comment]
I have the same problem on Safari desktop. If I set autoplay the stream is muted when it starts.

**Comment by bbbo** [comment]
yes of course. Safari (and Chrome) does not allow autoplay with sound anymore. You either have to live with that,  not use autoplay at all (recommended as almost all users are annoyed by autoplaying videos), or set `mutedAutoplay: false` (new feature from 7.2.2 on) so the player will not attempt autoplay in browsers which do not allow it with sound.

**Comment by fdambrosio** [comment]
thanks @bbbo but it Chrome it doesn't happen. 
I try ` mutedAutoplay: false`

**Comment by nnarhinen** [comment]
Chrome will stop supporting autoplay with audio from version 65.

More information: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by fdambrosio** [comment]
thanks @nnarhinen 
the new Chrome desktop policy is interesting too: 
_On desktop, the user's Media Engagement Index threshold has been crossed, meaning the user has previously play video with sound._
