### ISSUE TITLE
How to implement double click on the ui screen and enter the fullscreen state?

### ISSUE THREAD

**Issue by JSoon** [flowplayer/flowplayer#1261]
Besides to click the fullscreen button, how can i have fullscreen through double click?

**Comment by blacktrash** [comment]
Hit `f` on the keyboard while the mouse hovers over the player.

Double clicking cannot be caught reliably via JavaScript.

**Comment by blacktrash** [comment]
https://flowplayer.com/docs/setup.html#keyboard

@JSoon - please ask usage questions in our forum https://flowplayer.com/forum/ - thank you.

**Comment by JSoon** [comment]
Ok, will do, thanks

**Comment by awakenedguy** [comment]
In JWPlayer, YouTube and Vimeo double click works perfectly for toggling in and out full screen. The playback is not interrupted during the switch. Visibly the global handler first checks if it is a double click and only then - if it is a single click (or something more complicated than that).

Is it feasible to add such a behavior in Flowplayer? I can of course simply add:

`<script>
$( "#flowplayer" ).dblclick(function(dblClickEvent) {
	flowplayer().fullscreen();
});
</script>`

And it works, it can be used in production. The only major inconvenience is that the playback gets interrupted during the switch, as it first triggers a pause, then resume, and only then it toggles the fullscreen.

Another inconvenience is that the play/pause icons flash on the canvas during the switch. But that can be easily solved by adding:

`flowplayer(function (api, root) {
  api.on("ready", function () {
	$(".fp-ui>.fp-play, .fp-ui>.fp-pause", root).remove();
	})
  });`

Is there a way to fix the first inconvenience? That would be so good for QoE.
