### ISSUE TITLE
mutedAutoplay iOS: does not work with poster setups

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1262]
Player hangs in loading state.
Example: http://demos.flowplayer.org/playlist/linkable.html

Somehow escaped my attention for 7.1.2.

**Comment by nnarhinen** [comment]
Works here http://demos.1263f.flowplayer.me/playlist/linkable.html#video-0

**Comment by blacktrash** [comment]
http://demos.1263f.flowplayer.me/playlist/linkable.html#video-0 autoplays instead of hanging.
But it does not go into firstframe/poster state. Or does that mean that we are abolishing poster setups? If yes, for mobiles only? Or?
