### ISSUE TITLE
Changing player canvas color doesn't work anymore

### ISSUE THREAD

**Issue by awakenedguy** [flowplayer/flowplayer#1266]
Those are my findings about how canvas color should normally be changed:

1) https://flowplayer.com/forum/#!/flowplayer/skinning_css:grey-background-above-and-b
2) https://flowplayer.com/docs/skinning.html#canvas
3) https://github.com/flowplayer/flowplayer/wiki/2.99-Skinning-tips

None of those solutions work. Take a look at my sample, canvas should be black, but it still is grey:
http://gdf53zgt.b-cdn.net/sample/index.html

Here is my style.css:
`.flowplayer .flowplayer.is-ready .flowplayer.is-fullscreen .flowplayer.is-playing .fp-player .fp-full {
	background-color: #000;
}`

I am using Windows 10 Pro N, 64 bit
Chrome 61.0.3163.100 64 bit

**Comment by blacktrash** [comment]
That rule applies to a deeply nested element with class="fp-full", you proabably meant to separate these with commas.

```css
.flowplayer,
.flowplayer.is-ready .fp-player {
  background-color: #000;
}
```
should suffice (note the comma!).
