### ISSUE TITLE
Chromecast only works for one instance in a page

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1268]
Which is obviously not how it should be.

**Comment by xnejp03** [comment]
It might be the same cause, but also reloading the player means the Chromecast button is no longer available. Calling api.shutdown() and installing the player again on the same page (as per #1334) should initialize the Chromecast framework again.

**Comment by foliovision** [comment]
Hello @nnarhinen,

here is our fix for the issue: #1445 

1) We make sure https://www.gstatic.com/cv/js/sender/v1/cast_sender.js loads only once on the page
2) When it loads we store it in flowplayer.conf
3) Then we create the button in each player on ready event.
