### ISSUE TITLE
Can not exit full screen on Safari 11

### ISSUE THREAD

**Issue by kasidesh** [flowplayer/flowplayer#1270]
After latest version fixed on safari 10.1.2-3
This issue comes back on safari 11
Full screen cannot exit via click on the icon, It needs to be press `ESC`

![image](https://user-images.githubusercontent.com/829921/31109965-d021932a-a82d-11e7-873d-914472f9554b.png)

![image](https://user-images.githubusercontent.com/829921/31109968-dc2872c4-a82d-11e7-91c6-318584c9c160.png)

**Comment by nnarhinen** [comment]
Already fixed in `dev` branch: http://demos.dev94.flowplayer.us

**Comment by kasidesh** [comment]
When will you release this branch in production version?

**Comment by dattz** [comment]
@nnarhinen In which version is the fix going to be pushed into?

**Comment by nnarhinen** [comment]
@dattz This should be fixed in 7.2.1. Do you encounter the issue still?

**Comment by dattz** [comment]
@nnarhinen Yet to test it. (I don't know why, but I'm unable to find the 7.2 or 7.2.1 versions under my account's **unlimited** tab :confused: )

**Comment by nnarhinen** [comment]
Please contact support for an unlimited build.

**Comment by bbbo** [comment]
@dattz just send your account email to support@flowplayer.com and I'll create a build. You can also test with the standard commercial (or free) player of course.
