### ISSUE TITLE
No audio on Android Chrome

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer#1277]
I have no audio with 7.2.1 on Android Chrome. Samsung browser works ok. Mute/unmute not working.

**Comment by bbbo** [comment]
Works fine for me on Android 7. More details please, and a link to the page you're testing with.

**Comment by awakenedguy** [comment]
Exactly the same for me with 7.2.1. Works fine for Windows 10 desktop, but no audio on Android 7, Chrome, Samsung S8+, latest firmware. It worked just fine with 7.1.2. Checked exclusively on encrypted HLS, mpegts, aac 128k, segment size 2 seconds.

**Comment by bbbo** [comment]
Then as I said, please provide more details.  And a link to a minimal (player setup only) sample page. Our own eHLS demo at https://flowplayer.blacktrash.org/hls-crypt works fine for me with sound in any Droid I could tets with.

Which hlsjs / hls.js library do you use?

**Comment by popler** [comment]
You can check demo stream on http://www.popler.tv/live/4funtv. I'm using HLS (flowplayer.hlsjs.min.js). It is working without problem on Windows (Edge, CHrome, FF) or iOS (Safari).

**Comment by popler** [comment]
You are using 7.1.2 not 7.2.1 on https://flowplayer.blacktrash.org/hls-crypt

**Comment by bbbo** [comment]
damn, yeah you're right. The external demos are not updated automatically. @nnarhinen can you have a look?

**Comment by popler** [comment]
All demos with HLS are broken on http://demos.flowplayer.org/ also.

**Comment by popler** [comment]
This demo https://flowplayer.com/docs/plugins.html#hlsjs have no audio on CHrome Android.

**Comment by nnarhinen** [comment]
This is a bug in the HLS.js engine with splash setup, reported here: https://github.com/flowplayer/flowplayer-hlsjs/issues/100
