### ISSUE TITLE
Getting an error in the console related to buffer

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1278]
Seeing this in the console when using HLS with 7.2.1:

`Cannot` read property 'length' of undefined`

On this line: https://github.com/flowplayer/flowplayer/blob/5cbe2e00d7e7fb11f7525ebaabd4f88ffd1cd8be/lib/flowplayer.js#L643

I assume it's related to this commit: https://github.com/flowplayer/flowplayer/commit/5cbe2e00d7e7fb11f7525ebaabd4f88ffd1cd8be

**Comment by nnarhinen** [comment]
Where do you experience this and on which browser?

**Comment by xnejp03** [comment]
It's intermittent, cannot reproduce every time, so I assume it's a race condition.

Happened when using hls.js light and Chrome on Windows. Just after the load() method is called.

**Comment by huiyiqun** [comment]
I reproduce it each time in safari 11. [here](https://github.com/huiyiqun/flowplayer/commit/3304e7c872445aca833b308d5f958514955a65fc) is my fix(maybe incorrect for I do not have a big picture)

After I fix the error at [this line](https://github.com/huiyiqun/flowplayer/commit/3304e7c872445aca833b308d5f958514955a65fc#diff-e1931397a31f515c7f9fdb6036e34398L344), the error at [this line](https://github.com/huiyiqun/flowplayer/commit/3304e7c872445aca833b308d5f958514955a65fc#diff-e1931397a31f515c7f9fdb6036e34398L344) always appears.

I try to print the content of api.buffered and the result is:

<img width="1263" alt="2017-10-29 1 56 18" src="https://user-images.githubusercontent.com/3468160/32141066-8438cbf6-bc44-11e7-975e-d32c5bacac82.png">

I believe that's the cause.

**Comment by blacktrash** [comment]
Happens with native HLS (desktop Safari) or using hlsjs plugin (other browsers) e.g. here:
http://demos.flowplayer.org/basics/splash.html
Happens with 'minimal' hlsjs engine here: http://demos.dev94.flowplayer.us/lookandfeel/seek-by-time.html

**Comment by awener** [comment]
Having the same issue on safari 11. It works on initial load, but when requesting a new video it fails every time. Starts of fine, video plays for 5-6 seconds, stops and then resets the process and starts playing normally ( video freezes for 3-5 seconds)

**Comment by codener** [comment]
I'm experiencing the very same issue. It reliably occurs when seeking around in Chrome on Linux.

**Comment by epitaphmike** [comment]
This issue is still occurring after the latest update. I updated my version to https://releases.flowplayer.org/7.2.4/commercial/flowplayer.min.js and I am still able to reproduce.

**Comment by nnarhinen** [comment]
Link to a setup please.

**Comment by nnarhinen** [comment]
In which URL...

**Comment by pc9** [comment]
We are using flowplayer in out product and this happens when we seek around in video served from s3 bucket.

**Comment by nnarhinen** [comment]
Without a link to a setup where this happens I can't debug. I'm unable to reproduce this in our own demos.

**Comment by epitaphmike** [comment]
@nnarhinen go to https://media.nhl.com, create an account. I will approve it. Once approved, if you go to the a boxscore on any game page you will get the error.

**Comment by nnarhinen** [comment]
Oh! Thanks..

Before I go ahead and create an account, are you using either https://github.com/flowplayer/flowplayer-hlsjs or https://github.com/flowplayer/flowplayer-mpegdash ?

**Comment by epitaphmike** [comment]
Yes. the hlsjs plugin

**Comment by nnarhinen** [comment]
Could you try if switching to [hlsjs-lite](https://flowplayer.com/docs/player/setup#hlsjs-lite) engine fixes your problems?

**Comment by epitaphmike** [comment]
That seems to have solved the problem. What is the difference?

**Comment by nnarhinen** [comment]
The `hlsjs-lite` engine re-uses same internal HTML5 engine logic of the core Flowplayer. The full-blown flowplayer-hlsjs engine (that has some advanced features like HLS subtitles etc) is not yet migrated to this new re-usable factory and has been neglected for a while development-wise.

**Comment by epitaphmike** [comment]
Thanks for your help.
