### ISSUE TITLE
remove `support.mutedAutoplay`

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#1282]
Currently support.autoplay is true (wrong), but at least support.mutedAutoplay should report true.

**Comment by nnarhinen** [comment]
No one should rely on `support.mutedAutoplay` anymore. It does not reflect behavior anymore.

**Comment by blacktrash** [comment]
So (engine) plugins have to replicate the core code. Or some such.
Why's support.mutedAutoplay there then if it's useless?

**Comment by nnarhinen** [comment]
Forgot to remove it.
