### ISSUE TITLE
Android 4 playback fails for autoplay videos

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#1286]
My Samsung X-Cover 3 Android 4.4.4 phone with Chrome 61 (`Mozilla/5.0 (Linux; Android 4.4.4; SM-G388F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36`) thinks it supports **`autoplay`** and `firstframe`:

The issue can be seen here: http://demos.flowplayer.org/basics/autoplay.html The video fails to play and there is an error on console.

This is what I get in `flowplayer.support`:

```
android:{firefox: false, opera: false, samsung: false, version: 4.4}
animation:true
autoplay:true
browser:{chrome: true, version: "61.0.3163.98"}
cachedVideoTag:true
dataload:true
firstframe:true
flex:true
fullscreen:true
hlsDuration:false
iOS:false
inlineBlock:true
inlineVideo:true
mutedAutoplay:true
preloadMetadata:true
seekable:true
subtitles:true
svg:true
touch:true
video:true
volume:true
zeropreload:false
```

No issues with Android 6.0.1 (Samsung Galaxy S5) and 7.0 (Doogee Shoot 2), autoplay works on both. Sony Xperia with Android 4.0.4 plays the video fine, although with no autoplay.

Seems to me that you only need to **fix the Samsung detection** here to also check for `SM-`: https://github.com/flowplayer/flowplayer/blob/dev/lib/ext/support.js#L48

And/or that you need to improved the **Android version check** to require at least version 5.0 and **not 4.4**: https://github.com/flowplayer/flowplayer/blob/dev/lib/ext/support.js#L87

I tried to hack both fixes into our Flowplayer Unlimited library and it helped.

**Comment by foliovision** [comment]
Even when I fixed the `autoplay` issue to be properly detected for my device (doesn't support it) I run into some issues.

I got this when playing a MP4 video:

```
Uncaught DOMException: Failed to execute 'end' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).
```

It originated from this place: https://github.com/flowplayer/flowplayer/blob/master/lib/engine/html5-factory.js#L344

I see in Flowplayer 6.0.5 there was a try-catch block for it: https://github.com/flowplayer/flowplayer/blob/6ae6ef234951c823b2e0adaeedabc4094e9ef8b6/lib/engine/html5.js#L275-L278

**Comment by nnarhinen** [comment]
The upcoming release works with the 4.4 devices in browserstack:

![image](https://user-images.githubusercontent.com/265438/34669869-82901eec-f47c-11e7-8aa6-e453f9056746.png)


Screenshot from http://demos.dev94.flowplayer.us/basics/autoplay.html

**Comment by nnarhinen** [comment]
Re-open if it still doesn't work. Along with console output when `localStorage.flowplayerDebug = true;`

**Comment by foliovision** [comment]
Hello Niklas,

when using the **stock browser on Samsung X-Cover 3** `Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG SM-G388F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Samsung Browser/2.0 Chrome/34.0.1847.76 Mobile Safari/537.36` it plays.

But I'm not able to seek. When I tap to the timeline it shows the timestamp hint in the right place with the right value, but it won't seek. Since there is no developer console in that browser, I tried to provide my own function for console.log which works, but it won't give me the warnings and errors. But it seems to me that try-catch block is still missing.

When using **Google Chrome 63** on the same phone it still won't play - it gets stuck in the loading phase. I run `localStorage.flowplayerDebug = true;` on the console, reloaded the page and got:

```
DEBUG Autoplay / Splash setup, try to start video
DEBUG Play errored, trying muted DOMException: play() can only be initiated by a user gesture.
DEBUG volumechange -> volume 
DEBUG volumechange -> volume 
```

Thanks,
Martin

**Comment by nnarhinen** [comment]
I don't have access to such device. And X-Cover 3 is from 2015, which in smart device years is ancient. So unless you manage to find the cause and provide a fix, then this unfortunately will not be of high priority atm.

**Comment by foliovision** [comment]
**Stock browser on Samsung X-Cover 3** - unfortunately around 15% of Android users are on Android 4.x: https://developer.android.com/about/dashboards/index.html A lot of these might be Samsung phones.

What about the **Google Chrome 63** bug? It might be related to Android 4.4, but again - since 15% of Android users are still on 4.x, Goolge Chrome (and Firefox) is that they install to be able to play the videos on web reliably.

I **already suggested** a bugfix for that:

> [...] improved the Android version check to require at least version 5.0 and not 4.4: https://github.com/flowplayer/flowplayer/blob/dev/lib/ext/support.js#L87

Could you please check it out?

Thanks,
Martin

**Comment by nnarhinen** [comment]
I can't reproduce your issues at http://demos.dev94.flowplayer.us (or in any page using the development assets)

Please link to a misbehaving setup that misbehaves with a browser / OS combination found on browserstack and I'll fix it.

**Comment by foliovision** [comment]
I can confirm that http://demos.dev94.flowplayer.us/basics/autoplay.html works well with following on Browserstack:

* Galaxy Note 3
* Galaxy Tab 4 10.1

However the Google Chrome browser on these is not 63 but older (58), perhaps it's related to that. I will ask Browserstack support, perhaps they can put up Chrome 63.

However when you hit the home button on one of these devices and run "Internet" - the built in browser, you will at least see the issue with seeking not working. It should be the same "Failed to execute 'end' on 'TimeRanges'" issue with `api.buffered.end` which I reported in this ticket as well.

**Comment by foliovision** [comment]
I got a reply from Browserstack that they plan to update the apps on their physical devices, so once the Chrome 63 is available on these Android 4 devices perhaps you will be able to see the issue.

**Comment by blacktrash** [comment]
I can reproduce this on Nexus 5, Android 6.0.1, with an ancient Chrome 44.
imho there is a logic missing when the play promise is undefined; this seems to fix my scenario:
```diff
diff --git a/lib/engine/html5-factory.js b/lib/engine/html5-factory.js
index 01a200c..911ab0e 100644
--- a/lib/engine/html5-factory.js
+++ b/lib/engine/html5-factory.js
@@ -112,6 +112,11 @@ function html5factory(engineName, player, root, canPlay, ext) {

       ext(video, api, self);
       if (conf.autoplay || conf.splash || video.autoplay) {
+        var restoreManualPlay = function () {
+          conf.autoplay = false;
+          player.mute(false, true); // Restore volume as playback failed
+          player.trigger('stop', [player]);
+        };
         player.debug('Autoplay / Splash setup, try to start video');
         try {
           if (!support.preloadMetadata) api.load();
@@ -123,11 +128,9 @@ function html5factory(engineName, player, root, canPlay, ext) {
               player.debug('Play errored, trying muted', err);
               player.mute(true, true);
               return api.play();
-            }).catch(function() {
-              conf.autoplay = false;
-              player.mute(false, true); // Restore volume as playback failed
-              player.trigger('stop', [player]);
-            });
+            }).catch(restoreManualPlay);
+          } else {
+            restoreManualPlay();
           }
         } catch(e) {
           player.debug('play() error thrown', e);
```
