### ISSUE TITLE
default mediasource for casting

### ISSUE THREAD

**Issue by dominovox** [flowplayer/flowplayer#1287]
Hi,

we rely heavily on gaming 1080p 60fps videos. Is there any possibilty to declare a hls/dash/mp4 file for casting as "default"? Chromecast Gen1+2 and AppleTV 1-3 can't play 1080p 60fps h264 videos.

For example: 
- normal manifest with 480p, 720p and 1080p60 media for normal player/browsers
- manifest for casting with 480p and 720p media

Thanks,
Dominik

**Comment by nnarhinen** [comment]
I don't think there is. :( The Chromecast support will be greatly rewritten / re-designed in  the 7.3 release scheduled later this year / early next year. We will take this requirement in account then.

**Comment by dominovox** [comment]
Thanks, adding this feature would be great!
We are trying to establish Flowplayer as an alternative to our JW Player installation - in JW Player we just declare an alternative source (mostly hls after dash) as "default": "true" for the casting default source if that helps you :)
