### ISSUE TITLE
Manual seeking in control bar stopped workin until all video is loaded (7.2.1. Safari)

### ISSUE THREAD

**Issue by michellekg** [flowplayer/flowplayer#1288]
As I said in title, after upgrading to 7.2.1 manual seeking in control bar stopped workin until all video is loaded. It's in last version of Safari. Chrome looks fine.

**Comment by bbbo** [comment]
in our demos as well? If not: link to a minimal sample page please

**Comment by michellekg** [comment]
Your demos works well, I guess, but I'm not really sure because they are too short and loading too fast.

Here's long video on 7.2.1:
http://kg-portal.ru/player_temp.php

And the same video on 7.1.2:
http://kg-portal.ru/player_temp_old.php

Works jut fine.

**Comment by michellekg** [comment]
So, guys, any news on this bug?

**Comment by nnarhinen** [comment]
How about this one http://demos.flowplayer.org/basics/long.html?

**Comment by michellekg** [comment]
Yep, it works, but only with this line:

{ type: "application/x-mpegurl", src:  "//d12zt1n3pd4xhr.cloudfront.net/ccc.m3u8" },

7.1.2 works just fine without it.

**Comment by bbbo** [comment]
@nnarhinen apparently the issue concerns VOD MP4 clip in current Safari and FP 7.2.1, according to some users seeking does not work (even with MOOV atom at the beginning, correct byte-range requests etc). Cowboy Coma MP4 only sample:

http://stylebites.de/fp7/long.html

**Comment by michellekg** [comment]
Yep, it's not working for me either, so that's the problem apparently.

**Comment by michellekg** [comment]
Well, is there any chance this bug can be fixed? 4 days have passed already and this is not a minor bug. I simply cannot use Flowplayer on my website right now. I kinda expected more after I bought this player (

**Comment by nnarhinen** [comment]
I can't spot any problems with http://stylebites.de/fp7/long.html

**Comment by michellekg** [comment]
Well, I still can spot problems.

macOS 10.13, Safari 11.0 (13604.1.38.1.6)

According to @bbbo it's not only me who cannot seek until video is fully loaded.

**Comment by nnarhinen** [comment]
Please give more specific reproduce steps.

Like:

  * Open url X
  * Try to seek to YY:ZZ
  * Player does not seek

I can seek in that stylebites url just fine, and I'm behind a pretty bad 3G/4G connection

**Comment by michellekg** [comment]
1. Open http://kg-portal.ru/player_temp.php
2. Try to seek to 50:00
3. Player does not seek

Maybe it's just Safari 11.0 (not 11.0.1), but I cannot guarantee that all my macOS user using LATEST updates from Apple.

And, as I said many times, 7.1.2 works like magic.

**Comment by bbbo** [comment]
@nnarhinen also from a customer, perhaps this helps:

> We debugged the player a little bit and it seems that on line 1158:
> 
>     arg.seekable = /mpegurl/i.test(video ? (video.type || '') : '') && api.duration || api.seekable && api.seekable.end(null) || player.live;
> 
> The api.seekable.end(null) is throwing an exception, that is ignored few
> lines after.
> 
> If we call $(‘.fp-engine’)[0].seekable.end(null) on browser console it
> returns proper results. Which leads us to believe that Apple has changed
> something and that object is initialized at later stage. Indeed
> flowplayer 6.0.5 didn't have that problem and was able to seek outside
> downloaded parts..
>

**Comment by EggsAreCute** [comment]
My temporary solution is to comment line 3810.
```
max: function(value) {
  // maxValue = value;
},
```
Can you tell me what problems can it cause?

**Comment by michellekg** [comment]
Yeah, thanks a lot, EggsAreCute!

I'm kinda disappointed that support did nothing in almost a week.

**Comment by bbbo** [comment]
@nnarhinen according to a customer, even desktop Safari downloads the whole video before starting in some situations, like here:

https://squeezesupport.getforge.io/HTTPS.html

**Comment by michellekg** [comment]
> @nnarhinen according to a customer, even desktop Safari downloads the whole video before starting in some situations, like here:

No, it's not. This video is working fine. BTW, EggsAreCute's fix works like magic.

**Comment by bbbo** [comment]
hm, they see the problem. Guess it's specific to a Safari and MacOS version... will check
Cool the fix worked. We'll have to test whether it breaks anything else though ;)

**Comment by fdambrosio** [comment]
hi, there's news?

**Comment by nnarhinen** [comment]
Should now be fixed.

Can be tested using http://cdn.dev94.flowplayer.us/dev/flowplayer.min.js
