### ISSUE TITLE
Load into splash plays immediately

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1289]
In previous versions, calling api.load(clip) to a player with splash: true put the player into the splash state and required the user to click play. This seems to have changed in 7.2.1 Is that expected or a bug?

An example: http://jsfiddle.net/xnejp03/8zts054u/embedded/result/

Play the first clip, then click load -> second clip starts straight away.

**Comment by bbbo** [comment]
https://flowplayer.com/forum/#!/setup:load-into-splash-plays-imme

**Comment by nnarhinen** [comment]
This has been the case earlier too: https://jsfiddle.net/tu6z0bu8/embedded/result/ (using FP 7.1.2). In which version was this not the case?

**Comment by xnejp03** [comment]
It definitely worked like that in Flash Flowplayer. I might have missed this bug in earlier versions of Flowplayer 7, so it might have ben there for a while.

Anyway, what is the expected behaviour? If this issue is valid, I'd indeed like it to be fixed in 7.2.2 (have been holding on for this ticker for the last 2 months). If this is the expected behaviour, can you show me a way to load another video into the splash screen (ie to show the cover image) when the user requests it.

**Comment by nnarhinen** [comment]
I don't think we can change this in a patch version at least. AFAIK it has worked like this since the first version of Flowplayer HTML5.

You should call `shutdown()` on the api instance and re-init flowplayer:

https://codepen.io/anon/pen/XVaXPy

**Comment by xnejp03** [comment]
@nnarhinen This setup doesn't work, if I use a black background as per the skinning docs. Is that a bug?

To reproduce:
- play 1st video
- click Change video
- video plays but the black overlay is on top of it

https://codepen.io/xnejp03/pen/MrMdxW
