### ISSUE TITLE
flowplayer is stalled if autoplay is completely disabled

### ISSUE THREAD

**Issue by huiyiqun** [flowplayer/flowplayer#1290]
Since 7.2, the flowplayer try to play the video with sound, but fallback to mute and try again.

But if autoplay is completely disabled, the player will be stalled.

For example in safari 11.0, if I disable autoplay completely and open [this demo](http://demos.flowplayer.org/basics/autoplay.html), the player is not started and I cannot start it even manually.

**Comment by nnarhinen** [comment]
How did you disable autoplay?

**Comment by huiyiqun** [comment]
Safari -> Settings for This Site... -> Auto-Play -> Never Auto-Play

**Comment by nnarhinen** [comment]
Thanks will check

**Comment by Pawan-Bishnoi** [comment]
I am facing this issue too.
Looks like the state management gets messed up here.
Flowplayer assumes the video is running while safari did not let that happen.

**Comment by nnarhinen** [comment]
Fixed by the changes for bf36388e1455138e9fc914e23e15fbd539a95c77
