### ISSUE TITLE
allow Flash to be enabled from the player in Chrome

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1292]
currently in Chrome, if Flash is not set to "always allow" , the player will just show the "unsupported video format" error, but not show the allow Flash popup. Perhaps there is a way to pass this through so viewers can allow Flash for the site directly?

Sample: http://stylebites.de/fp7/rtmpchrome.html -> screenshot
![flowplayer rtmp setup_2017-11-08_16-16-00](https://user-images.githubusercontent.com/1395672/32556798-aa27a206-c4a0-11e7-84ab-a53253786077.png)

**Comment by fdambrosio** [comment]
I have the same problem, can I detect this event?

**Comment by bbbo** [comment]
@nnarhinen can there be anything done about this?

**Comment by nnarhinen** [comment]
Nope, unfortunately chrome is making it more and more hard to use the flash extension. There's no "click to enable" offered anymore AFAIK.

**Comment by fdambrosio** [comment]
@nnarhinen can I trigger this kind of event?

**Comment by nnarhinen** [comment]
What do  you want to trigger?

**Comment by fdambrosio** [comment]
@nnarhinen that event with the error message: "unsupported video format"

**Comment by nnarhinen** [comment]
`api.trigger('error', [api, 10]);` IIRC

**Comment by fdambrosio** [comment]
thanks @nnarhinen
