### ISSUE TITLE
Orientation change leads to error: ‘The index is not in the allowed range’

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1293]
from https://flowplayer.com/forum/#!/embedding_analytics:orientation-change-leads-to :

Using Flowplayer 7.2.1, and hlsjs. Video plays fine in Safari on iPhone. However, when the iPhone is rotated the video freezes. Console output: “IndexSizeError (DOM Exception 1): The index is not in the allowed range. flowplayer.min.js:6:22624”

**Comment by bbbo** [comment]
perhaps related:
https://flowplayer.com/forum/#!/plugins:hlsjs-video-stopping-on-saf

> Whenever scroll down on the screen on Safari (IOS) the video stops playing and wont play again unless I refresh the page. Only happens on mobile
> IndexSizeError (DOM Exception 1): The index is not in the allowed range.

**Comment by fdambrosio** [comment]
I have the same problem  on iOS

**Comment by sulphur** [comment]
me too. Someone know how to fix it ?

**Comment by nnarhinen** [comment]
This should be fixed by the fix for #1309 

Please re-open if not working at http://demos.dev94.flowplayer.us/
