### ISSUE TITLE
Safari 11 autoplay: video cannot be started

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1294]
https://flowplayer.com/forum/#!/setup:safari-autoplay-pause

test page: http://picrow.com/work/about/testfp.html 

> I've upgraded to Flowplayer 7.2 and the most recent HLSJS, I've also set:
> hls: { safari: true }
> Upgrading to 7.2 fixed my Safari 11 fullscreen issue, but my video is still pausing on load and can't be played at all. Is there a way to fix this?
> If you could please let me know, I'd greatly appreciate it. Thanks.

> I'm having a similar problem with Safari and autoplay. The video does not start automatically and clickin on the play button does nothing. I am including a test page. We invoke the Flowplayer instance automatically from the html and employ a commercial license and a playlist. I have simplified the page for ease of testing:

**Comment by nnarhinen** [comment]
http://picrow.com/work/about/testfp.html autoplays just fine on my safari

**Comment by nnarhinen** [comment]
11.0.1

**Comment by nnarhinen** [comment]
Closing until more info.

**Comment by blacktrash** [comment]
I can confirm this (also 11.0.1).
@nnarhinen - you can however observe an IndexError at the start of each video.
IIRC, when I checked this symptom with the unminified script, it was related to the buffer calculation in 7.2; maybe in Safari the length of time ranges _can_ be 0.

**Comment by nnarhinen** [comment]
Cool, I think there's an error about this open already in 7.2.2 milestone
