### ISSUE TITLE
Safari: initial volume set to 0

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1295]
from a user:

> looks like we found an additional issue with the new player in Safari.
> If you check this video for example, its initial volume is 0. In all other
> browsers it’s working well.
> https://www.beach-inspector.com/en/b/matala-beach
> I can remember that we had such an issue in the beginning of flowplayer

**Comment by michellekg** [comment]
I confirm this issue. Can we get a fix a little bit early then 7.2.2 release? The player is pretty much unusable to all safari users on our site right now.

**Comment by nnarhinen** [comment]
Does this happen on our own demos too?

**Comment by michellekg** [comment]
Yes, load method and some others did this on first run. After I changed volume all came back to normal.

**Comment by michellekg** [comment]
It's always mute here: http://demos.flowplayer.org/basics/js-setup-autoplay.html

I think that's somehow related to safari's new autoplay disabling feature.

**Comment by michellekg** [comment]
Okay, sometimes player mutes himself for no reason at all. Sometimes if I click twice (not really fast) on one player.

Here's video of that bug: http://kg-portal.ru/flowplayer/bug.mov

Common, guys, do something, please! The player is fast, but buggy as hell.

We fixed a couple of bugs ourselves, but I don't understand why I have to fix bugs in the player I payed for.

**Comment by nnarhinen** [comment]
It's expected to be muted on  http://demos.flowplayer.org/basics/js-setup-autoplay.html

That's how safari autoplay nowadays work, only allowed muted.

Does it happen on some of the other demos with a clear cache / localstorage?

**Comment by nnarhinen** [comment]
@bbbo that beach inspector stuff most likely is because of the splash setup used in an autoplay manner. That however should be supported, will investigate more.

**Comment by bbbo** [comment]
@michellekg can you provide a *minimal* sample page with splash setup where the player starts muted?

**Comment by bbbo** [comment]
@nnarhinen some further input from a user regarding autoplay / sound behavior:


test link: https://dittytv.com/watch/


> OS/Browser with the issue: Mac - High Sierra - Safari 11
> As you know, when Safari loads you can set a media preference by going to Safari -> Settings for this website and you have these 3 options:
> 1. If the Safari setting is on “Stop media with sound” - everything works as it should.
> 2. If the Safari setting is on “Never auto-play” - The preview is gray, and after clicking play the video plays with no sound until you fidget with the volume slider.
> 
> 3. If the Safari setting is on “Allow all auto-play” - everything works as it should.

**Comment by nnarhinen** [comment]
I'm 99% sure this got fixed by the other fixes made for 7.2.2 (namely #1307 and #1304).

If the problem persists on http://demos.dev94.flowplayer.us/ please re-open.
