### ISSUE TITLE
How to play video with pure js?

### ISSUE THREAD

**Issue by edouard-lopez** [flowplayer/flowplayer#1298]
I'm trying to setup flowplayer in order for user to play video by click a link.

### Works

When the container container a `href` attribute no problem

**html**

    <div id="player-one" class="player" href="http://lsf.education.fr/videos/abbaye.flv"></div>

**js**
```
    let container = document.getElementById('player-one');
    this.player = flowplayer(container, swf, {
      debug: false,
      clip: { autoplay: true }
    });
```

### Don't work

However when I try to pass the video to the flowplayer at instantiation nothing happen.
**html**

    <div id="player-one" class="player"></div>

**js**
```
    let container = document.getElementById('player-one');
    this.player = flowplayer(container, {
      debug: false,
      clip: {
        autoplay: true,
        sources: [
          {
            type: 'video/flash',
            src: 'http://lsf.education.fr/videos/abbaye.flv'
          }
        ]
      }
    });
```

**Comment by nnarhinen** [comment]
You are mixing Flowplayer Flash syntax with Flowplayer HTML5.

You should load the HTML5 assets and then use the syntax from your "Don't work" example.

Take a look here: http://demos.flowplayer.org/basics/js-setup.html

**Comment by nnarhinen** [comment]
Feel free to ask more usage questions at our forum: https://flowplayer.com/forum
