### ISSUE TITLE
Some ui options are not accessible in live stream mode.

### ISSUE THREAD

**Issue by MarcinRabczynski** [flowplayer/flowplayer#1299]
I noticed that .fp-buffer element width is increasing while live stream and is overlapping everything on his right size. After 15 minutes of live stream play .fp-buffer width is 42552%.
The problem exist in Flowplayer Commercial v7.2.1, didnt notice the issue in previous versions.

**Comment by nnarhinen** [comment]
You have to configure `live:true` for the player: http://demos.flowplayer.org/basics/live.html

In the future please ask these usage questions at our [forum](https://flowplayer.com/forum)

**Comment by MarcinRabczynski** [comment]
But this happening with live:true option.

**Comment by bbbo** [comment]
@nnarhinen he is referring to the .fp-buffer element which indeed is present and does have a width. In our own live example, the width fluctuates between ca 100% and 126% at maximum for me, but apparently it increases for him.
@MarcinRabczynski can you create a minimal sample page (clone http://demos.flowplayer.org/basics/live.html ) with your stream?
![flowplayer live stream_2017-11-13_14-59-03](https://user-images.githubusercontent.com/1395672/32729437-111bfdfe-c884-11e7-957b-4f0ef56b737d.png)

**Comment by MarcinRabczynski** [comment]
Unfortunately such sample page will not be possible, authorisation is needed to start camera live stream, stream url is valid only 15 minutes...

Stream type is HLS and is played by flash engine.

**Comment by nnarhinen** [comment]
Yes, sorry, this is a regression. I did not remember the buffer bar is hidden with `visibility: hidden` which is somewhat equivalent to `opacity: 0`.

**Comment by nnarhinen** [comment]
I think this can be worked around with  following CSS rule:

```css
.flowplayer.is-live .fp-bar > *.fp-buffer {
  max-width: 100%;
}
```

(Did not test though).
