### ISSUE TITLE
cuepoints at end of video fire 'cuepoint' events inconsistently

### ISSUE THREAD

**Issue by xxx** [flowplayer/flowplayer#1300]
Hi,

I've discovered that setting a cuepoint to the end of a video (even on just the last second mark) fires the `cuepoint` event inconsistently, like maybe 30% of the time in my experience.

There's a fiddle demonstrating this at https://jsfiddle.net/s8L38syd/15/. After some iterations, the 'unfudged' video will restart from the beginning, because its `cuepoint` event never fired. The fudge factor is an unsatisfactory workaround, but it does seem to work.

This is happening to me on Chrome 62.0.3202.89 on Ubuntu Linux.

edit: I was using 7.1.1 originally, and the issue occurred consistently. With 7.2.1, it still happens, but much less often, it seems. https://jsfiddle.net/s8L38syd/16/ is the 7.2.1 fiddle

**Comment by xxx** [comment]
I've also noticed that the cuepoint event is not fired sometimes, if the player's tab is not the active one. Not sure if related.

**Comment by nnarhinen** [comment]
I could not reproduce this in other browsers than safari. https://github.com/flowplayer/flowplayer/commit/8bac0b7ab33766b9b5f07ead3c6f335eaea2d6a1 fixed it for safari and I couldn't spot any differences in behavior in chrome.
