### ISSUE TITLE
strange behavior in multiple splash pages and lazy load

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1302]
ie https://www.burst.com/f8k5589f

in Firefox I scan scroll down and start / pause videos, but once I paused a video and scroll further down, the paused video resumes once it scrolls out of the viewport.

In Chrome I cannot start clips further down the line after I scrolled down a bit.

**Comment by nnarhinen** [comment]
This should be fixed in 7.2.2
