### ISSUE TITLE
speed and VOD qsel: resumed quality wrong

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1303]
another small thing (might be in the VOD qsel plugin as well): in combination with the speed menu plugin, changing speed and then quality resumes in 1x speed but shows the previously chosen speed in the menu, and it cannot be switched.

https://flowplayer.com/forum/#!/plugins:quality-selector-speed-me

**Comment by nnarhinen** [comment]
I think this has to be fixed in the speed menu plugin.
