### ISSUE TITLE
iOS + splash - player starts muted

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1304]
ie
http://multvn2.ru/video/films/istoriya_igrushek_1

![image](https://user-images.githubusercontent.com/1395672/33199483-de77306a-d0f0-11e7-9432-304389794ceb.png)

see https://flowplayer.com/forum#!/setup:flow-721-muted-sound-on-i

**Comment by nnarhinen** [comment]
How about splash setups in our own demos?

**Comment by blacktrash** [comment]
FWIW, http://multvn2.ru/player/flowplayer.js has no license header, so it might have been tampered with (flowplayer.version is 7.2.1, so header should always be present).

**Comment by foliovision** [comment]
Hello Christian and Niklas,

I can confirm this is an issue too, I just spent some time checking everything and then I found this ticket. When using iOS 11 the video here starts without sound (mute icon shows up): https://flowplayer.com/docs/player/standalone/basics/splash.html

Thanks,
Martin

**Comment by nnarhinen** [comment]
https://flowplayer.com/docs/player/standalone/basics/splash.html should not even have sound

**Comment by nnarhinen** [comment]
I seem to get it here: http://demos.dev94.flowplayer.us/basics/splash.html

**Comment by foliovision** [comment]
I took the first video sources from http://demos.dev94.flowplayer.us/basics/splash.html and put it into the player here: https://flowplayer.com/docs/player/standalone/basics/splash.html

The result can be found here: https://foliovision.com/html/flowplayer-7-ios-no-sound.html

There is no sound on iOS 11 there. So I guess the Flowplayer used in on demos.dev94.flowplayer.us fixed this issue.

When will it be released?

Thanks!
Martin

**Comment by nnarhinen** [comment]
It will be released along with other fixes in 7.2.2 release. You can follow progress at https://github.com/flowplayer/flowplayer/milestone/35

I hope to get the release out this week.
