### ISSUE TITLE
IE appends hash to document title with flash engine

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1305]
https://flowplayer.com/forum/#!/setup:ie-appends-location-hash-wh 

IE appends url hashes (if one is in the url) to the document title each time a splash is clicked, if a #hash is present in the page url.

![image](https://user-images.githubusercontent.com/1395672/33254703-634feaa6-d34a-11e7-829e-f971e5bba7c1.png)

**Comment by nnarhinen** [comment]
https://stackoverflow.com/questions/4562423/ie-title-changes-to-afterhash-if-the-page-has-a-url-with-and-has-flash-s

**Comment by nnarhinen** [comment]
This is such a corner case it does not make sense to implement the workarounds listed in that stackoverflow thread to the core player. So this would be a wontfix unfortunately.
