### ISSUE TITLE
add support for CEA-608/708 captions

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1306]
already implemented in [hls.js](https://github.com/video-dev/hls.js#features) , though missing from [FlashHLS](https://github.com/mangui/flashls/issues/11)

**Comment by mmccook** [comment]
@blacktrash Is this roadmapped and when can support be expected for html5.

**Comment by nnarhinen** [comment]
This is already possible with the `hlsjs-lite` engine and the [HLS subtitle plugin](https://github.com/flowplayer/flowplayer-hls-subtitles)
