### ISSUE TITLE
Chromecast: no subtitles on TV

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1308]
can be observed on
https://flowplayer.com/docs/player/subtitles#subtitle-options (once the subtitle loading issue is fixed) 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fvi2)

**Comment by bbbo** [comment]
https://developers.google.com/cast/docs/chrome_sender_advanced
https://stackoverflow.com/questions/25353459/trouble-getting-webvtt-captions-subtitles-working-on-chromecast
https://github.com/thibauts/node-castv2-client/wiki/How-to-use-subtitles-with-the-DefaultMediaReceiver-app

**Comment by CharlesLuis** [comment]
this is really important! Please, update milestone. Thanks.
