### ISSUE TITLE
Video is restarting on scroll iOS

### ISSUE THREAD

**Issue by AshMorrow** [flowplayer/flowplayer#1309]
On iPAD with iOS 10.2 video is restarting on scroll you can see it on video.

https://www.youtube.com/watch?v=kpVAtCYjI00&feature=youtu.be

**Comment by bbbo** [comment]
please provide a link to a minimal sample page with the video and player setup causing the issue.

**Comment by AshMorrow** [comment]
it's happening on all your demo pages where i tested.
here
http://demos.flowplayer.org/basics/minimal.html
or  here
http://beejee.bohdan.pro/

This problem happening in 90% case, in 10% cases all work normal but after page reload we have this problem again.

**Comment by blacktrash** [comment]
@nnarhinen - that is the 7.2.x viewport scroll issue.

**Comment by blacktrash** [comment]
I can repro at first page load in conjunction with https://github.com/flowplayer/flowplayer/issues/1304

**Comment by enfingit** [comment]
@blacktrash what is this viewport scroll issue? How to fix it?

**Comment by fdambrosio** [comment]
I have the same problem, on IOS the player is unusable. There's a workaround?

**Comment by FlyingPickle74** [comment]
Similar issues here. Can you please give more details on the "7.2.x viewport scroll issue" referenced 3 weeks ago?

**Comment by fdambrosio** [comment]
hi, can we have an update?

**Comment by nnarhinen** [comment]
This issue is scheduled for 7.2.2 which is scheduled to be released early January 2018.

**Comment by rahulshah123** [comment]
Hi there!
Do you have an updated date in January? We're relying on this fix. A date would help us plan out some work if known. It's ok if it's tentative too.
Thanks!
-Rahul

**Comment by fdambrosio** [comment]
thanks @bbbo  we're waiting 7.2.2 too

**Comment by nnarhinen** [comment]
Yes it will be out today or tomorrow. Still needs one issue fixed.

**Comment by rahulshah123** [comment]
Hi @nnarhinen @bbbo, any updates? Still looks like the download page on flowplayer.com is pointing to 7.2.1.

**Comment by bbbo** [comment]
the site has not been updated yet. You just have to replace the version number in the download url though:
https://releases.flowplayer.org/7.2.1/flowplayer-7.2.1.zip ->

1. https://releases.flowplayer.org/7.2.4/flowplayer-7.2.4.zip
