### ISSUE TITLE
On buffer error.

### ISSUE THREAD

**Issue by AshMorrow** [flowplayer/flowplayer#1310]
![selection_119](https://user-images.githubusercontent.com/17051909/33775722-ebc512de-dc47-11e7-8781-c022eeb30f0a.png)
Sometimes, "buffered" is "undefined" on line 4532.
It's happen when i try skip part of video.
Chrome 62. 
You can check it here:
http://demos.flowplayer.org/basics/long.html

**Comment by YaroslavShapoval** [comment]
http://joxi.ru/p27PybgU07pYYA

**Comment by bbbo** [comment]
hm, I can reproduce, but for me it only happens on first seek, not on subsequent seeks

**Comment by AshMorrow** [comment]
https://youtu.be/adoImU6GN3w

**Comment by eduardokraus** [comment]
In my case when progress reaches the buffer of this error and sometimes it stops playback.

**Comment by eduardokraus** [comment]
![75b9e956-44f5-4b3b-bfec-bc020077875c](https://user-images.githubusercontent.com/7725236/35094060-55b5b77c-fc2b-11e7-87b7-16e77fd9b52d.png)
![4cb388b1-3db2-4a49-b878-fc06252e7239](https://user-images.githubusercontent.com/7725236/35094062-55f1dedc-fc2b-11e7-9ba5-ebfc26efeb30.png)

**Comment by nnarhinen** [comment]
This is a bug in the dashjs engine, please re-open there @eduardokraus

**Comment by eduardokraus** [comment]
I got the problem today.

https://github.com/flowplayer/flowplayer/blob/98077d980763783e4f0977db74f46a58f667738e/lib/flowplayer.js#L654

buffered arrived undefined. 

So I did like this:
```
         }).on('buffer', function(e, api, buffered) {
            if( buffered === undefined )
                return;
            api.video.buffer = typeof buffered === 'number' ? buffered : buffered.length ? buffered[buffered.length - 1].end : 0;
         }).on("speed", function(e, api, val) {
```
