### ISSUE TITLE
Feature Request: Custom arrow keys seeking time

### ISSUE THREAD

**Issue by Amin52J** [flowplayer/flowplayer#1313]
I believe there should be a config to set the arrow keys seeking time, because it is not a good idea to edit the library file to change its value[1]. I think 10% of the total duration of the video is not the best practice as I observed popular players like **youtube** and **dailymotion's** seek time via arrow keys are +-5 seconds (it used to be 10 seconds).
Thanks in advance

[1] Please take a look at [this discussion](https://flowplayer.com/forum#!/flowplayer/scripting_api:8651_can_i_change_t) for a reference to this feature request.

**Comment by bbbo** [comment]
I agree this should be configurable with a second interval instead of %

**Comment by nnarhinen** [comment]
The seek step can now be configured with `conf.seekStep` conf option.
