### ISSUE TITLE
duration error “Infinity:0NaN:0NaN” using hlsjs + mp3 wowza stream

### ISSUE THREAD

**Issue by fdambrosio** [flowplayer/flowplayer#1315]
I have a problem using mp3 hls stream with Flowplayer 7.2.1. I'm streaming it with Wowza.
The player shows “Infinity:0NaN:0NaN” in the ‘duration’ control. Using Flash or Mp4 hls stream it shows duration correctly.
Testing this mp3 hls stream on HLSJS demo page it shows the duration info correctly ('stats display').

![bug-flowplayer-mp3](https://user-images.githubusercontent.com/2962823/34213481-a8535504-e59f-11e7-8747-0af837e9a927.png)

You can test the stream here: https://video-dev.github.io/hls.js/demo/?src=https%3A%2F%2Fvideo.radioradicale.it%2Fstore-68%2F_definst_%2Fmp3%3A2017%2F11%2FMP916817.mp3%2Fplaylist.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined

**Comment by bbbo** [comment]
looks like a bug in hlsjs, works with plain hls.js indeed. See https://flowplayer.com/forum#!/setup:flowplayer-html5-hls-audio/there-is-another-strange-bu (note: seeking does not workin Chrome even with plain hls.js)

**Comment by nnarhinen** [comment]
Plese re-open this in the hlsjs repository
