### ISSUE TITLE
Feature Request: toggle Full screen on double click

### ISSUE THREAD

**Issue by awakenedguy** [flowplayer/flowplayer#1316]
Was previously mentioned in #1261 

In YouTube and Vimeo double click works perfectly for toggling in and out full screen. The playback is not interrupted during the switch. Visibly the global handler first checks if it is a double click and only then - if it is a single click (or something more complicated than that).

Is it feasible to add such a behavior in Flowplayer? I can of course simply add:

`<script>
$( "#flowplayer" ).dblclick(function(dblClickEvent) {
flowplayer().fullscreen();
});
</script>`

And it works, it can be used in production. The only major inconvenience is that the playback gets interrupted during the switch, as it first triggers a pause, then - a resume, and only then it toggles the fullscreen.

Another inconvenience is that the play/pause icons flash on the canvas during the switch. But that can be easily solved by adding:

`flowplayer(function (api, root) { api.on("ready", function () { $(".fp-ui>.fp-play, .fp-ui>.fp-pause", root).remove(); }) });`

Is there a way to fix the first inconvenience? That would be so good for QoE.

**Comment by nnarhinen** [comment]
This can be scripted: https://demos.flowplayer.com/scripting/double-click-to-fullscreen.html

**Comment by awakenedguy** [comment]
Thank you, I was waiting for this functionality for so long. The player seemed incomplete without it. After customizing this scripting code a little, it becomes a perfection (in line with YouTube / Vimeo).

**Comment by awakenedguy** [comment]
There are 3 bad things about proposed scripting code:

1) 500ms is too much, as there is a price to pay - toggle pause/play also waits 500ms before reacting. I reduce it to 220ms, which seems to be very close to what Vimeo is using, according purely to feeling.

2) all click handlers were turned off, so now when one click to any player on screen GUI control button, it also triggers api.toggle() - play/pause, which is of course not desirable. E.g. that leads to play/pause button to trigger the same action twice. Also when I click to volume, or quality selector, or full screen button, play/pause triggers as well. So I fixed that. BTW some other player on screen controls should also be concerned, such as "share" or something else. I am just not using them.

3) for mobile it's not necessary at all

So here is my modified variant which includes those fixes:
https://gist.github.com/awakenedguy/62d259f42b20f34544a3236ebc6fc293

**Comment by awakenedguy** [comment]
Now the only big difference with Vimeo is what happens when one double click takes more than 220ms. In this case Vimeo doesn't trigger fullscreen at all, it instead just triggers first play, then a pause.

Flowplayer with this scripting in this case still triggers fullscreen + also play + pause.

Vimeo behavior seems way better from UX perspective to me, but I don't know how to do that here. It requires experiments + better knowledge of flowplayer click handling.

**Comment by zerom1nd** [comment]
awakenedguy, iam tested u script - work fine, but if i use CC (subtitle) and choose subtitle (one click of list) - work pause ((( and subtitle switch. How remove pause on click subtitle list menu ?
