### ISSUE TITLE
Global configuration option to disable localStorage

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1317]

**Comment by nnarhinen** [comment]
You can now pass `flowplayer.conf.storage = {}` to disable usage of `localStorage`.

**Comment by bbbo** [comment]
@nnarhinen   https://github.com/flowplayer/flowplayer/commit/086987b89284f6fe116ee763d86e76fffe244ac5 makes this a true/false player config option?

**Comment by nnarhinen** [comment]
No it does not.
