### ISSUE TITLE
New engine extension API could be more future-proof

### ISSUE THREAD

**Issue by triskweline** [flowplayer/flowplayer#1333]
I saw that the new [`hlsjs-lite` engine](https://github.com/flowplayer/flowplayer/blob/482a7fa1952f159c74fcb567b27087ba639b1b1b/lib/engine/hlsjs.js) contains an [`extensions` property](https://github.com/flowplayer/flowplayer/blob/482a7fa1952f159c74fcb567b27087ba639b1b1b/lib/engine/hlsjs.js#L24) where you can register functions to be called after the `<video>` element was initialized.

You might want to consider moving away from a long list of arguments (currently `hls, player, root`) to an object like `{ hls: ..., player: ..., root: ...}`. This way you can extend it the API with additional properties later, without worrying about breaking other people's code.

For instance, we would really love to get access to the `<video>` element. In the future, it would probably be nice to hook into additional points of the engine lifecycle. All that could be added to such an object.

**Comment by nnarhinen** [comment]
Good suggestion. Will add that in the next version.

**Comment by nnarhinen** [comment]
This will be changed in the next release.

The signature will now be
```js
function(opts) {
  // opts.hls - the hls.js instance
  // opts.root - player container
  // opts.player - player api
  // opts.videoTag - video tag used by the engine
}
```

**Comment by triskweline** [comment]
That will be a great improvement, thanks.
