### ISSUE TITLE
`.fp-player` element should be removed on `shutdown`

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1334]
As a workaround to #1289 @nnarhinen suggested to shutdown the api and re-install the player.

That works only when the background colour is transparent.
 
To reproduce:
 - play 1st video
 - click Change video
 - video plays but the black overlay is on top of it

https://codepen.io/xnejp03/pen/MrMdxW

**Comment by nnarhinen** [comment]
You can workaround this by emptying the container element after shutdown: https://codepen.io/anon/pen/dJxeYw
