### ISSUE TITLE
7.2.4 does not obey volume:

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1336]
see http://stylebites.de/fp7/724volume.html / http://stylebites.de/fp7/724droid.html
volume set to 0.1 but the player starts with 3/4 (as stored in local.Storage).

muted: true works.

**Comment by nnarhinen** [comment]
This has always been the case - localStorage wins.

**Comment by bbbo** [comment]
eh, no?
http://stylebites.de/fp7/712volume.html -> volume at 0.1
if you set the volume to 1 during playback with the volume control and then refresh the page it will start with 0.1 again
not so in the 724 demo.  Also not if i disable storage as in http://stylebites.de/fp7/724nostorage.html .

**Comment by bbbo** [comment]
actually I'm not sure storage: false does work at all...

**Comment by nnarhinen** [comment]
Yes setting to false will not have desired effect. It's an empty object you are looking for.

**Comment by DrakkhenD** [comment]
empty object?

**Comment by nnarhinen** [comment]
Yeah `flowplayer.conf.storage = {}` should do the trick.

**Comment by bbbo** [comment]
it does, see http://stylebites.de/fp7/724volume.html .

@nnarhinen this should be a true/false configuration parameter IMO.
