### ISSUE TITLE
Safari, green screen with hls.

### ISSUE THREAD

**Issue by AshMorrow** [flowplayer/flowplayer#1339]
We have problem with green screen on desktop safari when we use safari: true option and hls. 
https://ibb.co/ddex8x
We can't reproduce it on your demo pages but when we use base configuration on our test page we are have same result.
https://ibb.co/dQ3Sac
https://ibb.co/miZ5Tx
How i cant see here http://demos.flowplayer.org/plugins/hlsjs.html safari: true option enable manual quality selection and create problem. 
// enable hlsjs in desktop Safari for manual quality selection
// CAVEAT: may cause decoding problems with some streams!
But if we turn off this option, quality selection in auto mode doesn't work too. It's critical for us.

**Comment by bbbo** [comment]
we cannot debug screenshots. Please *always* provide  a minimal live page with a real stream.

With FP 7.2.4 you should use the [hlsjs-lite engine](https://flowplayer.com/docs/player/setup#hlsjs-lite) instead of the hlsjs plugin.

Does your streeam work in http://video-dev.github.io/hls.js/demo/ and safari?

**Comment by AshMorrow** [comment]
Warning !!! Adult content !
http://beejee.bohdan.pro
http://ibb.co/f56OJx
Here: http://video-dev.github.io/hls.js/demo/ Stream work but like on original page. Video is starting with green screen.
Now i can see that on safari without safari: true option quality can change but only when i use big player are or open video in full screen mode but quality doesnt change back when i have slow connection.
Also i cant get current quality video.haight = 0 other options like Current Level does not exists.

**Comment by bbbo** [comment]
If the stream starts with a green screen in the hls.js demo player, then either the stream is slightly problematic, or the MSE implementation in Safari still broken. Nothing we could do about, sorry.

Without safari: true, Flowplayer is not using hlsj.js but the native Apple HLS. Which does not offer manual selection or a level API.

**Comment by nnarhinen** [comment]
Yes, if the stream has same problems in hls.js reference player there's nothing we can do about it.
