### ISSUE TITLE
Stop load() method autoplay

### ISSUE THREAD

**Issue by elbasan** [flowplayer/flowplayer#1340]
http://demos.flowplayer.org/api/load.html

Is there anyway to load a new video with the load() method but to not start the video automatically  but wait for user input? It seems to also ignore `autoplay`

**Comment by fdambrosio** [comment]
I have the same problem. On the flowplayer forum I had this answer : 
forum thread:  https://flowplayer.com/forum#!/scripting_api:playlist-play-and-seek 

> support: api.load always starts the clip.Like

> will be fixed? How can I setup the player loading the second files without autoplay?Like

> support:  Call pause() immediately after load() I'd say. load() and play() are the same (see /docs/player/api#methods ), and I don't expect this to change.

**Comment by nnarhinen** [comment]
Yeah you need to either call pause/stop in the `load()` callback or then use a splash setup and use `shutdown()` and re-initialize the player. 

I can't really think of any use-case where you actually want to load a new video to the player without playing it. If you can reason enough, we can make this happen to 7.3.

**Comment by fdambrosio** [comment]
@nnarhinen because it doesn't work with 'autoplay: false'

**Comment by nnarhinen** [comment]
Why do you need that feature?

**Comment by elbasan** [comment]
@nnarhinen The main reason for this feature would be on mobile devices, where autoplay is disabled and flowplayer throws the Autoplay without userinput Promise rejection.

I want users to select a video they want to play, load the url with player.load() and then wait for user to play.

**Comment by nnarhinen** [comment]
https://codepen.io/anon/pen/KQOaGo this works just fine on mobiles too? Could you link to a setup where this is actually a problem.

**Comment by imben123** [comment]
@nnarhinen 
I know this is quite old, but I saw this because I'm having trouble with video's in Safari starting muted (even when the user initiates the playback)
Example: https://flowplayer.com/help/demos/basic
I think it's muted because the video autoplays when it loads.

**Comment by elbasan** [comment]
@imben123 have you tried setting `mutedAutoplay: false `

**Comment by imben123** [comment]
@elbasan Yes I've tried that. It didn't seem to have any effect.
See this example: https://codepen.io/imben123/pen/vzPpPv
