### ISSUE TITLE
SVG filters broken when pushState used

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1344]
Needs more investigation.

Refs: https://flowplayer.com/forum#!/skinning_css:svg-filter-url/ok-i-made-a-simple-page-by_1

**Comment by criticerz** [comment]
Hey @nnarhinen ran into this issue for a long time and couldn't figure out what it was until now. 

Any news on when this will be fixed? We're going to try inserting an additional play icon SVG below the default one in case it doesn't show.
