### ISSUE TITLE
add recoverMediaError and recoverNetworkError config options

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1345]
as in the hlsjs pugin: https://flowplayer.com/docs/player/plugins#hlsjs-options 
---

recoverMediaError | true | When true, the hlsjs engine will try to recover from otherwise fatal decoding errors if possible.
-- | -- | --
recoverNetworkError | false | When true, the hlsjs engine will try to recover from otherwise fatal network errors if possible.Note: Enabling network error recovery changes player behaviour, and only for the hlsjs engine.
---

See also 
https://github.com/video-dev/hls.js/blob/v0.8.4/doc/API.md#fatal-error-recovery

**Comment by nnarhinen** [comment]
I imported the code from flowplayer-hlsjs
