### ISSUE TITLE
GA: no views tracked with audio-only players

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1347]
It seems GA data is recorded if we play audio files inside a "normal" player container, but not with audioOnly: true

http://stylebites.de/fp7/hadynamic1.html

**Comment by nnarhinen** [comment]
You need to configure `analytics` in your players.

**Comment by bbbo** [comment]
It is configured. The same setup apparently works with tracking if it's a on audio-only player.

![view-source_stylebites de_fp7_hadynamic1 html_2018-02-18_11-13-24](https://user-images.githubusercontent.com/1395672/36350703-ce9eca3c-149c-11e8-90e6-39902ecb418f.png)

**Comment by nnarhinen** [comment]
You don't have any player with id `fp-audio` on that site. You have `player3` and `player4`.
