### ISSUE TITLE
Encrypted HLS fails on safari

### ISSUE THREAD

**Issue by robov** [flowplayer/flowplayer#1349]
I tried playing this file on safari, but it fails to play : https://flowplayer.blacktrash.org/hls-crypt/
on chrome it works like a charm

Any idea ?

**Comment by nnarhinen** [comment]
First of all, it seems that demo is way outdated, uses an old version of flowplayer. We need to upate that.

It does however work on my mac safari. So without further details and an url to a more recent setup we can't really do anything to help you.

**Comment by robov** [comment]
Interesting... now I have no clue how to debug... on my windows safari it breaks. Maybe if you update it... so I can check if it works with the new version on my safari ?

**Comment by nnarhinen** [comment]
Safari on Windows is from 2012. We cannot support abandoned browsers.

**Comment by robov** [comment]
Aha... I did not know that (I am a windows guy, so I installed safari only after hearing problems)

**Comment by bbbo** [comment]
better remove it ;) it's basically one big security hole.
https://www.pcper.com/news/General-Tech/Apple-No-Longer-Updating-Safari-Windows-Users-Should-Switch-More-Secure-Browser

**Comment by robov** [comment]
Good tip... although I never used it... just to test the player once I got a response that it did not work
