### ISSUE TITLE
Latest npm version is 7.2.1

### ISSUE THREAD

**Issue by Amin52J** [flowplayer/flowplayer#1350]
Why is the latest version on npm still 7.2.1? I really need to use 7.2.2 and have to only use npm packages in order to use flowplayer. I think it'd be best to publish to npm every time a new version tag is added on github.

**Comment by nnarhinen** [comment]
I pushed 7.2.4 now.

**Comment by philwareham** [comment]
Should be 7.2.5 now, but NPM still shows 7.2.4?

**Comment by nnarhinen** [comment]
pushed
