### ISSUE TITLE
rtmp stream without metadata

### ISSUE THREAD

**Issue by colmaengus** [flowplayer/flowplayer#1353]
We have a live stream source that doesn't trigger the flash onMetaData callback.
As a result in Chrome we don't get any video controls and in Firefox we don't get any video playback at all.

Firing the Flowplayer.READY event on NetStream.Play.Start solves the problem but I'm wondering if this is the best solution and if it should be behind a configuration option.

As a reference jwplayer plays the video fine.

**Comment by colmaengus** [comment]
I appreciate that RTMP is on the way out but our use case is interactive video so we can't work with the latency of HLS. We are planning investigating WebRTC but in the meantime RTMP is what we are using.
I'll see if I'm able to provide an example stream.

**Comment by nnarhinen** [comment]
Closing as stale.
