### ISSUE TITLE
hlsjs-lite does  not honor hlsjs: false

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1354]
sample: http://web-0.radioradicale.it/prova/fp/testie.html
uses hls.js instead of FlashHLS

while this might not be crucial,  it shoudl be fixed

**Comment by fdambrosio** [comment]
hi,  it will be fixed?

**Comment by nnarhinen** [comment]
What's the use case?

**Comment by fdambrosio** [comment]
@nnarhinen it's this: https://flowplayer.com/forum#!/plugins:ie11-flash-fallback-not-w

**Comment by nnarhinen** [comment]
Why are you loading the hlsjs plugin at all if you don't want to use it?

**Comment by nnarhinen** [comment]
Closing until more information.

**Comment by fdambrosio** [comment]
@nnarhinen  I load hlsjs because I use hls streaming and flowplayer suggest to use hlsjs, but on IE11 there's a problem, so I want to disable hlsjs only on IE11 (checking the useragent by  javascript). 
`hlsjs: false` is an official configuration

**Comment by nnarhinen** [comment]
What problem on IE11?

**Comment by fdambrosio** [comment]
@nnarhinen I copy/paste from forum:  I have an error when I use hlsjs plugin on Internet Explorer 11: the stream stop working after 19 or 29 seconds.
I'm testing Internet Explorer 11 on Windows 10 or Windows 8.1
The stream works well using the Flash engine.
The problem doesn't happen on hlsjs demo page
If I set 
`hlsjs: false`
the player doesn't fallback to Flash but it use hlsjs plugin.

How can I force to use flash plugin disabling hlsjs on IE11?

I hope that hlsjs plugin problem will be fixedless…

`hlsjs: false`
not work

**Comment by nnarhinen** [comment]
Link to stream and I could take a look..

**Comment by fdambrosio** [comment]
@nnarhinen   sample: http://web-0.radioradicale.it/prova/fp/testie.html

**Comment by nnarhinen** [comment]
Seems to work for me 
![image](https://user-images.githubusercontent.com/265438/42439368-698bae56-836b-11e8-995e-89f14d9dc7f8.png)

You might also want to play around with the `hlsjs.recoverMediaError` and `hlsjs.recoverNetworError` configuration options.

**Comment by nnarhinen** [comment]
But as this is a trivial fix, I can implement it. I just think it should be the last resort.
