### ISSUE TITLE
not show fullscreen button in ipad (ios 8.1 (12B410))

### ISSUE THREAD

**Issue by zerom1nd** [flowplayer/flowplayer#1355]
i have problems: in chrome (47.02526.107) on ipad (ios 8.1 (12B410)) not show fullscreen button.
![photo_2018-02-23_02-23-01](https://user-images.githubusercontent.com/7798572/36569936-e942ef7e-1840-11e8-94c3-4b5c0fd4c41c.jpg)
in player settings:
```
fullscreen: true,
native_fullscreen : true,
```

how check support fullscreen button ? flowplayer.support.fullscreen ? 

and we have problems with smartos on different version, 7.0.4 its work, but in 7.2.1 - first play one second and black screen.
Playstation4 - is unsupported ?
i find popular useragent smarttv:
var smartTV = ["googletv", "viera", "smarttv", "internet.tv", "netcast", "nettv", "appletv", "boxee", "kylo", "roku", "dlnadoc", "roku", "pov_tv", "hbbtv", "ce-html", "playstation"]
if useragent smartTV -> then native player, Is this a solution?

**Comment by nnarhinen** [comment]
We need a link to a minimal (no authentication, no extra css & javascript) page where the problem occurs. We can't debug screenshots. Also - one issue in github per problem, not multiple problems in same issue. Feel free to re-open with more information.

**Comment by nnarhinen** [comment]
Also a good habit is to check our demo area if the problem can be seen there. If not, you have to find the difference between your own setup and our demos.
