### ISSUE TITLE
Mac OS Browsers – green artifacts

### ISSUE THREAD

**Issue by YaroslavShapoval** [flowplayer/flowplayer#1356]
Hi. We are using commercial verstion of Flowplayer (v 7.2.1) with HLS plugin (hls light, v1.1.1).

When user changes between HLS sources then periodically appear green artifacts on video player.

I recorded my screen to show you the problem – https://drive.google.com/file/d/1fIk8oVZrY2XP0eioC8R4_AcHbOciwxpT/view.

Artifacts that can be seen in the video:

1. Small artifacts at the top of the video player:
    – 00:07 (when switching from “Auto” to “160p”),
    – 00:37 (720p -> 1080p),
    – 00:47 (720p -> 480p),
    – 01:56 (720p -> 1080p)
2. 01:17 (160p -> Auto) – almost the whole video
3. 01:34 (240p -> 360p) – half of the video

Also you can test it yourself here – lustery.com/developer/testvideos (carefully – adult content).

Also the problem looks connected with https://github.com/video-dev/hls.js/issues/843, but I'm not sure about that.

What could be the problem?

**Comment by nnarhinen** [comment]
If you can't see this while using the native HTML5 video tag, then this should be reported in the hls.js issue tracker.

In order for us to debug this, we need a link to a page where this behaviour can be seen. Please re-open if you think this is something we can fix in the core code.
