### ISSUE TITLE
unload() throws exception on iOS

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flowplayer#1357]
It seems that MediaSource is not supported on IOS 9 (not sure about 10 and 11). the unload() method fails due to it.
This makes this workaround (#1334) impossible on IOS devices.
Please prioritize for 7.2.5

**Comment by nnarhinen** [comment]
Where can you see this happening?

**Comment by xnejp03** [comment]
Ok, I think it might be only happening with the hack you proposed for #1334 (see clearing up the player container after unload() / shutdown())

https://codepen.io/xnejp03/pen/GQaqXM

This actually shows error in the console for iOS, but a different one than what I'm seeing in my app - possibly due to timing and how/when the container is cleared.

So perhaps that hack is not 100% and it breaks the player being cleared up properly, and hopefully #1334 will address it cleanly.

**Comment by nnarhinen** [comment]
7.2.5 is out and testable.

**Comment by xnejp03** [comment]
@nnarhinen 

updated the codepen with 7.2.5

Same error.

```
[Log] TypeError: undefined is not a constructor (evaluating 'new MediaSource') (console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js, line 1)
(anonymous function) — flowplayer.min.js:6:27396
forEach
unload — flowplayer.min.js:6:27319
unload — flowplayer.min.js:6:101687
shutdown — flowplayer.min.js:6:101745
unloadPlayer — index.html:35
(anonymous function) — index.html:44
```
Caused by https://github.com/flowplayer/flowplayer/blob/5b39ce8091e4f1127190bee67dd0c748121d59f2/lib/engine/html5-factory.js#L198

What I found out is that if I don't use the hls plugin (or setting hlsjs to `true` or safari to `true` .. maybe combination), is passes because the MediaSource is not in `window`. With the hls plugin it is in `window` but fails to initialize.

There is a follow up error I also saw, when not using hls, related to uloading / resetting AirPlay:

```
[Error] TypeError: undefined is not an object (evaluating 'n.insertBefore')
	(anonymous function) (flowplayer.min.js:6:28781)
```
This can be seen when debugging the iPad via Safari on a Mac.

**Comment by xnejp03** [comment]
Can this be added to 7.2.6 at all?

**Comment by mattsummers** [comment]
Same issue here

**Comment by nrk** [comment]
While waiting for a proper fix, is there any way to work around this issue?

**Comment by nnarhinen** [comment]
Could I have a link where this is happening? You must be loading a MediaSource polyfill or such to see this error. The code says `if ('MediaSource' in window) {` which in all my iOS devices / simulators states false.

If you manage to find a way to reproduce this so that I can have a look, then we'll try to find a fix for it.

**Comment by xnejp03** [comment]
@nnarhinen There is a link to codepen above in this ticket.

https://codepen.io/xnejp03/pen/GQaqXM

Please re-open.

**Comment by xnejp03** [comment]
@nnarhinen can this be re-opened pls?

**Comment by nnarhinen** [comment]
"This actually shows error in the console for iOS, but a different one than what I'm seeing in my app - possibly due to timing and how/when the container is cleared."

I want to see a reproducable test case outside of codepen where that actual error is reproducable.

**Comment by cravoley** [comment]
I can see that happening on latest IOS. 


I'm facing some issues with Flowplayer on IOS. On the unload event, it break up the page with the following error: TypeError: undefined is not a constructor (evaluating 'new MediaSource'). The error only happens on Safari for IOS. It can be simulated using IOS simulator on a Mac.
I've tried to debug and figured out that window.MediaSource is set as undefined on Safari for IOS

<img width="210" alt="mobile 2" src="https://user-images.githubusercontent.com/1307132/48220881-9d089980-e377-11e8-8963-5210873e6776.png">
<img width="996" alt="mobile" src="https://user-images.githubusercontent.com/1307132/48220882-9d089980-e377-11e8-987a-c089778f5d39.png">

On the Safari for MacOs window.MediaSource is defined 
<img width="1043" alt="desktop" src="https://user-images.githubusercontent.com/1307132/48220879-9d089980-e377-11e8-983a-e090e73d33ee.png">
<img width="300" alt="desktop 2" src="https://user-images.githubusercontent.com/1307132/48220877-9c700300-e377-11e8-84c0-acac7244d2cb.png">

**Comment by bbbo** [comment]
as @nnarhinen said: please provide a link to a reproducible test case, ie a standalone html page with the latest FP only (using the hlsjs-lite engine), no extra css/html/scripts. The root of the problem might of course be Apple's decision to not support MSE on iOS , but you should not encounter the error in normal circumstances.
