### ISSUE TITLE
buffered is undefined if seek on ready

### ISSUE THREAD

**Issue by Dalesjo** [flowplayer/flowplayer#1358]
Demo [Flowplayer · Start time](https://demos.flowplayer.com/commercial/starttime.html#t=60)  has an error. seeking then ready event is fired returns error below.

>  "Uncaught TypeError: Cannot read property 'length' of undefined"

parameter buffered seams to be undefined first time .on('buffer') is called.
https://github.com/flowplayer/flowplayer/blob/5b39ce8091e4f1127190bee67dd0c748121d59f2/lib/flowplayer.js#L659

on IOS 10 the player gui stops working after this error. No seeking is done.
Chrome on Android fails to seek sometimes?

**Comment by nnarhinen** [comment]
This is a problem in the `flowplayer-hlsjs` plugin, fixed by switching to the internal `hlsjs-lite` engine: https://flowplayer.com/docs/player/setup#hlsjs-lite

**Comment by Dalesjo** [comment]
Ok but switching also means you loose all error recovery/event listening that the old flowplayer-hlsjs had.

However i see you did commit https://github.com/flowplayer/flowplayer/commit/3a65dc0d83f39ac15d5fcc31de1f09ac36635372 for 7.2.5 that includes the old error recovery. so its coming in next release?

**Comment by nnarhinen** [comment]
7.2.5 is already released to the CDN.
