### ISSUE TITLE
Unnecessary DOM searches in loop

### ISSUE THREAD

**Issue by Katarn** [flowplayer/flowplayer#1360]
In ```requestAnimationFrame``` function an continuously interaction with DOM: https://github.com/flowplayer/flowplayer/blob/dev/lib/ext/ui.js#L532

Just open this page in Chrome http://demos.flowplayer.org/basics/bad-url.html, press Shift+Esc and see CPU usage in this tab.

**Comment by bbbo** [comment]
Hm, while it goes up a bit for the first seconds, CPU and memory usage are quickly cleaned up. It never goes beyond a certain threshold for me...

**Comment by nnarhinen** [comment]
I can't seem to reproduce this problem in any basic flowplayer setup.

**Comment by Katarn** [comment]
![image](https://user-images.githubusercontent.com/6339978/41531436-026e0b8a-72fc-11e8-8f59-f6a0ee9208c0.png)

I press F8 many times and debugger always stopped on this line:

![image](https://user-images.githubusercontent.com/6339978/41531505-2ed2337c-72fc-11e8-9b04-e72ec7d0ff99.png)

Next press on F11:

![image](https://user-images.githubusercontent.com/6339978/41531599-814a2ac4-72fc-11e8-8dc6-ac1dfff2de2b.png)

It means that many times per second there is a request to p.find()

**Comment by nnarhinen** [comment]
I will store the player element in the future so that we don't need to do DOM lookups in the loop.
