### ISSUE TITLE
Subtitle endtime not respected, remain on screen until next subtitle

### ISSUE THREAD

**Issue by jamin84** [flowplayer/flowplayer#1363]
Hi there,

Using 7.2.4, splash, playlist and pure Javascript configuration I'm encountering an error where the subtitles remain on screen until the next subtitle replaces them. I tried a custom parser found here `https://github.com/flowplayer/flowplayer/wiki/3.4-Subtitles` but to no avail. The cuepoint and subtitle arrays are generated and appear correct, the endTime is just not being respected.

![image](https://user-images.githubusercontent.com/392532/37624513-cc17d25e-2b9e-11e8-801c-8af29a5264b2.png)

![image](https://user-images.githubusercontent.com/392532/37624532-da0925a2-2b9e-11e8-9b8f-455a9e217e24.png)

Thanks, let me know if I can provide more info!

**Comment by bbbo** [comment]
Please provide a link to a minimal sample page (just the player setup with subtitles).

**Comment by jamin84** [comment]
Here ya go!

http://real34.com/flowplayer/

**Comment by stantale** [comment]
Hi All,

great it was added to 7.2.7 milestone. Can any timing be provided around a release date? Even an estimate would be appreciated.
