### ISSUE TITLE
Rough transitions between playlist videos (HTML5 player)

### ISSUE THREAD

**Issue by dejardine** [flowplayer/flowplayer#1364]
At the moment the transitions are very rough with a split second black screen between videos. Is there any way to achieve a smoother transition between videos?

A class to hook into or something like that?

**Comment by nnarhinen** [comment]
You could take a look at the [state modified classes](https://flowplayer.com/docs/player/skinning#states) to find a combination which you could apply specific CSS rules to. Fixing this in the core player is something out of the scope of the player.
