### ISSUE TITLE
Unloading the player does not stop manifest loading

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1365]
A call to `stop()` should call `stopLoad()` on the HLS.js instance.

**Comment by nnarhinen** [comment]
As a workaround something like
```js
api.on('unload', function() {
  flowplayer.engine('hlsjs-lite').hls.stopLoad();
});
```

 should do the trick.

**Comment by MarcinRabczynski** [comment]
On commercial flowplayer v7.2.4 provided workaround not working. 
On hlsjs engine, "fpInstance.engine.hlsjs.stopLoad();" worked. But hlsjs engine sometimes throws type error for "buffered" when running and "hlsjs-lite" not.

Any solution?

**Comment by nnarhinen** [comment]
Can you point to a setup where the workaround does not work (when using `hlsjs-lite`)?

**Comment by SilverStone2104** [comment]
@MarcinRabczynski Hello, if I understand right, you are using flowplayer.hlsjs.min.js from here. I am creating live streaming service, and  to avoid “buffer” error using this:
```
flowplayer(element, {
            live: true,
            ratio: 9 / 16,
            clip: {
                sources: [
                    { type: "application/x-mpegurl", src: source }

                ]
            }
        }).on("ready", function (e, api) {
            if (!videoObjects[api.video.src]) {
                api.engine.hlsjs.stopLoad();
                videoObjects[api.video.src] = true;
            }
        }).on("resume", function (e, api) {
            api.load();
        }).on('pause', function (e, api) {
            api.engine.hlsjs.stopLoad();
        });
```

**Comment by SilverStone2104** [comment]
@nnarhinen Hello again in right discussion. I still want to know the way to get access to hlsjs-lite engine for some specific flowplayer. In one web page, I have 4 flowplayers, but `flowplayer.engine('hlsjs-lite').hls` give me access to the last initialized player hls engine. With flowplayer.hlsjs.min.js everething working fine, I can just use `flowplayer([0-3]).engine.hlsjs ` and get hls object. So, I need something like `flowplayer(0).engine('hlsjs-lite').hls` for hlsjs-lite engine. 
I hope this is possible.

**Comment by nnarhinen** [comment]
I think this is a separate bug. I think the player falsely stores the hls instance globally.

I have not tested this, but something like this workaround could work:

```js
flowplayer.engine('hlsjs-lite').plugin(function(params) {
  var api = params.player
    , hls = params.hls;
  api.on('unload', function() { hls.stopLoad(); });
});
```

**Comment by SilverStone2104** [comment]
@nnarhinen So, the answer is “No, we can’t”. Sorry, but your example does not working with one flowplayer and with two or more. I’ll continue using flowplayer.hlsjs.min.js. The main problem is that in the [flowplayer docs setup](https://flowplayer.com/docs/player/setup) says, that hlsjs-lite engine is good instrument, but all it API just broken.

**Comment by JoeDuncko** [comment]
Agreed, really wish that I could stop hlsjs-lite from loading on the current instance of flowplayer, as opposed to globally, without weird workarounds. Thanks for offering some solutions though @nnarhinen

**Comment by MarcinRabczynski** [comment]
I was doing other things but just want to notice, that updating to latest version and the last workaraound from @nnarhinen worked for me.
Would be good to make it working in the future without that workaround. :)

**Comment by nnarhinen** [comment]
This is now fixed in the dev branch.

**Comment by JoeDuncko** [comment]
Awesome @nnarhinen ! Any idea when that might be released?
