### ISSUE TITLE
Empty VAST issue

### ISSUE THREAD

**Issue by Les4** [flowplayer/flowplayer#1366]
In order to help you with this issue, I copy and paste what I wrote on the Flowplayer forum. ;)

> Good moning Flowplayer team,
> 
> We are dealing with an issue with the VAST plugin (we have the $20 personnal VAST plugin). It cannot deal our network VAST when the xml is empty.
> 
> Here's the test page : https://steven-universe-fantasy.net/flow/java.html
> 
> Here's the URL of the VAST : https://diff.smartadserver.com/ac?siteid=134613&pgid=748595&fmtid=25670&oc=1&pb=15&visit=M&out=vast3&vcn=s&tmstp=[timestamp]
> 
> When the VAST is providing a preroll, everything is ok, but when it is empty because of the cap of our ad network, the playlist doesn't work anymore nor the player menu. If the user uses an adblock, everything is working too.
> 
> Can you help us ?
> 
> If you need any information, just ask us.
> 
> Thank you ! )
>
> --------------------------------------------------
> bbbo
> That is caused by recent changes in the IMA3 SDK I'm afraid. We have a fix in the upcoming new flowplayer.ads plugin, to be released next week.
> 

Good luck with the dev ! ;)

**Comment by bbbo** [comment]
Please don't use the player bugtracker for plugin issues ;)
The problem is mainly caused by recent changes in the IMA3 SDK; our upcoming flowplayer.ads plugin as successor to the VAST plugin will solve this. Please email us at support@flowplayer.com and we'll build a beta for your site.
