### ISSUE TITLE
Autoplay (JS Setup) not working  in Chrome Canary 

### ISSUE THREAD

**Issue by kawakibi** [flowplayer/flowplayer#1367]
Browser : Version 67.0.3382.0 (Official Build) canary (64-bit)

Open : http://demos.flowplayer.org/basics/js-setup-autoplay.html , autoplay is not working, it stuck and cannot be play by clicking the play button, same issue like https://github.com/flowplayer/flowplayer/issues/1260. 

maybe related to https://developers.google.com/web/updates/2017/09/autoplay-policy-changes?

we are preparing to use 7.2.5 version because Chrome's autoplay policies will change in April of 2018

**Comment by nnarhinen** [comment]
This is because the external `flowplayer-hlsjs` plugin is not updated in a while and is to be deprecated by the internal `hlsjs-lite` plugin introduced in Flowplayer 7.2. 

Please refer to https://flowplayer.com/docs/player/setup#hlsjs-lite for instructions on how to enable that.

**Comment by nnarhinen** [comment]
We need to go through the demos it seems and remove the usage of the hlsjs engine ourself.. :)

**Comment by kawakibi** [comment]
well noted! we will try hlsjs-lite... thanks @nnarhinen

**Comment by bbbo** [comment]
@nnarhinen yes that's on my todo.
