### ISSUE TITLE
Commercial version via npm?

### ISSUE THREAD

**Issue by maximivanov** [flowplayer/flowplayer#1368]
Hey guys,

after a switch from loading `<script src="//releases.flowplayer.org/7.2.4/commercial/flowplayer.min.js"></script>` in page source  to including flowplayer via npm's `"flowplayer": "^7.2.4",` package I started seeing flowplayer logo over the video. Is it because version in npm is not "commercial" as in url?

**Comment by bbbo** [comment]
The commercial player is not available through npm, sorry.

**Comment by nnarhinen** [comment]
You can however use the commercial package with npm using [napa](https://www.npmjs.com/package/napa).

Then you just have to do something like `var flowplayer = require('flowplayer-commercial/flowplayer.min.js');`

**Comment by maximivanov** [comment]
Thanks for suggestion Niklas, it worked perfectly. In case someone stumbles upon this issue, full use case:

Install napa
```
npm install napa --save-dev
```

Add to package.json so that flowplayer is installed on `npm install`
```
"scripts": {
    "install": "napa https://releases.flowplayer.org/7.2.5/commercial/flowplayer.commercial-7.2.5.zip:flowplayer-commercial",
    ...
}
```

Use in code
```
const flowplayer = require('flowplayer-commercial/flowplayer.min.js');
require('flowplayer-thumbnails')(flowplayer);

this.api = flowplayer(this.$refs.player, this.config);
...
```
