### ISSUE TITLE
HLS Vertical video resolutions are sorted by width instead of height.

### ISSUE THREAD

**Issue by fvilpoix** [flowplayer/flowplayer#1369]
Hello,

I have a vertical video in HLS, which manifest is 

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=126976,RESOLUTION=270x540
2d9f2de8d44b88d6_270_540_92_32_baseline.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=221184,RESOLUTION=360x720
2d9f2de8d44b88d6_360_720_152_64_baseline.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=320512,RESOLUTION=480x960
2d9f2de8d44b88d6_480_960_249_64_main.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=645120,RESOLUTION=720x1440
2d9f2de8d44b88d6_720_1440_502_128_main.m3u8
```

But the quality switch shows 270p, 360p, 480p and 720p, while it should be the vertical size : 540p, 720p, 960p, 1440p.

Here is the sample link : http://recette4.streamlike.com/hosting/test/flo/flow/vertical-hls.html

Flow 7.2.5 and hlsjs-lite engine.

Thanks !

**Comment by nnarhinen** [comment]
You can apply custom labels in the configuration with the `hlsQualities` property.
