### ISSUE TITLE
Autoplay on Android Chrome freezes the player

### ISSUE THREAD

**Issue by jrbasso** [flowplayer/flowplayer#1374]
When a video is set with autoplay, the Android Chrome browser shows the player, but doesn't start the video and even clicking you can't make the video to play.

I wrote a sample here: https://jsfiddle.net/0ovexrLs/5/ (using latest 7.2.5 flowplayer)
The same issue happen on some videos from the demos, such as https://demos.flowplayer.com/lookandfeel/scroll-float.html

I tested using Pixel 2, Android 8.1.0, Chrome 65.0.3325.109.

**Comment by jrbasso** [comment]
It may be related with #1372, but not sure because it's a different browser.

**Comment by jrbasso** [comment]
There is also a case on the forum: https://flowplayer.com/forum#!/flowplayer/setup:not-able-to-play-video-on-a

**Comment by nnarhinen** [comment]
Please try with 7.2.6

**Comment by jrbasso** [comment]
Same issue. I updated the jsfiddle to https://jsfiddle.net/0ovexrLs/7/

It shows the play button in the middle and the pause button on the control bar, see https://photos.app.goo.gl/WHDNDUYwl2DWwAxK2

**Comment by nnarhinen** [comment]
Sorry didn't notice earlier - you should update your setup to use the internal hlsjs engine: https://flowplayer.com/docs/player/setup#hlsjs-lite

**Comment by jrbasso** [comment]
Moving the hls to load before flowplayer solved the loading problem, but it starts muted. Clicking on the video enables the sound.

**Comment by bbbo** [comment]
That's how it should work. You cannót autoplay with sound on mobile devices.

**Comment by jrbasso** [comment]
@bbbo Interesting. I saw some docs on other players explaining that Chrome is changing it. However, we currently use Wistia player and it works fine, even on my Android/Chrome that I can't autoplay with audio from Flowplayer. Do you know if there is any workaround making it possible?

**Comment by jrbasso** [comment]
Never mind. I guess that's the new standard we will have to adapt to that. So I guess this issue is resolved by moving the hls load to before the player.

PS: Not sure if you guys want to leave it open since the flowplayer demos needs to be updated as well.
