### ISSUE TITLE
Uncaught TypeError: Cannot read property 'siteGroupId' of undefined

### ISSUE THREAD

**Issue by SCkath** [flowplayer/flowplayer#1377]
Using the JS embed code. 

On a simple page - nothing but flowplayer embed-code being loaded:

https://biites.com/dear-mom-and-dad/?embedded=true

Operating system:
Mac OSX 10.13.4

Firefox 59.0.2
TypeError: l.metadata is undefined

Google Chrome 65.0.3325.181 (Official Build)
Uncaught TypeError: Cannot read property 'siteGroupId' of undefined
    at s (flowplayer.js:12)
    at Function.i.ovp (flowplayer.js:12)
    at flowplayer.async.js:2
    at Array.forEach (<anonymous>)
    at HTMLScriptElement.<anonymous> (flowplayer.async.js:2)

**Comment by bbbo** [comment]
Please do not use the player tracker for platform issues. Send an email to support.
