### ISSUE TITLE
Google Chrome has autoplay disabled now

### ISSUE THREAD

**Issue by strarsis** [flowplayer/flowplayer#1378]
Google Chrome got autoplay disabled for videos now. In WordPress flowplayer plugin flowplayer crashes when attempting to start the playback using JavaScript (autoplay) because Chrome now throws an exception so flowplayer crashed. Because of the crash the user is also unable to start the playback manually. Flowplayer should catch this exception and continue functioning for manually initiated plabyack.

**Comment by nnarhinen** [comment]
Flowplayer handles this just fine. As per the contribution guidelines, please ask questions on our forums first and then open issues with proper reproduce steps & links to a misbehaving setup.

**Comment by strarsis** [comment]
@nnarhinen: Thanks. Then this is probably due to an older version of flowplayer used in the flowplayer WordPress plugin or by a script of the plugin itself.

**Comment by bbbo** [comment]
Just tested with the current version of the WP plugin (which bundles FP 7.2.5) and autoplay works fine.

**Comment by strarsis** [comment]
@bbo: I had this issue with `Flowplayer HTML5 for WordPress` Version `3.0.2`.
