### ISSUE TITLE
Video Preview Thumbnails seem to be broken for DASH/ HLS

### ISSUE THREAD

**Issue by majamee** [flowplayer/flowplayer#1380]
Hi, 
I was testing to get video previews working following your guide at https://docs.fluidplayer.com/preview_configuration/, but so far without success. 

I have also hosted here a demo that you can check it out:
https://majamee.000webhostapp.com/player/fluid-player.html

The WebVTT is included in the player code as shown in your documentation and the WebVTT file itself can be found here view-source:https://majamee.000webhostapp.com/player/thumbnails/thumbnails.vtt next to the referenced images.

I checked the WebVTT file for issues, but it is reported to be valid by several online WebVTT validators. I also checked, if the player throws any errors in the console, but also nothing. Therefore, I need to ask you, can you please check the issue and see if it is indeed a bug of some kind?

Thank you very much & keep up your great work, I am a fan of your player especially since version 2.0 and therefore I included it in my transcoding pipeline (http://alpine-dash-hls.gq/), testing it with each release and following its development closely.

Thank you & best regards

**Comment by nnarhinen** [comment]
We are not associated with fluidplayer.
