### ISSUE TITLE
strange buffering in MS Edge

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1381]
steps to reproduce:

open http://www.eroprofile.com/flowplayer_test2.html

start clip

seek to the middle

seek back 

The buffer indicator will bounce back and fort and short artefacts

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7rkq)

**Comment by bbbo** [comment]
![microsoft edge_2018-05-24_17-05-42](https://user-images.githubusercontent.com/1395672/40494269-bdc7397e-5f74-11e8-820d-5d0a2a560944.png)

**Comment by nnarhinen** [comment]
That is expected. The video can be partly buffered from many places

**Comment by bbbo** [comment]
but this is only visual in Edge, and it not only shows  the light artefacts, the buffer indicator also flickers which looks pretty ugly...

**Comment by bbbo** [comment]
@nnarhinen can we disable the visibility of those buffer elements? It looks really bad and I received more complaints about this...

**Comment by bbbo** [comment]
see also  https://app.frontapp.com/open/cnv_st9zya

**Comment by nnarhinen** [comment]
No, the timeline represents buffered parts. We should disable the buffer completely if we don't want to show what's buffered.
