### ISSUE TITLE
microsoft edge 7.2.6

### ISSUE THREAD

**Issue by zerom1nd** [flowplayer/flowplayer#1382]
Hello, my friend say me flowplayer 7.2.6 not work on last version win 10 microsoft edge, but i not have this issue, for me work fine.

<img width="602" alt="1" src="https://user-images.githubusercontent.com/7798572/40861787-0622e8a6-65f3-11e8-9613-3b4e4ada24e6.png">
<img width="556" alt="2" src="https://user-images.githubusercontent.com/7798572/40861788-0647c7a2-65f3-11e8-9190-a1b3a6a0a17a.png">

If replace version to 7.2.5 player work fine, u can fix it?

**Comment by bbbo** [comment]
Sorry, a report like "my friend says it not work" and some random screenshots is pretty useless.

What does not work? Which exact Edge version? Which exact Windows 10 version? Link to a minimal sample page? Exact and detailed steps to reproduce?

**Comment by zerom1nd** [comment]
last version Win 10 and Microsoft Edge 42.17134.1.0
we already replace on 7.2.5

**Comment by nnarhinen** [comment]
Without better reproduce steps or example setup there's nothing we can do.
