### ISSUE TITLE
Flowplayer 7.2.6 HLS.js lite engine doesn't expose the HLS.js library

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#1391]
In the Flowplayer HLS.js documentation is says we can use `flowpalyer(0).engine.hls` to access the HLS.js engine: https://flowplayer.com/docs/player/setup#hls.js-api

That seems to work on https://demos.flowplayer.com/plugins/hlsjs.html where running this gives you a list of video qualities: `flowplayer(0).engine.hlsjs.levels`

However when using Flowplayer 7.2.6 with its HLS.js-lite engine it doesn't work. Neither does `flowplayer(0).engine['hlsjs-lite']`. Seems like when integrating https://releases.flowplayer.org/hlsjs/flowplayer.hlsjs.light.min.js into Flowplayer core this was not properly addressed.

Here is my fix for the issue, could you please review it? #1390 

Thanks,
Martin

**Comment by nnarhinen** [comment]
If you need to access the hls instance you should write an HLS.js extension with:

```
flowplayer.engine('hlsjs-lite').plugin(function(params) {
  var hls = params.hls
      , player = params.player
      , videoTag = params.videoTag;
  })
```
