### ISSUE TITLE
Flowplayer receives invalid buffering event with hlsjs

### ISSUE THREAD

**Issue by KevinEady** [flowplayer/flowplayer#1392]
Flowplayer version: 7.2.4 (example page), 7.2.6 (my page)

Sometimes when clicking "play" and the video starts, Flowplayer receives a buffering event but with no ranges:

This area here: https://github.com/flowplayer/flowplayer/blob/dev/lib/flowplayer.js#L659

Gives an error saying "cannot read property length of undefined" because `buffer` comes in as `undefined`.

The root cause is from this part of flowplayer.hlsjs: https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L748

buffered.length was 0, so what ends up being set for `arg` is `[][0]` which is `undefined`.

I saw this error on my own page, and I have replicated it once on the Hls demo page here: http://demos.flowplayer.com/plugins/hlsjs.html

Screenshot here 
<img width="1889" alt="screen shot 2018-06-15 at 3 03 19 pm copy" src="https://user-images.githubusercontent.com/8634912/41470142-0a445902-70b0-11e8-8cce-f5aa349c56e8.png">

Please let me know if there's anything else I can provide.

**Comment by nnarhinen** [comment]
We are not actively developing the external hlsjs plugin. You should migrate your setup to [hlsjs-lite](https://flowplayer.com/docs/player/setup#hlsjs-lite)

**Comment by KevinEady** [comment]
Hi @nnarhinen ,

That did resolve my problem. Closing issue. Thanks!

**Comment by KevinEady** [comment]
Hi @nnarhinen ,

Not sure if this is the right place to ask, but we're migrating to the hlsjs-lite setup as you suggested. However, we no longer get the HLS-specific events, such as `hlsManifestLoaded` or `hlsLevelLoaded`. Before, we would pass to the flowplayer configuration an `hls : { listeners: ['hlsManifestLoaded', ...] }` type object that would forward those events from the engine, a la https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L1031 . I do not see anything similar for this hlsjs-lite engine, looking around here https://github.com/flowplayer/flowplayer/blob/dev/lib/engine/hlsjs.js#L23 ? 

If we could access the `hls` object directly, then we could attach our own events there. However, that `hls` object is only accessible globally via `flowplayer.engine('hlsjs-lite').hls` ... but I do not think this is safe in a multi-video page?

**Comment by KevinEady** [comment]
Figured it out: We were able to create an engine extension using `flowplayer.engine('hlsjs-light').plugin( o => .... )` and attach our Hls events there off of `o.hls` via https://github.com/flowplayer/flowplayer/blob/dev/lib/engine/hlsjs.js#L29

**Comment by nnarhinen** [comment]
Good that you found this hidden feature! We'll have to document it in the future as the API has now stabilized.
