### ISSUE TITLE
HLS instance not correctly cleared on load

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1395]
Symptoms: loading a new clip results into loading fragments from old clip.

Workaround of a kind (untested):

```js
flowplayer.engine('hlsjs-lite').plugin(function(d) {
  var player = d.player, hls = d.hls;
  player.on('load', function() {
    hls.stopLoad();
  });
});
```

**Comment by bbbo** [comment]
related to https://flowplayer.com/forum#!/plugins:hls-plugin-not-preventing-m I guess?

**Comment by josej30** [comment]
I'm the author of that issue in the flowplayer forums. I can confirm I'm able to reproduce the issue.
