### ISSUE TITLE
is-paused triggering always, tried multiple implementations

### ISSUE THREAD

**Issue by lykathe** [flowplayer/flowplayer#1397]
Hey so I'm using a WP implementation in the form of a plugin, and suddenly "is-paused" is injected to all Flowplayers on site, so I uninstall the plugin, set it up manually, same problem. This isn't a issue w FP6. Anyone familiar w the issue? I have the Autoplay/Muted sorted, this had worked before but it stopped, and I didn't change the environment.

**Comment by nnarhinen** [comment]
Please re-open with proper reproduce steps and a link to a sample page.
