### ISSUE TITLE
Property length error in flowplayer

### ISSUE THREAD

**Issue by Sportradar-KK** [flowplayer/flowplayer#1399]
Hi flowplayer team,

Occasionally I get this ‘length’ error in the console. I suppose that the video tag is not ready when this happens.
I let the flowplayer create the div so I do it all using JavaScript.

Uncaught TypeError: Cannot read property 'length' of undefined
   at flowplayer.js:4682

Nevertheless the player is running when this happens.

My setup:
Flowplayer 7.2.5 with hlsj.light.min.js/flowplayer.hls.min.js 
(I use light.js in Chrome + FF and classic in IE 11 + Edge)
Windows 10

**Comment by nnarhinen** [comment]
Please migrate your setup to use the [internal HLS.js engine](https://flowplayer.com/docs/player/setup#hlsjs-lite). It will fix your problem.
