### ISSUE TITLE
Android 9: Exception on plugin load due to issue with UA parsing

### ISSUE THREAD

**Issue by gmathis** [flowplayer/flowplayer#1404]
Android version detection in [support.js:L54](https://github.com/flowplayer/flowplayer/blob/dev/lib/ext/support.js#L54) assumes a format of `Android [major].[minor]`, but Android 9 UAs don't include minor, e.g. `Android 9`.

Example Pixel 2 / Android 9 UA string:
`Mozilla/5.0 (Linux; Android 9; Pixel 2 XL Build/PPP3.180510.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36`

Can repro with any Flowplayer demo page, e.g.: https://demos.flowplayer.com/basics/minimal.html

Also, this regex will fail again when Android reaches the next major version (10), because major / minor are assumed to be one digit.

**Comment by Senior-Fin** [comment]
Yep, I also saw this bug. You surrounded me. The solution I found by myself is to replace this one:
`ANDROID_VER = IS_ANDROID ? parseFloat(/Android\ (\d\.\d)/.exec(UA)[1], 10) : 0;`
to this:
`ANDROID_VER = IS_ANDROID ? parseFloat(/Android\ ((\d+\.\d+)|\d+)/.exec(UA)[1], 10) : 0;`

`\d\.\d ` RegExp matches only [0-9].[0-9] version. And `\d+\.\d+|\d+` will select all versions [0-Infinity].[0-Infinity]. But if the version has not got minor version, by default it will take only major.

E.g.
Android 8:
`Mozilla/5.0 (Linux; Android 8.1.0; Pixel 2 XL Build/PPP3.180510.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36`

It will match 8.1 version.

Android 9:
`Mozilla/5.0 (Linux; Android 9; Pixel 2 XL Build/PPP3.180510.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36`

It will match 9 version.

**Comment by Silex** [comment]
This line was forgotten: https://github.com/gmathis/flowplayer/blob/master/lib/ext/support.js#L54
