### ISSUE TITLE
Autoplay in Chrome 68

### ISSUE THREAD

**Issue by lon9man** [flowplayer/flowplayer#1406]
### **What i do**
**OS:** Ubuntu, MacOS
**browser:** Chrome 68
**autoplay policy:** by default

i want to use Flowplayer in iframe (content from my site), which user can embed into own site.
so needed parts is **autoplay** and **iframe**.

i tested functionality and see that current player's behaviour is buggy. you can test JSFiddle (http://jsfiddle.net/longman/9h27f6p0/1/). it consists of iframe, which pointed to other JSFiddle (https://jsfiddle.net/longman/u42fzq87/1/) with simple example (source i took from docs https://demos.flowplayer.com/basics/js-setup-autoplay.html)

### **What i get**
i get player, which pre-downloads content, but i am unable to start playing, it looks as stucked.

when disabled flowplayer **autoplay**-option - works as expected
Firefox/Safari - works as expected
with disabled in Chrome **autoplay policy** - works as expected

**videocast plan:** 
- basic example - works
- iframe example - doesn't work
- iframe example with additional JSFiddle's tabs (Javascript, HTML, CSS). from start video doesn't work, but when i click saying Javascript-tab and nextly return back to Result-tab - then video is playing as expected

**videocast URL:** https://photos.app.goo.gl/jNKs9fjEcUCwg7716 (please wait for FullHD-quality processing by Google)

### **What i expected**
i expect to have either:
1. playing video with volume ( it looks impossible forever with assumption by **autoplay policy** )
2. playing muted video
3. paused video, but with the possibility play it using UI

**Comment by nnarhinen** [comment]
Please migrate your setup to use [hlsjs-lite](https://flowplayer.com/docs/player/setup#hlsjs-lite). Should fix your problems.

**Comment by nnarhinen** [comment]
It does not use hlsjs-lite:
![image](https://user-images.githubusercontent.com/265438/44146665-60aa968a-a099-11e8-9d2f-d6df3c7f2fff.png)

**Comment by lon9man** [comment]
Sorry, maybe didn't press Update in fiddle.

so i changed to **hlsjs-lite** engine and Flowplayer's test video **works**.
but now using lite-engine my own video (from S3) **doesn't play completely**.

**Results:**
[HLS.js demo-page](https://video-dev.github.io/hls.js/demo/?src=https%3A%2F%2Fs3.amazonaws.com%2Ftranscoder.video.imagelockerdev.com%2F8960cac5-3e2e-11e8-a0f7-38d547b38d0c%2Findex.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsImVuYWJsZVdvcmtlciI6dHJ1ZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xLCJ3aWRldmluZUxpY2Vuc2VVcmwiOiIifQ==) - **works**

[simple JSFiddle](https://jsfiddle.net/longman/u42fzq87/18/) - **doesn't work**

what is the difference?

**Comment by lon9man** [comment]
big thanks for help! 

further testing give me a bug in thumbnail-plugin. but source code is in flowplayer.min.js
[Portrait-oriented thumbnail wrong position #23](https://github.com/flowplayer/flowplayer-thumbnails/issues/23)

P.S. not sure which github-repository i should place issue, sorry if i had mistake
