### ISSUE TITLE
HLS.js engine info empty

### ISSUE THREAD

**Issue by lon9man** [flowplayer/flowplayer#1407]
**Maybe not issue but development process, or i am unable to find obvious things?**

### **What i do**
1. i have used Flowplayer with **flowplayer.hlsjs.min.js** (will name it **OLD** approach)
demo: [OLD](http://jsfiddle.net/longman/oysgtemh/15/)
2. i have upgraded Flowplayer to version 7.2.6 and (as adviced in the docs) changed **hls.js** library to 
[hls.min.js](https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.10.1/hls.min.js) (tried light and full version) (will name it as **NEW** approach)
demo: [NEW](http://jsfiddle.net/longman/oysgtemh/7/)

### **What i get**
it is visible in the javascript console:
1. using **OLD** approach i have access to **hls.js** API using `api.engine.hlsjs-property`. it was object with info about played video (`currentLevel`, `levels` and etc). i used it to visualize what concrete quality level is playing
2. using **NEW** approach i don't see any property, which can help me to get the same info

### **What i expect**
i expect to get info related to **hls.js** library similarly as it was using **OLD** approach. basically i need `currentLevel`-property and etc, as much as possible

**Comment by bbbo** [comment]
https://flowplayer.com/docs/player/setup#hls.js-api

**Comment by lon9man** [comment]
i have found another issue [Flowplayer 7.2.6 HLS.js lite engine doesn't expose the HLS.js library #1391](https://github.com/flowplayer/flowplayer/issues/1391) .

questions:
1. how to get info about extensions and how they work?
2. how i can get HLS-info from extension for concrete video-tag, when i have multiple videos on the page simultaneously?

**Comment by snowinszu** [comment]
We are having the same issue. 
"flowplayer(0).engine.hls.nextLevel = 0; " doesn't work.
