### ISSUE TITLE
Loading animation broken on IE11 / Edge

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#1408]
Not animated.

**Comment by bbbo** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/1173754/

according to the last comment in that thread and https://developer.microsoft.com/en-us/microsoft-edge/platform/status/supportcsstransformsonsvg/ it should be supported by now, but it doesn't in my IE builds...
