### ISSUE TITLE
Choosing more generic event names

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#141]
Javascript being an unsafe environment for variable and event collisions, it might be an idea to choose generic event names. 

After a player upgrade and refactoring to the api breaks, the dailymotion api player is also dispatching an event name of "progress" and is triggering the event listeners on flowplayer also called "progress". I've contacted them to also do the same. Problems may arise for anything else also dispatching the same event names. 

see

http://flowplayer.electroteque.org/dailymotion/fp5

constant errors like 

Uncaught TypeError: Cannot read property 'video' of undefined flowplayer.js:400
root.bind.bind.bind.bind.bind.bind.bind.api.currentSpeed flowplayer.js:400
f.event.dispatch jquery.min.js:3
h.handle.i jquery.min.js:3
DM.provide._dispatch all.js:1
DM.provide._recvEvent all.js:1
a

around here

}).bind("progress", function(e, api, time) {
         api.video.time = time;

      }).

**Comment by nnarhinen** [comment]
Flowplayer6 will not listen to any external DOM events any more.

It will still trigger jQuery events on the root-element when used as an jQuery-plugin. The jQuery event namespacing won't help with this as it's mostly just about easing unlistening events.

**Comment by danrossi** [comment]
I will take a look eventually. It functions fine it will just produce a js error. Whatever fits the purpose.
