### ISSUE TITLE
Video's play muted in Safari

### ISSUE THREAD

**Issue by imben123** [flowplayer/flowplayer#1414]
See this example: https://codepen.io/imben123/pen/vzPpPv

It seems that because the video is always loaded with the autoplay attribute, Safari is always muting the video (even when the user has pressed the play button in flowplayer)

**Comment by oliversiegel** [comment]
Same thing on Chrome.

Would be nice to have a "tap to unmute" button, like you get on the mobile youtube site. I've implemented this myself, but it'd be nice if it were native to flowplayer.
