### ISSUE TITLE
Javascript Error with Minified Version

### ISSUE THREAD

**Issue by Vstoy001** [flowplayer/flowplayer#1415]
While using the player and selecting further in the video, I sometimes get a "Uncaught TypeError: Cannot read property 'length' of undefined".

I've tried to look into this and found that this line `t.video.buffer = "number" == typeof n ? n : n.length ? n[n.length - 1].end : 0`, is capable of throwing an error if n is undefined.

**Comment by nnarhinen** [comment]
Without a link to a problematic setup we cannot help.
