### ISSUE TITLE
Player not working on Android 9 Chrome (regex not matching) 

### ISSUE THREAD

**Issue by nmargaritis** [flowplayer/flowplayer#1419]
Hi there, 

it appears that flowplayer is breaking on page load on some android phones. Currently, I have identified that, the android regex does not match certain android versions. It expects the android version to have a major AND a minor version.

**For example my oneplus 6 has the following User Agent:**

> Mozilla/5.0 (Linux; Android 9; ONEPLUS A6003 Build/PKQ1.180716.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36

Opening a page with the flowplayer on oneplus 6 results on the following error.
`flowplayer.js:formatted:4066 Uncaught TypeError: Cannot read property '1' of null
    at flowplayer.js:formatted:4066
    at Object.25.../flowplayer (flowplayer.js:formatted:4144)
    at o (flowplayer.js:formatted:431)
    at flowplayer.js:formatted:433
    at Object.32../engine/embed (flowplayer.js:formatted:5812)
    at o (flowplayer.js:formatted:431)
    at r (flowplayer.js:formatted:439)
    at flowplayer.js:formatted:444
    at flowplayer.js:formatted:409
    at flowplayer.js:formatted:412
...`

At a closer look this is how the flowplayer detects if it is an android device
>, ANDROID_VER = IS_ANDROID ? parseFloat(/Android\ (\d\.\d)/.exec(UA)[1], 10) : 0;

As you can see this regex `/Android\ (\d\.\d)/` will never match the actual version of the user-agent i provided due to the fact that it **takes as granted that there is a minor version as well**. It would expect something like 9.0, 9.1 to match. **However, the actual version is 9**!!!

Please update this regex to the following:
`Android\ (\d(?:\.\d|))` so that you can support both major and major+minor versions.

**Comment by nmargaritis** [comment]
Version 

> Flowplayer v7.2.6 (Tuesday, 17. April 2018 01:58PM)

**Comment by nnarhinen** [comment]
This is already fixed in 7.2.7 - https://github.com/flowplayer/flowplayer/blob/dev/CHANGELOG.md#version-727
