### ISSUE TITLE
adapt to support hls subtitle tracks in m3u8 manifests with plugin

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#1424]
Currently the subtitle implementation in core FP7 kicks in at `ready`after the HLS plugin has created the menu and empties the menu -> webVTT tracks in the m3u8 manifest don't show.

Acceptance: change subtitle extension to kick in at an earlier time (at least when 
 https://github.com/flowplayer/flowplayer-hls-subtitles is used).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fugy)

**Comment by emanuelflowplayer** [comment]
Thanks for working on this. they are launching in public on Friday and really want this to work.

**Comment by nnarhinen** [comment]
This was fixed in https://github.com/flowplayer/flowplayer-hls-subtitles/commit/7126081f53901bad1ae81238b71ac0a056c72774
