### ISSUE TITLE
Subtitle issue for FP7 and issue release 7.2.8

### ISSUE THREAD

**Issue by emanuelflowplayer** [flowplayer/flowplayer#1425]
Please review and fix the issue described by MediaChoice (subtitles need to wait for the Ready event?).

Acceptance criteria:
-Marwin from Mediachoice has the feedback that it is working

**Comment by emanuelflowplayer** [comment]
@nnarhinen sorry I might have created this issue in the wrong repo, please confirm that you are aware and working on it

**Comment by bbbo** [comment]
#1424
