### ISSUE TITLE
Seek-at-start does not work on iOS 12

### ISSUE THREAD

**Issue by adriangodong** [flowplayer/flowplayer#1428]
Open the following URL in iOS 12 device (Safari or Chrome, both showing the same behavior)
https://demos.flowplayer.com/commercial/starttime.html#t=30

Expected:
* playback starts at 30 seconds

Actual:
* playback starts at 0
* the loading spinner is visible
* play/pause does not work
* performing seek will reset this state and everything is working afterwards

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i9ve)

**Comment by bbbo** [comment]
further input from customer:

Flowplayer 7.04 -> no issue
http://itv2.sabor.hr/demoplayer/player.aspx

Flowplayer 7.27 -> seek on start through APi does not work on iPhones
http://itv2.sabor.hr/demoplayer/player1.aspx
