### ISSUE TITLE
subtitles don't render until some event occurs

### ISSUE THREAD

**Issue by reeceward-vpm** [flowplayer/flowplayer#1429]
When I select English subtitles, after they have already been turned off, the subtitles won't begin rendering until:

- It moves onto the next timecode of subtitles
- You click somewhere on the scrub bar

It is more noticeable when you have longer periods of text
You can replicate it on the demo on the website: 
https://flowplayer.com/help/developers/flowplayer-7/subtitles

**Comment by foliovision** [comment]
This would really be a great thing to fix.

Thanks,
Martin

**Comment by bbbo** [comment]
Martin,

Flowplayer 7 is deprecated, so there will probably no further release, sorry.
