### ISSUE TITLE
Floplayer does not work in Safari

### ISSUE THREAD

**Issue by Alexsandr** [flowplayer/flowplayer#1437]
https://jsfiddle.net/exception777/4e3uv06o/39/

I had a problem for some reason that the stream player in Safari does not work with this configuration or with a minimal configuration. But the same video works with the <video> tag.
It seems that there is some problem with flowplayer.

In addition, flowplayer will not work in Opera, unless you specify “engine: html5”, it will try to load the flash engine. Is this normal behavior?
![Screenshot from 2019-03-18 19-19-33](https://user-images.githubusercontent.com/966534/54533498-84a72c00-49b4-11e9-9aeb-e552825d7f38.png)

**Comment by bbbo** [comment]
{ type: "application/x-mpegurl", src: "//edge.flowplayer.org/functional.webm" },

is wrong, you did not configure a HLS source but a WebM
