### ISSUE TITLE
Streaming .m3u8 in android/firefox problem 

### ISSUE THREAD

**Issue by mrnatuh** [flowplayer/flowplayer#1439]
I have one page site with a streaming config using FlowPlayer 7.2.6. It's perfect in all web browsers. When I play it in a android device with firefox I received one error: {isTrusted: false} (the protocol is https).

**Comment by bbbo** [comment]
Please provide a link to a MINIMAL (player setup only on a  dedicated html page outside of a site structure, no extra html/css/js except perhaps a width setting for the player div to make it less than 100%). Alos make sure you're using FP 7.2.7 with [hlsjs-lite](https://flowplayer.com/help/player/flowplayer-7/setup#hlsjs-lite)
