### ISSUE TITLE
Some FLV dont play in Flow player

### ISSUE THREAD

**Issue by RichardsonHubble** [flowplayer/flowplayer#1441]
Metadata:
    streamName      : HubbeLiveStream
    encoder         : Lavf55.12.100
    author          : leon
  Duration: 06:58:56.80, start: 25111.453000, bitrate: 0 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 614 kb/s, 12 fps, 15.17 tbr, 1k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

The FLV is unable to play in Flow player , We are hubble connected pvt ltd and we are hosting flowplayer in our webapp. Please help to fix ASAP

**Comment by bbbo** [comment]
We no longer support the Flash engine.

The problem might be the pcm audio track though. Try to sue AAC or MP3 instead.

**Comment by RichardsonHubble** [comment]
Dear sir, 
I dont think it is Audio issue, it is something to do with codecs please check this

**Working:**
Metadata:
    streamName      : flvLiveStream
    encoder         : Lavf55.12.100
  Duration: 00:00:46.00, start: 84866.185000, bitrate: 710 kb/s
    Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1280x720, 15 fps, 1k tbr, 1k tbn
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

**Not working:**

Metadata:
    streamName      : HubbeLiveStream
    encoder         : Lavf55.12.100
    author          : leon
  Duration: 06:58:56.80, start: 25111.453000, bitrate: 0 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720, 614 kb/s, 12 fps, 15.17 tbr, 1k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

Btw from your statement are you sure flowplayer will stop support for FLV??

**Comment by bbbo** [comment]
Well then try a lower h264 profile.

Yes, there is no further support for FLV or any other Flash format. Flash is a dead technology and support for the Flash plugin will be removed from all major browsers within the next weeks / months.
