### ISSUE TITLE
Unable to Leave Fullscreen on Safari (12.1.1) MacOS Mojave (10.14.5)

### ISSUE THREAD

**Issue by tadegunloye** [flowplayer/flowplayer#1444]
Whenever I enter fullscreen on Safari 12.1.1, I am unable to exit out of fullscreen. The fullscreen button does not change to the exit-fullscreen button, but Safari does put the video into fullscreen mode.

Pressing escape to leave fullscreen does work, but the fullscreen button changes to the exit-fullscreen button. This makes it impossible to return to fullscreen mode unless the page is reloaded.

This is related to a post made in 2017. #1191

**Comment by tadegunloye** [comment]
This issue also occurs on the flowplayer.com demo sites

**Comment by blacktrash** [comment]
Try this:
```diff
diff --git a/lib/ext/fullscreen.js b/lib/ext/fullscreen.js
index 3ccf3d0..19c8ba3 100644
--- a/lib/ext/fullscreen.js
+++ b/lib/ext/fullscreen.js
@@ -54,7 +54,7 @@ flowplayer(function(player, root) {
             ['requestFullScreen', 'webkitRequestFullScreen', 'mozRequestFullScreen', 'msRequestFullscreen'].forEach(function(fName) {
                if (typeof wrapper[fName] === 'function') {
                  wrapper[fName](Element.ALLOW_KEYBOARD_INPUT);
-                 if (fName === 'webkitRequestFullScreen' && !document.webkitFullscreenElement) wrapper[fName]();
+                 if (fName === 'webkitRequestFullScreen' && document.webkitFullscreenElement === undefined) wrapper[fName]();
                }
             });
```

**Comment by foliovision** [comment]
Hello @tadegunloye 

here's our fix for the issue #1447

It seems iOS 12.3 and Safari 12 triggers `fullscreenchange` twice when you open fullscreen. So we simplified the Flowplayer code to rely on one of `document.webkitCurrentFullScreenElement || document.mozFullScreenElement || document.fullscreenElement || document.msFullscreenElement` to determine if the fullscreen mode is active and it works.

Thanks!

**Comment by tadegunloye** [comment]
@foliovision Thank you so much! This worked for me also!

**Comment by lon9man** [comment]
my version is 7.2.6 and i see described behavior in iPadOS 13

@tadegunloye, can you explain:
1. was it fixed and in what version?
