### ISSUE TITLE
Do we need to enable flash plugin for this player?

### ISSUE THREAD

**Issue by zohaib-sarwar-confiz** [flowplayer/flowplayer#1449]
Do we need to enable flash for this player?

**Comment by bbbo** [comment]
Only if you have an rtmp feed or use HLs on IE10/11 on windows 7, where hlsjs does not work.

However, Flowplayer 7 is deprecated so we would not recommend using it anymore. For our current commercial offerings, please see https://flowplayer.com/features and https://flowplayer.com/pricing .
