### ISSUE TITLE
Set up automatic dependency updates

### ISSUE THREAD

**Issue by nikolas** [flowplayer/flowplayer#1452]
[Dependabot](https://dependabot.com/) would be useful to set up on flowplayer here.

**Comment by bbbo** [comment]
Generally speaking: yes. but FP7 is deprecated so there won't be any updates anyway...

**Comment by nikolas** [comment]
Ah - I wasn't aware of that. Maybe this repo's readme should be updated, with a link to the new version.

**Comment by bbbo** [comment]
true; full announcement and repo update will be done soon.

**Comment by ghost** [comment]
Hi @bbbo I noticed here that you are saying that FP7 is deprecated and I noticed that on the flowerplayer site in the help documents it says to use this [https://cdn.flowplayer.com/releases/native/stable/flowplayer.min.js](https://cdn.flowplayer.com/releases/native/stable/flowplayer.min.js) file and it says it's version is 2.3.0? I'm guessing the one you recommend on your site can only be used with a commercial licence whilst this one can be used without and is being deprecated?

**Comment by bbbo** [comment]
The flowplayer.com help pages all refer to Flowplayer Native, a completely new player which is only available as part of our platform subscriptions (so with some form of commercial license).

Flowplayer 7 is deprecated in both open source (with Flowplayer logo) and commercial versions. Of course it will continue to work until browser changes break it ;) . But there is no further support or development.

**Comment by ghost** [comment]
Thanks @bbbo. Is there any chance of there being a freemium version of the flowplayer native version?

**Comment by bbbo** [comment]
No, at least not in the forseeable future. Development and testing are cost intesive ;)
