### ISSUE TITLE
Link to commercial options in GPL is broken

### ISSUE THREAD

**Issue by karstenbruch** [flowplayer/flowplayer#1454]
in this Paragraph:
"Commercial licenses are available. The commercial player version does not require any Flowplayer notices or texts and also provides some additional features."

As a sidenote: seo wise you should always redirect broken broken links to something usefull on your website as with this page which has moved.

**Comment by bbbo** [comment]
The commercial version is no longer available as Flowplayer 7 is deprecated. But you're right we should add a hint to the license.
