### ISSUE TITLE
Playlist stops when file format changes

### ISSUE THREAD

**Issue by kimatcodeindigo** [flowplayer/flowplayer#1456]
Using FP version 7:
In a playlist with 2 files, one .mov and one .mp4, playing stops after the first. Reversing the file order still results in stop after first film. A playlist with more files always stops on first film with different format than those before.
Is this a known behaviour?

```
<div>
    <video>
        <source type="video/mp4" src="FilmA.mov" />
    </video>
    <div>
        <a href="FilmB.mov"></a>
        <a href="FilmC.mp4"></a>
    </div>
</div>
```

Thanks

**Comment by bbbo** [comment]
Flowplayer 7 is deprecated and there is no further support for it, sorry.

MOV is not an official html5 <video> container format, you should *always* use MPEG-4 part 10 in an MP4 container.

**Comment by kimatcodeindigo** [comment]
Thank you, Bernd,

Had a feeling this was the case. There is around 30000 MOV's in our archive but last couple of years is MP4 so quite a task to re-encode the old stuff. We'll try to figure out a solution, and anyway the old stuff is not used very often and less so as time passes.
Thanks again.


Br, Kim
Den 28. januar 2020 kl. 06.14.12 +01.00, skrev Bernd Backhaus <notifications@github.com>:
