### ISSUE TITLE
Do not working cast tab on chromecast device

### ISSUE THREAD

**Issue by grinspike** [flowplayer/flowplayer#1458]
Cast tab do not working. 
Next code is not working with **https** but working with **http**

https://codepen.io/sergej-prudnikow/pen/rNVoOxg (on codepen working, but on real hosting do not working)

**Comment by bbbo** [comment]
You're mixing the Chromecast plugin for the current player FP Native with the deprecated Flowplayer 7. It's probably only working due to the integrated Chromecast feature of FP7.

FP7 is unsupported now, so we cannot help here, sorry.
