### ISSUE TITLE
buffer continues to load on pause

### ISSUE THREAD

**Issue by staminna** [flowplayer/flowplayer#1459]
Hi

We have a commercial licence for Flowplayer, although we are using deprecated version 7. 2.7.
The issue is the videos keep buffering to "Infinity" even after pausing the playback.

```
function createPlayer(videoContainer,videos,splashConfiguration){
	flowplayer.conf = {
	    key: "$foobar",
            share: false,
            splash:true,            
            autoplay: false,
			hlsjs: {
				bufferWhilePaused: false,
				defaultAudioCodec: "mp4a.40.2",
				maxBufferLength: 0.5, //ignored
				maxMaxBufferLength: 5 // defaults 30
            bufferLength: 0,
            autoBuffering: false,
            preload: "none"
       };
	if(splashConfiguration) return flowplayer(videoContainer,{playlist: videos});
	return flowplayer(videoContainer,{playlist: videos});
}
```

And this is how we instatiate the videos:

```
<script type="text/javascript" src="https://releases.flowplayer.org/7.2.7/commercial/flowplayer.min.js"></script>
<script type="text/javascript" src="https://releases.flowplayer.org/hlsjs/flowplayer.hlsjs.light.min.js"></script>
<link href="https://releases.flowplayer.org/7.2.7/skin/skin.css" rel="stylesheet" type="text/css" />

<div id="fp-hlsjs"><span style="display:none">.</span></div>

<script>
    var playerFlow = document.getElementById("fp-hlsjs");
    flowplayer(playerFlow , {
        ratio: 9/16,
        key: "$foobar",
        splash:true,
            hlsjs: {
               bufferWhilePaused: false,
            },
        playlist: 
        {
            sources:
            [
                {type: "application/x-mpegurl", src: "https://vod-streaming/files/playlist.m3u8"}
            ]
        }
    });
</script>


```
We don't want videos to load on pause.

**Comment by bbbo** [comment]
As you said Flowplayer 7 is no longer supported so there is nothing we could do I'm afraid.

However you should not use the very old flowplayer.hlsjs plugin but plain hls.js with the integrated hlsjs-lite interface: https://flowplayer.com/developers/player/flowplayer-7/setup#hlsjs-lite

This might already solve the problem.

 bufferLength: 0,
 autoBuffering: false,
 preload: "none"

are all invalid main level config options (splash is equal to preload=none).

**Comment by staminna** [comment]
@bbbo  I am sorry but my organization requires compatibility with old I.E. bundled with Windows 7 which latest hlj.js alone cannot provide.

Are you sure there is no way to stop the buffer with the previous code I provided at the top of this issue?

**Comment by bbbo** [comment]
No version of hls.js is compatible with IE7 / Win7 as the browser does not support Media Source Extensions, so it does not matter which hls.js version you use (beside you can select the hls.js version you load with the hlsjs-lite engine). On IE7, FlashHLS is used (which is available as a plugin for the new player FP Native as well btw) and that is independent of hls.js

Your best bet is the bufferOnPause = false option which comes with hlsjs-lite.

**Comment by staminna** [comment]
We are using IE version 11 (not 7), on Windows 7, and we cannot use Flash in our organization.

> Your best bet is the bufferOnPause = false option which comes with hlsjs-lite.

Can you provide a link to a single snippet or player with this functionality working?

**Comment by bbbo** [comment]
https://flowplayer.com/developers/player/flowplayer-7/setup#hls-js-configuration

**Comment by staminna** [comment]
Hi bbbo, 

Here's what we have now:

```
<link rel="stylesheet" href="https://releases.flowplayer.org/7.2.7/skin/skin.css">
<script src="https://cdn.jsdelivr.net/npm/hls.js@0.13.0/dist/hls.light.min.js"></script>
<script src="https://releases.flowplayer.org/7.2.7/commercial/flowplayer.min.js"></script>
<script src="https://releases.flowplayer.org/hlsjs/flowplayer.hlsjs.light.js"></script>

<div id="fp-hlsjs"><span style="display:none">.</span></div>

<script>

var playerFlow = document.getElementById("fp-hlsjs");

var conf = {
    key: "$boofar321",
    ratio: 9/16, // set the aspect ratio of the stream
    bufferWhilePaused: false,
    share: false,
    splash:true,
    hlsjs: {
        autoplay:false,
        bufferOnPause: false,
        bufferWhilePaused: false,
        },
    clip: {
        hlsjs: {
            autoplay:false,
            bufferWhilePaused: false,
            bufferOnPause: false,
            },
        sources: [
            // path to the HLS m3u8
            { type: "application/x-mpegurl", src: "https://vod/testing.mp4/playlist.m3u8"},
            // path to an optional MP4 fallback, usually not available for live feeds
            // { type: "video/mp4", src: "//yourserver/path/index.mp4"}
        ]
    }
};

var player = flowplayer(playerFlow , conf);

if (conf.bufferWhilePaused === false) {
    player.on('pause', function() {
    var hls = flowplayer.engine('hlsjs-lite').hls
    hls.stopLoad();
    player.one('resume', function() {
        hls.startLoad();
    });
});
}
```

Uncaught TypeError: Cannot read property 'stopLoad' of undefined

**Comment by bbbo** [comment]
Do NOT load this:

<script src="https://releases.flowplayer.org/hlsjs/flowplayer.hlsjs.light.js"></script>

this

```
<!-- head section -->
<!-- skin -->
<link rel="stylesheet" href="https://releases.flowplayer.org/7.2.7/skin/skin.css">
<!-- hls.js -->
<script src="https://cdn.jsdelivr.net/npm/hls.js@0.11.0/dist/hls.light.min.js"></script>
<!-- flowplayer -->
<script src="https://releases.flowplayer.org/7.2.7/flowplayer.min.js"></script>

<!-- body section -->
<div id="player"></div>

<script>
        flowplayer('#player', {
        key: "$boofar321",
        autoplay:false,
    ratio: 9/16, // set the aspect ratio of the stream
    share: false,
    splash:true,
    hlsjs: {
        bufferWhilePaused: false,
        recoverNetworkError: true
        },
           clip: {
                sources: [
                // path to the HLS m3u8
            { type: "application/x-mpegurl", src: "https://someserver/Testing.mp4/playlist.m3u8"},
            // path to an optional MP4 fallback, usually not available for live feeds
            // { type: "video/mp4", src: "//yourserver/path/index.mp4"}
        ]
            }
        });
</script>
```

should be all you need to do.

**Comment by staminna** [comment]
I'm sorry but that works fine in Chrome, but Internet Explorer 11 from the moment you press play, won't stop buffering anymore, even if you press pause!
My video is 1 minute long, and buffers the whole file at once. If at least I could set up a maximum of 5 seconds, that would be great!

Thanks for quick reply.

**Comment by bbbo** [comment]
If you refer to IE11 on Windows 7 there is nothing which could be done as that browser cannot use hlsjs, it can only use Flash and hence all settings won't have any effect.

In any event there is no more help we could provide I'm afraid. Flowplayer 7 is no longer supported and will stop working in many browses soon anyway due to the rapid changes in browserland.

**Comment by staminna** [comment]
Okay!

Thanks!
