### ISSUE TITLE
iPhone Inline Player .. keeps going full screen

### ISSUE THREAD

**Issue by rowl3y** [flowplayer/flowplayer#1460]
Hi, I just cart get the player to stay inline on the web page. 

Does this now not work? 

thanks 

`<link rel="stylesheet" href="//releases.flowplayer.org/6.0.5/skin/functional.css">
	
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="//releases.flowplayer.org/6.0.5/flowplayer.min.js"></script>
<script src="//releases.flowplayer.org/hlsjs/flowplayer.hlsjs.min.js"></script>
<script src="flowplayer.inlinevideo.js"></script>
</head>

<body>
<div id="fp-hlsjs" style="width:80%" >

</div>
</div>
<script>
flowplayer("#fp-hlsjs", {
clip: {
autoplay: true,
title: "DJ LIVE",
sources: [
{ type: 'application/x-mpegurl',
src: "URL REMOVED",
live: true
}
]
},
embed: false

});
</script>`

**Comment by bbbo** [comment]
Flowplayer 6 (and 7) has been deprecated years ago. `flowplayer.inlinevideo.js` also is not our script.
Quite possible that ancient code does not work with current iPhones.
