### ISSUE TITLE
Playback affected by non-existing subtitles (HTTP 415)

### ISSUE THREAD

**Issue by dagwieers** [flowplayer/flowplayer#1461]
### Expected Behavior
So we have a stream from a live radio station that has subtitles available, but doesn't offer them currently. The reason why there is a subtitle track according to the VOD provider is that they can offer them when they are available without reloading the stream.

Fetching the subtitle track returns a HTTP 415 Unsupported Media Type, which causes playback to fail.

The stream is: https://live-radio-cf.lwc.vrtcdn.be/groupa/live/d6fdec5d-5d67-4cc3-9f8c-e3e8993c8ee4/live.isml/.mpd

### Actual Behavior
Video playback stops almost immediately with error: **This video file cannot be played.(Error Code: 241415)**

### Steps to reproduce
1. Go to: https://flowplayer.com/developers/tools/stream-tester?custom=https%3A%2F%2Flive-radio-cf.lwc.vrtcdn.be%2Fgroupa%2Flive%2Fd6fdec5d-5d67-4cc3-9f8c-e3e8993c8ee4%2Flive.isml%2F.mpd
2. Verify the playback issues

The player event log looks like this:
```
0s -- player loaded
0.02s -- config
0.08s -- resize
0.25s -- loadstart
0.26s -- config
0.26s -- qualities
0.27s -- config
0.27s -- durationchange
0.28s -- play
0.28s -- waiting
0.32s -- config
0.32s -- durationchange
0.32s -- resize
0.33s -- config
0.33s -- loadedmetadata
0.44s -- seeking
0.6s -- config
0.61s -- config
0.77s -- seeked
0.78s -- loadeddata
0.78s -- canplay
0.79s -- playing
0.95s -- config
0.96s -- config
1.02s -- resize
1.3s -- config
1.31s -- config
2.39s -- viewenter
2.41s -- config
2.42s -- qualities
2.71s -- config
2.72s -- config
3.05s -- config
3.06s -- config
4.51s -- viewleave
123.54s -- viewenter
123.69s -- viewleave
```
### Environment
- CentOS-7
- Chrome 80.0.3987.163 (Official Build) (64-bit)
- Player used: https://flowplayer.com/developers/tools/stream-tester

### Alternative players
We did a study on how other players handle this and made an overview here:
https://github.com/peak3d/inputstream.adaptive/issues/433#issuecomment-626994942

THEOplayer seems to handle this best. It never retries on failure, but keeps getting the next segment, so if subtitles (re)appear they would work immediately.

You can try out this stream and behaviour of THEOplayer from the VOD provider's website: https://radio1.be/kijk-live (You will have to enable subtitles by pressing the square on the lower-right)

**Comment by dagwieers** [comment]
A summary of this issue is offered in https://github.com/peak3d/inputstream.adaptive/pull/446

**Comment by bbbo** [comment]
this repo is for the deprecated Flowplayer 7 ;) However the issue is a valid point for Native as well, we'll fix the behavior in the DASH plugin asap. Please check again in a few days on our site, we already have a fix in dev.

**Comment by dagwieers** [comment]
Great, I'm interested to learn how it will behave compared to other players.

**Comment by dagwieers** [comment]
The original stream no longer includes the (missing) subtitle track. So cannot be used for testing this particular problem.
