### ISSUE TITLE
showing warning messages while creating production build in angular app.

### ISSUE THREAD

**Issue by pranabunni** [flowplayer/flowplayer#1470]
I am using flowplayer v2.5.15 in my angular app. When creating production build it shows below warnings from flowplayer.css file.

WARNING in Invalid property name 'rx' at 1882:3694. Ignoring.

WARNING in Invalid property name 'ry' at 1882:3699. Ignoring.

I solved the issue by removing the style 'fp-rect{rx:1;ry:1}'.

Actually is it a bug?

**Comment by bbbo** [comment]
We'll check this when we release our own npm packages ina  few days.
