### ISSUE TITLE
Not loading assets properly by GUID

### ISSUE THREAD

**Issue by ajdubovoy** [flowplayer/flowplayer#1471]
Hi,

I'm trying to initialize a Flowplayer instance with the options:

```js
{
  token: <VALID_TOKEN>,
  src: <VALID_VIDEO_GUID>
}
```

The token is configured with no domain limits, at least for local testing. I'm running the site from localhost.

The GUID is copied directly from Flowplayer and is verifiably correct.

Whenever `flowplayer` tries to load the video asset, I get a 404 error, and it tries to load the asset from "localhost:3000/<VALID_VIDEO_GUID>" instead of recognizing it as a GUID and converting to whatever Flowplayer link is needed.

If I go to Flowplayer and manually copy a link to the actually asset (like where the MP4 file is stored) and replace the SRC with that, it works fine...but then I lose all the advantages of Flowplayer's analytics and compression.

Any help would be appreciated. I'm wondering if somehow the script behaves weirdly with localhost? I'm loading from the CDN listed on the Flowplayer website.

Thanks so much.

**Comment by nnarhinen** [comment]
This repository is for the legacy FP7 open source version. Loading with platform ids is only available in Flowplayer Native with the OVP plugin: https://flowplayer.com/developers/plugins/ovp

**Comment by bbbo** [comment]
Addendum: since the main src is HLS, you also need to load the HLS plugin.

**Comment by ajdubovoy** [comment]
Thank you for your help!
