### ISSUE TITLE
.hls object is not coming in safari browser but coming in other browsers

### ISSUE THREAD

**Issue by yashrajsapra** [flowplayer/flowplayer#1473]
Hi 
Value of api.hls appears to be undefined in safari browser but in chrome we are able to access that object , even after including hls.min.js script i'm not able to access

**Comment by bbbo** [comment]
Do you force Apple's HLS with `native: true` ? In this case there will be no hls api object.

**Comment by yashrajsapra** [comment]
Even if I'm not doing that then also I'm not getting that object, i removed those lines from the player conf but still I'm not getting that object

**Comment by yashrajsapra** [comment]
chrome browser 
---------------.api.hls
value: i {_events: n, _eventsCount: 47, config: {…}, _autoLevelCapping: -1, abrController: i, …}

safari 
--------------.api.hls
value :undefined 


here ------------ is name of the player

**Comment by bbbo** [comment]
Do you include the airplay plugin? Airplay forces native HLS in Safari by default.

In any event, please write an email to support@flowplayer.com from the email with which you subscribed to Flowplayer, along with a link to a MINIMAL (player setup only, on a dedicated html page) sample url exposing the issue.

This repo is for the deprecated Flowplayer 7.

**Comment by yashrajsapra** [comment]
Hi Bend that solution actually works but it didn't work on any of the iPhone, it works on mac so is there any separate API that we need to include  for iPhone

**Comment by bbbo** [comment]
iPhones do not offer any API to access the HLS instance.
