### ISSUE TITLE
Integrating VastTag in FlowPlayer

### ISSUE THREAD

**Issue by yashrajsapra** [flowplayer/flowplayer#1474]
Hi,
I need to integrate VAST tag which I'm getting from one of the ad service group , which i tested on Google VAST inspector, there it's working fine but when I'm adding that URL in flowplayer instance that time it's not working so can you please tell how I can add that URL there

**Comment by bbbo** [comment]
This repository is for the deprecated and unsupported Flowplayer 7 .

For Flowplayer Native, follow the advise on https://flowplayer.com/help/advertising resp. https://flowplayer.com/developers/plugins/ads .

If you run into problems, please email support@flowplayer.com from the email address associated with your subscription.
