### ISSUE TITLE
setRatio should round

### ISSUE THREAD

**Issue by i8beef** [flowplayer/flowplayer#155]
Right now, setRatio simply takes ratio, evaluates it, and multiplies by 100. This could have the effect of the player window being a different size than the ratio overlay, which would manifest as a 1 pixel line at the bottom of the player under the control bar (I.e., ratio having a height of 501 and flowplayer having one of 500).

A slightly better solution would be to round this to the nearest whole number to avoid different CSS engines doing weird things with partial percentages. I believe rounding down is the better option here.

**Comment by nnarhinen** [comment]
The grey bar (2px) between the red area and player is the timeline border in that demo. Changing the css to

```css
.flowplayer.is-mouseout .fp-timeline {
  height: 0;
  border: 0;
}
```

Fixes this:

![image](https://cloud.githubusercontent.com/assets/265438/5625957/13ba9a2a-958d-11e4-8351-322bc12617c6.png)

**Comment by nnarhinen** [comment]
And IMO setRatio should _not_ round. That way it is left to the implementor to provide as accurate ratio as needed in his setup. If we round/floor the value, in some cases it will leave vertical borders to the player etc.

**Comment by blacktrash** [comment]
@nnarhinen - good catch, and I agree ;-)
