### ISSUE TITLE
embed: no subtitles

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#163]
Quote http://flowplayer.org/forum/#!/moot/4415

------

It would appear that the Embed code that gets generated for a video does not include the subtitle src in it, which means embedded videos will not be section 508 compliant. Is there a reason that these do not get added to the embed code?

------

I can confirm that subtitles are not embedded.

**Comment by blacktrash** [comment]
If embedding is not enabled, yes. Maybe add an embed option to enable subtitles, defaulting to false?

**Comment by nnarhinen** [comment]
That might be possible

**Comment by blacktrash** [comment]
Then the CORS onus is entirely on the user.

**Comment by nnarhinen** [comment]
IMO the ability to configure the iframe src url is enough. All complex embed setups can be then achived with that.
