### ISSUE TITLE
Don’t use @2x in the filename, since the @ character in a URL is reserved as the delimiter separating the username and password from the host in authentication URL schemes

### ISSUE THREAD

**Issue by lifeiscontent** [flowplayer/flowplayer#166]
> Create images that are twice the width and height of your current image resources. A common file-naming convention for high-resolution images on the web is to prepend _2x before the file extension; for example, myImage_2x.jpg. Don’t use @2x in the filename, since the @ character in a URL is reserved as the delimiter separating the username and password from the host in authentication URL schemes.

[Source](http://developer.apple.com/library/safari/#documentation/NetworkingInternet/Conceptual/SafariImageDeliveryBestPractices/ServingImagestoRetinaDisplays/ServingImagestoRetinaDisplays.html)

**Comment by nnarhinen** [comment]
No more images for FP7, thus this becomes invalid.
