### ISSUE TITLE
feature: optionally embed always latest

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#173]
The disadvantage of a  versioned embedded player is that it is stuck with the bugs of the respective version on the third party website forever.

Have "latest" option for embedding and link to a latest distribution?

Pitfalls:
- not a compact object is embedded, but a script whose structure might change fundamentally, thus breaking an embedded player completely
- licensing - but as long as latest points to a specific *feature* release, i.e. for the moment *5* this should be ok

**Comment by nnarhinen** [comment]
This will be addressed by the new share stuff
