### ISSUE TITLE
feature: more embed options

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#174]
1. custom link target
2. target _blank

asked for by potential customers

**Comment by cycleos** [comment]
Give an option for custom embed code. For example an iframe designed especially for embedding.

**Comment by nnarhinen** [comment]
this is allready possible:

```js
flowplayer(function(api) {
  api.embedCode = function() {
    return '<iframe ...></iframe>';
  });
});
```

**Comment by cycleos** [comment]
Nice, didn't see it documented. :)

**Comment by blacktrash** [comment]
@cycleos - because it will only be available in version 6, which is not released yet.

**Comment by nnarhinen** [comment]
@blacktrash that works allready with current release version.

**Comment by nnarhinen** [comment]
http://jsfiddle.net/papj3jxw/

**Comment by blacktrash** [comment]
Oops. Will document it then.

**Comment by blacktrash** [comment]
@cycleos - upon further reflection this is so advanced that it will open tons of cans of worms exposing this publicly and officially. Should be reserved to those users who are able to read source code ;-)

**Comment by cycleos** [comment]
Can I suggest a text for the documentation:


Flowplayer supports custom embedding code, which requires some advanced programming skills. The feature is useful in case you offer the option to the users to embed your videos in a different way than the Flowplayer standard. Example is to offer a separate page with the player only for embedding through iframe.
To use the feature, you need to call the Flowplayer API in the following way:
flowplayer(function(api) {
    api.embedCode = function() {
        return '<iframe src="http://example.com/YourPageWithVideoToEmbed.html"></iframe>';
    }
});

**Comment by cycleos** [comment]
Uh, it is deleting the iframe in the return :(

**Comment by blacktrash** [comment]
Because you are returning an empty string?

**Comment by cycleos** [comment]
Yes, github is deleting the iframe code inside.

**Comment by blacktrash** [comment]
:+1: - what about adding `mozallowfullscreen` and `webkitallowfullscreen` for safety?

**Comment by blacktrash** [comment]
Probably also explicit `fullscreen: true` in the player config, unless the originating player has `fullscreen: false`?

**Comment by nnarhinen** [comment]
blank target can now be configured by `conf.embed.popup = true`
