### ISSUE TITLE
expand the css designer to include all visible components

### ISSUE THREAD

**Issue by jedierikb** [flowplayer/flowplayer#233]
Your CSS designer is great.
http://flowplayer.org/designer/

Could you expand this utility to allow options for:
1. No control bar at all.
2. No fullscreen button overlay in top right (or option for where to place it).
3. No embed code in top left (or option for where to place it).
4. Option for where to put the logo.

And for bonus points:
A. an easy way to put a different graphic or css up for the playbutton and the buffering dots (or maybe just a few options).
B. it would be nice to have an option here to also enable/disable keyboard controls in this utility.

**Comment by nnarhinen** [comment]
The designer will get a rewrite.
