### ISSUE TITLE
finish event fired more than once

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#242]
Easy to detect:

``` js
flowplayer(function (api) {
  api.bind("finish", function () {
    console.log("finish event fired");
  });
});
```

See: http://flowplayer.org/forum/#!/moot/7204
Can be worked around with a more global var, but still unexpected.

**Comment by maheshkajaleinfobeans** [comment]
I am using Flowplayer 7.2, using API to get events like pause, next, finish.
When song completes the I expect finish event but before that pause event is also gets triggered before finish event.
How to prevent that, please suggest.
Also on pause, I required pause event also in another scenario.

Thanks,
Mahesh

**Comment by nnarhinen** [comment]
Please ask usage related questions in the [forums](https://flowplayer.com/forum).

Having the pause event triggered before finish is expected - technically the player pauses when it reaches the end of the video. You need to check `api.video.duration` on your pause handler to see if the video is reaching end. Or then delay the pause handler so long that `api.finished` is updated reliably.

**Comment by pranabVadakkath** [comment]
flowplayer api resume event  called more than once each time when reinitializing the flow player after stopping it.

**Comment by bbbo** [comment]
Flowplayer 7 is deprecated, there won't be any further fixes.
