### ISSUE TITLE
HTML5 audio support

### ISSUE THREAD

**Issue by queenvictoria** [flowplayer/flowplayer#260]
Hi there. I've begun work on `<audio/>` support for the HTML5 engine. It seems to be working in webkit browsers at the moment including Mobile Safari. Is this something that you would like to see in Flowplayer?

My fork is over here. The changes are fairly minor.
https://github.com/Laudanum/flowplayer/tree/audio-support

**Comment by danrossi** [comment]
Hi @PommeVerte  I have this ready and added a heap of audio player specific features to it here http://flowplayer.electroteque.org/audio/fp5.  The id3 reader feature will only work in some browsers because of the binary read support required. 

I can send that to you by contacting me from the site.

**Comment by queenvictoria** [comment]
Hi @danrossi . I did contact you via your site a couple of years ago. Any chance of releasing that code into the wild? I'll send you another message via the site.

**Comment by robinboening** [comment]
+1 for releasing @danrossi

**Comment by danrossi** [comment]
ALOT of work has gone into this but mainly the other features. I will release on github just the engine part for the budget tight people. It's basically just the video engine replacing the video tag with the audio tag minus various in events and mimetypes. No funky integration although it probably should be integrated directly into the html5 engine.  The rest of the other audio player specific features I will release separately.

**Comment by danrossi** [comment]
https://github.com/danrossi/audio-engine it's here. No support provided , I have too many priorities right now but follow the demo feature page and it will be easier to follow to override the player css.

**Comment by danrossi** [comment]
take note of the type="video/mp4" mimetype that gets replaced inside that is a hack work around.

**Comment by robinboening** [comment]
Thank you very much @danrossi I really apreciate that. Will try it later the day.

**Comment by danrossi** [comment]
@robinboening 

The engine has been updated for Version 6 as it as a pretty huge refactoring.  check it out. 

https://github.com/danrossi/audio-engine

http://flowplayer.electroteque.org/audio/fp5

**Comment by nnarhinen** [comment]
There's an officially supported audio plugin available: https://flowplayer.org/docs/plugins.html#audio
