### ISSUE TITLE
ready event and load callback not caught

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#284]
To make this demo
http://flowplayer.blacktrash.org/fp5/qsel.html
work on iPad I had to resort to an early cuepoint:
http://example.flowplayer.org/scripting/qsel.html

Will create a simpler example soon.

See also: http://flowplayer.org/forum/#!/moot/8827

The timing of video loading seems even broken for the same iPad version with the same iOS:
http://example.flowplayer.org/scripting/signed-ondemand.html
works on @nnarhinen's iPad 4th gen, iOS 6.1.2 - but not on mine.

**Comment by gmcnaughton** [comment]
Hi all!  Is this still the recommended way to start flowplayer on a playlist item other than the first?

We have the same use case as https://github.com/flowplayer/flowplayer/issues/284#issuecomment-21998156 -- we want to show a playlist, but based on url fragment the first video to play may vary.

**Comment by blacktrash** [comment]
@gmcnaughton - you probably want something like http://demos.flowplayer.org/playlist/linkable.html#video-2
This is not what this bug was about, and it was squashed a year ago ;-)

**Comment by gmcnaughton** [comment]
@blacktrash Thanks for the example, that helps a lot! Sorry for hijacking an old bug. :+1:
