### ISSUE TITLE
Preloading error "html5: video file not found"

### ISSUE THREAD

**Issue by pnewton** [flowplayer/flowplayer#288]
We have 8% of our traffic using this Firefox 4.0.1 on Windows XP. Viewing http://flowplayer.org/standalone/basics/autoplay.html in it produces the error, "html5: video file not found."

Interestingly enough, if autoplay.html is copied locally and the preload="none" attribute is added to the <video> tag, the video will play.

**Comment by nnarhinen** [comment]
This issue will kinda be fixed by the "pure" splash setup by javascript FP6 supports.
