### ISSUE TITLE
Request for Bower integration

### ISSUE THREAD

**Issue by jfroom** [flowplayer/flowplayer#289]
https://github.com/twitter/bower
https://github.com/twitter/bower#defining-a-package
http://sindresorhus.com/bower-components/

**Comment by dogancelik** [comment]
There is no "dist" folder. Look at these Bower packages for example:

```js
[
  'bower_components/jquery/dist/jquery.min.js',
  'bower_components/typed.js/dist/typed.min.js',
  'bower_components/bootstrap/dist/js/bootstrap.min.js',
  'bower_components/epoch/dist/js/epoch.min.js',
  'bower_components/skrollr/dist/skrollr.min.js',
]
```

They all have "dist" folder.

**Comment by nnarhinen** [comment]
I'm not going to add `dist/` directories to git. If this can be accomplished without that, it can be done. For now Flowplayer can be downloaded from [NPM](https://www.npmjs.com/package/flowplayer) and as [ZIP](https://flowplayer.org/latest/)
