### ISSUE TITLE
Playlists in Firefox sometimes shows the play-button while changing clips

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#295]

**Comment by nnarhinen** [comment]
With current firefox this is not reproducable

**Comment by blacktrash** [comment]
For me it is e.g. here: http://demos.flowplayer.org/playlist/minimal.html - Firefox 36.0, and in any other browser for that matter - must be somewhere between finish and load.

**Comment by nnarhinen** [comment]
Maybe needs a slow connection. On my 100/100 broadband I can't reproduce this on any browser.

**Comment by blacktrash** [comment]
a) people behind slow connections exist, people with tablets behind mobile networks too ;-)
b) Saturday is slow here, but 3.62 Mbps should be ok
c) more likely to happen with non-demo longer videos (longer loading time)

I don't think it's a show-stopper, but it's undeniable there.
