### ISSUE TITLE
embed: make playlists embeddable

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#368]
A playlist setup embeds only the first video - basically making embed a nono in conjunction with playlists.

In short: embed should contain ```conf.playlist```. A tricky one for js playlists. Raising the question how one could coerce JSON into a data-playlist attribute (escaping?) - which is by spec intended for private use on a page (so already debatable for embed purposes).

HTML playlists probably could be implemented with relative ease - with the default behaviour of ```advance: true, loop: false```.

**Comment by nnarhinen** [comment]
Playlists can now be made embedable by setting `conf.embed.playlist = true`

**Comment by blacktrash** [comment]
:+1:
