### ISSUE TITLE
MP4: may not play in some Chrome versions

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer#423]
e.g. Chrome 27 on windows - but do play in a plain video tag.
Demo to follow.

**Comment by evgeetha** [comment]
I am still facing this issue. My issue is very strange. I am capturing video from iphone and uploading to server. In website viewing the video in chrome, if the video size is less than 2 mb then it plays well. Downloading from server (mp4 files) alone having the issue. 

I can play local video files (having size 8 mb) before upload. The file size can't be played if downloads from server. 

This issue occurs in chrome only.

Guys, can you tell me the solution? In above solution how to convert MP4 video to WEBM.  I tried preload solution also it is not working.

**Comment by bbbo** [comment]
this is the bug tracker. please post usage issue sin the forums on flowplayer.org along with a link to an example page. Sounds like an encoding or server issue.
