### ISSUE TITLE
Video in playlist starts from previous timestamp on iPhone

### ISSUE THREAD

**Issue by lushchick** [flowplayer/flowplayer#433]
When I click on a video to play, then directly move to another video in playlist - it starts the second video from the timestamp of the previous video.
http://temp-share.com/show/FHKd4Gyg6

Such behavior could be also reproduced on FP demo page (from iPhone): http://flowplayer.org/demos/playlist/

**Comment by nnarhinen** [comment]
I can't reproduce this on iOS 8.1 simulator. Please report back if this still is an issue. (Also make sure you actually hit the 'playlist items' and not the player container.

**Comment by blacktrash** [comment]
@nnarhinen - i**Phone**, not i**Pad** - i.e. no inline video. Replicable for me in 8.1 simulator. You can also see the playhead at the current playback position after touching "Done". I think this is just the behaviour of the generic player. So I can repro, I'm in 2 minds whether it's worth fixing.

**Comment by blacktrash** [comment]
Done some more tests, with longer videos, and it works already in the 7.1 simulator, sort of. One can see for a moment an image at the last position of the other video, and then it jumps back to the beginning. With short clips, the jump back sometimes does not happen.
I don't deem this a player bug, and too erratic to fix.
