### ISSUE TITLE
interface to playlist elements outside container

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#443]
As a result of #359 there should be an interface to playlist elements which do not reside in the container.

For example http://demos.flowplayer.org/playlist/scrollable-jquerytools.html breaks fullscreen in Chrome when the scrollable positioned inside the container. While this is almost certainly a Chrome bug, it can be nevertheless very frustrating to find out about it only when your setup is finished, and then moreover to duplicate part of the playlist extension so to speak for elements outside the container.

In many circumstances - especially when the playlist is not placed directly near the container - one has to make quite some CSS contortions conceptually to get the desired layout.

Probable requirements:
- extra config option
- default className for element(s) container playlist items

The Flowplayer Flash playlist plugin http://flash.flowplayer.org/plugins/javascript/playlist.html might also give some ideas.

**Comment by Aybee** [comment]
:+1:  It's important for responsiveness to have the playlist outside the container (.flowplayer). Else we have to work with fixed values for height, padding or similar. In many cases we don't know the height of the playlist and height of playlist changes sometimes, e.g. if you turn a smartphone from portrait to landscape.

So, it's important to have an option to have the .fp-playlist as e.g. the next sibling of .flowplayer.

**Comment by nnarhinen** [comment]
@blacktrash How about this: if `conf.query` starts with `#`-sign then handle it as external?

**Comment by blacktrash** [comment]
Yes. In theory one could also use a class to avoid creating a different id for each player and map via index, but that feels like inviting breakage.

**Comment by nnarhinen** [comment]
http://demos.842f.flowplayer.me/ and the assets from there

**Comment by Aybee** [comment]
> http://demos.842f.flowplayer.me/ and the assets from there

This is not enough. Only chance to have playlist outside of container is to create playlist manually and map the playlist items to the player. It's really important to have an option to have the playlist outside of the container.

**Comment by Aybee** [comment]
e.g. here http://demos.842f.flowplayer.me/playlist/grid.html the demo says
> The dynamic positioning is optional (see the comments in the CSS code), but - effect aside - shows live how the playlist element can be placed **outside the player container**. There is no additional JavaScript involved, everything is done via CSS programming.

But playlist is inside the container even though in this design you can handle it with CSS showing the playlist outside the player. This is done by assigning a fixed `bottom: -440px;` to the `.fp-playlist`. But it is not possible handling a fluid playlist on different screens.
```html
<div class="flowplayer id="grid">
  <div class="fp-ratio"></div>
  <div class="fp-help"></div>
  <div class="fp-player">
    <object class="fp-engine"></object>
    <div class="fp-playlist"></div>
    <div class="fp-ui"></div>
    <div class="fp-subtitle"></div>
  </div>
  <a href="http://flowplayer.org"></a>
  <div class="fp-context-menu"></div>
</div>
```
To handle a real fluid playlist it has to be:
```html
<div class="flowplayer id="grid">
  <div class="fp-ratio"></div>
  <div class="fp-help"></div>
  <div class="fp-player">
    <object class="fp-engine"></object>
    <div class="fp-ui"></div>
    <div class="fp-subtitle"></div>
  </div>
  <a href="http://flowplayer.org"></a>
  <div class="fp-context-menu"></div>
</div>
<div class="fp-playlist"></div>
```

**Comment by nnarhinen** [comment]
With the changes I made for #842 you are able to do:

```html
<div data-ratio="0.5625" class="flowplayer" data-query="#my-playlist a">

   <video>
      <source type="application/x-mpegurl" src="//stream.flowplayer.org/night1.m3u8">
      <source type="video/webm"            src="//stream.flowplayer.org/night1.webm">
      <source type="video/mp4"             src="//stream.flowplayer.org/night1.mp4">
   </video>
</div>
<div id="#my-playlist">
   <a href="//stream.flowplayer.org/night1.mp4"></a>
   <a href="//stream.flowplayer.org/night3.mp4"></a>
   <a href="//stream.flowplayer.org/night5.mp4"></a>
   <a href="//stream.flowplayer.org/night6.mp4"></a>
</div>
```

Which makes flowplayer automatically use the playlist.

**Comment by blacktrash** [comment]
@nnarhinen :+1: - does this require jQuery?

**Comment by nnarhinen** [comment]
Flowplayer will not generate the playlist outside of the container still. So if your `conf.query` does not find the elements _or_ you specify playlist in the passed configuration to `flowplayer()`, the playlist will be generated inside the container and will not work. So specifying `conf.query` also implies that the playlist have to be found from the HTML markup. So in a way it mostly makes sense when using automatic installation with jQuery but does not necessarily need jQuery.

**Comment by blacktrash** [comment]
Understood. The very nature of the thing appeals to VIDEO tag based installs.

**Comment by Aybee** [comment]
@nnarhinen Thank you for your reply. I will test it on next need.
