### ISSUE TITLE
ability to load a good url when player fails with a bad one

### ISSUE THREAD

**Issue by tipiirai** [flowplayer/flowplayer#46]
see: 

https://github.com/flowplayer/flowplayer/issues/44#issuecomment-9592004

**Comment by nnarhinen** [comment]
@blacktrash this is already possible in an `error` handler.

 * remove `is-error` class
 * set `api.error = false;`
 * set `api.loading = false;`
 * `api.load('/path/to/good/source.webm')`

**Comment by nnarhinen** [comment]
The real question here is: should `api.load()` already do this by default?

**Comment by blacktrash** [comment]
Already possible? What am I missing: http://flowplayer.blacktrash.org/fp5/recover.html ?
That's why I went to the contortions at http://demos.flowplayer.org/scripting/recover.html

**Comment by nnarhinen** [comment]
Well at least with FP6 this works, didn't try with FP5:

```js
var el = document.getElementById('player');
var api = flowplayer(el, {
    splash: false,
    ratio: 0.417,
    logo: 'http://codesense.fi/codesense_logo.png',
    key: '$289122895653393',
    embed: {
      library: 'http://localhost:8000/dist/commercical/flowplayer.js',
      popup: true
    },  
    clip: {
      title: 'Example video',
      sources: [
        {   
          type: "video/webm",
          src: "http://stream.flowplayer.org/bauhaus/624x260invalid.webm"
        },  
        {   
          type: "video/mp4",
          src: "http://stream.flowplayer.org/bauhaus/624x260.mp4"
        }   
      ]   
    }   
}); 
api.on('error', function(ev, player, code) {
  flowplayer.common.removeClass(el, 'is-error');
  player.error = false;
  player.loading = false;
  player.load('http://stream.flowplayer.org/bauhaus.webm');
}); 
```

**Comment by blacktrash** [comment]
Didn't try with fp6 yet. I understood "already possible" as referencing the current release.

**Comment by blacktrash** [comment]
Yes. See: http://demos.flowplayer.org/scripting/recover.html
