### ISSUE TITLE
How can I remove a flowplayer instances?

### ISSUE THREAD

**Issue by danielmariz** [flowplayer/flowplayer#484]
I have a problem with flowplayer flash fallback. 
I'm binding two views that has flowplayer embed, so on console I have flowplayer(0) and flowplayer(1), flowplayer(2) is undefined. When I remove those views, and bind again, I have flowplayer(0), (1), (2), (3).
How can I remove older instances to have just 0 and 1?

**Comment by davutcavdar** [comment]
<div id="player"> </div> 

 container = document.getElementById(player);

 flowplayer(container).shutdown();

 document.getElementById(player).remove();
