### ISSUE TITLE
no loading indicator in Flash in IE8 and IE9

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#496]
In IE8 this should probably the "loading ..." text instead of the dots animation. Either way, it does not happen.
See: http://flowplayer.org/forum/#!/moot/15164 and confirmed by @bbbo 

A good example to verify might be the second one at http://demos.flowplayer.org/basics/subtitle.html

**Comment by nnarhinen** [comment]
http://demos.756f.flowplayer.me/bug/497.html

**Comment by nnarhinen** [comment]
@bbbo can you confirm my fix

**Comment by bbbo** [comment]
will check

**Comment by bbbo** [comment]
inconsistent :-( sometimes I see the "Adobe Flash is disabled for this page, click player area to enable." message and the Flowplayer UI does not show, sometimes it works fine with the "loading" text. Will do some tests in a fresh VM later today.

**Comment by bbbo** [comment]
Works fine in original IE8 with Flash 15.
Works fine in original IE8 with Flash 16.
works fine with IE9 and Flash 16.

Guess something is messy about my other IE9 install ;)
