### ISSUE TITLE
"cursor: none;" prevents toolbar from auto-hiding (Chrome, Opera)

### ISSUE THREAD

**Issue by slavafomin** [flowplayer/flowplayer#554]
Hello there again )

Let me revisit [this topic](https://github.com/flowplayer/flowplayer/issues/299#issuecomment-26888447) in a more structural way.

**What i'm trying to do?**
I'm trying to hide mouse cursor in flowplayer when the user is not interacting with it for some time.

**Why i'm doing this?**
I consider this a basic functionality for any video player. All other players do this (YouTube, Vimeo, VideoJS, etc). Looks like there is no such functionality in flowplayer out of the box so i'm trying to plug it in somehow.

**Where i can see a demonstration of this issue?**
http://jsfiddle.net/mM5QT/5/
First player is not auto-hiding the toolbar because of "cursor: none;" CSS instruction, second player is working properly.

**How do i implement it?**
I've played with the DOM inspector and found out that player's container gets class "is-mouseout" when cursor is not moving over it for some time (at the same time when toolbar auto-hides). So i'm trying to use this CSS-selector to apply "cursor: none;" instruction in order to hide the cursor. This CSS-selector was also recommended [here](https://github.com/flowplayer/flowplayer/issues/299#issuecomment-15010693).

I'm using latest flowplayer 5.4.3 commercial. This bug can be observed with Google Chrome browser (Firefox is working just fine). Looks like this CSS rule triggers cursor detection somehow.

[The solution to hide mouse cursor is here.](http://stackoverflow.com/questions/19630524/flowplayer-hide-cursor/19630525#19630525)

**Comment by metsehaf** [comment]
@nnarhinen you are a genius works perfectly on chrome, now I am able to remove annoying cursor on video.

**Comment by metsehaf** [comment]
can't believe I am posting this in 2018, just know that your solution is still valuable.
