### ISSUE TITLE
rtmp: recovery from bad url does not work

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#589]
http://demos.flowplayer.org/scripting/recover.html?engine=flash does not work if the flash sources would be delivered via RTMP.
Demo to follow.

**Comment by nnarhinen** [comment]
@blacktrash does FP Flash detect this correctly?

**Comment by blacktrash** [comment]
Yes: http://flowplayer.blacktrash.org/test/rtmp-recover.html correctly reports error 200 "stream not found".
Flowplayer HTML5 simply hangs, I also tried with full rtmp url.

**Comment by anssip** [comment]
fixed. Now fires an error with code 4 when the stream is not found.

**Comment by blacktrash** [comment]
There is an error, but the API only receives `undefined` as error, not an error object.

**Comment by blacktrash** [comment]
@anssip - sorry for the noise, I probably tested while the change was not yet propagated. All is fine.
