### ISSUE TITLE
preload="none" causes error in Internet Explorer 11

### ISSUE THREAD

**Issue by 19Gerhard85** [flowplayer/flowplayer#622]
Hey folks,

the attribute preload="none" on the video element causes following error on Internet Explorer:
the play button disappears
the player gets the class "is-playing" instead of "is-paused"

Greets

**Comment by JurisTechsys** [comment]
> Quick workaround to enable flash version only for IE11:
> 
> ```js
> var playerConfig = {
>   // your config
> };
> // Fix for IE11 https://github.com/flowplayer/flowplayer/issues/622
> if (/Trident\/7/.test(navigator.userAgent)) {
>   playerConfig["engine"] = "flash";
> }
> flowplayer.conf = playerConfig;
> ```

it's working in IE thank you
