### ISSUE TITLE
Add proper event listener cleanup

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#639]
If a flowplayer instance is removed from DOM, it still leaves traces of itself in form of event listeners listening to document-events.

This prevents the flowplayer instance from being garbage collected, ultimately resulting to very high memory consumption.

**Comment by kellyrmilligan** [comment]
hi, I see this is pretty old. is this still on the roadmap?  i'm seeing some things left over in detached dom tree, after calling unload and unbinding everything in a single page app. 

what is the proper way to clean up a flowplayer instance?

**Comment by nnarhinen** [comment]
Yes, this is issue will be fixed in the 6.0 milestone.

6.0 will be more suitable for single page apps otherwise too (complete javascript API, no jQuery dependency etc).

**Comment by nnarhinen** [comment]
If you want to use 5.x in a SPA you would have to go through flowplayer source code to see all the places where event handlers are bound to `document` and `window` and remove them manually on unload.

**Comment by kellyrmilligan** [comment]
When is the 6.0 milestone expected?  Love that jquery will not be a dep anymore

**Comment by nnarhinen** [comment]
There is no fixed date to give yet, but progress can be tracked at https://github.com/flowplayer/flowplayer/milestones/6.0%20-%20next%20major%20release
