### ISSUE TITLE
embed: make player size configurable (re: hls)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#651]
When hls is played the embed code will always pick the dimensions of the resolution which is chosen first by hls as _player_ size. This will more often than not differ from the WEBM or MP4 video dimensions.
The embedded player size must be configurable because with dynamic resolutions the video size is unpredictable, and therefore the size of the embedded player as well.

See also: #633

**Comment by nnarhinen** [comment]
I'm not completely sure how to do this..

Because now we should document something like

> Remember to _always_ configure `conf.embed.width` and `conf.embed.height` when using an HLS source

**Comment by nnarhinen** [comment]
@blacktrash do you have any other idea how this could be handled?

**Comment by nnarhinen** [comment]
(`conf.embed.width` and `..height` do not exist yet of course)

**Comment by nnarhinen** [comment]
The best I could come up with is to
 * allow configuring `conf.embed.width` and `conf.embed.height`
 * if they are not set, use dimensions from video as before
 * but if HLS source is selected use the dimensions of the current player

I guess the last is better than to have random(?) dimensions reported by the video tag.

**Comment by nnarhinen** [comment]
however: lookign at http://demos.flowplayer.org/videotest/hls.html

the `videoHeight` and `videoWidth` properties on Mac Safari are 360 and 640. Do you have any cases where it does not pick the 'default' resolution?

**Comment by nnarhinen** [comment]
Looking at the m3u8 file. There is no 'default' resolution. So maybe the browser just goes with the 'middle resolution' initially when on wlan or something.

**Comment by blacktrash** [comment]
Are you really sure? At http://demos.flowplayer.org/videotest/hls.html I get:
```
> $("video")[0].videoHeight
< 720
> $("video")[0].videoWidth
< 1280
```
in the Safari console, i.e. the highest resolution, or rather the first resolution from the variant playlist (in Drive we list resolutions in descending order, otherwise the highest resolution is never picked for very short videos).
Similarly http://demos.flowplayer.org/basics/long.html gives me 768x576 instead of 640x480. Consequentially with ascending variant playlist, at http://flowplayer.blacktrash.org/fp5/hls.html (temporary) I get 384x288, and that value is stuck even after switching to a higher resolution. So I don't think the connection speed is causing this. It could not give me Drive's default VOD resolution 640x480 because we have different clamp dimensions for HLS in Drive.

Either we introduce `embed.width` and `embed.height` parameters (or only `height`, and calculate width via width/height aspect ratio), or we take the container dimensions on load ... or ignore the problem ;-)

**Comment by nnarhinen** [comment]
What Safari version are you on?

Both Safari 8.0.2 and 8.0.3 seem to consistently give 640x360 dimensions.

**Comment by nnarhinen** [comment]
I added now `embed.width` and `embed.height` configuration variables. If not given the old behavior will be used.

**Comment by blacktrash** [comment]
Safari 7.1.2 (I'm still on Mac OS 10.9 because I don't upgrade my OS while I'm editing a movie).
If that's the case also at http://demos.flowplayer.org/basics/long.html (I can understand it at http://demos.flowplayer.org/videotest/hls.html because it is the size of the container) this is a bad regression in Safari because it even ignores the aspect ratio. As this is very buggy behaviour on the Safari 8 side, I argue for using e.g. height of the container and calculate the width from ratio by default.

**Comment by blacktrash** [comment]
Side note: the iOS 8.1 simulator shows the same values as Safari 7.1.2 here.

**Comment by nnarhinen** [comment]
http://demos.flowplayer.org/basics/long.html:

![image](https://cloud.githubusercontent.com/assets/265438/5823795/55f85b50-a0e8-11e4-9577-ea7594dcbdbf.png)

**Comment by blacktrash** [comment]
ok, it looks the same as on my machine - that's the first resolution listed in the variant playlist.
So where exactly do you always see 640x360?

**Comment by nnarhinen** [comment]
at http://demos.flowplayer.org/videotest/hls.html

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/videotest/hls.html differs from Flowplayer inasmuch as the video tag's `width` and `height` properties are given as `640` and `360` - that differs from Safari 7. I guess you'll find with Flowplayer (no video tag dimension property, unless inserted by user, and video tag css width 100%) it will yield the first resolution:
http://demos.flowplayer.org/basics/long.htm 768x576 (descending)
http://flowplayer.blacktrash.org/fp5/hls.html 384x288 (ascending)
correct? (same as Safari 7)
So, yes, an additional `width` option. What happens if I don't specify `height`, but only `width`? imho, it should then use ratio to calculate.
