### ISSUE TITLE
HTML5: Video File not found with m3u8

### ISSUE THREAD

**Issue by ArhamAliQureshi** [flowplayer/flowplayer#668]
I am running m3u8 in Android / iOS Chrome browser and getting error on screen that that "HTML5: Video File not found" although stream is playing in background and I can here the voice but error screen is hiding it.

1) How to fix it ?
     Right now I have edit flowplayer.js to fix it.
2) Is there any API in HTML5 to disable error message.

P.S: Working fine on SAFARI and Android Default browser. This error is sometimes not reproducible but for few live stream it always appears. I wish I could share problematic live streams URL here but I am afraid I cannot.

videoUrls['mpegurl'] = "http://itv08.digizuite.dk/tv2b/ngrp:ch1_all/playlist.m3u8";   //this is m3u8.
videoUrls['flash'] = "ch1";  //this is channel.
rtmp = "rtmp://itv08.digizuite.dk/tv2b";                       //this is rtmp url.

$('#player').flowplayer({
            rtmp: rtmp,
            live: true,
            // one video: a one-member playlist
            playlist: [
                // a list of type-url mappings in picking order
                [
                    videoUrls
                ]
            ],
            swf: "//releases.flowplayer.org/5.4.3/flowplayer.swf",
            preload:  "none" ,
            keyboard: false,
            fullscreen: false,
            splash: false,
            embed: false
        });

**Comment by ibnbd** [comment]
@haufes after 3 years, I am with the same problem ...

**Comment by haufes** [comment]
I checked the demo above (http://demos.dev94.flowplayer.us/basics/live.html) on my Nexus 5 x and it's working well. I assume the issue was I had a setting cached.. Look at the example compared to yours and clear your phone's browser's cache.
