### ISSUE TITLE
Videos do not play on Microsoft Surface

### ISSUE THREAD

**Issue by desrosj** [flowplayer/flowplayer#685]
We have a few people using our site on a Surface tablet that are reporting the videos do not play.

The poster loads, and most of the keyboard shortcuts work, but you can not get the video to actually play, unless you do the following:
1. Focus on the player.
2. Press Q to unload.
3. Press Space, or click play.

If autoplay is on, it plays when the page loads, however this is not desired.

**Comment by nnarhinen** [comment]
Please re-open this issue with a link to a minimal demo that fails to play on the surface. Then I'll try to find a device to test with.
