### ISSUE TITLE
Video not shown on Windows Phone 8.1

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#721]
According to a customer report, windows phone 8.1 shows only a grey screen instead of the video (audio plays).

According to http://blogs.msdn.com/b/ie/archive/2014/09/26/html5-audio-and-video-improvements-for-windows-phone-8-1.aspx IE11 on WP 8.1 by default plays video inline. We have to improve the feature- and user agent checks to catch this.

**Comment by lotterfriends** [comment]
WP 8.1. useragent is "Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11; IEMobile/11.0) 
 like Android 4.1.2; compatible) like iPhone OS 7_0_3 Mac OS X WebKit/537.36 
 (KHTML, like Gecko) Chrome/32.0.1700.99 Mobile Safari /537.36" so "IS_ANDROID" is also true. The result is that the fix don't work :(

**Comment by nnarhinen** [comment]
292e82d0600f7564c96a9f139235462c09becafb should fix this for the upcoming 6.0 release.

In the meantime you can do your own user agent detection mechanism and set `flowplayer.support.inlineVideo` accordingly.

**Comment by nnarhinen** [comment]
Oh but really, it says it's Android too..

**Comment by lotterfriends** [comment]
I create a pull request with a fix. See also https://gist.github.com/lotterfriends/c847dc13f6667b9f58e9
