### ISSUE TITLE
5.5.1 full rtmp url support trigger non-backwards compatible behaviour

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#741]
Example:
```js
flowplayer(function (api) {
  api.bind("ready", function (e, api, video) {
   console.log(video.src);
  });
});
```
will show full rtmp url with 5.5.1+, no matter whether conf.rtmp is set or not, or to a different value.
Maybe this is the right thing to do, but we have to look where it breaks the api - see: #740 - how do we handle overriding etc. etc.

**Comment by nnarhinen** [comment]
I guess we don't need this issue anymore as full rtmp urls are not supported anymore.

**Comment by blacktrash** [comment]
Correct.
