### ISSUE TITLE
flash wmode IE8: disallow window and direct

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#745]
As all UI elements will be overlayed in IE8 with wmode window/direct, maybe (pseudocode):
```
if (IE < 9 && /direct|window/.test(conf.wmode)) {
  conf.wmode = "opaque";
}
```

**Comment by nnarhinen** [comment]
@blacktrash / @bbbo what are the safe `wmode` values for which IE versions?

**Comment by blacktrash** [comment]
After @bbbo ran some tests in Windows (@bbbo, remind me: Chrome on Win couldn't handle "direct" either, right?), I'm currently experimenting with:
```js
wmode: navigator.platform.indexOf("Win") < 0 ? "direct" : "opaque"
```
So it would be great if you ran some tests on Linux: http://flowplayer.blacktrash.org/fp6/independent.html?wmode=direct and http://flowplayer.blacktrash.org/fp6/independent.html?wmode=window

So far there are no problems with "opaque", so it would qualify for an unconditional default.
But I did not test against older browser versions.

**Comment by bbbo** [comment]
http://flowplayer.blacktrash.org/fp6/independent.html?wmode=direct :
- seems to work quite OK in my Chrome 43 on Windows 7
- does not show the controlbar (at least not consistent) in IE11

http://flowplayer.blacktrash.org/fp6/independent.html?wmode=opaque
- is a bit jumpy in IE11
- a bit jumpy in FF 38, especially in fullscreen

http://flowplayer.blacktrash.org/fp6/independent.html?wmode=transparent
-is very jumpy in IE11

http://flowplayer.blacktrash.org/fp6/independent.html?wmode=window
- does not show the controlbar in IE11

So opaque seems to be the best compromise; though it is not ideal.

**Comment by bbbo** [comment]
in IE8, opaque and transparent are the only settings to work anyway

**Comment by blacktrash** [comment]
Let's go for opaque as default.
direct would be the best playback performance wise.

**Comment by nnarhinen** [comment]
Conclusion:
 * Default to `opaque`
 * Disallow `direct `and `window` on all IE's?

**Comment by blacktrash** [comment]
1. default to opaque: yes
2. disallowing: no, and IE would not be enought, e.g. FF on Win also problematic

Re: 2.: needs further testing, but also might change after browser upgrades. Main goal: find out where "direct" works because it gives noticeably better performance. @nnarhinen - did you test "direct" on Linux?

**Comment by nnarhinen** [comment]
So is 2. a documentation thing then?

**Comment by blacktrash** [comment]
It's _always_ a documentation thing ;-)
According to our _current_ tests: (with default opaque):
- IE (not sure about IE9 and IE10) and FF on Win (Linux?): override "direct" and "window" with default

Do you want to implement fine-grained client detection? With the risk of a different Flash version changing the behavior yet again? I guess not, or do you?
So I assume it's _realistic_ to unfortunately leave the onus on the user (and the doc writer to explain) in this case.

**Comment by nnarhinen** [comment]
It would be very nice to offer clever defaults. But this is such a case where I would have to match user agents and do educated guesses. And then have adobe or a browser vendor do something funny that would break everything. Just feels too brittle to me.

So maybe add a documentation blurb

> For best flash engine performance you can define `flowplayer.conf.wmode = someCondition ? 'direct' : 'opaque';`

**Comment by blacktrash** [comment]
Agree. Make "opaque" default, and leave the rest to me ;-)
