### ISSUE TITLE
Chrome PepperFlash immediately fails over to RTMPT

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#748]
Check the Chrome network console at http://demos.flowplayer.org/basics/rtmp.html
Does not happen with PepperFlash disabled (or with rtmpt: false obviously), but more importantly it does not happen in Flowplayer Flash in Chrome with PepperFlash _en_abled (even though Flowplayer Flash has the same failover delay by default as Flowplayer HTML5):
http://flowplayer.blacktrash.org/test/rtmp.html with Wowza (2nd example) just one cancelled attempt for ident2 application/x-fcs, with Adobe FMS not even that.
So it cannot be (only) a PepperFlash problem.
See also #743

**Comment by nnarhinen** [comment]
@blacktrash Is this still a problem with FP6?

**Comment by bbbo** [comment]
Apparently yes. I never get a pure rtmp connection with Chrome.

Additionally, http://demos.flowplayer.org/basics/rtmp.html always 
preloads the first 2 MB of the WebM source as well...

**Comment by nnarhinen** [comment]
The preloading cannot be helped without changin it to a pure javascript install (the browser starts preloading the webm source before flowplayer takes over)

**Comment by nnarhinen** [comment]
> I wonder whether this is because, contrary to fp flash, fp html5's flash engine code does not know about proxyType

What are the possible values?

**Comment by blacktrash** [comment]
@nnarhinen - the `proxy` option exists already since recent 5.x (making the `rtmpt` option somewhat redundant): https://flowplayer.org/docs/setup.html#rtmp-options
Values: http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetConnection.html#proxyType

And, yes, it still happens. Compare network console at
http://demos.flowplayer.org/basics/rtmp.html
with
http://flash.flowplayer.org/demos/standalone/plugins/streaming/rtmp.html (one cancelled request with Wowza)
or
http://flowplayer.blacktrash.org/test/rtmp.html (first cloudfront FMS as at demos+: no request at all)
or 
But it never has been tested thoroughly in practice.

**Comment by anssip** [comment]
It uses proxyType 'best' by default nowadays.

It always starts two connection attempts by default: RTMPT and RTMP. The first one that succeeds gets used and the second one is closed and discarded. The same logic is used in FP Flash.

My Chrome (with PepperFlash) ends up using RTMP in here: https://github.com/flowplayer/flowplayer/issues/775

Is this issue really valid?

**Comment by blacktrash** [comment]
Chrome network console. Same stream.

http://flowplayer.blacktrash.org/fp6/live-rtmp.html
![screen shot 2015-06-14 at 10 35 57 pm](https://cloud.githubusercontent.com/assets/168338/8150547/d7111d34-12e5-11e5-8ade-bb3b8ad62e78.png)

http://flowplayer.blacktrash.org/test/live.html (fp flash):
![screen shot 2015-06-14 at 10 34 28 pm](https://cloud.githubusercontent.com/assets/168338/8150540/9286150c-12e5-11e5-9da9-d1ab527e2f27.png)

**Comment by blacktrash** [comment]
With Flowplayer Flash you do not get all these x-fcs requests either, in Chrome.

**Comment by anssip** [comment]
@blacktrash should be fixed in this http://demos.854f.flowplayer.me/

**Comment by blacktrash** [comment]
Confirming fix :+1:
