### ISSUE TITLE
RTMP with / in stream name breaks when going fullscreen, or if full RTMP URL used

### ISSUE THREAD

**Issue by rmc47** [flowplayer/flowplayer#752]
Two symptoms, but I believe most likely the same underlying cause:
- If I specify a full RTMP URL where the stream name part includes a /, it gets split at the last /, rather than the one before mp4:, and the stream is not found
- If I specify data-rtmp for the server URL and src for the stream name, it works until you go fullscreen, at which point it seems to reconstruct the full URL, and the failure mode above happens

For example (using Wowza as a backend):
rtmp://someserver.com/vods3/_definst_/mp4:amazons3/bucketname/some/folder/video.mp4

Here the server is:
`rtmp://someserver.com/vods3/_definst_`
and the stream:
`mp4:amazons3/bucketname/some/folder/video.mp4`

However, FlowPlayer parses it as:
Server: `rtmp://someserver.com/vods3/_definst_/mp4:amazons3/bucketname/some/folder`
Stream: `video.mp4`

From the Wowza docs on stream name parsing:
http://www.wowza.com/forums/content.php?55-How-to-format-Adobe-Flash-RTMP-URLs

If I read that spec correctly, I think the following regex should parse it:
`^(.+://[^:]+)/(.+:.+)$`

(Explanation: match some protocol, plus the server name, followed by a prefix including a colon, then the stream name with path)

**Comment by campones** [comment]
I had that issue if you remember well Christian.

**Comment by nnarhinen** [comment]
@blacktrash This is fixed by FP6, right?

**Comment by blacktrash** [comment]
Yes, `rtmp` or `rtmp.url` is mandatory with Flowplayer 6.
