### ISSUE TITLE
FlowPlayer subtitles not working with IE9 and IE10

### ISSUE THREAD

**Issue by wajeeha-khalid** [flowplayer/flowplayer#755]
Hi,
I am using track element to show subtitles with an .srt file (the format is quite similar to .vtt file). This works fine on chrome and IE11 but subtitles are not showing up on IE9 and IE10.
The code goes something like this:
![image](https://cloud.githubusercontent.com/assets/6745069/5609722/f06c5730-94c8-11e4-945d-0aee314c5f09.png)
I tried with external source URL for .srt file and also by placing the file locally (as in above coe screenshot) but nothing works.

Regards

**Comment by nnarhinen** [comment]
We can not do anything for this issue without the actual subtitle file. Please link to a _live_ page where the player misbehaves.
