### ISSUE TITLE
IE11: timeline not working / flickering when in iframe and native fullscreen mode

### ISSUE THREAD

**Issue by stefan-hausmann** [flowplayer/flowplayer#757]
just bought a flowplayer html5 license and encountered the following issue:

when using new IE11's native fullscreen mode from a flowplayer instance embedded within an iframe and going to fullscreen mode, the timeline is flickering heavily (progress bar goes to 100% width multiple times per second, then going back to the correct playback position), making it completely unusable because seeking in fullscreen mode doesn't work correctly.

Just try seeking in fullscreen mode in IE11 here:
http://demos.flowplayer.org/basics/iframe.html
to see the issue.

Can someone confirm this / has someone a quick solution for this?

Thanks!

**Comment by stefan-hausmann** [comment]
just found this - has this been regarded when implementing IE11 native fullscreen in flowplayer?

http://christophercurrie.github.io/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html
http://bugs.jquery.com/ticket/14903

**Comment by nnarhinen** [comment]
Thanks for the links. I can confirm this issue with IE11 on Win 8.1. Will take a look.

**Comment by bbbo** [comment]
confirmed on Win7 as well.

**Comment by nnarhinen** [comment]
Please try with http://demos.758f.flowplayer.me/basics/iframe.html

**Comment by stefan-hausmann** [comment]
is now working for me in IE11 / Win 8.1
thanks for bugfixing this!

**Comment by nnarhinen** [comment]
This will be available in next bugfix release.

**Comment by stefan-hausmann** [comment]
ok, thanks. Do you know when the next bugfix release will be released?
