### ISSUE TITLE
Exclude subtitles from generated cuepoints

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#760]
Makes sense. See: https://flowplayer.org/forum/#!/setup:subtitles-and-cuepoints
I'll provide a patch.
Drawback: The `subtitle` and `subtitleEnd` cuepoint props become reserved, albeit only in conjunction with `generate_cuepoints: true`.

**Comment by blacktrash** [comment]
@nnarhinen - here's a demo: http://flowplayer.blacktrash.org/fp5/thumbs.html

**Comment by nnarhinen** [comment]
How about adding a general 'visible': false parameter to the cuepoints? then we wouldn't generate more cross-dependency between cuepoints and subtitles.

**Comment by nnarhinen** [comment]
Also I think this will only go to FP6.

**Comment by blacktrash** [comment]
Do as you see fit, it was just a quick (and probably too dirty) proposal. With the _current_ structure subtitles look like a sub-form of cuepoints to me. And convenience offerings out of the box, like `generate_cuepoints` (the name is slightly misleading, as the cuepoints themselves are not generated, only their display) are bound to create "non-structural" situations.

**Comment by nnarhinen** [comment]
Yeah now subtitles depend on cuepoints. But if cuepoints are trying to figure out whether it's a subtitle or not, then it adds a dependency on the opposite direction too. Better to generalize. Maybe add a hidden: true or something property. Hard to choose what it should call.

**Comment by blacktrash** [comment]
As one may choose _any_ property for cuepoints, one might as well reserve the existing ones (`subtitle`, `subtitleEnd`)?
But there's no rush. Really, do what fits your intended architecture best.
