### ISSUE TITLE
flowplayer() bind cuepoint and ready event, in ready event  seek doesn't work!!

### ISSUE THREAD

**Issue by ytapple** [flowplayer/flowplayer#763]
this's my page 
$(document).ready(function(){
	$(".flowplayer").flowplayer({
                cuepoints: [5,10]
          });
	flowplayer().bind("cuepoint", function (e,api,cuepoint) {
		alert(cuepoint.time);
           });
	 flowplayer().bind("ready", function (e,api) {
		api.seek(1000);
            });
});

<div class="flowplayer" data-swf="flowplayer.swf" data-ratio="0.4167" >
      <video autoPlay>
         <source type="video/mp4" src="http://v.jinlanmeng.cn:8080/edu/season1/zhuguangwen-8dbg.mp4">
      </video>
   </div>

**Comment by nnarhinen** [comment]
As per our [contribution guidelines](https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md) please use the [free support forums](http://flowplayer.org/forum/) before opening an issue here. You also forgot to add a _link_ to a live example where you encounter the issue.

For what it is worth I can't reproduce this problem: http://jsfiddle.net/vawhcabh/
