### ISSUE TITLE
"Adobe Flash is disabled" on IE10 even when Flash is enabled

### ISSUE THREAD

**Issue by apaatsio** [flowplayer/flowplayer#765]
We have reports that some IE10 users are seeing the "Adobe Flash is disabled for this page, click player area to enable." error message even though they have Flash enabled.

I couldn't reproduce this myself so unfortunately I can't debug this more. I'm just writing this here in case that someone else is experiencing this also.

**Comment by nnarhinen** [comment]
Users might see this message also if it takes long to load the swf-file (over 1 second). We might adjust this timeout but from user perspective it does not prevent video playback if the swf file is loaded in less than 5 seconds after which the player will error out.
