### ISSUE TITLE
hls seeking: seeking state too short

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#766]
Often, especially when seeking by click on target position, the seeking state ends way before the target position is reached. Is this because the video tag fires `seeked` so early?
Demo long video with high buffer size is well suited to observe the problem: http://demos.flowplayer.org/basics/long.html

Aside: What does `support.hlsDuration` mean, and why does desktop Safari not support it (if I read the conditional correctly)?

**Comment by blacktrash** [comment]
For the aside: https://github.com/flowplayer/flowplayer/issues/271 (when I find things, it's too late ;-))

**Comment by nnarhinen** [comment]
Yes, this is because the video tag emits `seeked` immediately after click on HLS. This is such a corner case that I don't think it should be special cased.
