### ISSUE TITLE
Throwing "Cannot read property 'length' of undefined."

### ISSUE THREAD

**Issue by bzmwillemsen** [flowplayer/flowplayer#767]
```
TypeError: Cannot read property 'length' of undefined
  at grep (/dist/bower_components/jquery/dist/jquery.js:477:12)
  at pick (/dist/flowplayer/flowplayer.js.src.js:709:26)
  at apply (/dist/flowplayer/flowplayer.js.src.js:232:35)
  at apply (/dist/flowplayer/flowplayer.js.src.js:2018:49)
```

I'm on flowplayer.js version 5.4.6 and I've recently started getting this error thrown a lot by clients. At reason you can think of that flowplayer would be trying to pass `$.grep()` a value of `null`?

This is the section in the source that this is happening in:
```
flowplayer.engine.flash = function(player, root) {
   var conf = player.conf,
      video = player.video,
      callbackId,
      objectTag,
      api;
   var engine = {
      pick: function(sources) {
         if (flowplayer.support.flashVideo) {
            // always pick video/flash first

#Error is happening here!!!!!
            var flash = $.grep(sources, function(source) { return source.type == 'flash'; })[0]; 

            if (flash) return flash;
            for (var i = 0, source; i < sources.length; i++) {
               source = sources[i];
               if (/mp4|flv/.test(source.type)) return source;
            }
         }
      }
```

**Comment by nnarhinen** [comment]
As per our [Contribution guidelines](https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md) always link to a live page where the misbehavior is apparent.

Also as a general advice always try with the latest stable distribution.

You also failed to specify the browser/OS combinations where the problem exist.

If the problem still persists with the latest stable version of Flowplayer, you can re-open this issue with a link to a stripped down minimal reproducable example page.
