### ISSUE TITLE
Player failed to load when opened in new tab in Safari browser

### ISSUE THREAD

**Issue by slavafomin** [flowplayer/flowplayer#768]
Hello!

We are using commercial version of FP `5.5.2` on our website — [video.oum.ru](http://www.en.video.oum.ru/).

Lately, our visitors started to experience a very strange issue with it in Safari browser: when you open the video page in a new tab — the FP fails to load (poster is not shown, endless loading animation is shown instead). However, if you navigate to the video page directly in the same tab ­— it loads just fine. There is no such issue in Chrome or FF.

I've created a minimal setup to demonstrate the issue here:
http://fp.video.oum.ru/safari-issue/index.html

I've also tried to investigate the problem, but I wasn't being able to open Safari developer tools in the new tab. I can only open it after page is loaded (crazy).

As a workaround we will try to put our player inside of an `iframe`. I think this will prevent this issue from happening.

The bug is noticed in *Safari* `8.0.2 (10600.2.5)` under control of *Mac OS X Yosemite* `10.10.1`.

I wish I had more details.

Could you elaborate please? Thank you!

**Comment by nnarhinen** [comment]
I can confirm this behavior.

Can you try changing the `preload` attribute to something else than `metadata` (try `none` for instance)?

If I open the page in new tab and open developer tools and type into the console `$('video')[0].load()` the player initializes. Also the `readyState` property of the video tag in the 'hanging' state seems to be `1` which means `NETWORK_IDLE`. That's why I think safari handles network differently when new tabs are opened.

**Comment by slavafomin** [comment]
Hello @nnarhinen! Thank you for your reply.

We've tried to put player into iframe, but it didn't helped. Also, I've managed to better understand the conditions in which bug occurs. It happens only when the tab is not active, i.e. in background. I've updated the demo [here](http://fp.video.oum.ru/safari-issue/index.html) — just press the button then switch to another opened tab. When you return to the tab, the player will not work.

It looks like Safari somehow behaves differently when user is not watching.

What do you think will be the best way to work around this issue for now? Are you planning to fix it in the library itself somehow? Thank you!

**Comment by slavafomin** [comment]
Yep, it's working with `preload="none"`. I think we will use this as a workaround for now then.

I've also added this case to the demo page.

**Comment by slavafomin** [comment]
### Working workaround

I've decided to opt for [`splash`](https://flowplayer.org/docs/setup.html#splash) mode with combination of `preload="none"` in order to mitigate different cross-browser issues. It helped.

---

@nnarhinen thank you for your suggestion! Cheers!

**Comment by nnarhinen** [comment]
The behavior of preload (and the configurability of it) will change for version 6.0 most likely (due to inconsistent behavior across browsers). We can leave this issue open until that. Going with splash setups most likely is best for your use case now.
