### ISSUE TITLE
Controls while splash

### ISSUE THREAD

**Issue by landsem** [flowplayer/flowplayer#769]
Possibility to display controls with splash screen.

**Comment by blacktrash** [comment]
imho this does not make much sense from the user-perspective: one of the purposes of a splash setup is not to preload the video, so you would get extra controls without meaning: no duration available, no video location for embedding ... so, in fact the play button indicates exactly the state.
With poster (implies preloading) it make more sense and we have a demo for that: http://demos.flowplayer.org/lookandfeel/postercontrols.html

:-1: for the feature from me.

**Comment by nnarhinen** [comment]
It would be exactly against the idea of a splash setup.
