### ISSUE TITLE
RTMP live stream autoplays and cannot be paused

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#775]
http://demos.flowplayer.org/basics/live.html in a browser which cannot play HLS.
Workaround: splash setup. Strangely enough even pausing then works.

**Comment by blacktrash** [comment]
Also happens with a first frame setup.
Note that this does not happen with _all_ live streams. Some actually work.

**Comment by nnarhinen** [comment]
Is this issue still present / relevant with FP6?

**Comment by blacktrash** [comment]
Confirming: Haven't found a way to reproduce.

**Comment by blacktrash** [comment]
I completely missed the RTMP thing, sorry. Yes, the problem is still there: http://flowplayer.blacktrash.org/fp6/live-rtmp.html

**Comment by nnarhinen** [comment]
Enabling debug on http://flowplayer.blacktrash.org/fp6/live-rtmp.html (`window.localStorage.flowplayerDebug = true`) I can see that it connects with rtmp and stops on first frame.

After a while it also connects with rtmpt and starts playing that.

**Comment by nnarhinen** [comment]
@anssip please take a look, this rtmp/rtmpt (also #748 even though it's a different problem) causes some confusion now it seems.

**Comment by nnarhinen** [comment]
@blacktrash can you make another demo (leave that for @anssip to debug) with rtmpt disabled to see if my initial guess is right.

**Comment by blacktrash** [comment]
@nnarhinen - your initial guess is indeed correct: http://flowplayer.blacktrash.org/fp6/live-rtmp-nortmpt.html
@anssip - http://flowplayer.blacktrash.org/fp6/live-rtmp.html no has debug enabled, I left it out initially to make the error easier to spot.

**Comment by anssip** [comment]
@blacktrash should be fixed in this http://demos.853f.flowplayer.me

**Comment by blacktrash** [comment]
Behaviour fix confirmed :+1: - not 100% sure about tunneling.
