### ISSUE TITLE
Support multi-channel of audio 

### ISSUE THREAD

**Issue by litvinok** [flowplayer/flowplayer#776]
Hello everyone.

I have some video file with two or many audio channels (different languages for example). I would like have ability to choice need channel. 

I believe that it will be very cool feature, I don't know any other flash player which supports it.
HTML5 video player already has specification for this feature, but at this moment it implemented only in the IE11.

I suggest to develop plugin or include this feature in the flowplayer core.

Thank you.

**Comment by blacktrash** [comment]
As in your other report, please use the Flowplayer Flash bug tracker: https://github.com/flowplayer/flash/issues
Technically this would have to be confined to Adobe httpstreaming I think, i.e. the httpstreaming plugin.

**Comment by litvinok** [comment]
Ok, I'll duplicate this issue to flowplayer/flash.
But how a streaming functionality affects a simply video playback?
And usually streaming server have ability to change current audio channel on a fly. But I not sure about all solutions.
