### ISSUE TITLE
Support multi-channel of subtitles

### ISSUE THREAD

**Issue by litvinok** [flowplayer/flowplayer#777]
We already have ability to show subtitles with using the content plugin.
But when we have one or more subtitles on different languages we should have wrapper which will switch them.

I would suggest additional control element which will make able to switch between few subtitles like out-of-box solution. 

This solution may include ability to use built-in to video subtitles as well.

**Comment by blacktrash** [comment]
content plugin? - You can find the bug tracker for Flowplayer Flash here: https://github.com/flowplayer/flash/issues
For embedded captions there is already a solution out of the box: http://flash.flowplayer.org/plugins/flash/captions.html#embedded-captions-example

**Comment by litvinok** [comment]
Ok, I'll duplicate this issue to ``flowplayer/flash``.
I've looked ``embedded-captions-example`` plugin but I've meant http://flash.flowplayer.org/plugins/flash/captions.html#mp4-embedded-captions-example and this solution is a crutch. How do you sell commercial license with functionality which customer need implement?
I want have minimum of wrappers, crutch and resulting in minimum of bugs.
