### ISSUE TITLE
issues with full rtmp urls

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#779]
Collecting these here.
Sample: http://flowplayer.blacktrash.org/fp5/rtmp.html
1. WebKit browsers complain about invalid URL scheme on load (Chrome regardless of PepperFlash enabled or not)
2. Fullscreen toggle starts playback from beginning in WebKit browsers because the flash reset does not handle that situation - #740, #752 - probably fixed in dev by https://github.com/flowplayer/flowplayer/commit/b4d6b3b4e14a49a4af63e3f6530f9ee63f204f6f
3. api.load(sources) hangs - https://flowplayer.org/forum/#!/setup:loading-rtmp-streams-throug and sample - EDIT: mistake in sample, this actually works.

See also: https://github.com/flowplayer/flowplayer/issues/741

**Comment by nnarhinen** [comment]
> 1. WebKit browsers complain about invalid URL scheme on load (Chrome regardless of PepperFlash enabled or not)

this comes from DOM parser (the javascript initialization method creates a temporary video tag for source parcing).

**Comment by blacktrash** [comment]
And now for the real problem: full RTMP urls do not work if the file is in a subfolder on the rtmp server, regardless of the installation method.
http://flowplayer.blacktrash.org/fp5/rtmp.html

**Comment by blacktrash** [comment]
This will be fixed in Flowplayer 6 by making the `rtmp` option available on a per clip basis.
Full RTMP urls are not supported.
