### ISSUE TITLE
[feature request] Allow completely destroy player object, removing it from instances

### ISSUE THREAD

**Issue by 39dotyt** [flowplayer/flowplayer#782]
It will be very helpful for environments with lots of videos opened and closed simultaneously to have an ability to completely destroy player object (not just unload it).

**Comment by blacktrash** [comment]
Version 6 will provide a `shutdown` method.

**Comment by blacktrash** [comment]
@39dotyt - "lots of videos opened and closed simultaneously" refers to videos, not players, which begs the question why you're not using a splash setup?

**Comment by 39dotyt** [comment]
@blacktrash, i mean in multiple players.

**Comment by 39dotyt** [comment]
@blacktrash what is the approximate version 6 release date?

**Comment by nnarhinen** [comment]
FP6 is released.
