### ISSUE TITLE
Flowplayer will not resume in an iframe in IOS Safari

### ISSUE THREAD

**Issue by ufucuk** [flowplayer/flowplayer#785]
it is really easy to reproduce this bug, visit http://demos.flowplayer.org/basics/iframe.html in IOS 8 Safari browser, start playing the video then pause, wait until control bar minifies then tap on play button over the video element, it will go fullscreen as paused and to resume user has to tap once more on quick time.

**Comment by nnarhinen** [comment]
Not reproducable anymore.
