### ISSUE TITLE
controlbar logo has too much empty space to it's right

### ISSUE THREAD

**Issue by anssip** [flowplayer/flowplayer#788]
Flowplayer-logo in controlbar has too much empty space to it's right. There's less margin on the left,  should be the same size both left and right.

**Comment by nnarhinen** [comment]
Screenshot please

**Comment by blacktrash** [comment]
![brand_not_centered](https://cloud.githubusercontent.com/assets/168338/7366921/85632a44-ed93-11e4-9de1-830f11a98c19.jpg)
