### ISSUE TITLE
Duration UI element dropped down

### ISSUE THREAD

**Issue by anssip** [flowplayer/flowplayer#790]
the duration value has dropped below the controlbar here: http://demos.711f.flowplayer.me/lookandfeel/controls-only.html   

Screenshot: http://d.pr/i/1clDV

**Comment by anssip** [comment]
time and duration values also look strange in these: 
	http://demos.711f.flowplayer.me/lookandfeel/finish.html
	http://demos.711f.flowplayer.me/scripting/recover.html

**Comment by nnarhinen** [comment]
@blacktrash as those are very custom pages, please take a look if it indeed is a player bug.

**Comment by blacktrash** [comment]
Both demos only customize an element inside the player which does not intefere with the controls afaics, it's too small.
It looks like it becomes more difficult to add custom elements. No idea what could be causing this.

**Comment by blacktrash** [comment]
With the below thing at http://demos.711f.flowplayer.me/scripting/recover.html I have no explanation either. Only the cursor is changed for those elements, no positioning.

**Comment by blacktrash** [comment]
Assigning to @nnarhinen for fixed-controls.
