### ISSUE TITLE
Canvas logo overlaps controlbar

### ISSUE THREAD

**Issue by anssip** [flowplayer/flowplayer#791]
The "canvas logo" is on top of the controlbar. Should always show above it. For example here: http://demos.711f.flowplayer.me/scripting/dynamic.html

**Comment by blacktrash** [comment]
That is one of the issues with the new functional controlbar: it sits higher into the canvas, also a problem with fixed controls: https://github.com/flowplayer/work/issues/1027#issuecomment-87589755

**Comment by blacktrash** [comment]
imho the controlbar _must_ be over the canvas, that's why it's a canvas.

**Comment by anssip** [comment]
I think we just need to move the canvas logo upwards so that it does not get hidden below the controlbar.

**Comment by blacktrash** [comment]
Affects drive watermarks as well.
