### ISSUE TITLE
Flowplayer has no ability to specify flashvars and/or optimizeBuffering and minContinuousPlaybackTime options

### ISSUE THREAD

**Issue by 39dotyt** [flowplayer/flowplayer#794]
It's maybe required in some cases to specify optimizeBuffer and minContinuousPlaybackTime params to flash flowplayer backend. It's will be very useful if FlowPlayer will allow this through configuration option.

**Comment by bbbo** [comment]
Niklas, didn't you create a generic way to pass arguments to the Flash engine?

**Comment by anssip** [comment]
There is the possibility to specify [bufferTime](https://flowplayer.org/docs/setup.html#config-options). What other options you would like to see added, @39dotyt ?

**Comment by 39dotyt** [comment]
@anssip Hm. Now I understand that I may be confused by the flash media playback docs and examples. I don't now, what exactly you are using, but [it](http://jodieorourke.com/view.php?id=139&blog=news) has few additional options, which also controls the buffer time. Sorry for the confusion.

My exact problem is when FlowPlayer (playing RTMP) receives two or three frames (with I-frame first) hi does nothing, seems like it waits for other frames. Seems that "optimizeBuffer=false" (whatever it does) may resolve this issue.

**Comment by 39dotyt** [comment]
According to [NetStream documentation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/NetStream.html) it's needed to reduce liveDelay (read-only property indicating the number of seconds of data in the subscribing stream's buffer in live (unbuffered) mode.).

May be a good idea to allow specifying next NetStream properties:

* backBufferLength/Time;
* inBufferSeek;
* useJitterBuffer.

**Comment by nnarhinen** [comment]
Unless there is a real world scenario where this is a problem we will not add these.
