### ISSUE TITLE
Mistake in the documentation

### ISSUE THREAD

**Issue by 39dotyt** [flowplayer/flowplayer#795]
> var bufferTime:Number = conf.hasOwnProperty("bufferTime") ? conf.bufferTime : 3;

https://github.com/flowplayer/flowplayer/blob/master/lib/as/Flowplayer.as#L351

seems that default bufferTime value is 3 but [documentation](https://flowplayer.org/docs/setup.html#core-options) says that it is 0.1.

Of course, it's true if master is the actual release :-)

**Comment by blacktrash** [comment]
@39dotyt - thanks for spotting this.
Will be corrected in our new site docs when version 6 comes out.
