### ISSUE TITLE
RTMP fullscreen trigger reconnect to invalid URL

### ISSUE THREAD

**Issue by kielstr** [flowplayer/flowplayer#797]
When switching to fullscreen using the flash engine the player generates a file not found error. I believe this is because 
of code within the flash action script method rtmpUrls and the source path containing a resource within a directory.

Managed to reproduce the error with the following node.js hack.

#!/usr/bin/env node

var url='rtmp://media3.au.cpdlive.com:80/cahoot-public/mp4:testing/BoomCrashOpera-OnionSkin.mp4';

var lastIndex = url.lastIndexOf("/");

console.log(url.substr(0, lastIndex));
console.log(url.substr(lastIndex+1));

$ ./lastindexof.js 
rtmp://media3.au.cpdlive.com:80/cahoot-public/mp4:testing
BoomCrashOpera-OnionSkin.mp4

can provide a public page and links to streems if needed.

**Comment by nnarhinen** [comment]
On which player version are you seeing this? We released 6.0.0 yesterday and it should not behave like that anymore in fullscreen toggles.

**Comment by kielstr** [comment]
> On 22 May 2015, at 3:30 pm, Niklas Närhinen <notifications@github.com> wrote:
> 
> On which player version are you seeing this? We released 6.0.0 yesterday and it should not behave like that anymore in fullscreen toggles.
> 
> 

I did notice the release of version 6 however the bug related to fullscreen was a bit vague. We are currently on version 5.5.2. We’ll upgrade and see how that goes and report back.

**Comment by kielstr** [comment]
Upgrading has resolved this issue. Should the older version be patched or does it make good business sense to upgrade all users pre 6v?

**Comment by nnarhinen** [comment]
The change cannot be easily backported to 5.x codebase.
