### ISSUE TITLE
Fonts hitting CORS issue for FP6

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#799]
It might make it easier on everyone if they were embedded into the CSS. There is an option to do this. 

I've used this https://icomoon.io/app/#/select as a generator. 

Your CORS wildcard rule is obviously incorrect and therefore nothing is loading.

**Comment by nnarhinen** [comment]
The double CORS rule was because of an issue with MaxCDN. The issue should now be resolved. Will think about font embedding to CSS later.
