### ISSUE TITLE
Acessing flowplayer internal libraries

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#800]
bean = require('bean'),

none of this is accessible out of the player and within global functions due to being wrapped within the file therefore not extensible ? 

Is there an undocumented feature required ?

**Comment by nnarhinen** [comment]
I'm not completely sure why you would need to access the eventing library from the outside, but for plugin developers (the plugin API not that well documented yet) we have exposed the possibility to use some of the internal libraries:

https://github.com/flowplayer/flowplayer/blob/2e757bfbd84af4ef8682a8e5a6179e27d323a1c6/lib/flowplayer.js#L134-L137

You can access them by `flowplayer.bean`, `flowplayer.common` and `flowplayer.extend` by now. Bear in mind these are currently undocumented and could in theory be changed or removed until properly documented in the upcoming Plugin API documentation.

**Comment by danrossi** [comment]
You've taken out one library and replaced with another. It would be natural to move to that instead. 

This is what I needed

common = flowplayer.common,

**Comment by danrossi** [comment]
ClassList is missing. How to access ? 

flowplayer.common and flowplayer.bean both accessible.
