### ISSUE TITLE
Simulated fullscreen - players pinned to top of window

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#802]
Compare bottom player on page:
http://demos.flowplayer.org/basics/multiple.html (fp6 broken)
http://demos.flowplayer.org/v5/basics/multiple.html (fp5 works)

**Comment by nnarhinen** [comment]
Should be fine now, also on IE9 etc

**Comment by blacktrash** [comment]
Confirmed - @anssip + @bbbo should double check.

**Comment by bbbo** [comment]
fixed for IE9
