### ISSUE TITLE
splash option: works only if no container background-color is given

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#803]
Bug or feature - if the latter, it has to be documented.

Feels like a bug because:
- poster: "//myserver/splash.jpg" is not affected by CSS background-color for the container (surprising behavior)
-  a background-color is handy because images take longer to load

Could be worked around with wrapper element.

**Comment by nnarhinen** [comment]
```html
<div class="flowplayer" style="background-image: url('img1.jpg')" data-poster="img2.jpg" data-splash="img3.jpg">
  <video>...</video>
</div>
```

What is the desired result?

**Comment by blacktrash** [comment]
I haven't considered mental setups yet ;-)
Misunderstanding: I wasn't talking about video loading, but page load.
I had a "normal" splash setup in mind, where it's often good to have both background-color and background-image set, so the player area is marked until the image is loaded. That was all.
Your example is unsupported because of conflicting instructions, I'd say.

**Comment by blacktrash** [comment]
So: with background-color set via CSS + splash option either true or an img url, I would expect a splash setup like with both background-color and background-image + splash: true or is-splash.

**Comment by nnarhinen** [comment]
Ok,
so: if splash explicitely set to string (`data-splash="img2.jpg"`)
 * ignore poster setup
 * always use img2.jpg as splash

**Comment by blacktrash** [comment]
I don't understand? where's the poster setup in this rather reasonable install:
```html
<div class="flowplayer" style="background-color:#bbb;" data-splash="img.jpg">
```
should behave like:
```html
<div class="flowplayer" style="background-color:#bbb; background-image:url(img.jpg);" data-splash="true">
```
We can decide later what happens when there are conflicting explicit instructions. But if it says splash and not poster, then it's splash.

**Comment by nnarhinen** [comment]
cool

**Comment by nnarhinen** [comment]
Should be fixed on dev branch

**Comment by blacktrash** [comment]
Confirmed.
