### ISSUE TITLE
iphone: does not resume after return from native fullscreen

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#806]
This is a behaviour change compared to fp5. Intentional?
https://flowplayer.org/forum/#!/setup:iphone-resume-playing-flo

It looks like bug because when you click again, then the skin appears intermittently with the playhead on the previous position.

**Comment by nnarhinen** [comment]
@blacktrash see #530

**Comment by blacktrash** [comment]
Can you differentiate between "done" and fullscreen exit? That would be ideal:
"Done": go into splash state (which should exclude the erroneous timeline display at restart)
"fs exit": as before.

Otherwise attempt to get a clean splash and unloaded state: when restarting the playhead which is shortly visible should be at 0 again.

Maybe hide all control elements completely where inline playback is not supported? They are only distracting as you can't use them anyway.

**Comment by nnarhinen** [comment]
I'm not completely sure I understand (I'm no iPhone user). What is the difference between done and fullscreen exit?

**Comment by nnarhinen** [comment]
At least in the iPhone simulator they do exactly the same thing with a plain video tag - exit from fullscreen and pause the player.

**Comment by nnarhinen** [comment]
![image](https://cloud.githubusercontent.com/assets/265438/7815128/34fbbb0a-03cf-11e5-9432-484e943148bc.png)

If this (the red area) is what you mean with fullscreen exit.

**Comment by blacktrash** [comment]
Yes.
In Flowplayer terms: "Done" corresponds to the close button `is-closeable` and the red area is the fullscreen exit button (looks suspiciosly similar ;-))
So if the inline Flowplayer behaviour can be mimicked ...

(personally I'd be fine or even would prefer a clean splash state for both, no fp controls appearing - you can't make it right for everyone)

**Comment by nnarhinen** [comment]
Yeah well event-wise they do just the same: fire `webkitendfullscreen`. So either we do nothing or we fire `unload` (and I have to fix unload to actually clean the buffer etc).

**Comment by nnarhinen** [comment]
So either we revert the "fix" to #530 or fix it properly :)

**Comment by blacktrash** [comment]
I'm not sure what the majority of users want.

My personal preference is:
- current behaviour
- no noop flowplayer widgets ever appearing - the only Flowplayer UI is the play button.

As they say: YMMV.

**Comment by nnarhinen** [comment]
I'm not adding any new modifier classes for hiding the UI widgets for devices not capable of showing inline video, can be offered as a "FAQ entry" later if needed. I just made the timeline to reset to zero when `unload` triggered.

**Comment by blacktrash** [comment]
:+1:

**Comment by nnarhinen** [comment]
Should be fixed now by setting timeline to zero.

**Comment by blacktrash** [comment]
But this breaks `native_fullscreen` for iPad now or I did not test properly before.
On iPad native_fullscreen:
- full screen exit during playback: playback continues with play button overlayed
- done during playback: paused state, resume starts from beginning
- fullscreen exit _and_ done in paused state: resume starts from begining

**Comment by nnarhinen** [comment]
Should behave better now with the iPad.

**Comment by blacktrash** [comment]
https://github.com/flowplayer/flowplayer/commit/4202fb01334bfb04f83d791afc3982051759cf0e fixes that:
- full screen exit during playback: continues to play
- done during playback: paused state, resume works
- fullscreen exit _and_ done in paused state: paused state, resum works

Makes all sense to me :+1:
