### ISSUE TITLE
IE11: time and timeline do not update

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#807]
https://flowplayer.org/forum/#!/drive_discussion:60-timeline-doesnt-updat

**Comment by nnarhinen** [comment]
@bbbo Can you test with real IE11 on http://demos.dev94.flowplayer.us

It works on browserstack now at least.

**Comment by bbbo** [comment]
confirming the fix for IE9. 10 and 11 on Win 7.

**Comment by bbbo** [comment]
confirmed for Win 8.1 as well
