### ISSUE TITLE
functional + playful fixed-controls: disappear in fullscreen

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#808]
Only time and duration/remaining visible.
http://flowplayer.org/demos/

**Comment by blacktrash** [comment]
This line is overridden somewhere later:
```
.is-fullscreen.flowplayer.fixed-controls .fp-controls{bottom:0}
```
When I add it after loading the skin it works.

**Comment by nnarhinen** [comment]
Should be fine now: http://dev94.flowplayer.us/standalone/skins/functional-fixed-controls.html

**Comment by blacktrash** [comment]
:+1:

**Comment by anssip** [comment]
The close X button disappears in fullscreen

**Comment by blacktrash** [comment]
Because you cannot unload from fullscreen, only stop.
