### ISSUE TITLE
HLS : lag issue with Firefox

### ISSUE THREAD

**Issue by DrySs** [flowplayer/flowplayer#810]
Hi there,

Please take a look at this HLS stream (working on CloudFront with Signed Cookies):
http://dev.dryss.com/signedcookiesfp/

On desktop with Chrome/Opera/IE, I can play video fullscreen without any problem.

But with Firefox, while fullscreen is enabled, I have some kind of "lag-time", I mean the image is like freezing every second...

Any idea of why I have this behavior (only with Firefox)?

Thanks

**Comment by blacktrash** [comment]
Please set `debug: true` in your configuration.

Firefox Flash performance is always a problem. Try `wmode: "opaque"`, or, at least for testing, `wmode: "direct"` to see whether this improves things.

We cannot diagnose the HLS streams themselves obviously.

**Comment by nnarhinen** [comment]
Doing wild guesses here.. Does your monitor have a 16:9 aspect ratio (as the video has)?

I mean, do you get the gray areas above and belove the video or does the video fill your whole screen?

If it does fill the whole screen, it might be the overlaid timeline updating on top of the flash object that makes it freeze every one second. You can try to add a CSS rule like:

```css
.flowplayer.is-fullscreen.is-mouseout .fp-timeline {
  display: none !important;
}
```

to see if hiding the timeline in fullscreen will help performance.

**Comment by DrySs** [comment]
Thanks for your replies :)
@blacktrash 

Just added "debug: true" config & wmode: "opaque" mode.

@nnarhinen 

Yes, I'm in 16:9.

Added CSS rules, but it does not change anything.

I just noticed that it affects playing even if *not* in fullscreen.

**Comment by blacktrash** [comment]
I'm afraid that is just Firefox' Flash performance. Even with a pure Flash player you will notice this (especially with other heavily loaded windows open), although admittedly _somewhat_ to a lesser extent.

**Comment by DrySs** [comment]
So... what should I do?

Forbid all Firefox users to play HLS stream ?? ô.O)

**Comment by blacktrash** [comment]
You can try:
```js
// IE does not handle overlayed control elements with direct wmode
wmode: /MSIE|Trident\/7/i.test(navigator.userAgent) ? "opaque" : "direct"
```
like at http://demos.flowplayer.org/basics/long.html

But also check thoroughly that your video is not bound to stutter even in html5 video, this one for instance is in danger of doing so: http://demos.flowplayer.org/lookandfeel/loading-custom.html even over fast connections.

**Comment by DrySs** [comment]
@blacktrash 

How could I try video in plain video HTML5 tag as Firefox does not handle HLS mimetype?
I cannot play video stream without any Flash player in Firefox.

On other browsers, not problem, as I said.

Is there a way to know if the problem is linked to video stream?

Thanks

**Comment by blacktrash** [comment]
@DrySs - the point I was trying to make that some videos border on stuttering in html5 video in _any_ browser, so if you create a HLS stream with similar transcoding settings (and/or not enough resolutions) this will make the problem in Flash HLS even more noticeable in Firefox. Furthermore variant playlists often declare the wrong BANDWIDTH (instead of peak bit rate, they announce a roughly calculated average bit rate, which might influence flash hls).  You stream is not publicly accessible, so we can't investigate, but I can see delays in Mac Safari as well with the typical candidates, for instance pan shots (to the trained eye those are very rarely entirely smooth over the wire).

btw, currently you botched up your installation because:
1. you are mixing automatic and manual installation methods
2. you are trying to install manually without the document being ready

**Comment by DrySs** [comment]
@blacktrash 

Just updated my page with on manual installation and a dom ready waiting:

http://dev.dryss.com/signedcookiesfp/

But now, player is not working anymore on Firefox (OK on Chrome), any idea why?

FIY, here is the exact HLS used for this example:

- http://dev.dryss.com/signedcookiesfp/hls/manifest.m3u8
- http://dev.dryss.com/signedcookiesfp/hls/hls_400k.m3u8
- http://dev.dryss.com/signedcookiesfp/hls/hls_600k.m3u8
- http://dev.dryss.com/signedcookiesfp/hls/hls_35m.m3u8
- http://dev.dryss.com/signedcookiesfp/hls/hls_5m.m3u8

**Comment by blacktrash** [comment]
Can you please use the current 6.0.1 release?

And the TS files are cannot be found:
```sh
$ curl -I http://dev.dryss.com/signedcookiesfp/hls/video00252.ts
HTTP/1.1 404 Not Found
Date: Mon, 01 Jun 2015 14:44:55 GMT
Server: Apache/2.2.22 (Debian) DAV/2 SVN/1.6.17 PHP/5.4.39-0+deb7u2 mod_ssl/2.2.22 OpenSSL/1.0.1e
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1
```

**Comment by blacktrash** [comment]
Your sample works now (maybe crossdomain policy was missing before), but I sometimes get artifacts which point to some encoding glitch imho.

**Comment by DrySs** [comment]
@blacktrash 

I put first & last TS file readable here: 

http://dev.dryss.com/signedcookiesfp/hls/video00000.ts
http://dev.dryss.com/signedcookiesfp/hls/video00252.ts

I reverted FP to 6.0.1.

About HLS encoding, we are using AWS Elastic Transcoder, what should we do more to no get artifacts?

**Comment by DrySs** [comment]
Notice that this implementation is not working Firefox:

```
// IE does not handle overlayed control elements with direct wmode
wmode: /MSIE|Trident\/7/i.test(navigator.userAgent) ? "opaque" : "direct"
```

I have a black screen.

**Comment by blacktrash** [comment]
> I put first & last TS file readable here: 
> 
> http://dev.dryss.com/signedcookiesfp/hls/video00000.ts
> http://dev.dryss.com/signedcookiesfp/hls/video00252.ts

2 TS files will not help for diagnosis, you have to make the whole kaboodle available.

> I reverted FP to 6.0.1.
> 
> About HLS encoding, we are using AWS Elastic Transcoder, what should we do more to no get artifacts?

I really can't say, there's a reason we are offering Flowplayer Drive ;-)

Highly speculative answer: some overoptimization in the segmenter - even Apple's segmenter (as long as they shipped it) sacrificed precision for lowering muxing overhead, for instance in some cases it got the duration wrong, quite noticeable actually.

I'm sorry, this is not the place to discuss HLS transcoding. Please use the AWS support for advice on their transcoding service.

**Comment by blacktrash** [comment]
> Notice that this implementation is not working Firefox:
> 
> ```
> // IE does not handle overlayed control elements with direct wmode
> wmode: /MSIE|Trident\/7/i.test(navigator.userAgent) ? "opaque" : "direct"
> ```
> 
> I have a black screen.

Not here. Looks like an improvement. Which Firefox version? What platform? Do you have any addons enabled?

Do you experience that at http://demos.flowplayer.org/basics/long.html as well?

**Comment by DrySs** [comment]
Firefox 38.0.1 Win 8.1 (addons: Firebug, ColorZilla, MeasureIt, Page Speed, Web Devloper, YSlow...)

http://demos.flowplayer.org/basics/long.html is working on Firefox.

**Comment by DrySs** [comment]
![image](https://cloud.githubusercontent.com/assets/230791/7932472/cfd1840e-0918-11e5-87a0-c033e51abe32.png)

**Comment by DrySs** [comment]
Ok it's finally working after 10-15sc loading with black screen.
But I don't have fullscreen button anymore to reproduce the lag.

BUT, with this settings, playing seems **really** more fluid, no more big lags...

**Comment by blacktrash** [comment]
You have to thoroughly purge the browser caches when (re)testing Flash stuff.
I see the fullscreen button at http://dev.dryss.com/signedcookiesfp/ (although it still loads the adhoc build) - but you can also hit "f" while hovering over the player area.

**Comment by DrySs** [comment]
Even after purge the browser cache (note that my cache browser is disabled by default for dev env), is still not have any buttons displayed:

![image](https://cloud.githubusercontent.com/assets/230791/7934241/deee536a-0925-11e5-8766-529da4f55e37.png)

Notice that press "f" key does not work too.
Indeed, it works for fullscreen before I play video, and then when video starts to play, fullscreen automatically close and "f" key does not work any more.

**Comment by blacktrash** [comment]
- please load the 6.0.1 release, also the skin, make that clear by loading them from //releases.flowplayer.org/6.0.1/
- which Firefox version? which platform?
- did you really disable all addons?
- same problem at  http://demos.flowplayer.org/basics/long.html ?
- to purge cache you sometimes have to close the page, purge cache, quit browser, restart, revisit page with modern browsers

**Comment by DrySs** [comment]
- 6.0.1 is already loaded and cleared
- Firefox 38.0.1 on Windows 8.1
- Disabled all addons, no change
- Yes, same issue on http://demos.flowplayer.org/basics/long.html
- cache purged, page closed, restarted browser and refreshed pages, no change

**Comment by blacktrash** [comment]
A colleague with Windows FF will check.
Not http://dev.dryss.com/signedcookiesfp/ though, which still uses the adhoc assets, but http://demos.flowplayer.org/basics/long.html

**Comment by blacktrash** [comment]
Please also give your Flash version (there is the odd buggy one) in FF.

**Comment by DrySs** [comment]
Shockwave Flash 17.0.0.169

**Comment by blacktrash** [comment]
Yes. Confirmed by a Windows colleague. Bummer :-(
wmode opaque is the best you'll get then - at least with that browser and Flash version; works fine in Mac FF.
