### ISSUE TITLE
Muted option does not work

### ISSUE THREAD

**Issue by DrySs** [flowplayer/flowplayer#811]
While I try to setup FlowPlayer (after an ajax request) with "muted" option at true, I still have sound level enabled:

http://vod2.dryss.com/w/series/breaking-bad/video-player.html

**Comment by DrySs** [comment]
Another strange behavior I got with muted option:

![image](https://cloud.githubusercontent.com/assets/230791/7869410/dd60fed6-0582-11e5-9586-4575bcc0cf49.png)

As you can see, sound icone is disabled, but sound volume is still 100%. And sound is not muted...
How is this possible?

Thanks,
Philippe

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/ and the assets there have this issue fixed and it will be available in the next release

**Comment by ahexdev1** [comment]
@nnarhinen I m still facing this issue, im using new version of flowplayer.
flowplayer({
       cuepoints: $scope.cueUniqueArray,
       key: '$423987114027190',
       logo: '/img/logo_244x45.png',
       swf: '//releases.flowplayer.org/6.0.5/flowplayer.swf',
       embed: true
});
the above code is were you can see im using new version of flowplayer.swf.

**Comment by blacktrash** [comment]
@ahexdev1 - I don't see the `muted` option in your code? - also the swf version does not indicate the flowplayer.js version you're using.
Usual mantra: link to a *minimal* sample page demonstrating the problem, please.

**Comment by nnarhinen** [comment]
also what does that code even do? When using javascript initialization you should give the container div as first argument: `flowplayer('#my-player', { ... conf });`
