### ISSUE TITLE
Any plans to publish as an NPM module

### ISSUE THREAD

**Issue by thanpolas** [flowplayer/flowplayer#814]
I noticed with the new v6 release that flowplayer is now using CJS for dependency management.

Most of today's frontend applications are using CJS so it would be cool to be able to install and require Flowplayer as an NPM module.

Right now, I am having issues loading 6.0, in my bootstrap file i require the `flowplayer.js` file however browserify errors with:

```
>> Error: Cannot find module '../common' from '/[...]/app/front/static/vendor/flowplayer'
```

**Comment by nnarhinen** [comment]
Yes, the next release will also be on NPM.

For now you can require the flowplayer.min.js file, it should be requirable directly from browserify.

**Comment by nnarhinen** [comment]
https://www.npmjs.com/package/browserify-derequire most likely this is needed to make the bundle requireable

**Comment by nnarhinen** [comment]
6.0.3 is published as https://www.npmjs.com/package/flowplayer

**Comment by thanpolas** [comment]
awesome!! Thanks @nnarhinen!
