### ISSUE TITLE
HTML5 Video not found

### ISSUE THREAD

**Issue by anandrajana** [flowplayer/flowplayer#815]
I'm getting this issue on our live site when I click to play the video. This is reproducible sometimes on mobile devices and web browsers. Below is the live site link.

 http://press.kia.com/eu/videos/products/soul%202014/

**Comment by blacktrash** [comment]
Please read the guidelines for submitting bugs: https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md - first turn to our public forum https://flowplayer.org/forum/ (monitored by staff) to make sure this is actually a bug.

In any case you should:
- provide a *minimal* sample page
- study the various modal window demos which are on offer - http://flowplayer.org/demos/layout/#overlay-demo http://demos.flowplayer.org/scripting/overlay-fancybox.html http://demos.flowplayer.org/scripting/overlay-jquerytools.html - mainly what they say regarding hidden videos

**Comment by bbbo** [comment]
Please post usage problems in the forums unless your're 100% this is a bug. See https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md

You're falsely configuring a single MP4 for both WebM and MP4 source types. If you configure a WebM source type, you must also offer a WebM _video_ . You're also delivering the MP4 with the wrong MIME type: application/octet-stream . ZThsi will fail in IE at least.

See https://flowplayer.org/docs/setup.html#mime-types and https://flowplayer.org/docs/setup.html#video-formats .
