### ISSUE TITLE
License check pausing the video on http://localhost:8080

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#816]
I'm using the auto.php script from our Unlimited license ZIP file: https://foliovision.com/flowplayer-keygen/auto.php

When I run that on http://localhost:8080/auto.php, it works. But if I enter bad license key, the video won't play, it just pauses every time it should play. Same if I remove "data-key" attribute.

Occuring on Firefox and Chrome on OS X 10.9.5.

Thanks!
Martin

**Comment by nnarhinen** [comment]
Please contact our support for a new unlimited build with the latest version.

**Comment by foliovision** [comment]
Unfortunatelly the issue is still present there.

Looking at changes in flowplayer.js I can see the only thing that is different is the key validation.

**Comment by blacktrash** [comment]
@foliovision - I cannot reproduce when I run e.g. http://flowplayer.blacktrash.org/fp6/unlimited.php on localhost (hard to verify or prove though ;-) - but I can create a screencast)
Are you sure you have set the `swf` and/or `swfHls` options correctly?

**Comment by foliovision** [comment]
@blacktrash here's how you can reproduce the bug -  try our version of flowplayer.min.js from https://foliovision.com/flowplayer-keygen/auto.php

When I use the Flowplayer 6 library which you used in your example it works. I can see that there are code differences between what you used and what we got in our unlimied license.

**Comment by blacktrash** [comment]
Looks like you managed to somehow get a broken build, duh.
I'll run some checks, and add a tested good one to your account if needed. Hang on.

**Comment by blacktrash** [comment]
@foliovision - I think you downloaded your first broken build again. I'll email you the link to the correct one which I tested successfully.

**Comment by blacktrash** [comment]
@foliovision - email sent to your Flowplayer account email address.
