### ISSUE TITLE
CloudFront signed URL with urlencode

### ISSUE THREAD

**Issue by DrySs** [flowplayer/flowplayer#817]
Hi there,

If I try to urlencode my CloudFront signed URL (I need to do it if my filename has special chars, like blank space "my video.mp4"), then FlowPlayer won't play the stream.

Example here: http://vod.dryss.com/w/django/lecteur-video.html

I'm unable to start video on Firefox / Chrome.

Any idea how to make it works?

Thanks

**Comment by blacktrash** [comment]
Please consult our forum https://flowplayer.org/forum/ first uness you're certain it's a bug in the _player_. See: https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md

Did you check this demo: http://demos.flowplayer.org/scripting/signed-ondemand.html ? And did you read the disclaimer, also re: signed urls in general? Is this worth the trouble of implementing and maintaining?

And please give really *minimal* samples for debugging.

Finally:
- spaces or non-ascii chars in filenames are evil ;-) especially in situations like that
- without seeing your code, my guess would be that you mustn't escape the characters _before_ generating the signed url
- test in a plain video tag first: http://demos.flowplayer.org/videotest/signedurl.html - again read the disclaimer

**Comment by DrySs** [comment]
@blacktrash 

1) Forums: No results for “signed space”
2) Your demo page does not talk about space in filename
3) I read the disclaimer, nothing about "signed URL"
4) I gave you a full demo page with the problem, why do you talk about minimal sample?
5) Space could be devil, I need to handle them for my customers, so I need a player which works with urlencode & space in filename
6) You can see my code, please take a look to my demo page given in my first page
7) Please reopen this case as this is a FlowPlayer bug

**Comment by DrySs** [comment]
This is a VERY BIG problem in FlowPlayer cannot handle special characters in CloudFront signed URLs !

**Comment by blacktrash** [comment]
You can _ask_ at the forum too ;-)

With disclaimer I meant that signed URLs offer no real protection with HTML5 video in general because the expiry time must be so high.

For *debugging* a *minimal* sample is needed, in a full page one has to dig through the page code, and in you case even find the external script which installs the player, plus, there seems to be other stuff going on because in Chrome I get no error, I can seek but not play or pause.

Will check re: spaces (I put a smiley there, in case you hadn't noticed), iirc they work fine in non-signed scenarios.

Can you create a *simple* demo where your signed URL works in a plain video tag. Thank you.

**Comment by blacktrash** [comment]
Same in Safari at http://vod.dryss.com/w/django/lecteur-video.html - only seeking works. So please boil the example down to Flowplayer relevant stuff. Thank you.

**Comment by DrySs** [comment]
"With disclaimer I meant that signed URLs offer no real protection with HTML5 video in general because the expiry time must be so high."

I know but this is not the issue I'm talking about here, I am?

"Same in Safari at http://vod.dryss.com/w/django/lecteur-video.html - only seeking works."

That just the issue opened here: video playing while filename has a space does not work!!

**Comment by blacktrash** [comment]
Works fine here: http://flowplayer.blacktrash.org/fp6/signed-with-space.html with
`encodeURIComponent("with space")` before signing.

**Comment by DrySs** [comment]
Here is an example with a filename urlencoded before signed it:

http://dev.dryss.com/cf/

FlowPlayer does not work in Firefox, I get "flash: Video file not found"

**Comment by DrySs** [comment]
Notice this not just a problem of withespace, second example without space:

http://dev.dryss.com/cf/v2.php

**Comment by blacktrash** [comment]
I don't understand? Both examples work?

**Comment by DrySs** [comment]
FlowPlayer does not work in Firefox, I get "flash: Video file not found"

**Comment by DrySs** [comment]
If you prefer a screenshot:

![image](https://cloud.githubusercontent.com/assets/230791/7882318/a6e45f08-060c-11e5-8e32-5667f88b47db.png)

**Comment by blacktrash** [comment]
Which Firefox version? No problem here with 38.0.1 (Mac).
![screen shot 2015-05-29 at 1 14 12 pm](https://cloud.githubusercontent.com/assets/168338/7882364/bc57a668-0604-11e5-839a-1c4d16e30946.png)

**Comment by DrySs** [comment]
38.0.1 on Desktop Win 8.1 :

![image](https://cloud.githubusercontent.com/assets/230791/7882381/42b22154-060d-11e5-900e-f9d1192c690c.png)

**Comment by DrySs** [comment]
Notice that Firebug returns a 403 error for FP request, while HTML5 video player has no problem with:

![image](https://cloud.githubusercontent.com/assets/230791/7882388/64c1eb30-060d-11e5-8fde-e0e368d335b6.png)

**Comment by blacktrash** [comment]
Well, it shouldn't fail over to Flash in the first place. I can only recommend that you use a JavaScript configuration in such scenarios. Otherwise you add one more level to escape hell (the player must retrieve a src which is already subject to different way of expansion by the browsers, nevermind further processing).
Not that strictly speaking you must write e.g. the ampersands as `&amp;` in a source tag for HTML parsers, but as you can see browsers try to be "friendly", but not all browsers in the same way.

**Comment by DrySs** [comment]
I don't understand what do you mean by "javascript configuration"?

What sould I do? Decode URL returned by CloudFront?

**Comment by DrySs** [comment]
FYI, here is the PHP code used with AWS PHP SDK:

```
$args = array(
    'url'  => 'https://d2vyyxzcikcr0b.cloudfront.net/'.urlencode('1/source/free video.mp4'),
    'expires' => (time() + 3600),
);
$url = $cdn->getSignedUrl($args);
```

**Comment by blacktrash** [comment]
No, as in my example and as I said: `encodeURIComponent("filename")` _before_ feeding it to cloudfront, and do not use a VIDEO tag based installation to avoid html parsing by the browser.

**Comment by DrySs** [comment]
Your example is a javascript encode, I need to encode using PHP SDK, so with PHP script.
So this is not possible for me.

How to make FlowPlayer works with urlencoded path?

**Comment by DrySs** [comment]
If I understand well, I cannot use VIDEO tag based installation with FlowPlayer if I have an URL encoded. What a pain!

**Comment by nnarhinen** [comment]
Could you please _try_ the JavaScript based installation method so that we could see if it is the browser HTML parsing mechanism that messes things up. We are not saying you should convert all your setups at once.

**Comment by DrySs** [comment]
@nnarhinen Done: http://dev.dryss.com/cf/

Still the same error.

**Comment by nnarhinen** [comment]
Could you add `engine: 'flash'` and to the player level configuration for debugging purposes. All browsers I have are able to play mp4 with html5 video tag.

like this:

```js
flowplayer(container, {
  engine: 'flash',
  clip: {
    sources: [{
      type: "video/mp4",
      src:  "<signed url>" }
    ]
  }
});
```

**Comment by DrySs** [comment]
Done :)

**Comment by nnarhinen** [comment]
Btw, why do you *need* to encode the urls beforehand? What happens if you don't do it?

**Comment by DrySs** [comment]
Filename has a blank space: "free video.mp4".

Refresh page: http://dev.dryss.com/cf/

I have deleted urlencode call before signing.
Now, CloudFront returns a "Access Denied".

This is a recommande way to use special chars in filenames:

https://github.com/aws/aws-sdk-php/issues/597

**Comment by nnarhinen** [comment]
Ok, can you change it back to urlencode the urls, I will try to debug further.

**Comment by DrySs** [comment]
Ok done, notice that I have the same error message in Chrome now that's we've forced Flash engine.

**Comment by blacktrash** [comment]
Yes, the Flash engine will open another can of worms, because Flash handles url escaping in a slightly different way and then it's handed back to the browser via the object tag ...

I am still interested what the _practical_ use case is? It doesn't give real protection because long expiry times are required. So why jump through all those hoops for an illusion of protection (which is somewhat worse than being upfront about the lack of it, especially towards a customer)?

**Comment by DrySs** [comment]
Protection here is not the problem, the problem is that Flash engine does not handle url encoded string.

I will be able to enhance the protection in the further with ajax request as you did in your demo.

**Comment by blacktrash** [comment]
Re: protection: that doesn't change the fact that for html5 video the entire video must be buffered to be playable entirely -> long expiry time to ensure it's entirely buffered. The FP demo just delays that to handle splash setups. But the basic problem is the same.

**Comment by blacktrash** [comment]
Re: Flash + encoded chars: both
```js
sources: [
  { type: "video/flash", src: "http://media.blacktrash.org/fp/test/with space.mp4" }
]
```
and
```js
sources: [
  { type: "video/flash", src: "http://media.blacktrash.org/fp/test/with%20space.mp4" }
]
```
work. So we have to look how the signed url scenario affects this in the Flash engine.

**Comment by DrySs** [comment]
Notice here encode is no the same:

```
https://d2vyyxzcikcr0b.cloudfront.net/1%2Fsource%2Ffree+video.mp4?Expires=1432909728&Signature=[...]
```

%2 => /
+ => space

**Comment by blacktrash** [comment]
You mean `%2F` for the directory separator. Again this is not a problem with the html5 engine: http://flowplayer.blacktrash.org/fp6/signed-with-space.html (updated).
But yes, escaping the directory separator is a problem for the Flash engine:
```
sources: [
  { type: "video/flash", src: "http://media.blacktrash.org/fp%2Ftest%2Fwith%20space.mp4" }
]
```
(of course you wouldn't do that normally)

**Comment by blacktrash** [comment]
There is actually only a problem with RTMP signed urls and special chars.
I've changed http://flowplayer.blacktrash.org/fp6/signed-with-space.html?forceflash to use a Flash http url and to use `encodeURI` instead of `encodeURICompenent` (which makes sense anyway) and it works.

**Comment by blacktrash** [comment]
@DrySs - can you confirm that both:
http://flowplayer.blacktrash.org/fp6/signed-with-space.html
and
http://flowplayer.blacktrash.org/fp6/signed-with-space.html?forceflash
work for you?

If yes, then:
1. we have indeed a problem with special characters in _RTMP_ urls in general: http://flowplayer.blacktrash.org/fp6/rtmp-with-space.html
2. cannot reproduce the problem with signed http urls if encoded, neither in html5 or flash

**Comment by DrySs** [comment]
Yes, both video works in Firefox.

**Comment by DrySs** [comment]
http://flowplayer.blacktrash.org/fp6/rtmp-with-space.html

does not works (same error Video file not found)

**Comment by blacktrash** [comment]
Yes. The problem with RTMP is undoubtedly there. But it's not related to signed urls.

**Comment by blacktrash** [comment]
The RTMP problem is now a separate issue: https://github.com/flowplayer/flowplayer/issues/821

**Comment by DrySs** [comment]
"2. cannot reproduce the problem with signed http urls if encoded, neither in html5 or flash"

Your are URL encoding using Javascript.

Just implements AWS PHP SDK and call CloudFront this way:

```
$args = array(
    'url'  => 'https://d2vyyxzcikcr0b.cloudfront.net/'.urlencode('1/source/free video.mp4'),
    'expires' => (time() + 3600),
);
$url = $cdn->getSignedUrl($args);
```

**Comment by blacktrash** [comment]
And did you let the php write as src into a JavaScript installation? Otherwise you have another round trip via the html parser, and Flowplayer retrieving the expanded value from the src attribute.

**Comment by DrySs** [comment]
Here is complete code:

```

require_once(dirname(__FILE__).'/aws/aws-autoloader.php');
use Aws\CloudFront\CloudFrontClient;

// Initialize CloudFront
$cdn = CloudFrontClient::factory(array(
    'key'    => _AWS_STREAMER_KEY_,
    'secret' => _AWS_STREAMER_SECRET_,
    'private_key' => _AWS_STREAMER_PK_,
    'key_pair_id' => _AWS_STREAMER_KEYPAIR_,
));

$args = array(
    'url'  => 'https://d2vyyxzcikcr0b.cloudfront.net/'.urlencode('1/source/free video.mp4'),
    'expires' => (time() + 3600),
);
$url = $cdn->getSignedUrl($args);

?>
<!doctype html>
<html lang="en">
    <head>
        <title>CF Signed URL with space</title>
        <link rel="stylesheet" href="skins/minimalist.css">
        <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="flowplayer.min.js"></script>
    </head>
    <body>
        <h1>CF Signed URL with space</h1>
        <a href="<?php echo $url ?>" download="download">Download file</a>
        <h1>HTML video player</h1>
        <div>
            <video src="<?php echo $url ?>" controls="controls" width="480" height="200"></video>
        </div>
        <h1>FlowPlayer</h1>
        <div id="flowplayer" style="width: 500px;"></div>
        <script>
        // select the above element as player container
        var container = document.getElementById("flowplayer");

        // install flowplayer into selected container
        flowplayer(container, {
            engine: 'flash',
            clip: {
                sources: [
                      { type: "video/mp4",
                        src:  "<?php echo $url ?>" }
                ]
            }
        });
        </script>
    </body>
</html>
```

**Comment by blacktrash** [comment]
So you are saying that the actual location of the video is at https://d2vyyxzcikcr0b.cloudfront.net/1source/free+video.mp4 - i.e. the "special char" is a plus sign?
(engine goes into clip object btw)

**Comment by DrySs** [comment]
Exact location is:

https://d2vyyxzcikcr0b.cloudfront.net/1source/free video.mp4

Encoded location sent to Flash is:

https://d2vyyxzcikcr0b.cloudfront.net/1%2Fsource%2Ffree+video.mp4?Expires=1432909728&Signature=[...]

**Comment by DrySs** [comment]
As I said before, space is replaced with a "+" chars and "/" with "%2F".

**Comment by blacktrash** [comment]
Why would spaces be replaced with a plus sign? The proper escape is `%20`, looks like your php is doing something wonky.

**Comment by DrySs** [comment]
This is what "urlencode()" method in PHP do.

**Comment by DrySs** [comment]
I just replaced urlencode with rawurlencode, which replace space with %20:

1%2Fsource%2Ffree%20video.mp4

But problem still remains, Flash does not play video.

So we have for exact location:

https://d2vyyxzcikcr0b.cloudfront.net/1/source/free video.mp4

Encoded location sent to Flash is:

https://d2vyyxzcikcr0b.cloudfront.net/1%2Fsource%2Ffree%20video.mp4?Expires=1432920589&Signature=[...]

**Comment by blacktrash** [comment]
Ah. It doesn't work if you set `engine: "flash"`, it will work if you specify `type: "video/flash"` as in the demo.
This should arguably work also with engine setting, but for the moment you should catch the failover by adding a (normally redundant) "video/flash" type in conjunction with `rawurlencode` for php.

**Comment by DrySs** [comment]
I don't wan't to setup video/flash, I want to have video/mp4, to have something working on all devices.

If I remove "engine: flash", then it still won't work on Firefox (cf. my first screenshots when you said it was working on your side).

**Comment by DrySs** [comment]
Tryed this for Firefox but it doesn't work anymore:

```
        flowplayer(container, {
            clip: {
                sources: [
                      { type: "video/flash",
                        src:  "<?php echo $url ?>" },
                      { type: "video/mp4",
                        src:  "<?php echo $url ?>" }
                ]
            }
        });
```

**Comment by DrySs** [comment]
BTW, if I just use video/flash, it won't work too in Firefox.

**Comment by blacktrash** [comment]
What you currently have at http://dev.dryss.com/cf/ at first glance is exactly what I have at http://flowplayer.blacktrash.org/fp6/signed-with-space.html?forceflash - so for the moment I am at a loss why yours does not work (I also tried without splash).

**Comment by DrySs** [comment]
I don't agree with you: you have 100% pure javascript (with Ajax request to get signed URL).
I've only have PHP, using PHP SDK (I suppose you don't).

What is the signed URL returned by your PHP script?
It should have some differences between our two URL encode.

**Comment by DrySs** [comment]
http://d2yz3vc7rxs49u.cloudfront.net/esc/with%20space.mp4?Expires=1432918520&Signature=

**Comment by DrySs** [comment]
Yout "/" are not encoded like mine with "%2F".

**Comment by DrySs** [comment]
Ok well this is the "/" encoded which made Flash to bug.

So, the trick is to no more encode this chars :

```
$path = '1/source/free video.mp4';
$path = implode('/', array_map('rawurlencode', explode('/', $path)));
$args = array(
    'url'  => 'https://d2vyyxzcikcr0b.cloudfront.net/'.$path,
    'expires' => (time() + 3600),
);
$url = $cdn->getSignedUrl($args);
```

And now it's work :)

**Comment by blacktrash** [comment]
That's right, so why don't you ditch the php encoding and use encodeURI().

**Comment by blacktrash** [comment]
Or like that, yes ;-)

**Comment by DrySs** [comment]
Ok, and seems to work too with other special chars like: "free [video].mp4".

Thanks for all your help @blacktrash & @nnarhinen!

**Comment by DrySs** [comment]
To remember for other persons:

- do not use urlencode but **rawurlencode**
- do not encode "/"

**Comment by nnarhinen** [comment]
@DrySs can you still leave an example online with the original PHP encode that was problematic and `engine: flash`

**Comment by nnarhinen** [comment]
I'd still like to test something out.

**Comment by DrySs** [comment]
Here it is:

http://dev.dryss.com/cf/

Tell me if you need anything else :)

**Comment by blacktrash** [comment]
@nnarhinen - when you go via clip.engine flash it breaks, it only works via video/flash, so there is something not quite right there (regardless of what comes from php).

**Comment by nnarhinen** [comment]
@blacktrash and you are sure it uses the flash engine?

**Comment by blacktrash** [comment]
Actually I was wrong: properly setting clip.engine (not at player level) works: http://flowplayer.blacktrash.org/fp6/signed-with-space.html now uses clip.engine flash.

**Comment by blacktrash** [comment]
We could consider converting the legit plus signs because JS doesn't deal with them.

**Comment by blacktrash** [comment]
Not sure whether it's worth dealing with the Flash engine not handling encoded path separators.

**Comment by nnarhinen** [comment]
This issue always comes back and back to haunt us. I want to try something out.

**Comment by blacktrash** [comment]
ok, but don't forget #821 - especially as in the context of signed urls rtmp is the best way to actually protect the content as you can use short expiry times.

**Comment by nnarhinen** [comment]
@DrySs can you change the demo to use http://cdn.820f.flowplayer.me/adhoc/flowplayer.min.js thanks

**Comment by DrySs** [comment]
Done, still broken on Firefox.

**Comment by nnarhinen** [comment]
Is the mp4 stream still accessible?

**Comment by DrySs** [comment]
You mean if the file is still available on CloudFront?
Yes it is :)

**Comment by nnarhinen** [comment]
But does not work on the plain video tag either, it seems. Or does it work for you?

**Comment by DrySs** [comment]
Ok was not the correct filename, can you try again?

**Comment by nnarhinen** [comment]
http://dev.dryss.com/cf/ even the download link does not work.

**Comment by DrySs** [comment]
Should work, sorry just refresh :)

**Comment by nnarhinen** [comment]
Can you make it use the flowplayer.min.js I linked earlier in this thread: http://cdn.820f.flowplayer.me/adhoc/flowplayer.min.js

**Comment by nnarhinen** [comment]
(it is using the ones built from pull request 819, should be 820)

**Comment by DrySs** [comment]
Done :)

**Comment by nnarhinen** [comment]
Are you sure, my browser after cache-refresh still tries to load http://cdn.819f.flowplayer.me/adhoc/flowplayer.min.js and it should be http://cdn.820f.flowplayer.me/adhoc/flowplayer.min.js

**Comment by DrySs** [comment]
You'r right, please refresh?

**Comment by nnarhinen** [comment]
cool thanks, will dig a little deeper

**Comment by nnarhinen** [comment]
@DrySs @blacktrash Can you see what is the difference between the two urls now?

Are the cloudfront urls disposable, I mean do they prevent loading same url multiple times?

![image](https://cloud.githubusercontent.com/assets/265438/7937092/76e74e4a-0946-11e5-9651-c08e66d4761a.png)

**Comment by nnarhinen** [comment]
(maybe try removing the plain video tag just to be sure)

**Comment by blacktrash** [comment]
Does flowplayer.js handle the plus sign for space?

**Comment by nnarhinen** [comment]
From my screenshot, the first one is the video tag request, the second one the flash object requesting. @blacktrash if you could open the site and check the console if you see what the difference in the two requests are, that would be much appreciated..

**Comment by nnarhinen** [comment]
flowplayer.js does nothing to the url in this adhoc build, it offloads everything to flowplayer.swf and the request is made by flash.

**Comment by blacktrash** [comment]
So does the swf handle the plus sign? Or is it like JS only aware of %20?

**Comment by nnarhinen** [comment]
I don't know anything else than what I see in the browser network console. I see two identical requests from which another fails with 403 and the other not. Can you spot some differences between the two requests?

**Comment by blacktrash** [comment]
As a reminder: this works here: http://flowplayer.blacktrash.org/fp6/signed-with-space.html?forceflash

**Comment by nnarhinen** [comment]
Are cloudfront signed urls one-time-only, as in do they expire on first load?

**Comment by blacktrash** [comment]
No they expire when expiry time is over.

**Comment by blacktrash** [comment]
But the browser might be able to deal with + for space, whereas JS and Flash may not be prepared for that.

**Comment by nnarhinen** [comment]
Can you please take a look in the network console of your browser to spot any differences in the requests.

**Comment by blacktrash** [comment]
The "malformed" signature *as presented by the console* is the same as the good one, I diffed them.

**Comment by blacktrash** [comment]
It's only the Flash engine that has the problem:
http://flowplayer.blacktrash.org/fp6/signed-with-space.php works
http://flowplayer.blacktrash.org/fp6/signed-with-space.php fails

Same url in both cases. Same problem over rtmp. Only happens with "special chars" in filenames.
It has to do with how Flash processes the filenames, writes them back to the page into the object.

**Comment by blacktrash** [comment]
To make the confusion complete: Unsigned all of the following work with Flash HTTP progressive download:
```js                                                                                                    
{ type: "video/flash", src: "http://media.blacktrash.org/fp/test/with space.mp4" }
```
```js                                                                                                    
{ type: "video/flash", src: "http://media.blacktrash.org/fp/test/with%20space.mp4" }
```
and(!):
```js                                                                                                    
{ type: "video/flash", src: "http://media.blacktrash.org/fp/test/with+space.mp4" }
```
Similarly UTF chars.
(they all do _not_ work over RTMP - https://github.com/flowplayer/flowplayer/issues/821)

**Comment by blacktrash** [comment]
Demo updated with an UTF8 filename: http://flowplayer.dev/fp6/signed-with-space.php?flash
As long as
1. the filenames are url encoded _before_ signing
2. the + for space encoding is avoided and %20 is used

it works in Flash (except for RTMP - different bug) and HTML5.

**Comment by nnarhinen** [comment]
It's good we have found a *workaround* for this. But for consistency our flash engine _should_ work just like the html5 one. And I'm close to the solution.

**Comment by blacktrash** [comment]
Encoding before signing must be done for HTML5 video as well. I don't see what's to change there.
The only difference I see (over HTTP) is that Flash can't deal with the plus sign returned by the AWS SDK (I speculate that the Flash engine does not write + in the object but 20% and that breaks the sig) - so afaics the only question is whether we want/can support the AWS SDK without breaking other stuff.
Outside of that situation the behaviour is the same already (over HTTP, RTMP does not work at all).

**Comment by DrySs** [comment]
@blacktrash 

The + sign is not returned by Amazon SDK, but when you use "urlencode".
When using "rawurlencode", there is no more + sign.

**Comment by DrySs** [comment]
http://stackoverflow.com/questions/996139/urlencode-vs-rawurlencode

**Comment by foliovision** [comment]
Any update on this? Thanks!

**Comment by DrySs** [comment]
@foliovision do you use rawurlencode?

**Comment by foliovision** [comment]
I realized our isssue is related to using playlists in Flash engine.

Our playlist has 2 videos, both have ?Signature= in URL.

When using Flash the first one plays, but the second one does not. When I disable escapeURL() in Flash Engine (flashEngine()) it works.

So I guess the Flash engine must be doing something wrong when loading playlist videos. It looks like it doesn't require escapeURL() when loading a playlist video.

**Comment by foliovision** [comment]
I realized our fix no longer works, so I put in this condition into escapeURL()

if( video.index > 0 || typeof(video.seekable) !="undefined" ) 

If the condition returns true I skip the escapeURL process. The thing is the escapeURL() is required for the first video playback in a player, but not when advancing in playlist or changing the video.

**Comment by blacktrash** [comment]
This looks now like a duplicate in #924 which should be solved by https://github.com/flowplayer/flowplayer/commit/ae876b21afb0b857320946b186bd3c47e09e1a94

**Comment by foliovision** [comment]
I still have this issue with version 6.0.4. It just can't handle URL like 

https://akamaihd.net/exp=1449504820~acl=%2A%2Ftest.mp4%2A~hmac=de7a03f342c30ab1f79487bfabd6f71a46c05db757758136f38210e7b95a343b

As it keeps changing it into https://akamaihd.net/exp=1449504820~acl=*/test.mp4*~hmac=de7a03f342c30ab1f79487bfabd6f71a46c05db757758136f38210e7b95a343b

**Comment by paja0012** [comment]
Hi, 
i have same issue as foliovision

flashhls change url from

https://lco-a.cdn.sportradar.com/53/9901055/mobile/master.m3u8?cid=53&mid=9901055&hdnts=ip=xx.xx.xx.xx~exp=1471704413~acl=%2F53%2F9901055%2Fmobile%2F%2A~hmac=8ac

to incorrect (they automatically decode %2F to /, but this is wrong)

https://lco-a.cdn.sportradar.com/53/9901055/mobile/master.m3u8?cid=53&mid=9901055&hdnts=ip=xx.xx.xx.xx~exp=1471704285~acl=/53/9901055/mobile/*~hmac=04d

With hlsjs is ok, but Interner Explorer 11 still must use flash fallback.

I pass url via clip object

clip: {
  ...
  sources: [{type: 'application/x-mpegurl', src: streamAddress}]
  ...
}
