### ISSUE TITLE
jQuery bind to load doesn't pass event data

### ISSUE THREAD

**Issue by foliovision** [flowplayer/flowplayer#818]
I'm using the following event hooks:

```
jQuery('.flowplayer').bind('load', function(e,api,video) {
  console.log('flowplayer loaded 1',e,api,video)
});

flowplayer( function(api,root) {
  api.bind('load', function(e,api,video) {
    console.log('flowplayer loaded 2',e,api,video)
  });
});
```

Check the output here:

**Flowplayer 5**: http://foliovision.com/html/fp5-events.html using /releases.flowplayer.org/5.5.2/flowplayer.min.js

* e Event data contains both currentTarget and target
* everything works in both events - api and video is present

**Flowplayer 6**: http://foliovision.com/html/fp6-events.html using /releases.flowplayer.org/6.0.1/flowplayer.min.js

* in case of using jQuery().bind() there is **no** currentTarget and target in e Event data
* in case of using jQuery().bind() both api and video is **undefined**
* everything works when using flowplayer()

Thanks!
Martin

**Comment by blacktrash** [comment]
Yes, this is documented here: https://flowplayer.org/docs/api.html#attaching-to-manual-installation
That is the price of ditching the jQuery requirement so to speak: switch to a pure JavaScript installation (you can still load jQuery of course, but you have to bind the event to the API, not the container element) if you want to cater for this or similar scenarios.

**Comment by foliovision** [comment]
Thanks, just wanted to make sure it's not a bug, but it's going to be that way in version 6.
