### ISSUE TITLE
RTMP: breaks with special chars in URLS

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#821]
Example: http://flowplayer.blacktrash.org/fp6/rtmp-with-space.html

**Comment by DrySs** [comment]
Hi,

Any idea when this bug will be fixed?

**Comment by nnarhinen** [comment]
http://demos.861f.flowplayer.me/ and the assets there.

@blacktrash do you still have the unicode filename video available via RTMP? I'd like to check this did not break that. Basic RTMP seems not affected: http://demos.861f.flowplayer.me/basics/rtmp.html

**Comment by blacktrash** [comment]
First off:
I've tested all variations of `with space`, `with%20space`, `with+space`, and they work _both_ in a JS and a VIDEO tag based install, i.e. even the illegal HTML `with space` in a src attribute.

**Comment by blacktrash** [comment]
Here's with UTF-8 filename: http://flowplayer.blacktrash.org/fp6/rtmp-utf.html - looking good.

**Comment by blacktrash** [comment]
FWIW, both `mp4:fp/test/Древние` and `mp4:fp/test/%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B5` work in both a JS install and VIDEO tag install.
