### ISSUE TITLE
clip options in playlists are sticky, triggering trouble with picking order

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#823]
The following config errs with "Flash: Video file not found" when switching to the 2nd clip:
```js
// setting rtmp on player level also triggers the issue
// rtmp: "my.rtmp.com",
playlist: [{
  rtmp: "my.rtmp.com",
  sources: [
     { type: "video/flash", src: "mp4:video1" },
     { type: "video/mp4", src: "//example.com/video1.mp4" }    
  ]
}, {
  // rtmp: 0, // does not help
  sources: [
    // { type: "video/mp4", src: "//example.com/video-f2.mp4", engine: "flash" }, // does not help
    { type: "video/flash", src: "//example.com/video-f2.mp4" },
    { type: "video/mp4", src: "//example.com/video.mp4" }
  ]
}]
```
That is: Currently RTMP in a playlist works only if *all* clips are also available via RTMP.

It can make sense that clip options are sticky, i.e. they do not fall back to to values given on player level *if* they fall back to their flowplayer.default consistently - but this is not the case with `rtmp` for instance.

RE doc: If the above description (minus the bug) about stickyness is correct, it must be documented clearly.

See: https://flowplayer.org/forum/#!/setup:flash-video-not-found-in-a

**Comment by nnarhinen** [comment]
This should be fixed with assets from http://demos.834f.flowplayer.me/

Even though I did test #834 locally to some extent, it would be awesome if you could test various configurations to see if it did break something regarding playlist clip changes.

**Comment by blacktrash** [comment]
hm, the scenario in https://github.com/flowplayer/flowplayer/issues/823#issue-83411367 still gives "Flash not found": http://flowplayer.blacktrash.org/fp6/rtmp-vflash.html

**Comment by blacktrash** [comment]
`title` property is not sticky anymore.

**Comment by nnarhinen** [comment]
@blacktrash maybe because you used the assets from #835 and not #834

**Comment by blacktrash** [comment]
Ah, right. :+1: 
@nnarhinen - doc-wise: can you confirm somthing like:
"`rtmp` *must* be set on clip level for *all* clips if the option does not apply to one clip in a playlist."
?
i.e.
1. you cannot expect a global rtmp setting to be unset for a "video/flash" clip which is served over http (this scenario)
2. you cannot expect `rtmp` to default to the global rtmp value if rtmp differs for one clip in a playlist (also fine, just might have to be documented more clearly)

That is: `rtmp` should only be set globally in conjunction with a playlist if its value applies to *all* clips in a playlist, there is no guessing of default values.

**Comment by nnarhinen** [comment]
the code goes something like

```js
var rtmp = clip.rtmp || player.conf.rtmp;
```

so now saying
```js
{
  rtmp: '<rtmpurl>',
  clip: {
    rtmp: false
  }
}
```

would make it use `<rtmpurl>`.

I could make special logic with `rtmp: false` to completely disable rtmp for current clip but I don't know if that is easier at all to document.

So the easiest to document I guess is to advice setting rtmp on clip level for playlists if *any* of the rtmp urls differ.

**Comment by blacktrash** [comment]
Thanks for clarifying. Fine with documenting it the way it is.
