### ISSUE TITLE
flashls: add debug option(s)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#824]
Add dedicated debug option to as of yet undocumented `flashls` config object.

See: https://flowplayer.org/forum/#!/setup:get-current-hls-bitrate

**Comment by nnarhinen** [comment]
@blacktrash You mean that stating `debug: true` should enable flashls debuggin options or?

**Comment by blacktrash** [comment]
No, that would be too verbose.
```js
flashls: {
  debug1: true,
  debug2: true
}
```
should have the appropriate effect.

**Comment by nnarhinen** [comment]
http://demos.839f.flowplayer.me/ and the assets from there should enable this

**Comment by blacktrash** [comment]
First of all: the options are (hls_)debug and (hls_)debug2 - *not* (hls_)debug1 - https://github.com/mangui/flashls#configuration - sorry, my bad.

In spite of that: both `flashls.debug` and `flashls.debug2` work as expected. :+1:
