### ISSUE TITLE
subtitle CORS: Chrome error w/o consequence

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#826]
At http://demos.flowplayer.org/basics/subtitle.html#vtt Chrome complains with an error:
"Text track from origin 'http://d12zt1n3pd4xhr.cloudfront.net' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://demos.flowplayer.org' is therefore not allowed access."
And then goes on to load the track anyway ...?

This might be a Chrome bug, so I'm gonna postpone fiddling with the CORS settings until I understand why they are wrong. @nnarhinen - any explanations?

**Comment by nnarhinen** [comment]
The error comes when the `<video>`-tag is being parsed. The reason why it works is that flowplayer will load it with Ajax and those headers most likely are sent correctly. To avoid this error you could just modify the html to be something like this:

```html
<div class="flowplayer">
  <video crossorigin>
    <source ...>
   <track ...>
  </video>
</div>
```

**Comment by blacktrash** [comment]
After my first attempt at documenting this, it turns out to be tricky:
At http://flowplayer.org/standalone/basics/subtitles.html the VTT file is loaded from a _different_ domain, but only the sub domain differs: no error, _but_ it requires CORS headers.
Now, when I add the `crossorigin` attribute there "for safety" the video does not load at all! So the `crossorigin` attribute must only be applied if the VTT is loaded from a different *main* domain?!

**Comment by blacktrash** [comment]
Re-opening for documentation. Not clear what the requirements for setting the `crossorigin` attribute are exactly.

**Comment by nnarhinen** [comment]
Flowplayer-wise the crossorigin attribute is not needed. In a plain HTML5 video tag setup it is needed to load cross-domain subtitles.

With the video-tag based setup the browser first parses the html, raises this error and refuses to load the track to the native html5-player. Then flowplayer takes over and loads the subtitle file with ajax (which succeedes) and then empties the video tag from track elements and uses its own subtitle implementation and everything works. There just is this unnecessary error in console from the native dom parser.

**Comment by blacktrash** [comment]
> Flowplayer-wise the crossorigin attribute is not needed. In a plain HTML5 video tag setup it is needed to load cross-domain subtitles.
> 
> With the video-tag based setup the browser first parses the html, raises this error and refuses to load the track to the native html5-player. Then flowplayer takes over and loads the subtitle file with ajax (which succeedes) and then empties the video tag from track elements and uses its own subtitle implementation and everything works. There just is this unnecessary error in console from the native dom parser.

Understood. The problem is that the server and client side conditions differ.

- Flowplayer's ajax request requires CORS policy on the server if the domain differs, even if its only a subdomain: releases.flowplayer.org needs to have CORS already if VTT is loaded from flowplayer.org
- The VIDEO tag requires the crossorigin attribute if the _main_ domain differs only. flowplayer.org loads VTT from releases.flowplayer.org: no. flowplayer.org loads VTT from some.other.net: yes.

Note: the main domain criterion is simply an uneducated guess on my part.

Because adding the crossdomain attribute when it not required causes a fatal error, we cannot simply say: add the attribute if you have to serve the VTT with CORS (for safety), the above distinction must be documented.

Currently it's only a console error, but we don't know what browsers will implement next ...

**Comment by blacktrash** [comment]
Native subtitles do not work even if `crossdomain` is added: http://flowplayer.blacktrash.org/fp6/subtitles.html

**Comment by nnarhinen** [comment]
The attribute is called `crossorigin`

**Comment by blacktrash** [comment]
> The attribute is called `crossorigin`

Too much testing typo lapse, sorry. But the diagnosis is the same.

http://flowplayer.blacktrash.org/fp6/subtitles.html corrected.

**Comment by nnarhinen** [comment]
from MDN

> crossorigin
This enumerated attribute indicates if the fetching of the related image must be done using CORS or not. CORS-enabled resources can be reused in the <canvas> element without being tainted. The allowed values are:
anonymous
A cross-origin request (i.e. with Origin: HTTP header) is performed. But no credential is sent (i.e. no cookie, no X.509 certificate and no HTTP Basic authentication is sent). If the server does not give credentials to the origin site (by not setting the Access-Control-Allow-Origin: HTTP header), the image will be tainted and its usage restricted..
use-credentials
A cross-origin request (i.e. with Origin: HTTP header) is performed with credential is sent (i.e. a cookie, a certificate and HTTP Basic authentication is performed). If the server does not give credentials to the origin site (through Access-Control-Allow-Credentials: HTTP header), the image will be tainted and its usage restricted.
When not present, the resource is fetched without a CORS request (i.e. without sending the Origin: HTTP header), preventing its non-tainted used in <canvas> elements. If invalid, it is handled as if the enumerated keyword anonymous was used. See CORS settings attributes for additional information.

**Comment by nnarhinen** [comment]
So I guess it has to be `crossorigin="anonymous"`

**Comment by nnarhinen** [comment]
Also: http://releases.flowplayer.org/fp5/subtitles-en.vtt is not accessible

**Comment by blacktrash** [comment]
Tried that as well: nope.
Now trying in plain VIDEO tag:
- with crossorigin attribute: video does not even play
- without crossorigin attribute: subtitles shown in e.g. Firefox, but not in Chrome

Demo http://flowplayer.blacktrash.org/fp6/subtitles.html updated and hopefully purged of all typos.

**Comment by nnarhinen** [comment]
Yeah, I have no clue why on http://jsfiddle.net/kyk71s38/ the first video does not play, not on firefox, not on chrome. On firefox it complains about no suitable mime-type..

**Comment by nnarhinen** [comment]
http://jsfiddle.net/kyk71s38/

Chrome:
 * Only second video plays, no subtitles
Firefox:
 * Only second video plays, subtitles shown
Safari:
 * Both videos play, subtitles shown for second player

So by spec, Safari seems to be the only one handling this as it should..

**Comment by nnarhinen** [comment]
So I guess what we actually have to do here, is to
 * remove `crossorigin` attribute from the video tag in first-frame setups (where the video tag is re-used) if `native_subtitles` is not in set
 * Add a disclaimer to the `native_subtitles` documentation that browsers are broken

**Comment by blacktrash** [comment]
I see the subtitles in second video in Firefox Mac 38.0.5.
Other than that I agree. Will add warning (bordering on deprecation) to option docs.

**Comment by blacktrash** [comment]
@nnarhinen - doc part is done.

**Comment by nnarhinen** [comment]
> I see the subtitles in second video in Firefox Mac 38.0.5.

Github messed up the formatting of the comment, edited :)

**Comment by nnarhinen** [comment]
Now flowplayer should handle crossorigin so that it does not break. Assets from http://demos.835f.flowplayer.me/ can be used to verify

**Comment by blacktrash** [comment]
Hm, I don't see a difference, I may be missing something.
Demo with all scenarios: http://flowplayer.blacktrash.org/fp6/subtitles.html
(It's not that big a problem, can be solved with advice).

**Comment by nnarhinen** [comment]
You had a demo where flowplayer errored out with HTML5: video not found when crossorigin was set but subtitles not loaded cross-domain. Now the only failing player is the one with `nativesubtitles: true`, because the code does not remove the attribute when `nativesubtitles` is used.

**Comment by blacktrash** [comment]
Yes. You're right. Confirming fix for non-native subtitles.
