### ISSUE TITLE
playlist embed: should embed _configured_ playlist

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#827]
And not start for instance autoplaying the last video. Imho that is pretty surprising behaviour.
Why are all those values from the current video object propagated? What are they good for? I would expect as much as possible of the origin _configuration_ embedded so the viewing experience is as similar as possible to that on my own page.

See also: https://flowplayer.org/forum/#!/setup:embedding-issues

**Comment by nnarhinen** [comment]
Is it better with the assets from http://demos.828f.flowplayer.me/ ?

**Comment by blacktrash** [comment]
First assessment:
- improvement for single clips: protocol is not expanded as well (not even with VIDEO tag install): solves problem when embedding from http site into a https site
- playlist: no autoplay (good)
- playlist VIDEO tag: muddles up the order of the clips, while keeping the order of e.g. `title`: http://flowplayer.blacktrash.org/fp6/embed-playlist.html embedded from http://flowplayer.blacktrash.org/fp6/playlist.html (night1 thru night7). It's not immediately obvious from the embed code which looks sorted, but I guess the additional `src` attribute for each clip outside of the `sources` array confuses the player:
```js
[{"src":"http://stream.flowplayer.org/night1.m3u8","sources":[{"type":"application/x-mpegurl","src":"http://stream.flowplayer.org/night1.m3u8"},{"type":"video/webm","src":"http://stream.flowplayer.org/night1.webm"},{"type":"video/mp4","src":"http://stream.flowplayer.org/night1.mp4"}],"index":0,"title":"Night no 1"}
```
The clip that is actually played on the embed page is not night1 (the title however is shown).
Note that also here the protocols are expanded. Will test with a JS install later.

**Comment by nnarhinen** [comment]
On during which video did you hit the embed button?

The sources expanded and intended show that the clip is night4 (taken from embed-playlist.html)

```js
{
    "ratio": 0.5625,
    "rtmp": 0,
    "live": false,
    "origin": "http://flowplayer.blacktrash.org/fp6/playlist.html",
    "swf": "//cdn.828f.flowplayer.me/adhoc/flowplayer.swf",
    "swfHls": "//cdn.828f.flowplayer.me/adhoc/flowplayerhls.swf",
    "embed": {
        "playlist": true
    },
    "adaptiveRatio": false,
    "playlist": [{
        "src": "http://stream.flowplayer.org/night1.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night1.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night1.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night1.mp4"
        }],
        "index": 0,
        "title": "Night no 1"
    }, {
        "src": "http://stream.flowplayer.org/night2.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night2.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night2.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night2.mp4"
        }],
        "index": 1,
        "title": "Night no 2"
    }, {
        "src": "http://stream.flowplayer.org/night3.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night3.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night3.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night3.mp4"
        }],
        "index": 2
    }, {
        "src": "http://stream.flowplayer.org/night4.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night4.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night4.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night4.mp4"
        }],
        "index": 3
    }, {
        "src": "http://stream.flowplayer.org/night5.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night5.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night5.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night5.mp4"
        }],
        "index": 4
    }, {
        "src": "http://stream.flowplayer.org/night6.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night6.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night6.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night6.mp4"
        }],
        "index": 5
    }, {
        "src": "http://stream.flowplayer.org/night7.m3u8",
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night7.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night7.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night7.mp4"
        }],
        "index": 6
    }],
    "clip": {
        "title": "Night no 1",
        "subtitles": [],
        "sources": [{
            "type": "application/x-mpegurl",
            "src": "http://stream.flowplayer.org/night4.m3u8"
        }, {
            "type": "video/webm",
            "src": "http://stream.flowplayer.org/night4.webm"
        }, {
            "type": "video/mp4",
            "src": "http://stream.flowplayer.org/night4.mp4"
        }]
    }
}
```

I will have to check why the title is wrong though.

**Comment by nnarhinen** [comment]
Yeah night4 does not have a title. Was there an independent issue for clip properties sticking while looping a playlist through?

**Comment by blacktrash** [comment]
The problem is 2-fold:
1. The embedded playlist should start playing with index 0 (that's not the case - look at http://stream.flowplayer.org/night1.mp4), not the the index when the viewer decides to embed. That is like if an embedded single clip always starts at the point when the viewer decided to embed it. Or as if someone decides to buy my record, and it always starts at track 4, because that's when (s)he made the decision to buy it ;-)
2. The title attribute belongs to index 0, so that might be/have been a consequence of #823

**Comment by nnarhinen** [comment]
1) The current behavior is by design --- the user clicks on the embed button when she sees a video and embeds it to her own site. *I* would be very surprised if it would embed something that would not be the video she was seeing.  So at least this would have to be communicated clearly in the embed dialog (see the youtube screenshot below)

2) Yeah that is definitely a bug

![image](https://cloud.githubusercontent.com/assets/265438/8001398/266c41f8-0b6e-11e5-8f88-db61d76e6ddb.png)

**Comment by blacktrash** [comment]
1) From a content provider's and site owner's view I strongly disagree with YouTube's behavior - we also do not autoplay by default, so we don't have to mimic everything YouTube does (Apples vs Oranges). It would maybe make optional sense if the playlist loops. But otherwise the moment of embedding is stuck on other sites forever (especially annoying if it starts with the last video). If I compile my playlist consciously I am not be interested in the embed moment snapshot at all, if I don't care, I also don't care if it starts at index 0.

**Comment by blacktrash** [comment]
If we say that 1) is not a bug, but a feature, maybe consider an option (like, ermh, in YouTube). As per aforementioned https://flowplayer.org/forum/#!/setup:embedding-issues I'm not the only one to find the YouTube default behavior surprising: "Is it possible to make the embedded playlist always start at the beginning?"

**Comment by nnarhinen** [comment]
@blacktrash http://demos.828f.flowplayer.me/

Using the assets from that site, now if you embed a playlist that has `conf.embed.playlist: true`, it will embed the playlist but not the clip, which means that the initialization of flowplayer will pick the first playlist item as the clip. Should resolve 1)

**Comment by blacktrash** [comment]
:+1: - we can still add the "current" thing as an option if demand arises.

**Comment by nnarhinen** [comment]
(Did you try it actually works as should? Just to confirm..)

**Comment by blacktrash** [comment]
Yes, I can confirm that it works.
