### ISSUE TITLE
ID3 events for HLS

### ISSUE THREAD

**Issue by joseluismg** [flowplayer/flowplayer#830]
It would be nice to be able to read meta events ID3  (or any other instream events)

Currently the flash player can be trigger when events happens using the onMetaData, but this is not implemented in the flowplayer HTML5. It will be awesome to have a similar feature,

**Comment by blacktrash** [comment]
This is planned. No exact time frame yet though - should be consistent also in generic HLS.

**Comment by nnarhinen** [comment]
@joseluismg Do you have any (semi-)public HLS stream I could use for developing purposes to add support for meta events?

**Comment by joseluismg** [comment]
please check you inbox,
