### ISSUE TITLE
Cuepoint not working on fullscreen.

### ISSUE THREAD

**Issue by zhjyii** [flowplayer/flowplayer#833]
I am loading a HTML page on cuepoints, it works on non-fullscreen state, but the HTML page won't shown on fullscreen mode. I tried it with the new v6 release on IE, Chrome and Friefox, neither works.

In my code I am catching the cuepoint event and then lower the player's z-index to show the html page, which has higher z-index as below:
/* on entering  cuepoints, lower player's z-index */
flowplayer(function (api, root) {
  api.bind("cuepoint", function () {
    /* lower player's z-index */
    $('.flowplayer video, .flowplayer .fp-ui').css({"z-index": 1});
    /* pause playback */
    api.pause();
    /* disable keyboard (so space key won't resume the playback) */
    api.conf.keyboard=false;
  });
});

The player paused at the cuepoint so I assume the event has been triggered and caught, but just the HTML page doesn't show.

Is this a known issue, any workaround?

Thanks,
Jian

**Comment by nnarhinen** [comment]
As per our [contribution guidelines](https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md), please move this discussion to our [forums](https://flowplayer.org/forum/)

Remember to
 * Link to a minimal live example that exposes this problem
 * Use code formatting when showing code

If this really boils down to a bug within the player, you or we can re-open this issue with more specific information

**Comment by zhjyii** [comment]
Sorry, will do.

Jian
