### ISSUE TITLE
subtiltes do not work in IE8 for Fp6

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#836]
did not check other Flash only devices yet

compare

http://demos.flowplayer.org/basics/subtitle.html ( no subs)
to
http://demos.flowplayer.org/v5/basics/subtitle.html
(strangely, only the srt subs work there)

**Comment by nnarhinen** [comment]
Well the first ones cannot work, because of no CORS in IE8. I don't know why the second video does not load. @blacktrash can you make a standalone page of the SRT example alone.

**Comment by blacktrash** [comment]
http://flowplayer.blacktrash.org/fp6/srt.html (currently uses 6.0.1)

**Comment by nnarhinen** [comment]
Ok, those seem to work on IE8 on browserstack. So the problem is the lack of CORS support. I guess this has always been the case on IE8.

**Comment by blacktrash** [comment]
But didn't @bbbo - say that there's a difference between http://demos.flowplayer.org/basics/subtitle.html and http://demos.flowplayer.org/v5/basics/subtitle.html ? If there's indeed a difference then that would mean that the srt subtitles do not work on http://demos.flowplayer.org/basics/subtitle.html ?
@bbbo - do you think it's better to switch back to local loading of vtt at https://flowplayer.org/standalone/basics/subtitles.html ? - Then embedding should be disabled for that demo (to avoid that I changed it to CORS loading).

**Comment by nnarhinen** [comment]
@blacktrash Yeah @bbbo said only the SRT subtitles work on the fp5 demo (because they are not loaded over CORS). And on the fp6 demo site the second example does not work at all on IE8 (no player loaded). But that has to be a different problem.
