### ISSUE TITLE
analytics: use clip.title?

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#837]
Currently analytics uses the `title` container attribute - which has no Flowplayer-related effect otherwise.
1. Make it use clip.title?
2. But 1. would mean that analytics also work on clip level, i.e. for each clip of a playlist - afaik this is not the case

See also: https://flowplayer.org/forum/#!/setup:analytics-not-using-clip-le

**Comment by nnarhinen** [comment]
http://demos.838f.flowplayer.me/ (And the assets from there) now should use `player.video.title` when reporting.

**Comment by nnarhinen** [comment]
Does someone want to check&confirm or should I just merge to dev?

**Comment by bbbo** [comment]
just merge to dev; I'll try with a test setup tomorrow

**Comment by nnarhinen** [comment]
Ok merged to dev.
