### ISSUE TITLE
jQuery plugin init - config precedence wrong

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#840]
Our documentation states overriding rules (lowest number wins)

 1. HTML configuration
 2. local JavaScript configuration
 3. global JavaScript configuration

However the current order in jQuery is

 1. local js conf
 2. container data attributes
 3. parsed video tag configuration
 4. global js conf

It makes much more sense to do this as per the documentation:

 * You can init multiple players by something like `$('.player').flowplayer({rtmp: ...});`
 * You can tweak individual players easily by adding data-attributes and use shared configuration objects
 * etc

**Comment by nnarhinen** [comment]
@blacktrash http://demos.841f.flowplayer.me/ and assets from there

**Comment by blacktrash** [comment]
Tested `rtmp` sucessfully.
But `autoplay` is not overridden: http://flowplayer.blacktrash.org/fp6/minimal.html should not autoplay imho (same if autoplay is set globally).

**Comment by nnarhinen** [comment]
Can you make that page load flowplayer.js only once?

**Comment by blacktrash** [comment]
Sorry, done. Still does autoplay though.

**Comment by nnarhinen** [comment]
opening javascript console on that page and writing `flowplayer(0).conf.autoplay` states `false`

there has to be something in the flash engine or somewhere that reads the data-attributes directly or smth..

**Comment by blacktrash** [comment]
Rather something which prevents the data attribute from being evaluated: it's `data-autoplay="false"`
But indeed only the Flash engine is affected, I just tested with RTMP video/flash first.

**Comment by nnarhinen** [comment]
The configuration evaluates just fine -- as I said `flowplayer(0).conf.autoplay` is `false` (of type `boolean`)

**Comment by nnarhinen** [comment]
Should be fine now.

**Comment by blacktrash** [comment]
That's sorta what I meant ;-)
Confirming that this fixes the problem.
