### ISSUE TITLE
rtmp live: error(s) on initialization and later

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#844]
http://flowplayer.blacktrash.org/fp6/live-rtmp.html
Firefox console:
Error: Error calling method on NPObject!    flowplayer.js (line 617, col 17)

Chrome:
flowplayer.js:625 Uncaught Error: Error: An invalid exception was thrown.
flowplayer.js:525 Uncaught Error: Error: An invalid exception was thrown.(anonymous function)

Chrome also:
Failed to load resource: the server responded with a status of 404 (Not Found) - but that is #748

**Comment by blacktrash** [comment]
#843 is maybe related.

**Comment by nnarhinen** [comment]
Does it autoplay for you too? I *guess* it has something to do with that. It's the initial volume setting on ready event that does it, maybe the stream provider is not ready yet or something like that.

Can you try make it a splash setup? (IMHO first frame setups with live streams do not make that much sense anyway..)

**Comment by blacktrash** [comment]
Right, splash works, it's in fact #755 - feel free to close one ;-)

**Comment by blacktrash** [comment]
The only argument for non-splash would be that the stream (maybe) comes on quicker on click ...

**Comment by cgcb** [comment]
I have this issue, and I see that #755 was closed due to the original reporter not providing a necessary file. I could be wrong, but I think the net is that both issues are closed without any remediation.

**Comment by blacktrash** [comment]
@cgcb - thanks for bringing this up again; there's actually a similar problem with native hls live: #1189
I cautiously optimistic that, at least behavior-wise, this can be solved, also for non-splash setups.
