### ISSUE TITLE
IE8: muted on start despite volume showing, chsanngin volume does not work

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#847]
see https://flowplayer.org/forum/#!/setup:supported-browsers/the-first-error-that-i-am-g .

HLS starts with sound, but I cannot change the volume there either.

**Comment by nnarhinen** [comment]
Do you get this also on http://demos.dev94.flowplayer.us ?

Because I already fixed most likely at least parts of this for #811

**Comment by bbbo** [comment]
will check

**Comment by bbbo** [comment]
nope, the clips start muted. Clicking on the volume button twice (off/on) enables sound.
BTW, would it make sense to build the demos with unminified scripts, and debug enabled? Or have a separate branch for debug purposes?

**Comment by nnarhinen** [comment]
We could make the dev- and adhoc demo pages use the unminified script. Debug can be enabled on any player with FP6 with following steps:

 * open javascript console
 * write `window.localStorage.flowplayerDebug = true;`
 * refresh page

When done debugging, it can be disabled with `delete window.localStorage.flowplayerDebug`

**Comment by nnarhinen** [comment]
Please try with http://demos.851f.flowplayer.me/

**Comment by bbbo** [comment]
seems to be fixed; I do get errors n the console, but volume is there from the beginning
