### ISSUE TITLE
Optionally start with subtitles present, but disabled

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#848]
`disableSubtitles()` has no effect on load or on ready. Eearliest oportunity is something like:
```js
flowplayer(function (api) {
  api.one("progress.nosub", function (e, api) {
    api.disableSubtitles();
  });
});
```
And if there's a subtitle at pos 0, it will still appear, unless one hides it with a CSS rule.
This should be easier to acchieve.
See:
https://flowplayer.org/forum/#!/setup:how-to-no-subtitles-on-th

**Comment by nnarhinen** [comment]
@blacktrash I don't know about the current HTML5 video tag implementations amongst browsers, but looking at the documentation of `<track>` the `default` property should be used for this.

So I propose that if no subtitles are defined with `default: true` then no subtitles are shown by default.

And the first one with `default: true` will be picked as the initial subtitle.

**Comment by blacktrash** [comment]
Makes absolute sense :+1: 
Just to avoid any misunderstanding: the menu will be displayed, but subtitles only upon manual selection from the menu.

**Comment by nnarhinen** [comment]
Yes, that's exactly how I thought it should behave.

**Comment by blacktrash** [comment]
Go for it then ;-)

**Comment by nnarhinen** [comment]
http://demos.856f.flowplayer.me/basics/subtitle.html -- seems to work as supposed, right?

**Comment by blacktrash** [comment]
Right - on to updating demos with default attribute :+1:

**Comment by blacktrash** [comment]
Hang on, there's a problem at least with poster setups if the first sub is at position 0: it disappears when playback starts. Same goes for the default attribute.
http://flowplayer.blacktrash.org/fp6/minimal.html

I encounterd the same problem with the workaround, see my answers at:
https://flowplayer.org/forum/#!/setup:how-to-no-subtitles-on-th

**Comment by nnarhinen** [comment]
```js
api.one("progress.nosub", function (e, api) {
  api.disableSubtitles();
});
```

Wouldn't you expect it to dissapear when you start playback?

**Comment by nnarhinen** [comment]
If I open the console in first frame mode and say `flowplayer(0).off('progress.nosub');` the subtitles stay as supposed.

**Comment by blacktrash** [comment]
arrgh - I used that demo as example in the forum and forgot to remove the workaround before testing - no problem in player, but PEPKAC.

**Comment by 737330613** [comment]
رووووووووووعه
