### ISSUE TITLE
analytics: use long hearbeat interval

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#852]
Current implementation - see: #644 - uses progress event. The progress interval is too short:
- will stop tracking after 500 hits
- most probably entails a performance hit

Use GA tracker functionality directly, up the interval.
See: http://stackoverflow.com/questions/19059919/google-analytics-real-time-active-page-keep-alive

**Comment by nnarhinen** [comment]
http://demos.855f.flowplayer.me/ should implement heartbeat every 10 minutes. I have no idea how to test this, @bbbo @blacktrash do you have any test setups?

**Comment by blacktrash** [comment]
Nope, I don't.

**Comment by bbbo** [comment]
I created an analytics account for fp; will try to dive into the details...
