### ISSUE TITLE
splash setup does not unload while embed code is shown

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#857]
1. go to http://demos.flowplayer.org/basics/splash.html
2. start a player
3. show embed code (do not close embed code field)
4. start a different player
5. first player does not unload

Already present in version 5.

**Comment by nnarhinen** [comment]
Git history does not tell, but I guess the original reason is to not unload when esc key is hit when embed dialog is open.

**Comment by nnarhinen** [comment]
No, that cannot be the case, esc does not unload.

**Comment by blacktrash** [comment]
I think esc did at some point, and I only allowed q because esc is builtin fullscreen exit in most (not all: Safari) browsers.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/basics/splash.html
