### ISSUE TITLE
Video file not found with -480p.avi extension

### ISSUE THREAD

**Issue by thanpolas** [flowplayer/flowplayer#859]
Hello,

We've been converting all our videos from their raw form to mp4 using ffmpeg, and save the new encoded files as `[filename]-480p.avi`.

Apparently FlowPlayer doesn't like that producing an error of:

```
html5: Video file not found

http://localhost:3000/media/clips/55800ce452a8c5deb18a8fe0-480p.avi
```

The problem persists if `_480p.avi` extension is used.

Both the raw file and the newly encoded files are in the same folder.

I am using FP 6.0.1 and I initialize FP through the JS API using a single source:

```js
    flowplayerConfig.clip = {
      sources: [{
        type: 'video/mp4',
        src: clipUrl,
      }],
    };

    var fl = flowplayer($player, flowplayerConfig);
```

**Comment by bbbo** [comment]
as per https://github.com/flowplayer/flowplayer/blob/master/CONTRIBUTING.md , please post problems in the forums first, along with a public example page. AVI is not really the container of choice for MPEG-4, it should be MP4. Please have a look at the [encoding docs](https://flowplayer.org/docs/encoding.html) as well.
Also make sure the videos are served with the correct MIME type: video/mp4 .
