### ISSUE TITLE
Flash: keep aspect ratio in the swf code, like swfHls does

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#866]
For Flash RTMP and progressive download the aspect ratio when going fullscreen is still calculated in JS. This falls short in scenarios like our video art demo:
http://flowplayer.blacktrash.org/fp6/art.html - simulates fallback to RTMP, go fullscreen
swfHls does this:
http://flowplayer.blacktrash.org/fp6/art-hls.html - different video because we currently don't have the art video available in HLS

A far more common case are playlists with varying aspect ratio, where the `flashfit` option must be set to recalculate the ratio via JS, but at the price of the player becoming non-responsive (no expensive on window resize implemented)  - resize window at http://demos.flowplayer.org/playlist/ratio.html during playback.

Adapting the code from swfHls should get rid of the ugly option and solve the problem where it should be solved.

**Comment by nnarhinen** [comment]
http://demos.868f.flowplayer.me/

**Comment by nnarhinen** [comment]
Also #868

**Comment by blacktrash** [comment]
Hm, doesn't do the trick yet: http://demos.868f.flowplayer.me/playlist/ratio.html - also tested without `flashfit` locally.

**Comment by nnarhinen** [comment]
Works for the fullscreen-toggle. Didn't check your playlist example.

**Comment by nnarhinen** [comment]
http://demos.868f.flowplayer.me/playlist/ratio.html now seems to work. This also removes the `flashfit` configuration completely.

**Comment by blacktrash** [comment]
YES! this is the best thing since sliced bread!

**Comment by blacktrash** [comment]
Tested successfully in conjunction with `adaptiveratio` as well.
