### ISSUE TITLE
Fullscreen toggle not available on touch devices when player is in iframe

### ISSUE THREAD

**Issue by zwerfkat** [flowplayer/flowplayer#869]
When using the player inside an iframe or frameset, the fullscreen toggle isn't always available. This is desired behavior on a desktop, but not for touch devices like Android/IOS phone or tablet. These devices can perfectly play full screen using their native html5 player. 

As a workaround I have changed the following lines:

   // no fullscreen in IFRAME
   try {
      if (!conf.fullscreen) common.removeNode(fullscreen);

   } catch (e) {
      common.removeNode(fullscreen);
   }

into:

   // no fullscreen in IFRAME
   try {
      if (!flowplayer.support.touch && !conf.fullscreen) common.removeNode(fullscreen);

   } catch (e) {
      common.removeNode(fullscreen);
   }

**Comment by blacktrash** [comment]
Not sure I understand: imho that will make the player fill the iframe - and not go fullscreen - on touch devices which support inline video (iPad), and on devices which do not support inline video you are in the native "fullscreen" player anyway?
Why not just set `native_fullscreen: true`, like in our demo which embeds using an iframe: https://flowplayer.org/demos/qsel/#drive-iframe-js ?

**Comment by zwerfkat** [comment]
Option `native_fullscreen` is already set to true. I simply made the following test file (without allowfullscreen):

`<html><body>`
`<iframe src="https://flowplayer.org/standalone/skins/functional.html" frameBorder="0" width="1000" height="500"></iframe>`
`</body></html>`

As expected no fullscreen button in the right upper corner on desktop browsers because the player is in an iframe, but also no fullscreen button on my Android Chrome or Opera browser.

**Comment by blacktrash** [comment]
??? that demo in your iframe hasn't set `native_fullscreen: true`, so it would just fill the iframe and not go fullscreen - at least that's what happens on iPad.

**Comment by zwerfkat** [comment]
The problem is that (at least on Android) there is no full screen button at all... So there is simply no possibility to fill up the iframe (or going fullscreen when native_fullscreen has been set). When I use https://flowplayer.org/demos/qsel/#drive-iframe-js as the src of the iframe I do get exactly the same results. Maybe it is an Android thing?

**Comment by blacktrash** [comment]
Even when you set `fullscreen: true`?

**Comment by blacktrash** [comment]
iow, you cannot go fullscreen at http://demos.flowplayer.org/basics/embedded-iframe.html ? (that's the result page)

**Comment by zwerfkat** [comment]
Yes I can. But I am talking about the situation where fullscreen is NOT possible on a desktop browser because of an iframe (without iframe property `allowfullscreen`).

**Comment by blacktrash** [comment]
That is consistent behaviour though, isn't it?

**Comment by blacktrash** [comment]
If you decide to offer the iframe not allowing fullscreen, or the embedding party removes the attribute, then that's exactly what happens, and an inline playback capable touch device behaves the same.

**Comment by blacktrash** [comment]
You want `native_fullscreen: true` to override `fullscreen: false`, do I understand correctly?
Personally I think this would be inconsistent.

**Comment by zwerfkat** [comment]
I think I have mixed up iframe with frameset, sorry about that. For an iframe this would probably the best way indeed, but I use a frameset. And a frame within a frameset does not have peoperty `allowfullscreen`. With the following code:

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"`
`"http://www.w3.org/TR/html4/frameset.dtd">`
`<html>`
`<frameset rows="100%">`
`<frame src="https://flowplayer.org/standalone/skins/functional.html">`
`</frameset>`
`</html>`

I do not get a fullscreen button. But I want to give my clients as much as flexibility to go fullscreen, and I do own both domains (for frameset and player). Any idea how this can be achieved? Or when I use `http://demos.flowplayer.org/basics/embedded-iframe.html` as source, I do always get the fullscreen button, while this button does nothing in desktop browsers.

**Comment by blacktrash** [comment]
You should probably rethink your setup. The `frameset` tag is not supported in HTML5, and you _must_ set the HTML5 DOCTYPE for Flowplayer (or video tags for that matter) to work properly in all browsers, especially IE: https://flowplayer.org/docs/setup.html#doctype

**Comment by nnarhinen** [comment]
Please continue this discussion on [Flowplayer Forums](https://flowplayer.org/forum/).

If there really is an issue with the player that can be fixed, please re-open with links to minimal live pages that represent this issue.
