### ISSUE TITLE
IE: load(clip) and setPlaylist() not reliable

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#870]
Our demo https://flowplayer.org/standalone/playlist/javascript.html fails _sometimes_ (unfortunately w/o error) in IE when the playlist is replaced: white screen, and sometimes video not found.

See: https://flowplayer.org/forum/#!/setup:issues-when-reloading-vid - you have to dig into the thread. Problem confirmed by @bbbo.

**Comment by blacktrash** [comment]
Maybe the `play(0)` call comes to early (although it's even bound to the return of a conditional), I could try it in a `one("ready")`, but there we're entering workaround territory.

**Comment by blacktrash** [comment]
@bbbo - can you test http://flowplayer.blacktrash.org/fp6/javascript.html wether you can still repro?
@nnarhinen - something interesting:
What I do on that page is, after `setPlaylist()`:
```js
jsPlaylistApi.one("ready", function (e, api) {                                                                  
  api.play(0);                                                                                                
});                                                                                                             
jsPlaylistApi.load();
```
Now, if I do the same in the "load" event, it will play the first clip of the **previously** compiled playlist, and only reset itself to the new playlist e.g. on replay.

**Comment by blacktrash** [comment]
So it looks like `setPlaylist()` goes into action only after the first "ready" which is encountered, and maybe IE's handling of `play(0)` gets into some kind of race condition.

**Comment by blacktrash** [comment]
@bbbo tested a looping playlist http://flowplayer.blacktrash.org/fp6/playlist-loop.html and could repro the problem as well after some time - so there the problem is actually deeper: with `load(clip)`.

**Comment by nnarhinen** [comment]
On which IE version do you encounter this? Can't reproduce on IE9 at least.

**Comment by bbbo** [comment]
confirmed this in IE11 at least, and I think IE10 as well. I'll check again

**Comment by nnarhinen** [comment]
@bbbo can you try http://codepen.io/anon/pen/zGLNPN

it is using the assets from #892

**Comment by bbbo** [comment]
this seems to behave well; changed the playlist a dozen of times and switched the clips even more, so far without an error.

**Comment by nnarhinen** [comment]
Yeah. I removed some old timer hack for some safari scenario / version. Unfortunately the commit was not bound to any issue so I can't be 100% this does not introduce a regression for some safari version / setup combinations.
