### ISSUE TITLE
Events not able to be prevented

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#874]
As you could with Flowplayer 5 events cannot be fully prevented unless I missed something ?. 

The documentation states preventDefault and stopPropogation will stop the internal events but it doesn't seem to do anything. 

I've noticed I can block events if I set them up within jquery ie $(timeline).on . but player.on or bean.on cannot prevent defaults. 

The error screen is not customisable if at all and displays alot of things that aren't configurable including a disabled flash message. All that needs to go with a singular message for offline status that is still clickable. That is the intention therefore need to override the error event.

**Comment by nnarhinen** [comment]
Please show (in code or live pages) what you would like to accomplish.

**Comment by danrossi** [comment]
Pretty straight forward. any "preventDefault" on events. 

ie
```
player.on("error", function(event, api, error) {
event.preventDefault();
});
```

That does not work. I found these elsewhere on element events that use "bean" unless I used jquery then it wouldn't fire the internal ones ? ie if I tried

```
bean.on(root, 'mousemove', '.fp-timeline', function(event) {
event.preventDefault(); 
event.stopPropagation();
});
```

Does not work however

```
 $(timeline).on("mousemove",function(event) { 
event.stopPropagation();
});
```
Does.

The error screen is too prohibitive and not customisable and it disables the player. Resetting the message is fine in another error callback ie
```
 common.find('h2', el)[0].innerHTML =  "message";
common.find('p', el)[0].innerHTML = "";
```

And also need to take this out. This is uneccessary

```
  common.removeNode(common.find('.fp-flash-disabled', root)[0]);
```

But prefer nothing happening internally. 

For a live stream there should be the option of trying again ?  

Is there a way to re-enable the player + flash engine ? It has become an apparent requirement to replicate what it used to be able to do in Flowplayer 3 ;) Somewhere it is disabling the flash. 

Thanks.

**Comment by danrossi** [comment]
Ive got this partially working. on error screens, clicking is broken because it detects "fp-message" as the target. So I have to setup a seperate root click and reload the video

```
bean.on(root, "click.player", replay);
```

Also remove all these flags, well quite a bit of flags including the engine as the flash externalinterface object is broken and throws errors. 

```
 api.error = false;

            //undisable the player
            player.disable(false);

            //set all these flags to get playback working
            api.ready = false;
            api.paused = false;
            api.loading = false;
            api.playing = true;
            api.engine = null;

            //enable clicking again from errors
            api.on("mouseenter click");
```

Still preventing default on the error event or any other event would be good.

**Comment by nnarhinen** [comment]
Did `preventDefault()` really work on FP5 error event?

I have always used on FP6 something like this:

```js
api.bind('error', function() {
  root.removeClass('is-error');
  api.error = false;
  api.loading = false;
  // Do something else
});
```

also: http://demos.flowplayer.org/scripting/recover.html

**Comment by danrossi** [comment]
prevent defaults work when using jquery yes. If I still setup an event using jquery not the bean events it prevents the internal events but not when trying to use the bean events ? 

It seems you have to specify the prevent default check and it's only on a few event callback methods not all of them ? 

I have now just run into another problem when unbinding "local" player events turns off the internal ones simply by calling "off" 

 player.off("resume", onResume);

I just want to unlisten on a local event and turn it back on when needed ? The play button does not toggle  because the resume event gets disabled inside the player.

**Comment by nnarhinen** [comment]
http://codepen.io/anon/pen/LVBdQz

The `error` event wasn't cancelable on FP5 either.

Only the `load` and and `beforeseek` events have currently the mechanism of canceling the action. I'm not really sure what is the 'default' action that should be canceled if `ev.preventDefault()` is called on error. On `load` and `beforeseek` it's clear: loading and seeking should be canceled.

On `error` the UI updating is the result of an `error` handler. Even on standard DOM `click` handlers *all* `click` handlers are fired even though one of the handlers calls `preventDefault`. So if you would like `preventDefault` in an  `error` handler to cancel the UI showing the error state and message, it would mean flowplayer would have to *unbind* all other error handlers and that would be against any expected behavior.

**Comment by nnarhinen** [comment]
Please open individual minimal issues with *links*  to example *minimal* setups that misbehave with clear descrption what you would like to accomplish.

Now you have reported multiple issues in this same thread and I at least have lost track.

**Comment by danrossi** [comment]
var playBtn = common.find(".fp-toggle, .fp-play", root)[0];

    playBtn.addEventListener("click", function(event) {

      
            event.preventDefault();
            event.stopPropagation();
          
    });

I have to do this to overriding the play button toggling also. So some of the ui is ok like 

```
    bean.off(root, "click.player");
    bean.on(root, "click.player", function(e) {
```

But then others are not.

 It seems there is various issues with the "bean" api. So Jquery and raw event functions works. Perhaps it's a priority thing which only can be set using "addEventListener"

I guess if you've closed it it means won't fix so at least I know how to hack something that is supposed to be "flexible"

**Comment by blacktrash** [comment]
See: http://demos.flowplayer.org/lookandfeel/controls-only.html

**Comment by nnarhinen** [comment]
@danrossi As I said - open new individual simple issues with links to an issue or sample code. One problem per issue. If you just need help with scripting you can turn to our forums.
