### ISSUE TITLE
playlist: is-active not applied to playlists outside container

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#876]
Functionality is there. But the `active` class is not applied: http://flowplayer.blacktrash.org/fp6/playlist-outside.html

See also: https://flowplayer.org/forum/#!/setup:jquery-selector-for-trigger

**Comment by nnarhinen** [comment]
http://codepen.io/anon/pen/ZGRmpQ is using the assets from #890 and seems to work

**Comment by nnarhinen** [comment]
@blacktrash assigning this to you for testing

**Comment by blacktrash** [comment]
Confirming fix and closing. Thank you.
