### ISSUE TITLE
jQuery JS install triggers error (regression in 6.0.2)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#877]
EDIT: Narrowed down the issue, see [below](https://github.com/flowplayer/flowplayer/issues/877#issuecomment-116600102).

http://flowplayer.blacktrash.org/fp6/speed-601.html version 6.0.1 (works, although there is an error when leaving or reloading the page).
http://flowplayer.blacktrash.org/fp6/speed.html version 6.0.2 (error)

Will use `swfHls: false` as temporary work around at http://demos.flowplayer.org/api/speed.html

**Comment by blacktrash** [comment]
This is actually caused by the jQuery install incantation, not source picking related - see https://github.com/flowplayer/demos/commit/b783993c8f7d07096bbbfbdc56e2d5972ae89786

**Comment by blacktrash** [comment]
This can be narrowed down to a manual jQuery install with a JS clip configuration:

```js
$(function () {
  $("#player").flowplayer({
    ratio: 9/16,
    splash: true,
    clip: {
      sources: [
        { type: "application/x-mpegurl", src: "//stream.flowplayer.org/drive.m3u8" },
        { type: "video/webm",            src: "//stream.flowplayer.org/drive.webm" },
        { type: "video/mp4",             src: "//stream.flowplayer.org/drive.mp4" }
      ]
    }
  });
});
```
The above works in version 6.0.1, but not in 6.0.2.

This is already discouraged in the docs: https://flowplayer.org/docs/setup.html#javascript-install :

------

If the jQuery library is loaded, flowplayer() can also be invoked as jQuery extension like in the VIDEO tag based installation methods with the player configuration including clip in the first argument:
```js
$("#player").flowplayer({
    // mandatory player and clip configuration goes here
});
```
*Warning* The jQuery invocation syntax is strongly discouraged for this installation method because it will not give instant access to the Flowplayer JavaScript API and blurs the structure of the code.

-------

Personally I'm also fine with *disallowing* the scenario. Probably will have to add something to the migration notes then.
@nnarhinen ?

**Comment by nnarhinen** [comment]
http://codepen.io/anon/pen/LVBxJQ is using the assets from #893, please confirm fix

**Comment by blacktrash** [comment]
Fix confirmed: http://flowplayer.blacktrash.org/fp6/speed.html :+1:
