### ISSUE TITLE
ipad: duration/remaining inside timeline for videos longer than 1hr

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#878]
Can be observed at
http://demos.flowplayer.org/basics/long.html
http://demos.flowplayer.org/basics/splash.html
etc.

**Comment by nnarhinen** [comment]
Actually can be generalized to `.no-long.no-volume` which breaks the positioning.

**Comment by nnarhinen** [comment]
http://demos.889f.flowplayer.me/basics/long.html should be fixed, my ipad battery is dead atm, please confirm :)

**Comment by nnarhinen** [comment]
Found life to the iPad, fix confirmed by me.
