### ISSUE TITLE
Native subtitles need crossOrigin flag to work properly. 

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#880]
Trying to configure this option falls into CORS issues. See this error

"Text track from origin 'https://static.electroteque.org' has been blocked from loading: Not at same origin as the document, and parent of track element does not have a 'crossorigin' attribute. Origin 'http://localhost:8000' is therefore not allowed access."

The only problem is the general inconsistent support for "crossorigin" attributes across browsers for various tags and general VTT text track support. IE seemed it was a good idea to leave it out  I believe, perhaps Safari also like they have for the video tag requiring cross origin work arounds.  Firefox seemed to think it was a good idea to not implement cue change events.  

So in general do not use this option ?

**Comment by blacktrash** [comment]
It's pretty clear from the docs that we discourage the use of this option:
https://flowplayer.org/docs/subtitles.html#player-options

------

*Warning* Support for loading VTT files from a different domain for native subtitle display is broken in most browsers.

------

Plus the option is marked in red.

Furthermore it is explained that we disable embedding in our demo for that reason: https://flowplayer.org/docs/subtitles.html#native-subtitles

See also: https://flowplayer.org/docs/known-issues.html
