### ISSUE TITLE
Flash engine reports invalid volume for zero

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#882]
While playing a video with the flash engine (flashls, rtmp or mp4, does not matter) sliding the volume switch to zero or pushing mute button volume in `volume` event is reported as `undefined` instead of `0` which causes `api.volumeLevel` to ultimately become `NaN` which causes invalid behavior for subsequent `load()` calls, for instance in the quality selection plugin.

**Comment by blacktrash** [comment]
Can be obvserved with simple load call here: http://demos.flowplayer.org/api/load.html

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/ should have this fixed, can you confirm?

**Comment by bbbo** [comment]
the behavior seems better, but a minor problem remains: when muting in the Flash engine (qsel demo), the muted icon disappears when switching to manual selection (html5 engine) and you need to drag the volume slider to get sound 8which then shows the muted
![flowplayer quality selection plugin for drive_2015-07-13_15-30-54](https://cloud.githubusercontent.com/assets/1395672/8650637/6bbdab6a-2974-11e5-9579-c03fe160ed81.png)
 icon)

**Comment by nnarhinen** [comment]
Should be fine now.
