### ISSUE TITLE
data-autoplay and player.autoplay have no effect with html5 engine in VIDEO tag installs

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#883]
E.g.
```html
<div class="flowplayer" data-autoplay="true" data-ratio="0.4167">
  <video>
    <source type="video/webm" src="//stream.flowplayer.org/playful.webm">
    <source type="video/mp4"  src="//stream.flowplayer.org/playful.mp4">
  </video>
</div>
```
does not autoplay, and playback cannot be started. Configuring `autoplay: true` on player level does not help either, only video tag attribute works.

No problem with Flash engine, or in a JS install.

**Comment by nnarhinen** [comment]
@blacktrash Please test with assets from http://demos.887f.flowplayer.me/

**Comment by blacktrash** [comment]
works :+1:
