### ISSUE TITLE
play() is not working on iOS

### ISSUE THREAD

**Issue by slavafomin** [flowplayer/flowplayer#884]
Hello!

We've stumbled on an issue with Flowplayer in one of our projects. We are using API's `play()` function to trigger video playback. It works flawlessly on almost any platform, except iOS.

The issue is confirmed at least on iOS 8.3/8.4.

I've isolated the problem in a Plunk:
http://plnkr.co/edit/QlVh2AAaEvkJcQ6tOTFC?p=preview

What could be the issue? Thanks.

**Comment by blacktrash** [comment]
You are trying to circumvent that iOS prevents autoplay. See http://flowplayer.org/docs/known-issues.html
On most mobile devices playback can only be started by user interaction.

`play()` (without argument the synonym for `load()`) or `play(index)` work otherwise, also on iOS.

**Comment by slavafomin** [comment]
Oh, I see. Is this a programmatic or political limitation? We're developing a page where pre-recorded videos should start on a specific time schedule and it would be highly unusable for our clients to start each video manually.

**Comment by blacktrash** [comment]
It's a device limitation, which cannot be worked around. It's not Flowplayer related, you verify that yourself with a plain video tag:
```html
<video id="vtag" controls width="640" height="360">
<source type="video/mp4" src="myvideo.mp4">
</video>
<script>
setTimeout(function () {
  document.getElementById("vtag").play();
}, 3000);
</script>
```
The reason for this is most likely "political" in the sense that a lot of users would complain if video playback started without being asked for over an expensive mobile connection.
But if there was a way to work around it, we would have implemented it by now ;-)

**Comment by slavafomin** [comment]
Thank you Christian, you are most helpful, as always = )

By the way, if I trigger `play(0)` from the click on a button event, will it play?

Also, it looks like player is broken after I try to play it on iOS. The video loads, buffers, I can seek it manually, but there is no way to play it, no play button and such.

The interesting aspect of it is if video is fully buffered (i.e. downloaded), what is the meaning of this limitation?

**Comment by blacktrash** [comment]
Flowplayer is tested heavily on iOS, so if you encounter the problem at one of our demos, please provide the link. Otherwise please turn to our forum with a link to a *minimal* sample page demonstrating the problem.
