### ISSUE TITLE
fp-next playlist overlayed control not visible in full screen mode

### ISSUE THREAD

**Issue by SteveAATW** [flowplayer/flowplayer#894]
When using the player with playlist functionality where the fp-next and fp-prev controls are overlayed on top of the player itself, when the player is sent full screen, the fp-next control disappears.

This is visible on the demo of the functionality: http://demos.flowplayer.org/playlist/prev-next-overlayed.html

![screen shot 2015-07-19 at 23 45 19](https://cloud.githubusercontent.com/assets/8937625/8768236/5b01fcee-2e70-11e5-8223-e966445f8317.png)

![screen shot 2015-07-19 at 23 45 26](https://cloud.githubusercontent.com/assets/8937625/8768239/5fe41c42-2e70-11e5-9218-1de5a904a123.png)

Looking at the rendered HTML, it appears the fp-next anchor is created outside the fp-player div, whilst the fp-prev control is inside of it. 

![screen shot 2015-07-19 at 23 42 10](https://cloud.githubusercontent.com/assets/8937625/8768217/dd2f0eec-2e6f-11e5-9b44-1811070fb86c.png)

By moving the fp-next anchor inside the fp-player div, the control becomes visible again in full screen mode.

**Comment by blacktrash** [comment]
@SteveAATW, well spotted, thank you. I somehow managed to forget to report this when reworking the demos.

**Comment by nnarhinen** [comment]
http://demos.896f.flowplayer.me/playlist/prev-next-overlayed.html

Seems to fix the problem. (Icons not working on the adhoc site, but that's not related)

**Comment by blacktrash** [comment]
Confirming that this fixes the problem. `.fp-prev` and `.fp-next` both inside `.fp-player` wrapper.
