### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by liquidleaf** [flowplayer/flowplayer#895]
I want to use [Sourcegraph](https://sourcegraph.com) for flowplayer code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/flowplayer/flowplayer. (It should only take 30 seconds.)

Thank you!

**Comment by bbbo** [comment]
@nnarhinen please review

**Comment by nnarhinen** [comment]
Flowplayer can be deemed as blackbox software, you don't need to touch the code internals.
