### ISSUE TITLE
6.0.3: live option not recognized on clip level with generic HLS

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#898]
View http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html in a HLS capable client.
Also fails if it's only one clip.

**Comment by blacktrash** [comment]
Regression from 6.0.2.

**Comment by blacktrash** [comment]
It might be that this only affects the skin (duration display). At least while the live stream is playing I get `true` for `flowplayer(0).video.live`.

**Comment by blacktrash** [comment]
@nnarhinen - something removes the `is-live` class right after (or on) ready, it is still there when checked exactly on ready.

**Comment by blacktrash** [comment]
May be confined to Mac OS Safari - does not happen on iOS.
@nnarhinen - I think I have a fix.

**Comment by blacktrash** [comment]
@bbbo - fix can be tested on Android here: http://demos.899f.flowplayer.me/playlist/vodpreroll-livefeature.html

**Comment by blacktrash** [comment]
@bbbo - this fix should be tested with VOD as well: http://demos.899f.flowplayer.me/basics/hls.html

**Comment by blacktrash** [comment]
In view of #900 both demos must be tested on both devices which do not need enforcing of live and those which do.
This fix must not break the live enforcement, if it fixes the playback problem of #900 on other devices which do not need the live enforcement, that's of course a nice extra.

**Comment by nnarhinen** [comment]
I guess this can now be closed?
