### ISSUE TITLE
Android: live stream only audio if not 1st item of playlist

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#900]
@bbbo - for testing:
http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html

See: https://flowplayer.org/forum/#!/setup_configuration:hls-audio-no-video - further down in thread.

**Comment by bbbo** [comment]
http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html worsk for me, plays pre-roll and the live stream, it just does not switch to is-live but shows "Infinity: NaN" for the running time

**Comment by bbbo** [comment]
the fix in https://github.com/flowplayer/flowplayer/issues/898#issuecomment-124975810 solves this for me on the Nexus 5 and the Galaxy Tab 2. http://demos.899f.flowplayer.me/playlist/vodpreroll-livefeature.html plays fine on both.

**Comment by blacktrash** [comment]
Ah, so the demo work around is also needed for Android - will revert the additional condition.

**Comment by bbbo** [comment]
at least is fixed the Infinity: NaNaN problem in http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html (see #900 )

**Comment by blacktrash** [comment]
Yeah, the inifity thing is not specific to this issue. This one is just about playback.

**Comment by blacktrash** [comment]
@bbbo - so the live stream plays OK on all _your_ devices?

**Comment by bbbo** [comment]
with the fix, it plays in all devices I own, including the Moto G (where the original demo doesn't work, it shows the symptoms (loading dots and audio in the background).

**Comment by blacktrash** [comment]
You are saying the fix for #898 also fixes this one? iow
http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html does not play
but
http://demos.899f.flowplayer.me/playlist/vodpreroll-livefeature.html does play
?

**Comment by bbbo** [comment]
yes, for the Moto G where the symptoms in https://flowplayer.org/forum/#!/setup_configuration:hls-audio-no-video were visible.

I'll test in more depth tomorror.

**Comment by geniuswebsk** [comment]
I can confirm that it works also on Honor 3c - android with chrome, previously, it wasn't working. But, buttons disappeared, only transparent areas where buttons should be placed remain visible (play button, embed button, full screen button).

**Comment by blacktrash** [comment]
@geniuswebsk - the button thing is to be expected because dev assets are served w/o the required CORS needed for the skin fonts, nothing to worry about in this context.

**Comment by geniuswebsk** [comment]
Hello Christian, do you know app. time when new version with fix will be
available to download?

2015-07-27 21:41 GMT+02:00 Christian Ebert <notifications@github.com>:

**Comment by blacktrash** [comment]
@geniuswebsk - for the moment you can grab http://cdn.899f.flowplayer.me/adhoc/flowplayer.min.js and deploy it yourself.

**Comment by geniuswebsk** [comment]
Perfect, and what about button showing "issue" which I mentioned
previously? Is it coded somewhere else? Or it is  included in css file?

Many thanks Christian.

2015-07-28 11:31 GMT+02:00 Christian Ebert <notifications@github.com>:

**Comment by blacktrash** [comment]
Just use the 6.0.3 skins you are currently using. There is no change there.
Just to be clear: do not load this from http://cdn.899f.flowplayer.me but download and deploy yourself - until the next release is out.

**Comment by nnarhinen** [comment]
@blacktrash So is there an actual issue left for this one?

**Comment by blacktrash** [comment]
http://demos.899f.flowplayer.me/playlist/vodpreroll-livefeature.html
I can't vouch for Android, but according @bbbo yes, only for the Mac OS Safari part concerning https://github.com/flowplayer/flowplayer/issues/898.

**Comment by nnarhinen** [comment]
Can you please tell me the status of this issue. I'm lost. What example does not work and on which device?

**Comment by nnarhinen** [comment]
Removing from the 7.0 milestone from now, please re-add or alternatively close.

**Comment by blacktrash** [comment]
@bbbo - can you test http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html on Android, please? In browserstack it does not work. Can't be a problem with the live stream because it works otherwise.
We are now using the hlsjs engine there, so it might be related to that.

**Comment by blacktrash** [comment]
With the hlsjs engine it fails on
```js
 bean.one(video, 'canplay', function() {                                                                        
  video.play();                                                                                               
});
```
in core: https://github.com/flowplayer/flowplayer/blob/master/lib/ext/mobile.js#L111-L113

<img width="839" alt="screen shot 2016-10-19 at 2 24 15 pm" src="https://cloud.githubusercontent.com/assets/168338/19520338/d0a0a41e-9607-11e6-9bc7-8aaa629f4fe4.png">

The strange thing is that this is not a problem with VOD playlists, and also not with the html5 engine.
- http://flowplayer.blacktrash.org/fp6/vodpreroll-livefeature.html (with hlsjs)
- http://flowplayer.blacktrash.org/fp6/vodpreroll-livefeature.html?hlsjs=false (without hlsjs)

**Comment by blacktrash** [comment]
It's also not related to an engine switch, again the same scenario works with VOD: mp4 -> hlsjs.

**Comment by blacktrash** [comment]
@bbbo - http://demos.flowplayer.org/playlist/vodpreroll-livefeature.html should now work in Android - because it now uses HLS for the VOD pre-roll too.
I will close this here. Has to be sorted out - if at all possible - at flowplayer/flowplayer-hlsjs#50.
