### ISSUE TITLE
RTMP: src location w/o prefix considered as HTTP

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#901]
Regression from 6.0.1:
http://flowplayer.blacktrash.org/fp6/rtmp.html
rtmp://s3b78u0kbtx79q.cloudfront.net/cfx/st/flowplayer-700 is a valid rtmp location, but only works if the url part is prefixed with `flv:` (or `mp4:` or similar). Without prefix the player thinks it's a local http path.
In some cases - live streams - prefixing the url part might not work.

**Comment by blacktrash** [comment]
https://flowplayer.org/forum/#!/setup:flowplayer-603-doesnt-pl

**Comment by TapaniJVeikkaus** [comment]
Hi all, you've propably answered this, but I ask again. What is the fixing schedule for this https://github.com/flowplayer/flowplayer/issues/901 ?

**Comment by foliovision** [comment]
We are having this issue as well.

**Comment by nnarhinen** [comment]
@blacktrash Do you remember why https://github.com/flowplayer/flowplayer/commit/3eea290fcc6fd474697c19198c251fbc71253b45 was introduced. This is exactly why one should always tie commit messages to issues :(

**Comment by nnarhinen** [comment]
http://demos.953f.flowplayer.me/ and the assets there. @blacktrash could you check? Not elegant but works..

**Comment by blacktrash** [comment]
Not for me: http://flowplayer.blacktrash.org/fp6/rtmp.html - see also my comment here: https://github.com/flowplayer/flowplayer/commit/ec83e2c61d80722df22dd70783694d9cc15d3aba#commitcomment-14245895

**Comment by nnarhinen** [comment]
Yeah, that's because I used the wrong url.. http://demos.954f.flowplayer.me/ also moved the converting to `engine.pick`

**Comment by blacktrash** [comment]
http://flowplayer.blacktrash.org/fp6/rtmp.html works now as expected. :+1:
