### ISSUE TITLE
Wowza rtmp: lag on replay of short clips

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#902]
http://flowplayer.blacktrash.org/fp6/wowza-rtmplag.html
- replay 1st example: notice incremental lag
- replay 2nd example (fms): works
- replay 3rd example (wowza, slightly longer clip): no lag

Regression from version 5.x:
http://flowplayer.blacktrash.org/fp5/wowza.html (no lag on replay)

See:
https://flowplayer.org/forum/#!/setup:flowplayer-6-rtmp-lagging

**Comment by nnarhinen** [comment]
Demo does not work anymore.

**Comment by blacktrash** [comment]
Sorry, should be back now.

**Comment by mdargavel** [comment]
Is there an estimated release date for 6.0.5? This bug was part of 6.0.4 but was not fixed in that one. This is holding us from upgrading from 5 to 6 and we need some kind of estimated date to notify our customers of when this will happen. Thanks!

**Comment by nnarhinen** [comment]
I'm baffled why this happens. Found something else too when debugging this.

For those short clips there's something obviously wrong with the counter implementation or something like this. The progress events are gone for subsequent replays for the short clips etc. Can be ovserved with this snippet:

```
flowplayer(function(ev, api) {
  api.on('progress', function(e,a,time) {
    if (time >= 4) { api.seek(0); }
  });
});
```

It only works for the first play for the short videos, no problem with the longer video.

**Comment by blacktrash** [comment]
The reason why it works with FMS, but no Wowza, could be Wowza's load balancing.
Maybe this https://github.com/flowplayer/flowplayer/commit/e7188399a474754274ef36578fd574a9ab4b2477 needs some tuning for very shorts.

**Comment by nnarhinen** [comment]
It's actually https://github.com/flowplayer/flowplayer/commit/c911eb580c1d4b30a78a9ae1cac4a967132a297a that introduced this

**Comment by nnarhinen** [comment]
That code is too much actionscript for me, @anssip can you check why that change would introduce this behavior.

**Comment by mdargavel** [comment]
Just looking for an ETA on this.. is it still looking like it will be released with 6.0.5? Thanks.

**Comment by anssip** [comment]
This smells like an issue that should be fixed by Wowza.

**Comment by bbbo** [comment]
seems it works for the users with FP5 though

**Comment by DanLirette** [comment]
This bug seems to be working fine now. Can you guys confirm if this was fixed?

Thanks,

**Comment by blacktrash** [comment]
In the demo it looks fixed, yes. But we did not change anything afaik.
