### ISSUE TITLE
MPEG-DASH support - Android playback issue + fix

### ISSUE THREAD

**Issue by ipernet** [flowplayer/flowplayer#910]
Hi

The official demo for MPEG-DASH http://demos.flowplayer.org/api/dash.html does not play correctly on  Android Lollipop (5.1.1) with latest Chrome version or Chrome Beta version.

The issue is that the player gets loaded but the video is unable to play, even when the user tries to interact with it (the player is stuck in playing mode without playing).

The issue is related to ```autoplay``` beeing disabled on mobile devices making ```<DASH Player>.setAutoPlay(true)```  (which is the case in splash-forced mode) not playing. The fix consists in triggering an explicit programmatic ```play()``` if autoplay is set (splash setup or desktop autoplay), which is working since directly following a user interaction.

Fix: https://github.com/ipernet/ipernet.github.io/commit/bcd315f92e2fadcbcfeb7556cdaa29ef7e5bf342 

Test: http://ipernet.github.io/flowplayer/flowplayer-mpegdash.html

**Comment by blacktrash** [comment]
Thanks.
I was just about to remove the or condition because a splash setup sets autoplay to true.
I don't have an Android device for testing here right now, but I can check whether the excplicit play() call breaks other stuff (poster setups etc.).

**Comment by blacktrash** [comment]
Hm, your demo does not work in desktop Chrome here. Can you make it use our mpd?

**Comment by ipernet** [comment]
hi @blacktrash, my mistake, I have updated the MPD!

**Comment by blacktrash** [comment]
@ipernet - thanks. Could you do me a favour and try this where you have the conditional `play()` on your android:
```js
if (!flowplayer.support.zeropreload && api.conf.autoplay) {
  videoTag.load(); // similar to iPad
}
```

**Comment by blacktrash** [comment]
And, on the slight off-chance that it is related to dash.js, could you use http://flowplayer-releases.s3.amazonaws.com/mpegdash/dash.all.js for testing? I've just updated it with the fix for end of video handling in Safari, I doubt that it matters here, but you never know.
Thanks.

**Comment by ipernet** [comment]
@blacktrash 

Test page updated with your snippet and with latest ```dash.js``` but this cause a JS error because ```api``` is undefined. 

For testing I have changed your snippet to get a reference to ```api.conf``` from ```engineImpl.canPlay```, this is not very clean but does not require ```flowplayer.js``` change https://github.com/ipernet/ipernet.github.io/commit/86dc0e5e9fd6dfaa3c339e37725cc510d270abfe

The result of this change makes the video plays correctly too on my Android.

**Comment by blacktrash** [comment]
@ipernet - sorry, not enough coffee, should have been:
```js
if (!flowplayer.support.zeropreload && player.conf.autoplay) {
  videoTag.load(); // similar to iPad
}
```
The plugin uses `player` as variable name (I should know ;-))

**Comment by ipernet** [comment]
@blacktrash 

Change reverted and snipped fixed https://github.com/ipernet/ipernet.github.io/commit/462933ff00d3d8ce18909bc79efaf70fbe0b5087

The playback works as expected on Android ("touch to play")

FYI on my Android ```flowplayer.support.zeropreload === false``` and ```player.conf.autoplay === true```, as expected

Thanks!

**Comment by blacktrash** [comment]
@ipernet - thank _you_ for pointing this out with a way to fix.
Plugin will be updated shortly.

**Comment by ipernet** [comment]
@blacktrash great!

FYI I have implemented a flowplayer plugin using Google Shaka player as engine provider to work around some issues. It's very similar to the Dash.js provider plugin, so I'll release it in the afternoon in case you might want to have a look (I'll test it on more devices when I can)

**Comment by blacktrash** [comment]
@ipernet - you can verify at http://demos.flowplayer.org/api/dash.html
Closing.

**Comment by ipernet** [comment]
@blacktrash 

Something is wrong on the link: it (still) does not play on touch (Chrome Android latest). Cache is clear and I can see the latest changes in the plugin script using a debug session on my mobile. 

On my test link (http://ipernet.github.io/flowplayer/flowplayer-mpegdash.html) where I use ```//flowplayer-releases.s3.amazonaws.com/mpegdash/dash.all.js``` and now ```//releases.flowplayer.org/mpegdash/flowplayer.mpegdash.js```, it's playing properly (Chrome Android)

- Firefox (Desktop) is also impacted (using both my link and the official one) - ```dash.js``` related issue I guess given that plugin change does not impact it.

- Chrome (Desktop) is OK.

**Comment by ipernet** [comment]
Note fore Firefox (Desktop, latest):

Works as expected ("play on click") with ```splash``` = ```false``` or unset.

**Comment by blacktrash** [comment]
Better wait with final diagnosis on the demo. You'd be surprised how persistent caches are.
@ipernet - which platform is that? Firefox 40 on Mac doesn't work for me, never did.

**Comment by ipernet** [comment]
@blacktrash Firefox 40.0.2, Windows 10.

**Comment by blacktrash** [comment]
@ipernet - FYI, I probably have to downgrade dash.all.js again, because while the very latest fixes end of video handling to a certain extent in Safari, it breaks playlist transitions both in Chrome and Safari (also related to end of video).

**Comment by ipernet** [comment]
@blacktrash I can't remember if the mpeg-dash demo was working on Firefox before, however after a few tests it looks like it is not an issue of the (1) dash engine and not an issue of the plugin code.

The following trick makes the playback working on Firefox 40+Win10+splash:true

```javascript
                        // Android requires extra load, like iPad
                        // https://github.com/flowplayer/flowplayer/issues/910
                        if (player.conf.autoplay) {
                          if( !flowplayer.support.zeropreload) {
                            videoTag.load(); // similar to iPad
                          } else if (player.conf.splash){
                            videoTag.play(); // Force playback for Firefox
                          }
                        }
```

Demo: http://ipernet.github.io/flowplayer/flowplayer-mpegdash.html

Other than that, regarding ```dash.js```, you may want to give a try to my first release of a shaka-player based engine for flowplayer, I'm looking for more testing, but I don't have "test suites" for flowplayer handy. The plugin shares almost the same code than the dash based one, but there is a chance this engine works better (or worse!) for playing MPEG-DASH.

http://ipernet.github.io/flowplayer/flowplayer-mpegdash-shaka.html

**Comment by blacktrash** [comment]
@ipernet - thanks, maybe I'll just simplify to:
```js
if (player.conf.autoplay) {
  videoTag.load();
}
```
It does not really hurt 'false' positives, there's also no extra event fired.

**Comment by blacktrash** [comment]
Thanks for the link to your work btw.

**Comment by blacktrash** [comment]
@ipernet - FYI, quite some problems with your shaka implementation in Mac OS Safari when seeking, even crashed.

**Comment by ipernet** [comment]
@blacktrash Let me do more tests on Firefox/win10, because as of *now* http://demos.flowplayer.org/api/dash.html works fine("click to play", splash:true, no cache).

Regarding shaka, I'll try to get some Mac handy to work on it!

**Comment by ipernet** [comment]
@blacktrash In fact it works because it has been updated ;) thanks!
