### ISSUE TITLE
flash hls: seeking beyond end of video causes undefined player state

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#911]
To repro:
1. http://demos.flowplayer.org/basics/hls.html in a browser needing flash hls
2. start playback
3. hit "9" to seek to 90% of duration
4. hit right arrow to seek to over 100% (by now)
5. play/pause has no effect anymore, a seek to a different position is required before the player becomes workable again

Beforeseek: If seek pos > duration; seek pos = duration
?

**Comment by nnarhinen** [comment]
Can you check at http://demos.dev94.flowplayer.us Should now be fixed

**Comment by nnarhinen** [comment]
The fix: seek is constrained to `api.video.duration - 0.1`. Can this become a problem?

**Comment by nnarhinen** [comment]
With FlashHLS one is not able to seek to the end anyway - to the closest keyframe start.

**Comment by blacktrash** [comment]
Should be ok, _looks_ like latest flashls is even more brutal:
https://github.com/mangui/flashls/issues/413
https://github.com/mangui/flashls/commit/fe1c1ec93170e94b3f1cf39158647fd3a6308691
https://github.com/mangui/flashls/commit/7736ac1714832b4aed6f4c04f958d91d2ea58016
Let's tread softly.

Aside: seek to keyframe is default, you can also `flashls: {seekmode: "ACCURATE"}` - but visually it will only pause on the next keyframe and then jump.
