### ISSUE TITLE
Crossorigin subtitles do not work on iPhone

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#912]
(Or on iPad with native_subtitles etc)

This is because crossorigin attribute needs to be set.

**Comment by blacktrash** [comment]
@nnarhinen - I'll add a note to the warning here: https://flowplayer.org/docs/subtitles.html#player-options - according to my tests setting the attribute does by no means always help, on iOS it depends on OS version and device.

**Comment by nnarhinen** [comment]
Yeah and if `crossorigin` is set but subtitles are in fact loaded from same origin it might prevent video loading on some browsers. I guess we had an issue about this somewhere with test cases.

But the fix from #913 was needed to make http://demos.flowplayer.org/basics/subtitle.html show subtitles on iPhones.
