### ISSUE TITLE
Flowplayer blocks gif, even css animations during loading video stream.

### ISSUE THREAD

**Issue by vvelar** [flowplayer/flowplayer#914]
FlowPlayer 6.0.3 version. Chrome 44 version. 
Steps to reproduce:
Create infinite css animation for some div, place a gif image on a page, and flowplayer block with some stream. Press start video - animation freezes for some time.

**Comment by bbbo** [comment]
do you have a link to a minimal example?

**Comment by blacktrash** [comment]
Indeed, especially as http://demos.flowplayer.org/lookandfeel/loading-custom.html works using an animated gif as loading indicator in Chrome 44.

**Comment by vvelar** [comment]
Sorry, but i can't reproduce it yet. I'll prepare fiddle if this issue occur again
