### ISSUE TITLE
Microsoft Edge DASH support fix

### ISSUE THREAD

**Issue by ipernet** [flowplayer/flowplayer#916]
Hi

Edge (Win10) has **native** [experimental support for MPEG-DASH and HLS streaming](http://blogs.msdn.com/b/ie/archive/2015/01/29/simplified-adaptive-video-streaming-announcing-support-for-hls-and-dash-in-windows-10.aspx). DASH support is however still in development and requires [Edge experimental features enabled](http://blogs.msdn.com/b/ie/archive/2015/01/29/simplified-adaptive-video-streaming-announcing-support-for-hls-and-dash-in-windows-10.aspx) to be tested.

The official Flowplayer [MPEG-DASH](http://demos.flowplayer.org/api/dash.html) demo **doesn't work** on Edge because the Edge *video* tag claims support for ```application/dash+xml``` type but is then **unable** to play without the Edge experimental features ON.

![image](https://cloud.githubusercontent.com/assets/1324566/9547389/6a1685ee-4d9a-11e5-97cb-53f20fd00dc1.png)

The solution is however simple: make the Flowplayer ```mpegdash``` engine with higher priority than the internal ```html5``` engine for ```application/dash+xml``` type so that **native** playback capability is bypassed still complete support is available.

```javascript
    // only load engine if it can be used
    if (clientSupport) {
        flowplayer.engines.unshift(engineImpl); // put the dash engine on top of the engine list
    }
```

Demo: http://ipernet.github.io/flowplayer/flowplayer-mpegdash.html

![image](https://cloud.githubusercontent.com/assets/1324566/9547430/c0e01458-4d9a-11e5-8009-218dd54fa71e.png)

**Comment by blacktrash** [comment]
@ipernet - thanks for this, always welcome. Will look into it later.
Just out of curiosity: Would it work already if you specify:
```js
sources: [
  { type: "application/x-mpegdash", src: "mydash.mpd", engine: "mpegdash" }
]
```
?

**Comment by ipernet** [comment]
Hi @blacktrash 

With this code the result is that Edge (experimental feature off or on) plays my video using Flowplayer **html5 engine** and the **HLS stream**  of the video (so a fallback stream)

![image](https://cloud.githubusercontent.com/assets/1324566/9548721/5991fea8-4da2-11e5-892e-aa086060946d.png)

So it *doesn't work* per say since expectation is to play the DASH stream.

Ref: http://ipernet.github.io/flowplayer/flowplayer-mpegdash-test.html

However just forcing the engine without whanging the content type **works**:

```
sources: [
  { type: "application/dash+xml", src: "mydash.mpd", engine: "mpegdash" }
]
```

![image](https://cloud.githubusercontent.com/assets/1324566/9548895/5b9e1596-4da3-11e5-9efd-a0478a571f49.png)

Ref: http://ipernet.github.io/flowplayer/flowplayer-mpegdash-test2.html

**Comment by blacktrash** [comment]
@ipernet - this is now in and deployed.
Thank you very much!

**Comment by ipernet** [comment]
@blacktrash Confirmed woking on the official demo page but beware of a JS error related to the MPEG-DASH JS detection code on the page (wrong reference to ```flowplayer.engines[2]```) (should be [0])

```
var dashsupported = function () {
  var canDash = flowplayer.engines.length > 2 && flowplayer.engines[2].canPlay("application/dash+xml"),

```

**Comment by blacktrash** [comment]
> However just forcing the engine without whanging the content type **works**:
> 
> ```
> sources: [
>   { type: "application/dash+xml", src: "mydash.mpd", engine: "mpegdash" }
> ]
> ```

Yes, that's what I meant, the 'imaginary' mime type was just absentmindedness, sorry.

I had actually intended to implement your proposal since quite a while, but then got side-tracked by other stuff, so thanks again for the reminder.

**Comment by blacktrash** [comment]
* Guillaume Simon on Friday, August 28, 2015 at 11:13:54 -0700
> @blacktrash Confirmed woking on the official demo page but beware of a JS error related to the MPEG-DASH JS detection code on the page (wrong reference to ```flowplayer.engines[2]```) (should be [0])

I did update the demo page, but the site builder has a problem. So you currently have the latest plugin, but not the latest demo page version.

**Comment by blacktrash** [comment]
@ipernet - FYI, https://github.com/flowplayer/flowplayer-mpegdash/ is now public. Your input is welcome there.
