### ISSUE TITLE
js error if ghostery blocks analytics

### ISSUE THREAD

**Issue by philipp90** [flowplayer/flowplayer#917]
Steps to reproduce
* install the [Ghostery](https://www.ghostery.com/) plugin/extension in your Browser (Chrome, Firefox)
* enable the tracking analytics filter
* start the video and then load another one

_Uncaught TypeError: e._setAllowLinker is not a function - flowplayer.min.js:7_

Furthermore on Chrome (Version 44.0.2403.157, OSX Yosemite) the newly loaded video isn't visible. The player stays black and shows the loading bubbles. Actually the video is played in the background - you can hear the sound and you can see it if you unload the player (e.g. page reload).

The js error also appears in v6.0.3 but the video is visible on Chrome.

**Example:**
```
<!DOCTYPE html>
<html>
<head>
  <title>flowplayer, ga, ghostery</title>
  <meta charset="utf8">
  <link rel="stylesheet" href="//releases.flowplayer.org/6.0.3/skin/minimalist.css">
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//releases.flowplayer.org/5.5.2/flowplayer.min.js"></script>
  <script>
    flowplayer.conf = {
      ratio: 5/12,
      splash: true,
      analytics: 'UA-27182341-1',
      muted: true
    };

    $(document).ready(function() {
      $('a').click(function(e) {
        e.preventDefault();
        var video = '//stream.flowplayer.org/functional.webm';
        $('.flowplayer').data('flowplayer').load(video);
      });
    });
  </script>
</head>
<body>
  <div class="flowplayer">
    <video>
      <source type="video/mp4" src="//stream.flowplayer.org/functional.webm">
    </video>
  </div>
  <a href="#">load "another" video</a>
</body>
</html>
```
**Note:** Couldn't share it on [fiddle](http://jsfiddle.net/bgt58mLq/5/), because google analytics won't be loaded.

A quick fix for v5.5.2 would be to wrap the _setAllowLinker function call (line 2435).
```
if (tracker._setAllowLinker) {
  tracker._setAllowLinker(true);
}
```

**Comment by blacktrash** [comment]
Normally we can't cater for browser addons, but as it looks simple in this case we'll have a look.

**Comment by nnarhinen** [comment]
It seems this is fixed with a recent version of ghostery.

**Comment by philipp90** [comment]
I cannot confirm that there has anything changed - I have sill the same issues.

Yes, your demo on https://flowplayer.org/standalone/complete.html works, however it also throws the following error message on switching the source:
```
Uncaught TypeError: e._setAllowLinker is not a function - flowplayer.min.js:7
```

As already mentioned above it's working (except of the error message) with **v6.0.3**.
The problem with the *invisible* video appears in **v5.5.2**. Please try out my example and you should be able to reproduce this in Chrome (latest).
