### ISSUE TITLE
Native subtitles shown when mixed native and flowplayer subtitles on same page

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#918]
http://flowplayer.blacktrash.org/fp6/subtitles-rtl.html?native=true
in spite of `flowplayer.support.subtitles` returning `true` in Firefox.
Browser bug?

**Comment by blacktrash** [comment]
Yuck. This seems to be some persistent setting in browsers, although I can't detect anything related in localStorage.
To get an impression play around with this demo where one player has nativesubtitles configured, the other has not:
http://flowplayer.blacktrash.org/fp6/subtitle-alt.html

**Comment by nnarhinen** [comment]
What's the problem here?

The players are playing with the flash engine (HLS source) so no native subtitles available.

**Comment by blacktrash** [comment]
Right, tomatoes on eyes.
But `nativesubtitles` is still a page-wide setting, not really a player option, and that leads to problems when you have one player with native, one not: http://flowplayer.blacktrash.org/fp6/subtitle-alt.html (not using HLS anymore) - once you've gone _back_ to the second player, you get _both_ native and player subtitles:
<img width="625" alt="screen shot 2015-11-02 at 11 04 31 am" src="https://cloud.githubusercontent.com/assets/168338/10880289/ec329a8c-8151-11e5-8bb3-f65afff6238a.png">

**Comment by nnarhinen** [comment]
Yeah this is because the splash setup caches the videoTag. Can't remember the reasoning but have to make sure it is emptied of any track elements before re-using.

**Comment by nnarhinen** [comment]
@blacktrash could you try with assets from http://demos.953f.flowplayer.me/

Should fix this situation.

**Comment by blacktrash** [comment]
Ugh, that somehow worsens the situation: http://flowplayer.blacktrash.org/fp6/subtitle-alt.html
1. start top player: native subs
2. start bottom player: html subs - Safari: both
3. start top player - Firefox: no subtitles; Chrome: 'Video file not found'; Safari: html subs in bottom player stay visible in splash state

(I tried both 953f and 954f)

Maybe that option should only be allowed on the global page level?

**Comment by nnarhinen** [comment]
I copied your example locally and used http://cdn.953f.flowplayer.me/adhoc/flowplayer.min.js

And here's the result for a run of  Start top player -> Start bottom player -> Start top player

Chrome & Safari: top player uses native subtitles, bottom player uses flowplayer subtitles
Firefox: top player starts with native subtitles, bottom player uses flowplayer subtitles, on replay the top player does not have subtitles

At least it's a lot better now..

**Comment by blacktrash** [comment]
As long as there's no 'video not found' message, it's ok.
We can still think of allowing the option in the global configuration only.

**Comment by nnarhinen** [comment]
Now they show on firefox on second play also after 9a08891
