### ISSUE TITLE
Issue when subtitles shorter than video

### ISSUE THREAD

**Issue by vkhramtsov** [flowplayer/flowplayer#920]
Try to play video with subtitles, when subtitles ends earlier than video. 

Actual result: Last subtitle hangs till the end of video
Expected result: Last subtitle will hide at end time

Example of subtitle:
```
WEBVTT

00:00:01.478 --> 00:00:04.020
I want to break free

00:00:05.045 --> 00:00:09.545
<i>I want to break free,</i>

00:00:10.378 --> 00:00:13.745
<b>I want to break free from your lies,
you're so self satisfied, I don't need you</b>

00:00:14.812 --> 00:00:16.144
I've got to break free
God knows, god knows I want to break free

00:00:18.211 --> 00:00:21.211
I've fallen in love

```

Watch it with video longer than 22 seconds

**Comment by vkhramtsov** [comment]
We are using flowplayer 6.0.2, on you site I see 6.0.3. So I will try to investigate issue deeper.

**Comment by vkhramtsov** [comment]
As I can see standard allow files formatted like this (without frame numbers). Would you be so kind to fix this issue?

**Comment by nnarhinen** [comment]
If the shipped VTT parser does not fulfill your needs, you can use the `subtitleParser` configuration option to override default behavior.

Something like this:

```js
var conf = {
  clip: { ... },
  subtitleParser: function(txt) {
    return parseVTTFile(txt);
  }
};
```

The default shipped implementation can be found here: https://github.com/flowplayer/flowplayer/blob/master/lib/ext/subtitle.js#L7-L40

You could easily hook flowplayer up with libraries like https://github.com/mozilla/vtt.js using this configuration.

**Comment by nnarhinen** [comment]
This been said, small patches to the parsing implementations are always welcome.
