### ISSUE TITLE
Vimeo external URLs not found

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#921]
See: https://flowplayer.org/forum/#!/drive_embedding:vimeo-hls-issue
```sh
$ curl -I 'https://player.vimeo.com/external/XXX.m3u8?p=high,standard,mobile&s=XXX'
HTTP/1.1 302 Found
Server: nginx
Content-Type: text/html; charset=UTF-8
Expires: Fri, 15 Dec 1985 19:30:00 GMT
Strict-Transport-Security: max-age=15120000; includeSubDomains
Location: https://fhls.vimeocdn.com/master/video/XXX.m3u8?token=XXX
P3p: CP="This is not a P3P policy! See http://vimeo.com/privacy"
Via: 1.1 varnish
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
X-Varnish-Cache: 0
X-VServer: dfvimeoplayproxy3
Via: 1.1 varnish
Fastly-Debug-Digest: ed7bf54eece2522dd60066eadf782f00cf771c70ec81c7b0f2af262789c9eeed
Content-Length: 0
Accept-Ranges: bytes
Date: Thu, 10 Sep 2015 12:35:07 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-iad2131-IAD, cache-fra1242-FRA
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
Vary: Accept-Encoding
```
Plays in plain video tag, and in generic HLS with:
```js
flowplayer(container, {
  // config goes here
}).on("error", function (e, api, err) {
  if (err.code == 4) {
    container.className = container.className.replace(/ *is-error */, "");
    api.error = api.loading = false;
    api.load(api.conf.clip);
  }
});
```
But Flash HLS fails (with or without workaround), making it look like its `manifestloadmaxretry` (default `-1` for infinite) is not properly evaluated.

**Comment by blacktrash** [comment]
Ah - won't work in Flash HLS because of crossdomain problem.

**Comment by nnarhinen** [comment]
Bug demo please. Maybe we can fix the HTML5 part atleast?

**Comment by blacktrash** [comment]
This boils down to the following:
- HTML5: works without workaround on the 'allowed' sites
- Flash HLS cannot work because there are 302 re-directs involved, see: https://github.com/mangui/flashls/issues/261

Was about to close this. Doing it now.

**Comment by foliovision** [comment]
Here's another HLS stream from Vimeo Pro which doesn't work: https://player.vimeo.com/external/46195780.m3u8?p=high,standard,mobile&s=64c504b85ee64c5d1b12e24f81ac7ca2a3ac7971

Looking at https://player.vimeo.com/crossdomain.xml it appears to me all domains are allowed.

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.adobe.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
    <site-control permitted-cross-domain-policies="master-only"/>
    <allow-access-from domain="*"/>
    <allow-http-request-headers-from domain="*" headers="*"/>
</cross-domain-policy>`

Hower I see that the HLS URL does HTTP 302 redirection to https://05-lvl3-hls.vimeocdn.com/1454676728-faa08ec03a9792ae55985cba872d78233967e598/01/4239/1/46195780/108988234.mp4.m3u8 - if I use that one directly, then it works.

I tested this in JW Player and got the same behavior.

**Comment by blacktrash** [comment]
@foliovision - as already mentioned above - https://github.com/flowplayer/flowplayer/issues/921#issuecomment-139568856 - 302 redirects cannot be made to work.
Unfortunately Vimeo also do not deliver with the required CORS settings for hlsjs: https://flowplayer.org/docs/plugins.html#hlsjs
