### ISSUE TITLE
Chrome: Flash object with less than 461px width does not work

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#922]
Demo:
http://flowplayer.blacktrash.org/fp6/chrome-flash-461.html
At first it looks like a Chrome bug - or some weird restriction they suddenly introduced, but it does not happen e.g. with Flowplayer Flash.

Not Flash HLS specific, happens also with flash progressive download or RTMP.

See:
https://flowplayer.org/forum/#!/setup:the-video-cant-autoplay-in

**Comment by nnarhinen** [comment]
Can you make this a bug demo under demos.flowplayer.org thanks.

**Comment by nnarhinen** [comment]
Works on 46.0.2490.13 beta (64-bit)

**Comment by blacktrash** [comment]
Not in Canary Version 47.0.2509.0 canary (64-bit).

**Comment by blacktrash** [comment]
And it works with FP Flash: http://flowplayer.blacktrash.org/test/flashls.html

**Comment by blacktrash** [comment]
Not related to hardware acceleration, turning it off does not have an effect.

**Comment by nnarhinen** [comment]
Tried with Version 47.0.2498.0 dev-m on browserstack and not reproducable there either.

**Comment by blacktrash** [comment]
Demo at http://demos.flowplayer.org/bug/922.html

**Comment by nnarhinen** [comment]
A friend of mine tested and both players on that site works with Version 47.0.2508.0 canary (64-bit)

**Comment by blacktrash** [comment]
Then it's maybe Mac Chrome specific. I can ask in the forum on which OS the reporter experiences this.

**Comment by blacktrash** [comment]
According to user also happens on windows 8.1, Chrome (Version 45.0.2454.85)

**Comment by nnarhinen** [comment]
![win8 1_chrome_45 0 1](https://cloud.githubusercontent.com/assets/265438/9874405/8186c438-5bae-11e5-9300-58b1314d9ae6.jpg)
![win8 1_chrome_45 0](https://cloud.githubusercontent.com/assets/265438/9874406/818afc38-5bae-11e5-9a7b-2ed481e43766.jpg)

**Comment by blacktrash** [comment]
Did you play the other one first? According to the user then it works. - I can confirm that. Some initialization timing.
Realistically we should wait for Chrome's next update cycle.

<img width="535" alt="screen shot 2015-09-15 at 12 41 50 pm" src="https://cloud.githubusercontent.com/assets/168338/9874586/3726c160-5ba7-11e5-8089-1536f4a0ef5c.png">

<img width="599" alt="screen shot 2015-09-15 at 12 42 44 pm" src="https://cloud.githubusercontent.com/assets/168338/9874604/5ba27b92-5ba7-11e5-8d12-fd59455951cd.png">

**Comment by nnarhinen** [comment]
Nope, always tried the smaller (the top one) first.

But yes, I agree that it most likely is a chrome bug somewhere.

**Comment by blacktrash** [comment]
At least with how Flowplayer HTML5 initializes the Flash object; Flowplayer Flash does not exhibit the problem.

**Comment by jaq316** [comment]
This is probably related to http://chrome.blogspot.co.za/2015/06/better-battery-life-for-your-laptop.html

**Comment by nnarhinen** [comment]
Good find. That's exactly the setting that makes this reproducable.

**Comment by blacktrash** [comment]
@jaq316 - spot on!
@nnarhinen - this could turn out to be a bad bummer.
It's strange/absurd though that
1. content smaller than 462x260 is considered not important
2. it becomes important after playing some other content
3. Flowplayer Flash works

**Comment by nnarhinen** [comment]
3. is most likely because the flash object is foremost in the page. In Flowplayer HTML5 the flash object is overlaid by other HTML elements so I guess chrome thinks it's some background animation or such.

**Comment by blacktrash** [comment]
@nnarhinen - yes. Unfortunately wmode direct or wmode window does not help either.

**Comment by nnarhinen** [comment]
What we most likely have to do, is to make similar detection as with the plugin disabled. If the plugin is being stopped (progress not firing or something else) we have to raise it on top of UI and make it clickable.

**Comment by cgcb** [comment]
This is closed, but is there a resolution? This remains an issue in 7.0.4.

**Comment by blacktrash** [comment]
@cgcb - there will be no resolution, because recent Chrome behaves that way. If anything Flash will be even more deprecated/disabled by default. Other browsers as well, albeit somewhat more consistently, and not depending on size.
Nothing we can do from our side, except for the ugly workarounds already in place.
The resolution is to go for video which can be played in HTML5 video or, like HLS and DASH, with the MediaSource extension and the respective plugins.
