### ISSUE TITLE
Controlbar mouse over problem

### ISSUE THREAD

**Issue by frkcn** [flowplayer/flowplayer#923]
When control bar (".fp-volume") hidden if mouse over bottom right of the player (I mean hidden volume element), controlbar be active (and shaking). 

I think the reason of this problem, when mouse out of the player controlbar volume element hiding but it's just opacity: 0. Not in the real sense hiding. 

You must be adding display none to the fp-volume element when controlbar hiding.

**Comment by bbbo** [comment]
demo page please

**Comment by frkcn** [comment]
I think it is demo page: https://flowplayer.org/standalone/asf/image-text.html
or any flowplayer 6 (html5 version).

**Comment by bbbo** [comment]
this relates to a demo for our advertising offer.
please be more specific: do you experience any problems with the standard player? where any under which conditions?

**Comment by frkcn** [comment]
I know it is your demo page but this has same problem.
Demo page: http://angelfish.io/flow/
versions : 
css -> //releases.flowplayer.org/6.0.3/skin/functional.css
flowplayer -> //releases.flowplayer.org/6.0.3/flowplayer.min.js

**Comment by blacktrash** [comment]
@frkcn - this page also uses the google sdk, and I get a video not found error.

But I can reproduce it in a dead simple setup: https://flowplayer.org/standalone/quickstart.html
@nnarhinen - we talked about this already, but on revisiting I can give a perhaps more precise diagnosis:
- hold/move the mouse *below volume*, best slowly from volume downwards, or horizontally *below* the player to see it happening only below volume
- the controlbar starts to judder
- cursor oscillates between pointer and col-resize

Screencast: http://media.blacktrash.org/fp/test/control-judder.mp4

**Comment by blacktrash** [comment]
It looks like the player element is extended below the player in that area: if you ctrl-click it, the context menu appears.
@nnarhinen - I found a solution to reduce the judder area to only below mute, maybe I can solve that as well.

**Comment by blacktrash** [comment]
Got it: http://flowplayer.blacktrash.org/fp6/minimal.html

The problem is still there for the entire controlbar width when one manages to slide the mouse horizontally in the area where the 'reduced' timeline is on mouseout, but maybe that cannot be solved.

**Comment by frkcn** [comment]
You got this. By the way other css versions ( minimalist, playful ) have this issue.

**Comment by blacktrash** [comment]
@frkcn - yes, I'm aware of that, I just did in functional for a quick demo.
