### ISSUE TITLE
flash: play(index) and load(clip) load encoded url

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#924]
Flash engine encodes video src when it is given in an argument. This becomes a problem when the URL contains a query: the commands fail.

Demo: http://flowplayer.blacktrash.org/fp6/signed-ondemand-flash.html (long expiry time, that's not the problem).

1. Compare the URL displayed on the page, and also returned by `flowplayer(0).video.url` in the console: not encoded - to the URL logged by debug: encoded.
2. `load()` without arguments succeeds, `api.play(0)` and also - tested from console - `flowplayer(0).play(flowplayer(0).video.src)` fail.

Why is the internal url encoding needed? Why does `load()` not do it, so it seems?

First reported here: https://flowplayer.org/forum/#!/scripting_api:problem-switching-playlist

**Comment by blacktrash** [comment]
https://flowplayer.org/forum/#!/scripting_api:javascript-playlist

**Comment by nnarhinen** [comment]
@blacktrash Should be fixed on the assets at http://demos.948f.flowplayer.me/

**Comment by blacktrash** [comment]
:+1:
