### ISSUE TITLE
BeforeSeek Event does not working in IE11

### ISSUE THREAD

**Issue by cecbr** [flowplayer/flowplayer#928]
I'm trying cancel seek event (FP6) but it does not working in Internet Explorer 11. 

When using google Chrome, run perfect.

My code:

currentapi.bind("beforeseek", function (e, api, position) {
            if (position > api.video.time)
                e.preventDefault();
        })

**Comment by blacktrash** [comment]
Can you confirm that you can seek further than 40 seconds in this demo: http://demos.flowplayer.org/scripting/preview.html in IE11?

**Comment by nnarhinen** [comment]
Yeah it seems the event is fired but `preventDefault()` does not work.

**Comment by nnarhinen** [comment]
Should be fixed:

@bbbo can you test with a real IE
http://demos.947f.flowplayer.me/scripting/preview.html (fixed version)
http://demos.flowplayer.org/scripting/preview.html (current stable)

**Comment by bbbo** [comment]
I cannot seek beyond the 40sec, but sometimes after doing a couple of seeks, the clip will continue to play to the nd.

**Comment by nnarhinen** [comment]
The behavior is same for Chrome - after trying to seek beyond limits it will play to the end of the video. So there's something else wrong with the scripting of the page but the `beforeseek` stuff is correctly fixed with this patch, I'd say.

**Comment by blacktrash** [comment]
This looks like a different bug to me:  _the attempt_ to seek beyond the cuepoint disables the cuepoint? Is that expected?

**Comment by nnarhinen** [comment]
It should not. Please open another issue and I will take a look.
