### ISSUE TITLE
Flowplayer (6.0.3) reuse with new URL start playing immediately

### ISSUE THREAD

**Issue by ajit-sarnaik** [flowplayer/flowplayer#931]
We have started using the flowplayer version 6.0.3 in our environment, and it works fine when we invoke it the first time. But when we intialize it again, and provide a new url and initialize it using the clip, it begins to play immediately even though the autoplay property is set to false. Below is the js snipped for your reference.

        function initializeLiveFeed(dataUrl){
                //alert(dataUrl);
                var Videocontainer = document.getElementById("flowvideoplayer");

                console.log("INIT = ", dataUrl);
                console.log("Videocontainer: ", Videocontainer);
                Flvplayer = flowplayer(Videocontainer, {
                    clip: {
                        sources: [
                          {
                             type: "video/mp4",
                            src: dataUrl,
                            autoplay: false,
                         }
                       ]
                    }
                }).load(dataUrl);
     }

**Comment by blacktrash** [comment]
1. Please make our forum - https://flowplayer.org/forum/ (monitored by staff) - your first port of call to make sure it's a bug, not a usage question. Increase your chances for a speedy and qualified answer by providing a link to a **minimal** sample page demonstrating the problem.
2. It sounds like you are instantiating Flowplayer again, either the clip configuration or the load call is certainly spurious in your code snippet.
3 `autoplay` is not a source option but a player option and is false by default, but the load call will play the video - see the api docs for the load method and this basic demo: http://demos.flowplayer.org/api/load.html
4. Commas before closing braces, brackets, or parens are not allowed in JSON syntax; browsers may choke on it

RE 3. Once you have sorted out how to load into an _existing_ player instance (as it sounds by your description, you _probably_ want to do:
```js
// reference an existing API instance
var api = flowplayer(Videocontainer);
api.load({
  sources: [
    { type: "video/mp4", src: dataUrl }
  ]
}, function (e, api) {
  // pause on first frame in the load callback
  api.pause();
});
```
Again, see the docs on the load() method: https://flowplayer.org/docs/api.html#load-method
