### ISSUE TITLE
api.load() also starts playback of video

### ISSUE THREAD

**Issue by user890104** [flowplayer/flowplayer#932]
Hello,

I am developing a jQuery plugin, which bridges Google's JS IMA SDK to Flowplayer. There is a live demo at: http://vivo.bg/flowplayer/v4/
It is mostly done, but there is an important issue - when I call api.load(), it does not only preload the video, but also starts the playback. This causes an unwanted side-effect when there is a pre-roll ad - the video starts for 500-1000 ms, then the ad SDK pauses it so it can display the ad.
When using a video tag, load() only preloads the content, but does not start the playback. A live demo is included here: http://vivo.bg/flowplayer/v3/
Is it possible to add an option to api.load() to not start the playback when called, or is there a workaround? The main concern is, that on mobile devices you need to call load() on the video element from a user initiated event (e.g. click, touch), so we are forced to call load() this way.

**Comment by blacktrash** [comment]
Answered in our forum: https://flowplayer.org/forum/#!/setup:apiload-parameter
