### ISSUE TITLE
[Question] HLS Flash background color

### ISSUE THREAD

**Issue by oleynikd** [flowplayer/flowplayer#934]
Hi,

First of all thank you for such a great player!!!

How can I change default background color (`#333`) of both HTML5 and Flash video players (I'm playing HLS)

Thanks.

**Comment by blacktrash** [comment]
Hi,
This is a _bug_ tracker, please ask usage questions in our public forum - https://flowplayer.org/forum/ - (monitored by staff) - in the future, thank you.

- For Flowplayer HTML5 the background color of the container element is used; you can override that with the `bgcolor` [player option](https://flowplayer.org/docs/setup.html#player-options) - although there is currently a bug + fix pending for the latter: https://github.com/flowplayer/flowplayer/issues/906
- This is the Flowplayer HTML5 bug tracker, but if your question is _also_ about Flowplayer Flash (not the Flash backend of Flowplayer HTML5), then you can set it in the [Flash configuration](http://flash.flowplayer.org/documentation/configuration/player.html#standard-flash-parameters).
