### ISSUE TITLE
Feature Request: Meteor Package

### ISSUE THREAD

**Issue by boustanihani** [flowplayer/flowplayer#935]
Please provide an official package for **Meteor.js** on https://atmospherejs.com/

**Comment by nnarhinen** [comment]
We would be happy to provide a Meteor package under the flowplayer organization if someone would volunteer.

Looking at meteor documentation it would be enough to provide a loader script that would load flowplayer from our CDN.

Please provide that loader script in a github repository, contact us at support@flowplayer.org and we can look into moving that repository under the flowplayer organization and then publishing to to athmospherejs.com.
