### ISSUE TITLE
IE8: no player displayed for splash setups if no height: for container

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer#936]
see http://stylebites.de/fp6/ie8splash.html vs. http://stylebites.de/fp6/ie8swf.html

**Comment by blacktrash** [comment]
You mean for the element wrapping the player container?

**Comment by bbbo** [comment]
no, seems it needs to be the flowplayer container itself; adding a height to the #content wrapper in http://stylebites.de/fp6/ie8swf.html and removing it from the .flowplayer class breaks the player. Just like in all our demos with splash...

**Comment by blacktrash** [comment]
hm, I could swear you had `max-height` set for #content in one of those. What happens if you set `min-height` or `height` for #content?

**Comment by bbbo** [comment]
yes I had but without effect. Tried all permutations. min/max , (min/max width) or percentages do not work, only fixed height in the flowplayer container.
