### ISSUE TITLE
Question: Fallback Flash Player too restrictive, custom provider cannot be built

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flowplayer#938]
Hi how is it possible to rebuild the fallback player to build in custom providers. There is key restrictions in the base class and therefore cannot be rebuilt. 

Is it required to roll your own player for each feature required ? 

FP3 can build in external providers and plugins independently of the key, this can't. 

I am forced to embed the FP3 feature for now, I believe DFP has exactly the same issue they embed FP3. 

https://flowplayer.electroteque.org/widevine/fp6

Required for Widevine Classic and possible HDS Adobe DRM option. 

Thanks

**Comment by anssip** [comment]
We want DRM implemented with JavaScript, not Flash.

**Comment by danrossi** [comment]
OK i'll work out something if people don't have FP3 no worries. Flash is needed :)

**Comment by danrossi** [comment]
No EME in Safari / Firefox or Widevine module.

**Comment by nnarhinen** [comment]
The flash fallback really is about being a fallback / polyfill for browsers lacking support of HTML5 video features.

If you need something that can't be done in any browser on html5 video tag, then Flowplayer HTML5 is not the product for you. This is why we have the Flowplayer Flash product line. Using Flowplayer HTML5 always falling back  to Flash does not make any sense.
