### ISSUE TITLE
autoplay: does not go into poster state on stop

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#940]
This is surprising from the UX perspective. I would expect `autoplay` to mean just that: start playback automatically on load.

**Comment by blacktrash** [comment]
Or we decide that `stop()` just means pause and seek to 0. Then `stop()` should not trigger poster state when `autoplay` is not set. This would be consistent with splash setups, where `stop()` does not go back into splash state (only unload does).

**Comment by nnarhinen** [comment]
http://demos.945f.flowplayer.me/

@bbbo @blacktrash Please test with this ad-hoc build. Now it enables the `is-poster` handling for autoplay setups too. It was specifically set by @tipiirai to not do it when originally implemented so there might be some cases that could potentially break with this..

**Comment by nnarhinen** [comment]
I rebased and rebuilt the ad-hoc site. please test.
