### ISSUE TITLE
quality selector loses poster state with playlist

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#942]
Demo: http://flowplayer.blacktrash.org/fp6/qsel-playlist.html

Steps to reproduce (there may be other ways):
1. start playback by clicking on container
2. select a non-Auto resolution
3. switch to 2nd or 3rd clip
4. hit `q` for stop

Expected: player stops and goes into poster state.

Result: player pauses (sort of in the middle of stop), no poster state. On resume player seeks to 0 (leftover from stop), and resumes.

Does not happen with flashls turned off. So an engine switch _to_ html5 is involved.

**Comment by blacktrash** [comment]
In a first frame setup without poster, the 'postponed seek' behavior on resume is similar.

**Comment by blacktrash** [comment]
@nnarhinen - if you load the hlsjs engine, it works around the poster part of the problem by applying a hack for the hlsjs engine to all engines: https://github.com/flowplayer/flowplayer-hlsjs/commit/5f4aafd67889806972256292f17ed4d089dfd375
(ugly, very ugly, but seems to work)

Demo: http://flowplayer.blacktrash.org/fp6/qsel-playlist-hlsjs.html

**Comment by nnarhinen** [comment]
Can we have these bug demos under demos.flowplayer.org or is it too much extra work for you?

**Comment by blacktrash** [comment]
@nnarhinen  - if I can't make it until tomorrow evening, either Sunday night or Monday.

**Comment by blacktrash** [comment]
@nnarhinen
- http://demos.flowplayer.org/bug/942.html
- http://demos.flowplayer.org/bug/942-hlsjs.html

**Comment by nnarhinen** [comment]
From those demos I can't really see the difference. 

http://demos.flowplayer.org/bug/942.html does behave completely the same with both safari and chrome (where safari uses html5 engine for everything).

Also in the player initialization I can't see any reference to the `poster` attribute. What poster state are you talking about?

**Comment by nnarhinen** [comment]
Ok with another read of the reproduce steps I can see the difference in behavior.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/bug/942.html does not seem to have this problem anymore. Maybe the fix for #941 already fixed this.

**Comment by blacktrash** [comment]
Maybe. Poster is still a can of worms, and probably unavoidibly so. The timing also varies depending on the (loading time) of the actual video: https://github.com/flowplayer/flowplayer-hlsjs/commit/92c433fcd6b0e8037916ddf4e12ea4d921b07977

**Comment by nnarhinen** [comment]
Please clarify.

Looking at the code `is-poster` class is added on `ready` and `stop` and removed at first `progress` event. Is there a problem with this behavior?

**Comment by nnarhinen** [comment]
But can you confirm, this problem does not exist with the dev branch?

**Comment by blacktrash** [comment]
1. I confirm that the problem is gone (testing with 954f adhoc)
2. But now the 'Flash is disabled' message appears at every switch from html5 to flash hls, even when starting playback at Auto level

**Comment by blacktrash** [comment]
I would clarify if I could. I'll try based on my adventures with hlsjs:

The `stop()` method contrary to (most?) other methods is a 'compound' method as there is no corresponding method for a video tag: it pauses first, and then seeks to 0. Therefore the stop event is triggered sometimes before the seek or during the seek, and that timing varies depending on browser and circumstances: stop for poster, stop at beginning of clip, stop way into a longer video.
I managed to compact the stop handling for poster in hlsjs, and it makes it hopefully a bit clearer what events can be involved: https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L245-L277
To catch stop for poster reliably (at least with 6.0.3) I have to listen to the ready, stop, and seek events, add the 'lost' poster with a timeout, and then turn off the listeners to ready and seek ...

https://github.com/flowplayer/flowplayer-hlsjs/blob/master/flowplayer.hlsjs.js#L245-L277
- maybe the api must be returned later if and when stop is fired?

**Comment by nnarhinen** [comment]
This is because of #959, continuing there.

**Comment by nnarhinen** [comment]
> Therefore the stop event is triggered sometimes before the seek or during the seek, and that timing varies depending on browser and circumstances: stop for poster, stop at beginning of clip, stop way into a longer video.

The `stop` event is fired after the seek. Can you make a reproducable case where stop is fired before seek?

**Comment by blacktrash** [comment]
No, well, sort of. At http://flowplayer.blacktrash.org/fp6/qsel-playlist-hlsjs.html the first stop event is not fired on load, only seek. If I stop later pause, seek, and stop are fired. - Now updated to //cdn.960f.flowplayer.me/adhoc/flowplayer.min.js and pause, seek, stop, seek are fired ...
Furthermore, I have to add the poster class with a timeout consulting the ready, seek, and stop events because it's wiped otherwise, so there is some race condition.
With mpegdash I haven't solved it yet. The same workaround (without qsel) prevents the poster from going away when I click an a playlist item.
I can check again with a debug hat on at some point, so far I've just tried to make it work ;-)

**Comment by nnarhinen** [comment]
Where are you calling `stop` in  http://flowplayer.blacktrash.org/fp6/qsel-playlist-hlsjs.html ?

**Comment by blacktrash** [comment]
I call stop by typing `q` - to test whether and how the poster setup works.

**Comment by blacktrash** [comment]
I believe it all now works with hlsjs. With mpegdash I have made progress, but still have a problem in Mac OS Safari.
