### ISSUE TITLE
poster: add new api property when poster condition is met

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#944]
Engine implementors may encounter all kinds of weird timing issues in conjunction with poster. See: https://github.com/flowplayer/flowplayer-hlsjs/blob/804bb5707781355fdb6c3a44e81041715ad8d38c/flowplayer.hlsjs.js#L244-L278
That situation could probably be eased by adding `api.posterCondition = true` or similar at the point in time where core encounters the poster condition because one at least would not have to replicate and monitor core code regarding the conditional.

**Comment by blacktrash** [comment]
See my comment https://github.com/flowplayer/flowplayer/commit/559f3b56496589079690caa3ca51b769384234e9#commitcomment-14255260 - my idea was something more persistent. Maybe it must be api.conf.poster = true unless poster is already configured.

**Comment by nnarhinen** [comment]
@blacktrash Better now?

**Comment by blacktrash** [comment]
If that doesn't help, I don't know what does ;-)
Actually dealing with the situation is a different story ...
