### ISSUE TITLE
Prevented seek beyond cuepoint disables cuepoint once

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#955]
http://demos.flowplayer.org/scripting/preview.html
1. start playback
2. try seek beyond 40 seconds: correctly prevented by `beforeseek`
3. let playback continue: pause on cuepoint at 40 seconds is not triggered

If one seeks to an 'allowed' position after failed seek, no problem.

See also https://github.com/flowplayer/flowplayer/issues/928#issuecomment-154399319 ff.

**Comment by nnarhinen** [comment]
http://demos.956f.flowplayer.me/scripting/preview.html

**Comment by blacktrash** [comment]
:+1:
