### ISSUE TITLE
generate_cuepoints: seeks to timeline postion, not cuepoint (regression from v5)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#957]
This is not immediately obvious in many circumstances because by default the generated cuepoint elements are positioned horizontally according to cuepoint position.

To reproduce: click on different horizontal positions inside a generated cuepoint element at
https://flowplayer.org/standalone/timeline/thumbs.html
The playhead changes position.
Do the same with version 5 at
https://flowplayer.org/standalone/v5/timeline/thumbs.html
The playhead does not move.

I will submit a patch shortly. The solution is easy, even with cleaner code.

**Comment by blacktrash** [comment]
Here's the demo using the fix: http://flowplayer.blacktrash.org/fp6/thumbs.html

**Comment by nnarhinen** [comment]
Thanks
