### ISSUE TITLE
Flash HLS - ready fired too early

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer#959]
Ready is fired when manifest is received, even though the HLS object itself still is in buffering state. This will cause flowplayer to remove loading indicator and people see just a black screen while waiting for the playback to start.

**Comment by nnarhinen** [comment]
@blacktrash Can you try the playlist example to check if http://demos.960f.flowplayer.me/ fixes the "Flash disabled" message.

**Comment by blacktrash** [comment]
It does. And even better! The loading animaition is now shown while the first resolution is determined, that's great :+1:
