### ISSUE TITLE
minimalist: wrong mouseout transitions for volume & mute (regression from 6.0.3)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#961]
https://github.com/flowplayer/flowplayer/commit/4f7129bb698f11fc0118b4823b78f73a4d71735b fixed a problem which only existed in the functional and playful skins because their controls are positioned into the screen. But the fix was applied generally and thereby has an adverse effect in minimalist: volume and mute 'jump' upwards' on mouseout.

**Comment by blacktrash** [comment]
@nnarhinen: While my patch was sloppy it reveals a deeper problem with what happens during css transitions, especially with minimalist.

- sloppiness: fp-volume should be height 0 on mouseout (although 4px is not noticeable)
- minimalist: during transition time volume and mute take space below the container because the controlbar sits at the bottom of the container; while height is also transitioning the elements claim space below (that issue was always present, and before v6 with all skins, because they all sat at the bottom), so in a way the change made the problem just more obvious; I've tried to bottom-anchor fp-volume (as this works for fp-brand), but to no avail
- not related here: but timeline-tooltip expands to the entire controlbar width during transition before it's completly hidden, displaying time values beyond duration (when you hover to the right of timeline) - this probably can be solved by hiding timeline-tooltip without transition (imho no visual advantage by transitioning this element)

Assigning this to you, at least for the moment.

**Comment by blacktrash** [comment]
Problem description helped me to find a solution.

**Comment by nnarhinen** [comment]
These should be fixed by the (now merged) PR, right? (Thanks, btw)

**Comment by blacktrash** [comment]
yes: http://demos.965f.flowplayer.me/basics/poster.html
