### ISSUE TITLE
rtmp: live:true doesn't set bufferTime:0

### ISSUE THREAD

**Issue by colmaengus** [flowplayer/flowplayer#966]
When playing a live rtmp stream it sounds like it should be enough to set live:true.
However this doesn't seem to set bufferTime:0 so you get the default 3 seconds delay before playback begins. Explicitly setting bufferTime in player options works.

You can see this by enabling debug messages.
Trivial example (without a real rtmp stream since I couldn't find a public one)

```html
<!doctype html>

<html>

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="//releases.flowplayer.org/6.0.4/skin/functional.css">
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//releases.flowplayer.org/6.0.4/flowplayer.min.js"></script>

  <script>
    flowplayer.conf = {
      live: true,
      debug: true
    };
  </script>

</head>

<body>

<div class="flowplayer">
  <video>
    <source type='video/flash' src="rtmp://example.com/live/stream">
  </video>
</div>

</body>
</html>
```

**Comment by blacktrash** [comment]
Sample page: http://flowplayer.blacktrash.org/fp6/live-rtmp.html - indeed shows bufferTime 3 in the debug log; which is at least contrary to our docs.

**Comment by nnarhinen** [comment]
Fixed in dev
