### ISSUE TITLE
RTMP live doesn't observe mute setting on pause/resume

### ISSUE THREAD

**Issue by colmaengus** [flowplayer/flowplayer#967]
If you mute audio when playing an RTMP live stream and then pause/resume the audio returns when you resume. You then have to click the mute button twice to get it back in sync with the audio.

**Comment by salem00** [comment]
Thanks

**Comment by nnarhinen** [comment]
Can you provide a live RTMP stream? I have none available and this can't be reproduced with a VOD RTMP setup.

**Comment by blacktrash** [comment]
@nnarhinen - you can take the one from our v5 demo: http://demos.flowplayer.org/v5/basics/live.html

rtmp://wms.shared.streamshow.it/canale8/canale8

**Comment by nnarhinen** [comment]
Should be fixed in dev now
