### ISSUE TITLE
flashls live: player does not change on resume state after longer pause (regression from 6.0.3)

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#968]
After a longer pause, presumably once the current position is not in the still available 'DVR' window, on resume, the video resumes, but the player is stuck in paused state and unworkable.
Can be observed at our basic demo:
http://demos.flowplayer.org/basics/live.html

Maybe (parts of) https://github.com/flowplayer/flowplayer/pull/879 have been accidentally disabled in 6.0.4.

See also: https://flowplayer.org/forum/#!/setup:hls-pause-at-desktop

**Comment by nnarhinen** [comment]
It's actually #897

**Comment by nnarhinen** [comment]
And yes, I most likely broke this while fixing the buffer indicator for 6.0.4

**Comment by blacktrash** [comment]
> It's actually #897 

Sorry, yes, I looked up the bug, but had still the PR url in the clipboard.

**Comment by nnarhinen** [comment]
Should bne fixed http://demos.dev94.flowplayer.us/basics/live.html

**Comment by blacktrash** [comment]
Confirming :+1:
