### ISSUE TITLE
addCuepoint bug when using an object to define the cue.

### ISSUE THREAD

**Issue by fabianweb** [flowplayer/flowplayer#969]
The addCuepoint function has a bug when using an object to define the cuepoint.

```javascript
var time = cue.time || cue;
if (time < 0) time = duration + cue;
```

should be:

```javascript
var time = cue.time || cue;
if (time < 0) time = duration + time;
```

as ```cue``` may be an object resulting in something like ```10.013[object Object]``` for ```time```.

**Comment by nnarhinen** [comment]
This will be released later with 6.0.5, thanks for reporting and fixing
