### ISSUE TITLE
Flowplayer Flash: Corner case issue with playback of short videos

### ISSUE THREAD

**Issue by lori-annw** [flowplayer/flowplayer#971]
There seems to be an issue with playback of short videos (specifically a video of length 2 seconds)

On page load the video plays successfully, but on attempted playback the video tries to play from 2 seconds (aka the end of the video).
Current behaviour: On clip.onFinish the code triggers player.play(0).pause()

I tried setting the clip.start property to 0 seconds under the clip configuration, but it does not seem to work
If I change the clip.start property to 1, the issue disappears (except it truncates playback to 0:01-0:02)

I am not sure how to post an example, my apologies.

Browser: Chrome
OS: Windows 7 Professional

**Comment by nnarhinen** [comment]
This is the bug tracker of Flowplayer HTML5. Please take a look at our [forums](https://flowplayer.org/forum/) or https://github.com/flowplayer/flash

**Comment by lori-annw** [comment]
Sorry about that. I looked in the forum already but thanks for redirecting me to the appropriate repo.
