### ISSUE TITLE
Feature request: allow specifying a playlist index to start from

### ISSUE THREAD

**Issue by gmcnaughton** [flowplayer/flowplayer#973]
I want to be able to configure a player with a playlist of videos, then start from an arbitrary index in that playlist. Currently playlists always start from the beginning (index 0).

The current workaround is to listen for the first click on `.fp-ui` and then call `play(index)`, as illustrated in the [linkable demo](http://demos.flowplayer.org/playlist/linkable.html#javascript-setup).  However, this has side-effects such as generating two "load" events (one for the 0th playlist item and then a second for the requested item).  Being able to tell the player which index to start from would avoid this.

**Comment by nnarhinen** [comment]
http://demos.dev94.flowplayer.us/playlist/startindex.html

**Comment by nnarhinen** [comment]
Thanks

**Comment by gmcnaughton** [comment]
Thanks so much! :heart:
