### ISSUE TITLE
BUG all browsers - exit fullscreen don't work anymore (+ fullscreen events not triggered) after calling shutdown function

### ISSUE THREAD

**Issue by sebpatu** [flowplayer/flowplayer#977]
on one instance fullscreen works as expected.
but if i call shutdown, and then create a new instance (even for a different tag) i will be able to go to fullscreen, but no event is triggered, and i won't be able to get out of fullscreen by clicking on button, only with escape key, and still no event is triggered. (no javascript crash in debugger)

i made a fiddle, but you can't test the fullscreen on it.
http://jsfiddle.net/ramp/shAV7/
just copy the code of the generate page. its 100% on all modern browsers for me.

first video is plaid, and can be put in fullscreen and out by clicking on fullscreen button
after 3 seconds! i shutdown the first player.
i wait another 1 scond (because i observed that if i reinstanciate a player just after shutdown it will crash. another bug?)
second video is launched after 1 more second.
try to click on fullscreen button: it will get to fullscreen, but no event is triggered.
when in fullscreen, try to click on button to get out of fullscreen. it won't work.
you need to type escape key to gt out of fullscreen, and no event is triggered either.

for the record, i also get the bug in my app, by simply loading a new video, on same instance, without calling shutdown. but i can't reproduce it on a simple sample.

its very anoying, when we use the player in a React app or any one page app, where we need to release previous instances.
thanks

**Comment by nnarhinen** [comment]
You are posting on the wrong issue tracker, this is for the Flowplayer HTML5 player.

**Comment by sebpatu** [comment]
no i mean BUG on all browsers! but of course its about flowplayer !

**Comment by bbbo** [comment]
but your fiddle is about Flowplayer Flash, so it belongs to https://github.com/flowplayer/flash/issues
