### ISSUE TITLE
Quality selector with multi source on different server

### ISSUE THREAD

**Issue by hxdev** [flowplayer/flowplayer#978]
Following this https://flowplayer.org/docs/plugins.html#quality-selector-configuration  I made a demo and look like the quality selector will choose source base on name + {resolution}. So are there any way to make the selector choose source from some sources which serve on different server or different name?

**Comment by bbbo** [comment]
Please use the forums for technical questions, thank you.
The qsel plugin requires all source variants to be in the same directory :
>File name layout
>The plugin expects all the sources to reside in the same directory according to this file naming scheme:
But feel free to write your own selector plugin ;)

**Comment by hxdev** [comment]
Thank, try to modify original plugin right now ;)
