### ISSUE TITLE
Volume state linked between browsers

### ISSUE THREAD

**Issue by jrasanen** [flowplayer/flowplayer#984]
Not sure whether this is by design or a bug. :)

Steps:
1. Load the webpage on Chrome (incognito or normal mode, doesn't seem to matter)
2. Mute flowplayer (video still plays)
3. Load the same page on Firefox, click mute
4. Player on FF is muted, player on Chrome un-mutes itself.

Expected:
Player mute state would be per browser and not get out of incognito.

I can reproduce this only on localhost, not on jsbin. Code attached.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
  <script src="//releases.flowplayer.org/6.0.5/flowplayer.min.js"></script>
  <link rel="stylesheet" href="//releases.flowplayer.org/6.0.5/skin/functional.css" media="screen" title="no title" charset="utf-8">
  <title>Volume state linked between all browsers</title>
</head>
<body>
  <div class="flowplayer functional no-time aside-time" data-live="true" data-embed="false">
    <video autoplay>
      <source type="application/x-mpegurl" src="//stream.flowplayer.org/FlowplayerHTML5forWordPress.m3u8">
    </video>
  </div>
</body>
</html>
```

**Comment by nnarhinen** [comment]
Cannot (obviously) reproduce this (with that html or any other page running at localhost or remote). Having two browsers communicating between one another like this just is not even possible.

**Comment by jrasanen** [comment]
Hi, thank you for answering! I solved the problem myself already, [here](https://www.youtube.com/watch?v=0lNEdLq1ePk) is a video of the problem I had.
