### ISSUE TITLE
rtl: branding overlaps duration

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#985]
https://flowplayer.org/demos/i18n/

<img width="183" alt="screen shot 2016-01-18 at 12 07 24 pm" src="https://cloud.githubusercontent.com/assets/168338/12390957/47347c40-bddc-11e5-8166-0cdbf6593d36.png">

**Comment by blacktrash** [comment]
As per https://flowplayer.org/forum/#!/skinning_css:missing-class-for-rtl-fp-du probably `right: auto` is missing.

**Comment by nnarhinen** [comment]
Invalid because of new skin.
