### ISSUE TITLE
rtl: tooltip time is ltr

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#986]
https://flowplayer.org/demos/i18n/ - tooltip time displays in wrong direction. Must start at 0 at the right end of timeline.

<img width="239" alt="screen shot 2016-01-19 at 2 14 52 pm" src="https://cloud.githubusercontent.com/assets/168338/12420897/2d8f055e-beb7-11e5-9681-086e75fd05a7.png">

See also: https://flowplayer.org/forum/#!/setup:flowplayer-right-to-left

**Comment by nnarhinen** [comment]
@blacktrash How about this one?

**Comment by nnarhinen** [comment]
Any demo about this in demos.flowplayer.org?

**Comment by blacktrash** [comment]
http://demos.flowplayer.org/bug/310.html - also for dev
