### ISSUE TITLE
rtl is-touch: no duration; branding on right instead of left side and overlays time

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#987]
No duration:
<img width="138" alt="screen shot 2016-01-19 at 2 26 39 pm" src="https://cloud.githubusercontent.com/assets/168338/12421148/b18109ce-beb8-11e5-80d2-730b82358495.png">

Probably because duration is invisible rightmost, can be noticed when debranded:
![fp-commercial-touch-rtl-duration](https://cloud.githubusercontent.com/assets/168338/12421232/15cefc38-beb9-11e5-9231-cdc58b2b7b07.jpg)

While time display is completely overlayed by branding:

<img width="171" alt="screen shot 2016-01-19 at 2 22 35 pm" src="https://cloud.githubusercontent.com/assets/168338/12421097/655c32c6-beb8-11e5-9a91-2f74b28ec0cd.png">

See: https://flowplayer.org/forum/#!/setup:flowplayer-right-to-left

**Comment by nnarhinen** [comment]
This most likely is invalid now with the new skin.
