### ISSUE TITLE
RTMPT not working in Chrome

### ISSUE THREAD

**Issue by colmaengus** [flowplayer/flowplayer#988]
Hi folks,

Playback of an rtmpt url in Chrome 47 doesn't work.
I'm connecting to a Wowza server via a firewall that doesn't allow RTMP.
I'm providing an rtmp url and I can see from the logs that flowplayer is trying to connect via rtmpt but the console logs show two "NetConnection.Connect.Failed" messages and the player displays "flash: Invalid RTMP URL" message.

I've also tried using an rtmpt url but this also fails. In this case it shows a single "NetConnection.Connect.Failed" message but then just shows the loading icons.

Both of the above setups work fine in IE 11.

I tested with flowplayer html5 6.0.5.

Regards

Colm A

**Comment by blacktrash** [comment]
Please provide a link to a *minimal* sample page demonstrating the problem.
RTMPT works fine at this temporary page http://flowplayer.blacktrash.org/fp6/rtmp.html in Chrome 47.0.2526.111 (64-bit) [Mac]

**Comment by nnarhinen** [comment]
Please re-open with a link to a misbehaving page.

**Comment by colmaengus** [comment]
Interesting, it seems to be an issue with our network/firewall. Even your demo page doesn't work for my in Chrome but works fine in IE.
