### ISSUE TITLE
On mobile resume still works when flowplayer is disabled.

### ISSUE THREAD

**Issue by anaptfox** [flowplayer/flowplayer#989]
For the desktop, when clicked `api.disabled` is checked. See: 
https://github.com/flowplayer/flowplayer/blob/14388e1a9902dd08886621140fafe2becf65475f/lib/ext/ui.js#L282
On the mobile touch event, it is not: 
https://github.com/flowplayer/flowplayer/blob/069a49bd4f468e79c6bab06bed496a7d12f12640/lib/ext/mobile.js#L69

Is there a reason for this? Shouldn't it not handle the event on mobile is the player is disabled? 

Help is appreciated!

**Comment by nnarhinen** [comment]
This most likely is just a bug, thanks for reporting
