### ISSUE TITLE
Force flowplayer html5 to start faster

### ISSUE THREAD

**Issue by ermiri** [flowplayer/flowplayer#990]
My files are mp4 and they are prepared for fast start(using mp4box).
The problem is that for my movies flowplayer wait 15-25sec to start the movie and the buffer is 80-100 sec.
If i copy->paste the video url to browser address bar(chrome browser),i can play it in 3-5 sec.
So i don't need to buffer so much(80-100sec),it would be better a low buffer(because this disturb clients,they think it will never start).
How can i speed up flowplayer for a faster start?

**Comment by blacktrash** [comment]
Flowplayer does not do anything especially time consuming when evaluating video metadata, and we cannot observe this with other videos. So please provide a link to a *minimal* sample page where this can be observed, and make the video available for inspection.

**Comment by ermiri** [comment]
You can check it here http://www.flowyourvideo.com/file/56a9ea740fb74 click "Proceed to Video" to see the real player.

**Comment by nnarhinen** [comment]
Even in plain video tag (http://codepen.io/anon/pen/xZjevm?editors=1010) it takes something like 25 seconds with my internet connection to have a playable video, so it most likely has something to do with the way your video is encoded.

With a video encoded by @blacktrash (http://codepen.io/anon/pen/yejWBp?editors=1010) it takes one second to have a playable video.

Take a look at our [encoding docs](https://flowplayer.org/docs/encoding.html) for tips how to encode your videos.

**Comment by ermiri** [comment]
Thanks for your reply nnarhinen,
I tried to use your command from https://flowplayer.org/docs/encoding.html:
ffmpeg -y -i in.suffix \
       -filter:v scale=640:360,setsar=1/1 -pix_fmt yuv420p \
       -c:v libx264 -preset:v slow -profile:v baseline \
       -x264opts level=3.0:ref=1 -b:v 700k -r:v 25/1 -force_fps \
       -movflags +faststart -c:a libfaac -b:a 80k -pass x out.mp4
but it show me errors.
Anyway i found anoter solution http://stackoverflow.com/questions/6616408/ffmpeg-encode-video-and-audio-for-streaming-with-flowplayer :

infile="billboardReplaceFvS_jun29.mov"
  tmpfile="billboardReplaceFvS_jun29.mov_tmp.mp4"
  tmpfile2="billboardReplaceFvS_jun29.mov_tmp2.mp4"
  outfile="video.mp4"
  options="-vcodec libx264 -b 1200k -flags +loop+mv4 -cmp 256 \
       -partitions +parti4x4+parti8x8+partp4x4+partp8x8+partb8x8 \
       -me_method hex -subq 7 -trellis 1 -refs 5 -bf 3 \
       -flags2 +bpyramid+wpred+mixed_refs+dct8x8 -coder 1 -me_range 16 \
           -g 150 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -qmin 10\
       -qmax 51 -qdiff 4"

  ffmpeg -y -i "$infile" -an -pass 1 -threads 2 $options "$tmpfile"

  ffmpeg -y -i "$tmpfile" -acodec libfaac -ar 44100 -ab 96k -pass 2 -threads 2 $options "$tmpfile2"

but this is in two steps.
You will help me a lot if you can merge this two commands in one step.

Thanks

**Comment by blacktrash** [comment]
If our sample command doesn't work for you it probably means that you're using a really ancient ffmpeg version.
Also please understand that we cannot offer detailed transcoding support, in your own interest you should take this to a dedicated place - forum, mailing list etc. as stated at https://flowplayer.org/docs/encoding.html#encoding-samples

Or you decide that you've found the hard way why we are offering Flowplayer Drive ;-)

**Comment by ermiri** [comment]
Thanks a lot.
