### ISSUE TITLE
not playing after upgrade to Firefox 44.0 - engine hlsjs

### ISSUE THREAD

**Issue by jikard0** [flowplayer/flowplayer#991]
Double picture or nor playing hls at all on Firefox 44.0(Windows) using hlsjs engine.

**Comment by bbbo** [comment]
cannot reproduce, http://demos.flowplayer.org/api/hlsjs.html for example plays fine in my FF 44 on Windows 7. Please provide a sample link where you experience this.

**Comment by nnarhinen** [comment]
Let's continue this at https://github.com/flowplayer/flowplayer-hlsjs/issues/20
