### ISSUE TITLE
clip rtmp option still leads to src prefix requirement.

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#992]
```js
flowplayer("#player", {
  // rtmp: "rtmp://s3b78u0kbtx79q.cloudfront.net/cfx/st", // player level works
  clip: {
    rtmp: "rtmp://s3b78u0kbtx79q.cloudfront.net/cfx/st",
    sources: [
      { type: "video/flash", src: "flowplayer-700" } // fails
      // { type: "video/flash", src: "flv:flowplayer-700" } // prefix works
    ]
  }
});
```
This also affects `load(clip)`. Even more so, as in this case (without prefix), `rtmp` on the player or global level is also ignored.

@nnarhinen - tell me if you require a sample page.

**Comment by nnarhinen** [comment]
A bug demo would be very helpfull

**Comment by blacktrash** [comment]
Either this magically healed itself, or I was confused by Drive sample codes appending .mp4 suffix and might have tested with `flowplayer-700.flv`.
The latter is not ideal habitual practice because on Adobe FMS (contrary to Wowza):
- `mp4:video` and `mp4:video.mp4` works
- `video` and `flv:video` works
- `video.flv` and `flv:video.flv` do *not* work

http://flowplayer.dev/fp6/rtmp.html (FMS)
http://flowplayer.dev/fp6/wowza.html

Closing.
