### ISSUE TITLE
iframe embed code lacks px units in style directive

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer#997]
Introduced by me in https://github.com/flowplayer/flowplayer/commit/bc2d20c016b9266a03b12e05a65fffb285a35475 - contrary to attributes, style directives require units

See also: https://flowplayer.org/forum/#!/setup:embed-iframe-wrong-style

**Comment by nnarhinen** [comment]
Thanks

**Comment by blacktrash** [comment]
@nnarhinen - re-opening to accept both numbers `800` and string `800px` (may have been used as a workaround, so these setups do not break with upgrade).
Will submit patch shortly.
