### ISSUE TITLE
Can't go to next clip if 

### ISSUE THREAD

**Issue by arlindpajaziti** [flowplayer/flowplayer#999]
i have some clips that i play in flowplayer
`    playlist: [
				{
                    sources: [
                        {
                            type: "application/x-mpegurl",
                            src: "http://live.site.com/1.m3u8"
                        }
      ]	
    }, {
                    sources: [
                        {
                            type: "application/x-mpegurl",
                            src: "http://live.site.com/2.m3u8"
                        }
      ]
    }`

but if example 1.m3u8 is not working then i see white screen and message (flash: Video file not found) , and then i cant go to  2.m3u8, so its blocked the player.

Also when i try to play video i see loading so i can not switch to next source until it start the video

**Comment by blacktrash** [comment]
If a source is not available, it's correct behviour to throw an error. Please use our forum at https://flowplayer.org/forum as first port of call, unless you're 100% sure it's a bug. Thank you.

See this demo for an example how to recover from an invalid source URL: http://demos.flowplayer.org/scripting/recover.html

See also this demo http://demos.flowplayer.org/api/live-check.html for how to hide this message once in a specific error scenario in the `flashdisabled` event.

**Comment by blacktrash** [comment]
An even better way to avoid the Flash disabled message with HLS is to use the hlsjs plugin: https://flowplayer.org/docs/plugins.html#hlsjs

**Comment by nnarhinen** [comment]
This is not an issue with the player per se. It's more a scripting problem. If you can't find help from the demos @blacktrash provided, you can ask our forums for help.
